function cyrlat() {
	document.transcription.text2.value = document.transcription.text1.value
		.replace(/Щ/g, "Ш")
		.replace(/щ/g, "ш")
		.replace(/Ы/g, "И")
		.replace(/ы/g, "и")

		.replace(/([БВГҒДЖЗКҚЛМНПРСТФХҲЦЧШЩбвгғджзкқлмнпрстфхҳцчшщ])Е/g, "$1Э")
		.replace(/([БВГҒДЖЗКҚЛМНПРСТФХҲЦЧШЩбвгғджзкқлмнпрстфхҳцчшщ])е/g, "$1э")
		.replace(/(\p{Uppercase})Я/ug, "$1ЙА")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Я/ug, "$1$2 ЙА")
		.replace(/Я (\p{Uppercase})(\p{Uppercase})/ug, "ЙА $1$2")
		.replace(/Я(\p{Uppercase})/ug, "ЙА$1")
		.replace(/Я/g, "Йа")
		.replace(/я/g, "йа")
		.replace(/(\p{Uppercase})Е/ug, "$1ЙЭ")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Е/ug, "$1$2 ЙЭ")
		.replace(/Е (\p{Uppercase})(\p{Uppercase})/ug, "ЙЭ $1$2")
		.replace(/Е(\p{Uppercase})/ug, "ЙЭ$1")
		.replace(/Е/g, "Йэ")
		.replace(/е/g, "йэ")
		.replace(/(\p{Uppercase})Ё/ug, "$1ЙО")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ё/ug, "$1$2 ЙО")
		.replace(/Ё (\p{Uppercase})(\p{Uppercase})/ug, "ЙО $1$2")
		.replace(/Ё(\p{Uppercase})/ug, "ЙО$1")
		.replace(/Ё/g, "Йо")
		.replace(/ё/g, "йо")
		.replace(/(\p{Uppercase})Ю/ug, "$1ЙУ")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ю/ug, "$1$2 ЙУ")
		.replace(/Ю (\p{Uppercase})(\p{Uppercase})/ug, "ЙУ $1$2")
		.replace(/Ю(\p{Uppercase})/ug, "ЙУ$1")
		.replace(/Ю/g, "Йу")
		.replace(/ю/g, "йу")

		.replace(/([АЭИОУЎ])Ц([ЪЬ])?([АБВГҒДЖЗИЙКҚЛМНОПРСТУЎФХҲЦЧШЭ])/g, "$1ТС$2$3")
		.replace(/([АЭИОУЎаэиоуў])ц([ъь])?([абвгғджзийкқлмнопрстуўфхҳцчшэ])/g, "$1тс$2$3")
		.replace(/Ц/g, "С")
		.replace(/ц/g, "с")

		.replace(/СҲ/g, "С\u00b7Ҳ")
		.replace(/([Сс])ҳ/g, "$1\u00b7ҳ")

		.replace(/ГҲ/g, "Г\u00b7Ҳ")
		.replace(/([Гг])ҳ/g, "$1\u00b7ҳ")

		.replace(/КҲ/g, "К\u00b7Ҳ")
		.replace(/([Кк])ҳ/g, "$1\u00b7ҳ")

		.replace(/Ў([Ъъ])/g, "Ў")
		.replace(/ўъ/g, "ў")

		.replace(/(\p{Uppercase})Ч/ug, "$1CH")
		.replace(/Ч (\p{Uppercase})(\p{Uppercase})/ug, "CH $1$2")
		.replace(/Ч(\p{Uppercase})/ug, "CH$1")
		.replace(/(\p{Uppercase})Ғ/ug, "$1GH")
		.replace(/Ғ (\p{Uppercase})(\p{Uppercase})/ug, "GH $1$2")
		.replace(/Ғ(\p{Uppercase})/ug, "GH$1")
		.replace(/(\p{Uppercase})Х/ug, "$1KH")
		.replace(/Х (\p{Uppercase})(\p{Uppercase})/ug, "KH $1$2")
		.replace(/Х(\p{Uppercase})/ug, "KH$1")
		.replace(/(\p{Uppercase})Ш/ug, "$1SH")
		.replace(/Ш (\p{Uppercase})(\p{Uppercase})/ug, "SH $1$2")
		.replace(/Ш(\p{Uppercase})/ug, "SH$1")

		.replace(/а/g, "a")
		.replace(/б/g, "b")
		.replace(/в/g, "w")
		.replace(/г/g, "g")
		.replace(/ғ/g, "gh")
		.replace(/д/g, "d")
		.replace(/ж/g, "j")
		.replace(/з/g, "z")
		.replace(/и/g, "i")
		.replace(/й/g, "y")
		.replace(/к/g, "k")
		.replace(/қ/g, "q")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/о/g, "o")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ў/g, "ŭ")
		.replace(/ф/g, "f")
		.replace(/х/g, "kh")
		.replace(/ҳ/g, "h")
		.replace(/ч/g, "ch")
		.replace(/ш/g, "sh")
		.replace(/ъ/g, "\u2019")
		.replace(/ь/g, "\u2019")
		.replace(/э/g, "e")
		.replace(/А/g, "A")
		.replace(/Б/g, "B")
		.replace(/В/g, "W")
		.replace(/Г/g, "G")
		.replace(/Ғ/g, "Gh")
		.replace(/Д/g, "D")
		.replace(/Ж/g, "J")
		.replace(/З/g, "Z")
		.replace(/И/g, "I")
		.replace(/Й/g, "Y")
		.replace(/К/g, "K")
		.replace(/Қ/g, "Q")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/О/g, "O")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ў/g, "Ŭ")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "Kh")
		.replace(/Ҳ/g, "H")
		.replace(/Ч/g, "Ch")
		.replace(/Ш/g, "Sh")
		.replace(/Ъ/g, "\u2019")
		.replace(/Ь/g, "\u2019")
		.replace(/Э/g, "E");
}

function latcyr() {}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}
