
var car;

function cyrlat () {
car = document.transcription.text1.value;
car = car.replace(/(0|1|2|3|4|5|6|7|8|9)Х/g, "$1X");
car = car.replace(/(0|1|2|3|4|5|6|7|8|9)х/g, "$1x");
car = car.replace(/Х(0|1|2|3|4|5|6|7|8|9)/g, "X$1");
car = car.replace(/х(0|1|2|3|4|5|6|7|8|9)/g, "x$1");

car = car.replace(/дж/g, "џ");
car = car.replace(/Д(Ж|ж)/g, "Џ");

car = car.replace(/(А|Е|И|Ё|О|У|Ы|Э|Ю|Я)(Ы|И)/g, "$1\u2019$2");
car = car.replace(/(А|а|Е|е|И|и|Ё|ё|О|о|У|у|Ы|ы|Э|э|Ю|ю|Я|я)(ы|и)/g, "$1\u2019$2");
car = car.replace(/ИЙ/g, "ИЙ\u2060");
car = car.replace(/(И|и)й/g, "$1й\u2060");
car = car.replace(/Й(И|и)/g, "Й\u2060$1");
car = car.replace(/йи/g, "й\u2060и");
car = car.replace(/ИЕ/g, "ИЙ\u2060Э");
car = car.replace(/(И|и)е/g, "$1й\u2060э");
car = car.replace(/ИЁ/g, "ИЙ\u2060О");
car = car.replace(/(И|и)ё/g, "$1й\u2060о");
car = car.replace(/ИЮ/g, "ИЙ\u2060У");
car = car.replace(/(И|и)ю/g, "$1й\u2060у");
car = car.replace(/ИЯ/g, "ИЙ\u2060А");
car = car.replace(/(И|и)я/g, "$1й\u2060а");
car = car.replace(/Ё/g, "Ио");
car = car.replace(/Ю/g, "Иу");
car = car.replace(/Я/g, "Иа");
car = car.replace(/ё/g, "ио");
car = car.replace(/ю/g, "иу");
car = car.replace(/я/g, "иа");
car = car.replace(/Й/g, "И");
car = car.replace(/й/g, "и");
car = car.replace(/(Б|В|Г|Д|Џ|Ж|З|К|Л|М|Н|П|Р|С|Т|У|Ф|Х|Ц|Ч|Ш|Щ)ЫИ/g, "$1Ы");
car = car.replace(/(Б|В|Г|Д|Џ|Ж|З|К|Л|М|Н|П|Р|С|Т|У|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|д|џ|ж|з|к|л|м|н|п|р|с|т|у|ф|х|ц|ч|ш|щ)ыи/g, "$1ы");
car = car.replace(/ЫИ/g, "ИЙ\u2060");
car = car.replace(/Ыи/g, "Ий\u2060");
car = car.replace(/ыи/g, "ий\u2060");
car = car.replace(/ИЫ/g, "Й\u2060И");
car = car.replace(/Иы/g, "Й\u2060и");
car = car.replace(/иы/g, "й\u2060и");
car = car.replace(/(Б|В|Г|Д|Џ|Ж|З|Й|Й\u2060|К|Л|М|Н|П|Р|С|Т|У|Ф|Х|Ц|Ч|Ш|Щ)Ы/g, "$1И\u2060");
car = car.replace(/(Б|В|Г|Д|Џ|Ж|З|Й|Й\u2060|К|Л|М|Н|П|Р|С|Т|У|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|д|џ|ж|з|й|й\u2060|к|л|м|н|п|р|с|т|у|ф|х|ц|ч|ш|щ)ы/g, "$1и\u2060");
car = car.replace(/(Б|В|Г|Д|Џ|Ж|З|Й|Й\u2060|К|Л|М|Н|П|Р|С|Т|У|Ф|Х|Ц|Ч|Ш|Щ)И\u2060(Б|В|Г|Д|Џ|Ж|З|Й|Й\u2060|К|Л|М|Н|П|Р|С|Т|У|Ф|Х|Ц|Ч|Ш|Щ)/g, "$1Ы$2");
car = car.replace(/(Б|В|Г|Д|Џ|Ж|З|Й|Й\u2060|К|Л|М|Н|П|Р|С|Т|У|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|д|џ|ж|з|й|й\u2060|к|л|м|н|п|р|с|т|у|ф|х|ц|ч|ш|щ)и\u2060(б|в|г|д|џ|ж|з|й|й\u2060|к|л|м|н|п|р|с|т|у|ф|х|ц|ч|ш|щ)/g, "$1ы$2");
car = car.replace(/(Б|В|Г|Д|Џ|Ж|З|Й|Й\u2060|К|Л|М|Н|П|Р|С|Т|У|Ф|Х|Ц|Ч|Ш|Щ)(Б|В|Г|Д|Џ|Ж|З|Й|Й\u2060|К|Л|М|Н|П|Р|С|Т|У|Ф|Х|Ц|Ч|Ш|Щ)И\u2060/g, "$1$2Ы");
car = car.replace(/(Б|В|Г|Д|Џ|Ж|З|Й|Й\u2060|К|Л|М|Н|П|Р|С|Т|У|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|д|џ|ж|з|й|й\u2060|к|л|м|н|п|р|с|т|у|ф|х|ц|ч|ш|щ)(б|в|г|д|џ|ж|з|й|й\u2060|к|л|м|н|п|р|с|т|у|ф|х|ц|ч|ш|щ)и\u2060/g, "$1$2ы");
car = car.replace(/(И|и)\u2060/g, "$1");
car = car.replace(/И(А|Э|Ə|О|Ө|У|Ү|а|э|ə|о|ө|у|ү)/g, "Й$1");
car = car.replace(/и(а|э|ə|о|ө|у|ү)/g, "й$1");
car = car.replace(/\u2060/g, "");

car = car.replace(/(С|с)(Х|х)/g, "$1\u2019$2");
car = car.replace(/(Ш|ш)(Х|х)/g, "$1\u2019$2");

car = car.replace(/Щ(А|Б|В|Г|Д|Џ|Е|Ё|Ж|З|И|Й|К|Л|М|Н|О|П|Р|С|Т|У|Ф|Х|Ц|Ч|Ш|Щ|Ы|Э|Ю|Я)/g, "SHH$1");
car = car.replace(/Щ(а|б|в|г|д|џ|е|ё|ж|з|и|й|к|л|м|н|о|п|р|с|т|у|ф|х|ц|ч|ш|щ|ы|э|ю|я)/g, "Shh$1");
car = car.replace(/щ(А|Б|В|Г|Д|Џ|Е|Ё|Ж|З|И|Й|К|Л|М|Н|О|П|Р|С|Т|У|Ф|Х|Ц|Ч|Ш|Щ|Ы|Э|Ю|Я|а|б|в|г|д|џ|е|ё|ж|з|и|й|к|л|м|н|о|п|р|с|т|у|ф|х|ц|ч|ш|щ|ы|э|ю|я)/g, "shh$1");
car = car.replace(/Щ/g, "SH");
car = car.replace(/щ/g, "sh");

car = car.replace(/бе/g, "be");
car = car.replace(/ве/g, "ve");
car = car.replace(/ге/g, "ge");
car = car.replace(/де/g, "de");
car = car.replace(/џе/g, "je");
car = car.replace(/же/g, "jhe");
car = car.replace(/зе/g, "ze");
car = car.replace(/йе/g, "ĭe");
car = car.replace(/ке/g, "ke");
car = car.replace(/ле/g, "le");
car = car.replace(/ме/g, "me");
car = car.replace(/не/g, "ne");
car = car.replace(/пе/g, "pe");
car = car.replace(/ре/g, "re");
car = car.replace(/се/g, "se");
car = car.replace(/те/g, "te");
car = car.replace(/фе/g, "fe");
car = car.replace(/хе/g, "he");
car = car.replace(/це/g, "tse");
car = car.replace(/че/g, "che");
car = car.replace(/ше/g, "she");
car = car.replace(/ще/g, "shhe");

car = car.replace(/Бе/g, "Be");
car = car.replace(/Ве/g, "Ve");
car = car.replace(/Ге/g, "Ge");
car = car.replace(/Де/g, "De");
car = car.replace(/Џе/g, "Je");
car = car.replace(/Же/g, "Jhe");
car = car.replace(/Зе/g, "Ze");
car = car.replace(/Йе/g, "Ĭe");
car = car.replace(/Ке/g, "Ke");
car = car.replace(/Ле/g, "Le");
car = car.replace(/Ме/g, "Me");
car = car.replace(/Не/g, "Ne");
car = car.replace(/Пе/g, "Pe");
car = car.replace(/Ре/g, "Re");
car = car.replace(/Се/g, "Se");
car = car.replace(/Те/g, "Te");
car = car.replace(/Фе/g, "Fe");
car = car.replace(/Хе/g, "He");
car = car.replace(/Це/g, "Tse");
car = car.replace(/Че/g, "Che");
car = car.replace(/Ше/g, "She");
car = car.replace(/Ще/g, "Shhe");

car = car.replace(/БЕ/g, "BE");
car = car.replace(/ВЕ/g, "VE");
car = car.replace(/ГЕ/g, "GE");
car = car.replace(/ДЕ/g, "DE");
car = car.replace(/ЏЕ/g, "JE");
car = car.replace(/ЖЕ/g, "JHE");
car = car.replace(/ЗЕ/g, "ZE");
car = car.replace(/ЙЕ/g, "ĬE");
car = car.replace(/КЕ/g, "KE");
car = car.replace(/ЛЕ/g, "LE");
car = car.replace(/МЕ/g, "ME");
car = car.replace(/НЕ/g, "NE");
car = car.replace(/ПЕ/g, "PE");
car = car.replace(/РЕ/g, "RE");
car = car.replace(/СЕ/g, "SE");
car = car.replace(/ТЕ/g, "TE");
car = car.replace(/ФЕ/g, "FE");
car = car.replace(/ХЕ/g, "HE");
car = car.replace(/ЦЕ/g, "TSE");
car = car.replace(/ЧЕ/g, "CHE");
car = car.replace(/ШЕ/g, "SHE");
car = car.replace(/ЩЕ/g, "SHHE");

car = car.replace(/џё/g, "jo");
car = car.replace(/жё/g, "jho");
car = car.replace(/чё/g, "cho");
car = car.replace(/шё/g, "sho");
car = car.replace(/щё/g, "shho");
car = car.replace(/Џё/g, "Jo");
car = car.replace(/Жё/g, "Jho");
car = car.replace(/Чё/g, "Cho");
car = car.replace(/Шё/g, "Sho");
car = car.replace(/Щё/g, "Shho");
car = car.replace(/ЏЁ/g, "JO");
car = car.replace(/ЖЁ/g, "JHO");
car = car.replace(/ЧЁ/g, "CHO");
car = car.replace(/ШЁ/g, "SHO");
car = car.replace(/ЩЁ/g, "SHHO");

car = car.replace(/џю/g, "ju");
car = car.replace(/жю/g, "jhu");
car = car.replace(/шю/g, "shu");
car = car.replace(/Џю/g, "Ju");
car = car.replace(/Жю/g, "Jhu");
car = car.replace(/Шю/g, "Shu");
car = car.replace(/ЏЮ/g, "JU");
car = car.replace(/ЖЮ/g, "JHU");
car = car.replace(/ШЮ/g, "SHU");


car = car.replace(/а/g, "a");
car = car.replace(/б/g, "b");
car = car.replace(/в/g, "v");
car = car.replace(/г/g, "g");
car = car.replace(/д/g, "d");
car = car.replace(/џ/g, "j");
car = car.replace(/е/g, "ĭe");
car = car.replace(/ж/g, "jh");
car = car.replace(/з/g, "z");
car = car.replace(/и/g, "i");
car = car.replace(/й/g, "y");
car = car.replace(/к/g, "k");
car = car.replace(/л/g, "l");
car = car.replace(/м/g, "m");
car = car.replace(/н/g, "n");
car = car.replace(/о/g, "o");
car = car.replace(/п/g, "p");
car = car.replace(/р/g, "r");
car = car.replace(/с/g, "s");
car = car.replace(/т/g, "t");
car = car.replace(/у/g, "u");
car = car.replace(/ф/g, "f");
car = car.replace(/х/g, "h");
car = car.replace(/ц/g, "ts");
car = car.replace(/ч/g, "ch");
car = car.replace(/ш/g, "sh");
car = car.replace(/ы/g, "y");
car = car.replace(/э/g, "e");

car = car.replace(/А/g, "A");
car = car.replace(/Б/g, "B");
car = car.replace(/В/g, "V");
car = car.replace(/Г/g, "G");
car = car.replace(/Д/g, "D");
car = car.replace(/Џ/g, "J");
car = car.replace(/Ж/g, "Jh");
car = car.replace(/З/g, "Z");
car = car.replace(/И/g, "I");
car = car.replace(/Й/g, "Y");
car = car.replace(/К/g, "K");
car = car.replace(/Л/g, "L");
car = car.replace(/М/g, "M");
car = car.replace(/Н/g, "N");
car = car.replace(/О/g, "O");
car = car.replace(/П/g, "P");
car = car.replace(/Р/g, "R");
car = car.replace(/С/g, "S");
car = car.replace(/Т/g, "T");
car = car.replace(/У/g, "U");
car = car.replace(/Ф/g, "F");
car = car.replace(/Х/g, "H");
car = car.replace(/Ц/g, "Ts");
car = car.replace(/Ч/g, "Ch");
car = car.replace(/Ш/g, "Sh");
car = car.replace(/Ы/g, "Y");
car = car.replace(/Э/g, "E");

car = car.replace(/Ь|Ъ|ь|ъ/g, "");
car = car.replace(/«/g, "\u201c");
car = car.replace(/»/g, "\u201d");
document.transcription.text2.value = car;
}

function copy1()
{ textRange=document.transcription.text1.createTextRange();
textRange.execCommand("Copy");
textRange="";
}
function copy2()
{ textRange=document.transcription.text2.createTextRange();
textRange.execCommand("Copy");
textRange="";
}
