function latcyr() {}

function cyrlat() {
	document.transcription.text2.value = document.transcription.text1.value
		.replace(/ağa/g, "a-a")
		.replace(/âğâ/g, "â-â")
		.replace(/ağâ/g, "a-â")
		.replace(/âğa/g, "â-a")
		.replace(/eğe/g, "e-e")
		.replace(/ığı/g, "ı-ı")
		.replace(/iği/g, "i-i")
		.replace(/îğî/g, "î-î")
		.replace(/iğî/g, "i-î")
		.replace(/îği/g, "î-i")
		.replace(/oğo/g, "o-o")
		.replace(/öğö/g, "ö-ö")
		.replace(/uğu/g, "u-u")
		.replace(/ûğû/g, "û-û")
		.replace(/ûğu/g, "û-u")
		.replace(/uğû/g, "u-û")
		.replace(/üğü/g, "ü-ü")

		.replace(/Ağa/g, "A-a")
		.replace(/Âğâ/g, "Â-â")
		.replace(/Ağâ/g, "A-â")
		.replace(/Âğa/g, "Â-a")
		.replace(/Eğe/g, "E-e")
		.replace(/Iğı/g, "I-ı")
		.replace(/İği/g, "İ-i")
		.replace(/Îğî/g, "Î-î")
		.replace(/İğî/g, "İ-î")
		.replace(/Îği/g, "Î-i")
		.replace(/Oğo/g, "O-o")
		.replace(/Öğö/g, "Ö-ö")
		.replace(/Uğu/g, "U-u")
		.replace(/Ûğû/g, "Û-û")
		.replace(/Ûğu/g, "Û-u")
		.replace(/Uğû/g, "U-û")
		.replace(/Üğü/g, "Ü-ü")

		.replace(/AĞA/g, "A-A")
		.replace(/ÂĞÂ/g, "Â-Â")
		.replace(/AĞÂ/g, "A-Â")
		.replace(/ÂĞA/g, "Â-A")
		.replace(/EĞE/g, "E-E")
		.replace(/IĞI/g, "I-I")
		.replace(/İĞİ/g, "İ-İ")
		.replace(/ÎĞÎ/g, "Î-Î")
		.replace(/İĞÎ/g, "İ-Î")
		.replace(/ÎĞİ/g, "Î-İ")
		.replace(/OĞO/g, "O-O")
		.replace(/ÖĞÖ/g, "Ö-Ö")
		.replace(/UĞU/g, "U-U")
		.replace(/ÛĞÛ/g, "Û-Û")
		.replace(/UĞÛ/g, "U-Û")
		.replace(/ÛĞU/g, "Û-U")
		.replace(/ÜĞÜ/g, "Ü-Ü")
		.replace(/ağı/g, "a:")
		.replace(/âğı/g, "â:")
		.replace(/Ağı/g, "A:")
		.replace(/Âğı/g, "Â:")
		.replace(/AĞI/g, "A:")
		.replace(/ÂĞI/g, "Â:")
		.replace(/ğa/g, "a")
		.replace(/ğâ/g, "â")
		.replace(/ğe/g, "e")
		.replace(/ğı/g, "ı")
		.replace(/ği/g, "i")
		.replace(/ğî/g, "î")
		.replace(/ğo/g, "o")
		.replace(/ğö/g, "ö")
		.replace(/ğu/g, "u")
		.replace(/ğû/g, "û")
		.replace(/ğü/g, "ü")
		.replace(/ĞA/g, "A")
		.replace(/ĞÂ/g, "Â")
		.replace(/ĞE/g, "E")
		.replace(/ĞI/g, "I")
		.replace(/Ğİ/g, "İ")
		.replace(/ĞÎ/g, "Î")
		.replace(/ĞO/g, "O")
		.replace(/ĞÖ/g, "Ö")
		.replace(/ĞU/g, "U")
		.replace(/ĞÛ/g, "Û")
		.replace(/ĞÜ/g, "Ü")
		.replace(/ağ/g, "a:")
		.replace(/âğ/g, "â:")
		.replace(/eğ/g, "ey")
		.replace(/ığ/g, "ı:")
		.replace(/iğ/g, "iy")
		.replace(/îğ/g, "îy")
		.replace(/oğ/g, "o:")
		.replace(/öğ/g, "ö:")
		.replace(/uğ/g, "u:")
		.replace(/ûğ/g, "û:")
		.replace(/üğ/g, "ü:")
		.replace(/Ağ/g, "A:")
		.replace(/Âğ/g, "Â:")
		.replace(/Eğ/g, "Ey")
		.replace(/Iğ/g, "I:")
		.replace(/İğ/g, "İy")
		.replace(/Îğ/g, "Îy")
		.replace(/Oğ/g, "O:")
		.replace(/Öğ/g, "Ö:")
		.replace(/Uğ/g, "U:")
		.replace(/Ûğ/g, "Û:")
		.replace(/Üğ/g, "Ü:")
		.replace(/AĞ/g, "A:")
		.replace(/ÂĞ/g, "Â:")
		.replace(/EĞ/g, "EY")
		.replace(/IĞ/g, "I:")
		.replace(/İĞ/g, "İY")
		.replace(/ÎĞ/g, "ÎY")
		.replace(/OĞ/g, "O:")
		.replace(/ÖĞ/g, "Ö:")
		.replace(/UĞ/g, "U:")
		.replace(/ÛĞ/g, "Û:")
		.replace(/ÜĞ/g, "Ü:");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}