function cyrlat() {
	document.transcription.text2.value = document.transcription.text1.value
		.replace(/ац/g, "атс")
		.replace(/яц/g, "ятс")
		.replace(/ец/g, "етс")
		.replace(/иц/g, "итс")
		.replace(/ӣц/g, "ӣтс")
		.replace(/оц/g, "отс")
		.replace(/ёц/g, "ётс")
		.replace(/уц/g, "утс")
		.replace(/юц/g, "ютс")
		.replace(/ӯц/g, "ӯтс")
		.replace(/Ац/g, "Атс")
		.replace(/Яц/g, "Ятс")
		.replace(/Ец/g, "Етс")
		.replace(/Иц/g, "Итс")
		.replace(/Ӣц/g, "Ӣтс")
		.replace(/Оц/g, "Отс")
		.replace(/Ёц/g, "Ётс")
		.replace(/Уц/g, "Утс")
		.replace(/Юц/g, "Ютс")
		.replace(/Ӯц/g, "Ӯтс")
		.replace(/АЦ/g, "АТС")
		.replace(/ЯЦ/g, "ЯТС")
		.replace(/ЕЦ/g, "ЕТС")
		.replace(/ИЦ/g, "ИТС")
		.replace(/ӢЦ/g, "ӢТС")
		.replace(/ОЦ/g, "ОТС")
		.replace(/ЁЦ/g, "ЁТС")
		.replace(/УЦ/g, "УТС")
		.replace(/ЮЦ/g, "ЮТС")
		.replace(/ӮЦ/g, "ӮТС")

		.replace(/а/g, "a")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/ғ/g, "gh")
		.replace(/д/g, "d")
		.replace(/е/g, "e")
		.replace(/ё/g, "yo")
		.replace(/ж/g, "zh")
		.replace(/з/g, "z")
		.replace(/и/g, "i")
		.replace(/ӣ/g, "í")
		.replace(/й/g, "y")
		.replace(/к/g, "k")
		.replace(/қ/g, "q")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/о/g, "o")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ӯ/g, "ŭ")
		.replace(/ф/g, "f")
		.replace(/х/g, "kh")
		.replace(/ҳ/g, "h")
		.replace(/ц/g, "s")
		.replace(/ч/g, "ch")
		.replace(/ҷ/g, "j")
		.replace(/ш/g, "sh")
		.replace(/щ/g, "sh")
		.replace(/ъ/g, "’")
		.replace(/ы/g, "i")
		.replace(/ь/g, "")
		.replace(/э/g, "ė")
		.replace(/ю/g, "yu")
		.replace(/я/g, "ya")
		.replace(/А/g, "A")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Ғ/g, "Gh")
		.replace(/Д/g, "D")
		.replace(/Е/g, "E")
		.replace(/Ё/g, "Yo")
		.replace(/Ж/g, "Zh")
		.replace(/З/g, "Z")
		.replace(/И/g, "I")
		.replace(/Ӣ/g, "Í")
		.replace(/Й/g, "Y")
		.replace(/К/g, "K")
		.replace(/Қ/g, "Q")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/О/g, "O")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ӯ/g, "Ŭ")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "Kh")
		.replace(/Ҳ/g, "H")
		.replace(/Ц/g, "S")
		.replace(/Ч/g, "Ch")
		.replace(/Ҷ/g, "J")
		.replace(/Ш/g, "Sh")
		.replace(/Щ/g, "Sh")
		.replace(/Ъ/g, "’")
		.replace(/Ы/g, "I")
		.replace(/Ь/g, "")
		.replace(/Э/g, "Ė")
		.replace(/Ю/g, "Yu")
		.replace(/Я/g, "Ya");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}