function latcyr() {}

function cyrlat() {
	document.transcription.text2.value = document.transcription.text1.value

		.replace(/ е/g, " je")
		.replace(/\nе/g, "\nje")
		.replace(/\rе/g, "\rje")
		.replace(/^е/g, "je")

		.replace(/ае/g, "аje")
		.replace(/ие/g, "иje")
		.replace(/ые/g, "ыje")
		.replace(/ее/g, "еje")
		.replace(/эе/g, "эje")
		.replace(/уе/g, "уje")
		.replace(/ое/g, "оje")
		.replace(/өе/g, "өje")
		.replace(/ёе/g, "ёje")
		.replace(/үе/g, "үje")
		.replace(/йе/g, "йje")
		.replace(/юе/g, "юje")
		.replace(/яе/g, "яje")
		.replace(/ье/g, "je")
		.replace(/ъе/g, "je")

		.replace(/ Е/g, " Je")
		.replace(/\nЕ/g, "\nJe")
		.replace(/\rЕ/g, "\rJe")
		.replace(/^Е/g, "Je")

		.replace(/Ае/g, "Аje")
		.replace(/Ие/g, "Иje")
		.replace(/Ые/g, "Ыje")
		.replace(/Ее/g, "Еje")
		.replace(/Эе/g, "Эje")
		.replace(/Уе/g, "Уje")
		.replace(/Ое/g, "Оje")
		.replace(/Өе/g, "Өje")
		.replace(/Ёе/g, "Ёje")
		.replace(/Үе/g, "Үje")
		.replace(/Йе/g, "Йje")
		.replace(/Юе/g, "Юje")
		.replace(/Яе/g, "Яje")

		.replace(/АЕ/g, "АJE")
		.replace(/ИЕ/g, "ИJE")
		.replace(/ЫЕ/g, "ЫJE")
		.replace(/ЕЕ/g, "ЕJE")
		.replace(/ЭЕ/g, "ЭJE")
		.replace(/УЕ/g, "УJE")
		.replace(/ОЕ/g, "ОJE")
		.replace(/ӨЕ/g, "ӨJE")
		.replace(/ЁЕ/g, "ЁJE")
		.replace(/ҮЕ/g, "ҮJE")
		.replace(/ЙЕ/g, "ЙJE")
		.replace(/ЮЕ/g, "ЮJE")
		.replace(/ЯЕ/g, "ЯJE")
		.replace(/ЬЕ/g, "JE")
		.replace(/ЪЕ/g, "JE")

		.replace(/а/g, "a")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/д/g, "d")
		.replace(/е/g, "e")
		.replace(/ё/g, "jo")
		.replace(/ж/g, "đ")
		.replace(/з/g, "z")
		.replace(/и/g, "i")
		.replace(/й/g, "j")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/ң/g, "ň")
		.replace(/о/g, "o")
		.replace(/ө/g, "ö")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ү/g, "ü")
		.replace(/ф/g, "f")
		.replace(/х/g, "h")
		.replace(/ц/g, "c")
		.replace(/ч/g, "č")
		.replace(/ш/g, "š")
		.replace(/щ/g, "ś")
		.replace(/ъ/g, "")
		.replace(/ы/g, "y")
		.replace(/ь/g, "")
		.replace(/э/g, "e")
		.replace(/ю/g, "ju")
		.replace(/я/g, "ja")
		.replace(/А/g, "A")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Д/g, "D")
		.replace(/Е/g, "E")
		.replace(/Ё/g, "Jo")
		.replace(/Ж/g, "Đ")
		.replace(/З/g, "Z")
		.replace(/И/g, "I")
		.replace(/Й/g, "J")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/Ң/g, "Ň")
		.replace(/О/g, "O")
		.replace(/Ө/g, "Ö")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ү/g, "Ü")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "H")
		.replace(/Ц/g, "C")
		.replace(/Ч/g, "Č")
		.replace(/Ш/g, "Š")
		.replace(/Щ/g, "Ś")
		.replace(/Ъ/g, "")
		.replace(/Ы/g, "Y")
		.replace(/Ь/g, "")
		.replace(/Э/g, "E")
		.replace(/Ю/g, "Ju")
		.replace(/Я/g, "Ja")

		.replace(/AA/g, "Á")
		.replace(/EE/g, "É")
		.replace(/II/g, "Í")
		.replace(/OO/g, "Ó")
		.replace(/ÖÖ/g, "Ő")
		.replace(/UU/g, "Ú")
		.replace(/ÜÜ/g, "Ű")
		.replace(/YY/g, "Ý")
		.replace(/Aa/g, "Á")
		.replace(/Ee/g, "É")
		.replace(/Ii/g, "Í")
		.replace(/Oo/g, "Ó")
		.replace(/Öö/g, "Ő")
		.replace(/Uu/g, "Ú")
		.replace(/Üü/g, "Ű")
		.replace(/Yy/g, "Ý")
		.replace(/aa/g, "á")
		.replace(/ee/g, "é")
		.replace(/ii/g, "í")
		.replace(/oo/g, "ó")
		.replace(/öö/g, "ő")
		.replace(/uu/g, "ú")
		.replace(/üü/g, "ű")
		.replace(/yy/g, "ý");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}