function cyrlat() {
	document.transcription.text2.value = document.transcription.text1.value
		.normalize('NFD')
		.replace(/ᆪ/g, 'gs')
		.replace(/ᆬ/g, 'nj')
		.replace(/ᆭ/g, 'nh')
		.replace(/ᆰ/g, 'rg')
		.replace(/ᆲ/g, 'rb')
		.replace(/ᆶ/g, 'rh')
		.replace(/ᆱ/g, 'rm')
		.replace(/ᆹ/g, 'bs')
		.replace(/ㄿ/g, 'rp')
		.replace(/ᆳ/g, 'rs')
		.replace(/ㄾ/g, 'rt')
		.replace(/ᄀ/g, 'g')
		.replace(/ᆨ/g, 'g')
		.replace(/ᄁ/g, 'ġ')
		.replace(/ᆩ/g, 'ġ')
		.replace(/ᄂ/g, 'n')
		.replace(/ᆫ/g, 'n')
		.replace(/ᄃ/g, 'd')
		.replace(/ᆮ/g, 'd')
		.replace(/ᄄ/g, 'ḍ')
		.replace(/ᄅ/g, 'r')
		.replace(/ᆯ/g, 'r')
		.replace(/ᄆ/g, 'm')
		.replace(/ᆷ/g, 'm')
		.replace(/ᄇ/g, 'b')
		.replace(/ᆸ/g, 'b')
		.replace(/ᄈ/g, 'ḅ')
		.replace(/ᄉ/g, 's')
		.replace(/ᆺ/g, 's')
		.replace(/ᄊ/g, 'ṡ')
		.replace(/ᆻ/g, 'ṡ')
		.replace(/ᄋ/g, '\u2019')
		.replace(/ᆼ/g, 'ǹ')
		.replace(/ᄌ/g, 'j')
		.replace(/ᆽ/g, 'j')
		.replace(/ᄍ/g, 'ɉ')
		.replace(/ᄎ/g, 'c')
		.replace(/ᆾ/g, 'c')
		.replace(/ᄏ/g, 'k')
		.replace(/ᆿ/g, 'k')
		.replace(/ᄐ/g, 't')
		.replace(/ᇀ/g, 't')
		.replace(/ᄑ/g, 'p')
		.replace(/ᇁ/g, 'p')
		.replace(/ᄒ/g, 'h')
		.replace(/ᇂ/g, 'h')
		.replace(/([bḅcdḍgġhjɉkmnṅprsṡt])\u2019/g, "$1\u002d")
		.replace(/\u2019/g, "")

		.replace(/ᅡ/g, 'a')
		.replace(/ᅢ/g, 'æ')
		.replace(/ᅣ/g, 'ya')
		.replace(/ᅤ/g, 'yæ')
		.replace(/ᅥ/g, 'ŏ')
		.replace(/ᅦ/g, 'e')
		.replace(/ᅧ/g, 'yŏ')
		.replace(/ᅨ/g, 'ye')
		.replace(/ᅩ/g, 'o')
		.replace(/ᅪ/g, 'ẇa')
		.replace(/ᅫ/g, 'ẇæ')
		.replace(/ᅬ/g, 'ẇi')
		.replace(/ᅭ/g, 'yo')
		.replace(/ᅮ/g, 'u')
		.replace(/ᅯ/g, 'wo')
		.replace(/ᅰ/g, 'we')
		.replace(/ᅱ/g, 'wi')
		.replace(/ᅲ/g, 'yu')
		.replace(/ᅳ/g, 'ŭ')
		.replace(/ᅴ/g, 'ŭy')
		.replace(/ᅵ/g, 'i')
		.normalize('NFC');
}


function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}