function cyrlat() {
	document.transcription.text2.value = document.transcription.text1.value
		.replace(/Ե(Ւ|ւ)/g, "Վ")
		.replace(/եւ/g, "վ")
		.replace(/(Ք|Կ)ԵԱ/g, "$1Â")
		.replace(/(Ք|Կ|ք|կ)եա/g, "$1â")
		.replace(/(Ք|Կ)ԵՈՒ/g, "$1Û")
		.replace(/(Ք|Կ|ք|կ)եու/g, "$1û")
		.replace(/Ո(Ւ|ւ)/g, "U")
		.replace(/ու/g, "u")
		.replace(/Ի(Ւ|ւ)/g, "Ü")
		.replace(/իւ/g, "ü")
		.replace(/Է(Օ|օ)/g, "Ö")
		.replace(/էօ/g, "ö")
		.replace(/Ն(Կ|կ)/g, "N")
		.replace(/նկ/g, "n")

		.replace(/Ա/g, "A")
		.replace(/Բ/g, "P")
		.replace(/Գ/g, "K")
		.replace(/Դ/g, "T")
		.replace(/Ե/g, "Y")
		.replace(/Զ/g, "Z")
		.replace(/Է/g, "E")
		.replace(/Ը/g, "I")
		.replace(/Թ/g, "T")
		.replace(/Ժ/g, "J")
		.replace(/Ի/g, "İ")
		.replace(/Լ/g, "L")
		.replace(/Խ/g, "H")
		.replace(/Ծ/g, "Dz")
		.replace(/Կ/g, "G")
		.replace(/Հ/g, "H")
		.replace(/Ձ/g, "Ts")
		.replace(/Ղ/g, "Ġ")
		.replace(/Ճ/g, "C")
		.replace(/Մ/g, "M")
		.replace(/Յ/g, "Y")
		.replace(/Ն/g, "N")
		.replace(/Շ/g, "Ş")
		.replace(/Ո/g, "O")
		.replace(/Չ/g, "Ç")
		.replace(/Պ/g, "B")
		.replace(/Ջ/g, "Ç")
		.replace(/Ռ/g, "R")
		.replace(/Ս/g, "S")
		.replace(/Վ/g, "V")
		.replace(/Տ/g, "D")
		.replace(/Ր/g, "R")
		.replace(/Ց/g, "Ts")
		.replace(/Ւ/g, "V")
		.replace(/Փ/g, "P")
		.replace(/Ք/g, "K")
		.replace(/Օ/g, "O")
		.replace(/Ֆ/g, "F")
		.replace(/ա/g, "a")
		.replace(/բ/g, "p")
		.replace(/գ/g, "k")
		.replace(/դ/g, "t")
		.replace(/ե/g, "y")
		.replace(/զ/g, "z")
		.replace(/է/g, "e")
		.replace(/ը/g, "ı")
		.replace(/թ/g, "t")
		.replace(/ժ/g, "j")
		.replace(/ի/g, "i")
		.replace(/լ/g, "l")
		.replace(/խ/g, "h")
		.replace(/ծ/g, "dz")
		.replace(/կ/g, "g")
		.replace(/հ/g, "h")
		.replace(/ձ/g, "ts")
		.replace(/ղ/g, "ġ")
		.replace(/ճ/g, "c")
		.replace(/մ/g, "m")
		.replace(/յ/g, "y")
		.replace(/ն/g, "n")
		.replace(/շ/g, "ş")
		.replace(/ո/g, "o")
		.replace(/չ/g, "ç")
		.replace(/պ/g, "b")
		.replace(/ջ/g, "ç")
		.replace(/ռ/g, "r")
		.replace(/ս/g, "s")
		.replace(/վ/g, "v")
		.replace(/տ/g, "d")
		.replace(/ր/g, "r")
		.replace(/ց/g, "ts")
		.replace(/ւ/g, "v")
		.replace(/փ/g, "p")
		.replace(/ք/g, "k")
		.replace(/օ/g, "o")
		.replace(/ֆ/g, "f")

		.replace(/(A|I|O|U|E|İ|Ö|Ü)(G|Ġ)/g, "$1Ğ")
		.replace(/(A|I|O|U|E|İ|Ö|Ü|a|ı|o|u|e|i|ö|ü)(g|ġ)/g, "$1ğ")
		.replace(/(A|I|O|U)Ğ(E|İ|Ö|Ü)/g, "$1G$2")
		.replace(/(A|I|O|U|a|ı|o|u)ğ(e|i|ö|ü)/g, "$1g$2")
		.replace(/(E|İ|Ö|Ü)Ğ(A|I|O|U)/g, "$1G$2")
		.replace(/(E|İ|Ö|Ü|e|i|ö|ü)ğ(a|ı|o|u)/g, "$1g$2")
		.replace(/Ġ/g, "G")
		.replace(/ġ/g, "g")

		.replace(/(\u055b|\u055c|\u055e)/g, "")
		.replace(/(\u055d|\u0060)/g, "\u003b")
		.replace(/(\u003a|\u0589)/g, "\u002e")
		.replace(/\u2024/g, "\u003a")
		.replace(/\u058a/g, "\u002d")
		.replace(/\u055a/g, "\u2019");
}

function latcyr() {
	document.transcription.text1.value = document.transcription.text2.value
		.replace(/(A|Â|E|I|İ|Î|O|Ö|U|Û|Ü)Y/g, "$1Ẏ")
		.replace(/(A|Â|E|I|İ|Î|O|Ö|U|Û|Ü|a|â|e|ı|i|î|o|ö|u|û|ü)y/g, "$1ẏ")

		.replace(/(A|I|O|U)G/g, "$1Ġ")
		.replace(/(A|I|O|U|a|ı|o|u)g/g, "$1ġ")
		.replace(/(A|I|O|U)K/g, "$1Ḳ")
		.replace(/(A|I|O|U|a|ı|o|u)k/g, "$1ḳ")
		.replace(/G(A|I|O|U|a|ı|o|u)/g, "Ġ$1")
		.replace(/g(a|ı|o|u)/g, "ġ$1")
		.replace(/K(A|I|O|U|a|ı|o|u)/g, "Ḳ$1")
		.replace(/k(a|ı|o|u)/g, "ḳ$1")
		.replace(/Ġ(Â|E|İ|Î|Ö|Û|Ü|â|e|i|î|ö|û|ü)/g, "G$1")
		.replace(/ġ(â|e|i|î|ö|û|ü)/g, "g$1")
		.replace(/Ḳ(Â|E|İ|Î|Ö|Û|Ü|â|e|i|î|ö|û|ü)/g, "K$1")
		.replace(/ḳ(â|e|i|î|ö|û|ü)/g, "k$1")

		.replace(/(A|I|O|U)Ğ/g, "$1Ġ")
		.replace(/(A|I|O|U|a|ı|o|u)ğ/g, "$1ġ")
		.replace(/(E|İ|Ö|Ü)Ğ/g, "$1G")
		.replace(/(E|İ|Ö|Ü|e|i|ö|ü)ğ/g, "$1g")

		.replace(/(K|G)Â/g, "$1YA")
		.replace(/(K|G|k|g)â/g, "$1ya")
		.replace(/(K|G)Û/g, "$1YU")
		.replace(/(K|G|k|g)û/g, "$1yu")

		.replace(/Â/g, "A")
		.replace(/â/g, "a")
		.replace(/Î/g, "İẎ")
		.replace(/î/g, "iẏ")
		.replace(/Û/g, "U")
		.replace(/û/g, "u")

		.replace(/A/g, "Ա")
		.replace(/a/g, "ա")
		.replace(/B/g, "Պ")
		.replace(/b/g, "պ")
		.replace(/C/g, "Ճ")
		.replace(/c/g, "ճ")
		.replace(/Ç/g, "Չ")
		.replace(/ç/g, "չ")
		.replace(/D/g, "Տ")
		.replace(/d/g, "տ")
		.replace(/E/g, "Է")
		.replace(/e/g, "է")
		.replace(/F/g, "Ֆ")
		.replace(/f/g, "ֆ")
		.replace(/G/g, "Կ")
		.replace(/g/g, "կ")
		.replace(/Ġ/g, "Ղ")
		.replace(/ġ/g, "ղ")
		.replace(/H/g, "Հ")
		.replace(/h/g, "հ")
		.replace(/I/g, "Ը")
		.replace(/ı/g, "ը")
		.replace(/İ/g, "Ի")
		.replace(/i/g, "ի")
		.replace(/J/g, "Ժ")
		.replace(/j/g, "ժ")
		.replace(/K/g, "Ք")
		.replace(/k/g, "ք")
		.replace(/Ḳ/g, "Գ")
		.replace(/ḳ/g, "գ")
		.replace(/L/g, "Լ")
		.replace(/l/g, "լ")
		.replace(/M/g, "Մ")
		.replace(/m/g, "մ")
		.replace(/N/g, "Ն")
		.replace(/n/g, "ն")
		.replace(/Ñ/g, "ՆԿ")
		.replace(/ñ/g, "նկ")
		.replace(/O/g, "Օ")
		.replace(/o/g, "օ")
		.replace(/Ö/g, "Էօ")
		.replace(/ö/g, "էօ")
		.replace(/P/g, "Փ")
		.replace(/p/g, "փ")
		.replace(/Q/g, "Գ")
		.replace(/q/g, "գ")
		.replace(/R/g, "Ր")
		.replace(/r/g, "ր")
		.replace(/S/g, "Ս")
		.replace(/s/g, "ս")
		.replace(/Ş/g, "Շ")
		.replace(/ş/g, "շ")
		.replace(/T/g, "Թ")
		.replace(/t/g, "թ")
		.replace(/U/g, "Ու")
		.replace(/u/g, "ու")
		.replace(/Ü/g, "Իւ")
		.replace(/ü/g, "իւ")
		.replace(/V/g, "Վ")
		.replace(/v/g, "վ")
		.replace(/W/g, "Վ")
		.replace(/w/g, "վ")
		.replace(/X/g, "Խ")
		.replace(/x/g, "խ")
		.replace(/Y/g, "Ե")
		.replace(/y/g, "ե")
		.replace(/Ẏ/g, "Յ")
		.replace(/ẏ/g, "յ")
		.replace(/Z/g, "Զ")
		.replace(/z/g, "զ")

		.replace(/\u002e/g, "\u0589")
		.replace(/\u003a/g, "\u2024")
		.replace(/\u003b/g, "\u055d")
		.replace(/\u002d/g, "\u058a");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}