function cyrlat() {
	document.transcription.text1.value = document.transcription.text1.value
		.replace(/<</g, "«")
		.replace(/>>/g, "»");

	document.transcription.text2.value = document.transcription.text1.value
		.replace(/(\u2019|\u0027|\u02bc)/g, "\u0022")

		.replace(/(\p{Lu})(\p{Lu}) Я/ug, "$1$2 ЙА")
		.replace(/Я (\p{Lu})(\p{Lu})/ug, "ЙА $1$2")
		.replace(/Я(\p{Lu})/ug, "ЙА$1")
		.replace(/Я/g, "Йа")
		.replace(/я/g, "йа")
		.replace(/(\p{Lu})(\p{Lu}) Є/ug, "$1$2 ЙЕ")
		.replace(/Є (\p{Lu})(\p{Lu})/ug, "ЙЕ $1$2")
		.replace(/Є(\p{Lu})/ug, "ЙЕ$1")
		.replace(/Є/g, "Йе")
		.replace(/є/g, "йе")
		.replace(/(\p{Lu})(\p{Lu}) Ї/ug, "$1$2 ЙІ")
		.replace(/Ї (\p{Lu})(\p{Lu})/ug, "ЙІ $1$2")
		.replace(/Ї(\p{Lu})/ug, "ЙІ$1")
		.replace(/Ї/g, "Йі")
		.replace(/ї/g, "йі")
		.replace(/(\p{Lu})(\p{Lu}) Ю/ug, "$1$2 ЙУ")
		.replace(/Ю (\p{Lu})(\p{Lu})/ug, "ЙУ $1$2")
		.replace(/Ю(\p{Lu})/ug, "ЙУ$1")
		.replace(/Ю/g, "Йу")
		.replace(/ю/g, "йу")
		.replace(/(\p{Lu})(\p{Lu}) Щ/ug, "$1$2 ШЧ")
		.replace(/Щ (\p{Lu})(\p{Lu})/ug, "ШЧ $1$2")
		.replace(/Щ(\p{Lu})/ug, "ШЧ$1")
		.replace(/Щ/g, "Шч")
		.replace(/щ/g, "шч")

		.replace(/а/g, "a")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "h")
		.replace(/ґ/g, "g")
		.replace(/д/g, "d")
		.replace(/е/g, "e")
		.replace(/ж/g, "ž")
		.replace(/з/g, "z")
		.replace(/и/g, "y")
		.replace(/і/g, "i")
		.replace(/й/g, "j")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/о/g, "o")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ф/g, "f")
		.replace(/х/g, "x")
		.replace(/ц/g, "c")
		.replace(/ч/g, "č")
		.replace(/ш/g, "š")

		.replace(/А/g, "A")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "H")
		.replace(/Ґ/g, "G")
		.replace(/Д/g, "D")
		.replace(/Е/g, "E")
		.replace(/Ж/g, "Ž")
		.replace(/З/g, "Z")
		.replace(/И/g, "Y")
		.replace(/І/g, "I")
		.replace(/Й/g, "J")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/О/g, "O")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "X")
		.replace(/Ц/g, "C")
		.replace(/Ч/g, "Č")
		.replace(/Ш/g, "Š")
		.replace(/(Ь|ь)/g, "\u0027");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}