var car;
function cyrlat () {
car = document.transcription.text1.value;
  car = car.replace(/iang/g, "yáng");
  car = car.replace(/ying/g, "íng");
  car = car.replace(/iong|yong/g, "yúng");
  car = car.replace(/uang|wang/g, "váng");
  car = car.replace(/weng/g, "vıng");
  car = car.replace(/juan/g, "jüén");
  car = car.replace(/quan/g, "qüén");
  car = car.replace(/xuan/g, "xüén");
  car = car.replace(/lüan/g, "lüén");
  car = car.replace(/yuan/g, "üén");
  car = car.replace(/zhi/g, "zhı");
  car = car.replace(/chi/g, "chı");
  car = car.replace(/shi/g, "shı");
  car = car.replace(/eng/g, "ıng");
  car = car.replace(/ong/g, "úng");
  car = car.replace(/iao|yao/g, "yáú");
  car = car.replace(/ian|yan/g, "yén");
  car = car.replace(/yin/g, "ín");
  car = car.replace(/uai|wai/g, "váy");
  car = car.replace(/ui|wei/g, "véy");
  car = car.replace(/uan|wan/g, "ván");
  car = car.replace(/un|wen/g, "vın");
  car = car.replace(/jue/g, "jüé");
  car = car.replace(/que/g, "qüé");
  car = car.replace(/xue/g, "xüé");
  car = car.replace(/yue/g, "üé");
  car = car.replace(/jun/g, "jün");
  car = car.replace(/qun/g, "qün");
  car = car.replace(/xun/g, "xün");
  car = car.replace(/yun/g, "ün");
  car = car.replace(/zi/g, "zı");
  car = car.replace(/ci/g, "cı");
  car = car.replace(/si/g, "sı");
  car = car.replace(/ri/g, "rı");
  car = car.replace(/ai/g, "áy");
  car = car.replace(/ei/g, "éy");
  car = car.replace(/ao/g, "áú");
  car = car.replace(/en/g, "ın");
  car = car.replace(/er/g, "ár");
  car = car.replace(/ia/g, "yá");
  car = car.replace(/ie/g, "yé");
  car = car.replace(/iu/g, "yóú");
  car = car.replace(/ua|wa/g, "vá");
  car = car.replace(/uo|wo/g, "vó");
  car = car.replace(/bo/g, "bvó");
  car = car.replace(/po/g, "pvó");
  car = car.replace(/mo/g, "mvó");
  car = car.replace(/fo/g, "fvó");
  car = car.replace(/ju/g, "jü");
  car = car.replace(/qu/g, "qü");
  car = car.replace(/xu/g, "xü");
  car = car.replace(/io/g, "yó");
  car = car.replace(/yu/g, "ü");
  car = car.replace(/wu/g, "ú");
  car = car.replace(/yi/g, "í");
  car = car.replace(/e/g, "ı");
  car = car.replace(/ê/g, "é");
  car = car.replace(/ch/g, "ç");
  car = car.replace(/c/g, "ts");
  car = car.replace(/j/g, "c");
  car = car.replace(/r/g, "j");
  car = car.replace(/q/g, "ç");
  car = car.replace(/x/g, "ş");
  car = car.replace(/zh/g, "c");
  car = car.replace(/sh/g, "ş");

  car = car.replace(/á/g, "a");
  car = car.replace(/é/g, "e");
  car = car.replace(/í/g, "i");
  car = car.replace(/ó/g, "o");
  car = car.replace(/ú/g, "u");
document.transcription.text2.value=car;
}
function copy1()
{ textRange=document.transcription.text1.createTextRange();   textRange.execCommand("Copy");   textRange="";
}
function copy2()
{ textRange=document.transcription.text2.createTextRange();   textRange.execCommand("Copy");   textRange="";
}
