var car;
function cyrlat () {
car = document.transcription.text1.value;
  car = car.replace(/(b|p|m|f)o/g, "$1uo");
  car = car.replace(/(j|q|x)u/g, "$1ü");
  
  car = car.replace(/y(a|e|o)/g, "\u0027i$1");
  car = car.replace(/yi/g, "\u0027i");
  car = car.replace(/w(a|e|o)/g, "\u0027u$1");
  car = car.replace(/wu/g, "\u0027u");
  car = car.replace(/yu/g, "\u0027ü");
  
  car = car.replace(/iang/g, "йанғ");
  car = car.replace(/iong/g, "йунғ");
  car = car.replace(/uang/g, "ванғ");
  car = car.replace(/ang/g, "анғ");
  car = car.replace(/eng/g, "ынғ");
  car = car.replace(/ong/g, "унғ");
  car = car.replace(/iao/g, "йав");
  car = car.replace(/ian/g, "йен");
  car = car.replace(/ing/g, "инғ");
  car = car.replace(/uai/g, "вай");
  car = car.replace(/uan/g, "ван");
  car = car.replace(/ong/g, "вынғ");
  car = car.replace(/üan/g, "үен");
  car = car.replace(/iou/g, "йов");
  car = car.replace(/uei/g, "вей");
  car = car.replace(/uen/g, "вын");
  car = car.replace(/ai/g, "ай");
  car = car.replace(/ei/g, "ей");
  car = car.replace(/ao/g, "ав");
  car = car.replace(/ou/g, "ов");
  car = car.replace(/an/g, "ан");
  car = car.replace(/en/g, "ын");
  car = car.replace(/er/g, "ар");
  car = car.replace(/ia/g, "йа");
  car = car.replace(/ie/g, "йе");
  car = car.replace(/iu/g, "йов");
  car = car.replace(/in/g, "ин");
  car = car.replace(/ua/g, "ва");
  car = car.replace(/uo/g, "во");
  car = car.replace(/ui/g, "вей");
  car = car.replace(/un/g, "вын");
  car = car.replace(/üe/g, "үе");
  car = car.replace(/ün/g, "үн");
  car = car.replace(/io/g, "йо");
  car = car.replace(/a/g, "а");
  car = car.replace(/e/g, "ы");
  car = car.replace(/u/g, "у");
  car = car.replace(/ü/g, "ү");
  car = car.replace(/ê/g, "е");
  car = car.replace(/o/g, "о");
  
  car = car.replace(/қ/g, "q");
  car = car.replace(/ў/g, "w");
  car = car.replace(/е/g, "e");
  car = car.replace(/р/g, "r");
  car = car.replace(/т/g, "t");
  car = car.replace(/й/g, "y");
  car = car.replace(/у/g, "u");
  car = car.replace(/ы/g, "ı");
  car = car.replace(/о/g, "o");
  car = car.replace(/п/g, "p");
  car = car.replace(/ғ/g, "ğ");
  car = car.replace(/ү/g, "ü");
  car = car.replace(/а/g, "a");
  car = car.replace(/с/g, "s");
  car = car.replace(/д/g, "d");
  car = car.replace(/ф/g, "f");
  car = car.replace(/г/g, "g");
  car = car.replace(/һ/g, "h");
  car = car.replace(/ж/g, "j");
  car = car.replace(/к/g, "k");
  car = car.replace(/л/g, "l");
  car = car.replace(/ш/g, "ş");
  car = car.replace(/и/g, "i");
  car = car.replace(/з/g, "z");
  car = car.replace(/х/g, "x");
  car = car.replace(/ц/g, "c");
  car = car.replace(/в/g, "v");
  car = car.replace(/б/g, "b");
  car = car.replace(/н/g, "n");
  car = car.replace(/м/g, "m");
  car = car.replace(/ө/g, "ö");
  car = car.replace(/ч/g, "ç");
  car = car.replace(/Қ/g, "Q");
  car = car.replace(/Ў/g, "W");
  car = car.replace(/Е/g, "E");
  car = car.replace(/Р/g, "R");
  car = car.replace(/Т/g, "T");
  car = car.replace(/Й/g, "Y");
  car = car.replace(/У/g, "U");
  car = car.replace(/Ы/g, "I");
  car = car.replace(/О/g, "O");
  car = car.replace(/П/g, "P");
  car = car.replace(/Ғ/g, "Ğ");
  car = car.replace(/Ү/g, "Ü");
  car = car.replace(/А/g, "A");
  car = car.replace(/С/g, "S");
  car = car.replace(/Д/g, "D");
  car = car.replace(/Ф/g, "F");
  car = car.replace(/Г/g, "G");
  car = car.replace(/Һ/g, "H");
  car = car.replace(/Ж/g, "J");
  car = car.replace(/К/g, "K");
  car = car.replace(/Л/g, "L");
  car = car.replace(/Ш/g, "Ş");
  car = car.replace(/И/g, "İ");
  car = car.replace(/З/g, "Z");
  car = car.replace(/Х/g, "X");
  car = car.replace(/Ц/g, "C");
  car = car.replace(/В/g, "V");
  car = car.replace(/Б/g, "B");
  car = car.replace(/Н/g, "N");
  car = car.replace(/М/g, "M");
  car = car.replace(/Ө/g, "Ö");
  car = car.replace(/Ч/g, "Ç");
 
document.transcription.text2.value=car;
}
function copy1()
{ textRange=document.transcription.text1.createTextRange();   textRange.execCommand("Copy");   textRange="";
}
function copy2()
{ textRange=document.transcription.text2.createTextRange();   textRange.execCommand("Copy");   textRange="";
}
