function latcyr() {

	document.transcription.text2.value = document.transcription.text2.value
		.replace(/ň/g, "ñ")
		.replace(/Ň/g, "Ñ")
		.replace(/è/g, "ä")
		.replace(/È/g, "Ä")
		.replace(/ə/g, "ä")
		.replace(/Ə/g, "Ä")
		.replace(/ê/g, "ä")
		.replace(/Ê/g, "Ä")
		.replace(/w/g, "v")
		.replace(/W/g, "V");

	document.transcription.text1.value = document.transcription.text2.value
		.replace(/ə/g, "ä")
		.replace(/ě/g, "ä")
		.replace(/â/g, "a")
		.replace(/î/g, "i")
		.replace(/û/g, "u")
		.replace(/è/g, "ä")
		.replace(/j/g, "ž")
		.replace(/c/g, "j")
		.replace(/ñ/g, "ň")
		.replace(/v/g, "w")
		.replace(/y/g, "ý")
		.replace(/ı/g, "y")
		.replace(/q/g, "g")
		.replace(/ğ/g, "g")
		.replace(/x/g, "h")
		.replace(/Ə/g, "Ä")
		.replace(/Ě/g, "Ä")
		.replace(/Â/g, "A")
		.replace(/Î/g, "I")
		.replace(/Û/g, "U")
		.replace(/È/g, "Ä")
		.replace(/Y/g, "Ý")
		.replace(/I/g, "Y")
		.replace(/İ/g, "I")
		.replace(/J/g, "Ž")
		.replace(/C/g, "J")
		.replace(/Ñ/g, "Ň")
		.replace(/V/g, "W")
		.replace(/Q/g, "G")
		.replace(/Ğ/g, "G")
		.replace(/X/g, "H");
}

function cyrlat() {
	document.transcription.text1.value = document.transcription.text1.value
		.replace(/c/g, "ç")
		.replace(/C/g, "Ç");

	document.transcription.text2.value = document.transcription.text1.value
		.replace(/ҳ/g, "х")
		.replace(/Ҳ/g, "Х")
		.replace(/һ/g, "х")
		.replace(/Һ/g, "Х")
		.replace(/ҹ/g, "җ")
		.replace(/Ҹ/g, "Җ")
		.replace(/ҝ/g, "г")
		.replace(/Ҝ/g, "Г")
		.replace(/ғ/g, "г")
		.replace(/Ғ/g, "Г")
		.replace(/јо/g, "ё")
		.replace(/Јо/g, "Ё")
		.replace(/ЈО/g, "Ё")
		.replace(/ју/g, "ю")
		.replace(/Ју/g, "Ю")
		.replace(/ЈУ/g, "Ю")
		.replace(/ја/g, "я")
		.replace(/Ја/g, "Я")
		.replace(/ЈА/g, "Я")
		.replace(/ј/g, "й")
		.replace(/Ј/g, "Й")

		.replace(/ю/g, "йу")
		.replace(/ё/g, "йо")
		.replace(/я/g, "йа")
		.replace(/Ю/g, "Йу")
		.replace(/Ё/g, "Йо")
		.replace(/Я/g, "Йа")
		.replace(/ае/g, "аýe")
		.replace(/ее/g, "еýe")
		.replace(/әе/g, "әýe")
		.replace(/эе/g, "эýe")
		.replace(/ые/g, "ыýe")
		.replace(/ие/g, "иýe")
		.replace(/йе/g, "йýe")
		.replace(/ое/g, "оýe")
		.replace(/өе/g, "өýe")
		.replace(/уе/g, "уýe")
		.replace(/үе/g, "үýe")
		.replace(/ье/g, "ьýe")
		.replace(/ъе/g, "ъýe")
		.replace(/Ае/g, "Аýe")
		.replace(/Ее/g, "Еýe")
		.replace(/Әе/g, "Әýe")
		.replace(/Эе/g, "Эýe")
		.replace(/Ые/g, "Ыýe")
		.replace(/Ие/g, "Иýe")
		.replace(/Йе/g, "Йýe")
		.replace(/Ое/g, "Оýe")
		.replace(/Өе/g, "Өýe")
		.replace(/Уе/g, "Уýe")
		.replace(/Үе/g, "Үýe")
		.replace(/Ье/g, "Ьýe")
		.replace(/Ъе/g, "Ъýe")
		.replace(/АЕ/g, "АÝE")
		.replace(/ЕЕ/g, "ЕÝE")
		.replace(/ӘЕ/g, "ӘÝE")
		.replace(/ЭЕ/g, "ЭÝE")
		.replace(/ЫЕ/g, "ЫÝE")
		.replace(/ИЕ/g, "ИÝE")
		.replace(/ЙЕ/g, "ЙÝE")
		.replace(/ОЕ/g, "ОÝE")
		.replace(/ӨЕ/g, "ӨÝE")
		.replace(/УЕ/g, "УÝE")
		.replace(/ҮЕ/g, "ҮÝE")
		.replace(/ЬЕ/g, "ЬÝE")
		.replace(/ЪЕ/g, "ЪÝE")
		.replace(/ е/g, " ýe")
		.replace(/^е/g, "ýe")
		.replace(/-е/g, "-ýe")
		.replace(/–е/g, "–ýe")
		.replace(/:е/g, ":ýe")
		.replace(/\nе/g, "\nýe")
		.replace(/ Е/g, " Ýe")
		.replace(/^Е/g, "Ýe")
		.replace(/-Е/g, "-Ýe")
		.replace(/–Е/g, "–Ýe")
		.replace(/:Е/g, ":Ýe")
		.replace(/\nЕ/g, "\nÝe")
		.replace(/а/g, "a")
		.replace(/б/g, "b")
		.replace(/ч/g, "ç")
		.replace(/д/g, "d")
		.replace(/э/g, "e")
		.replace(/е/g, "e")
		.replace(/ә/g, "ä")
		.replace(/ф/g, "f")
		.replace(/г/g, "g")
		.replace(/х/g, "h")
		.replace(/и/g, "i")
		.replace(/җ/g, "j")
		.replace(/ж/g, "ž")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/ң/g, "ň")
		.replace(/о/g, "o")
		.replace(/ө/g, "ö")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/ц/g, "s")
		.replace(/ш/g, "ş")
		.replace(/щ/g, "şç")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ү/g, "ü")
		.replace(/в/g, "w")
		.replace(/ы/g, "y")
		.replace(/й/g, "ý")
		.replace(/з/g, "z")
		.replace(/ь/g, "")
		.replace(/ъ/g, "")
		.replace(/А/g, "A")
		.replace(/Б/g, "B")
		.replace(/Ч/g, "Ç")
		.replace(/Д/g, "D")
		.replace(/Э/g, "E")
		.replace(/Е/g, "E")
		.replace(/Ә/g, "Ä")
		.replace(/Ф/g, "F")
		.replace(/Г/g, "G")
		.replace(/Х/g, "H")
		.replace(/И/g, "I")
		.replace(/Җ/g, "J")
		.replace(/Ж/g, "Ž")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/Ң/g, "Ň")
		.replace(/О/g, "O")
		.replace(/Ө/g, "Ö")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Ц/g, "S")
		.replace(/Ш/g, "Ş")
		.replace(/Щ/g, "Şç")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ү/g, "Ü")
		.replace(/В/g, "W")
		.replace(/Ы/g, "Y")
		.replace(/Й/g, "Ý")
		.replace(/З/g, "Z")
		.replace(/Ь/g, "")
		.replace(/Ъ/g, "")

		.replace(/j/g, "c")
		.replace(/ž/g, "j")
		.replace(/ň/g, "ñ")
		.replace(/y/g, "ı")
		.replace(/g/g, "ğ")
		.replace(/w/g, "v")
		.replace(/ý/g, "y")
		.replace(/I/g, "İ")
		.replace(/J/g, "C")
		.replace(/Ž/g, "J")
		.replace(/Ň/g, "Ñ")
		.replace(/Y/g, "I")
		.replace(/G/g, "Ğ")
		.replace(/W/g, "V")
		.replace(/Ý/g, "Y")
		.replace(/kğ/g, "kg")
		.replace(/ ğ/g, " g")
		.replace(/^ğ/g, "g")
		.replace(/-ğ/g, "-g")
		.replace(/–ğ/g, "–g")
		.replace(/:ğ/g, ":g")
		.replace(/\.ğ/g, "\.g")
		.replace(/\?ğ/g, "\?g")
		.replace(/\!ğ/g, "\!g")
		.replace(/\;ğ/g, "\;g")
		.replace(/\nğ/g, "\ng")
		.replace(/KĞ/g, "KG")
		.replace(/ Ğ/g, " G")
		.replace(/^Ğ/g, "G")
		.replace(/-Ğ/g, "-G")
		.replace(/–Ğ/g, "–G")
		.replace(/:Ğ/g, ":G")
		.replace(/\.Ğ/g, "\.G")
		.replace(/\?Ğ/g, "\?G")
		.replace(/\!Ğ/g, "\!G")
		.replace(/\;Ğ/g, "\;G")
		.replace(/\nĞ/g, "\nG");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}