function topleft() {
	document.transcription.text1.value = document.transcription.text1.value
	.replace(/(\p{Script=Cyrl})(I|1)/ug, "$1Ӏ")
	.replace(/(I|1)(\p{Script=Cyrl})/ug, "Ӏ$2")
	.replace(/(\p{Script=Cyrl})l/ug, "$1ӏ")
	.replace(/l(\p{Script=Cyrl})/ug, "ӏ$1")
	.replace(/(\p{Lowercase})( )?Ӏ/ug, "$1$2ӏ")
	.replace(/(\p{Uppercase})( )?Ӏ( )?(\p{Lowercase})/ug, "$1$2ӏ$3$4");
	
	document.transcription.text2.value = document.transcription.text1.value
	.replace(/(А|Е|Ё|И|О|У|Ы|Ю|Я)Щ(А|Е|Ё|И|О|У|Ы|Ю|Я)/g, "$1ШШ$2")
	.replace(/(А|Е|Ё|И|О|У|Ы|Ю|Я)щ(а|е|ё|и|о|у|ы|ю|я)/g, "$1Шш$2")
	.replace(/(а|е|ё|и|о|у|ы|ю|я)щ(а|е|ё|и|о|у|ы|ю|я)/g, "$1шш$2")
	.replace(/щ/g, "ш")
	.replace(/Щ/g, "Ш")

	.replace(/(Б|В|Г|Д|Ж|З|Й|К|КЪ|Л|М|Н|П|Р|С|Т|Ф|Х|ХЬ|Ц|Ч|Ш|Ӏ)Е/g, "$1Э")
	.replace(/(Б|В|Г|Д|Ж|З|Й|К|Къ|Л|М|Н|П|Р|С|Т|Ф|Х|Хь|Ц|Ч|Ш|Ӏ|б|в|г|д|ж|з|й|к|къ|л|м|н|п|р|с|т|ф|х|хь|ц|ч|ш|ӏ)е/g, "$1э")

	.replace(/(Б|В|Г|Д|Ж|З|К|Л|М|Н|П|Р|С|Т|Ф|Ц|Ч|Ш)ЬИ/g, "$1ЙИ")
	.replace(/(Б|В|Г|Д|Ж|З|К|Л|М|Н|П|Р|С|Т|Ф|Ц|Ч|Ш|б|в|г|д|ж|з|к|л|м|н|п|р|с|т|ф|ц|ч|ш)ьи/g, "йи")

	.replace(/(\p{Uppercase})(\p{Uppercase}) Я/ug, "$1$2 ЙА")
	.replace(/(\p{Uppercase})Я/ug, "$1ЙА")
	.replace(/Я (\p{Uppercase})(\p{Uppercase})/ug, "ЙА $1$2")
	.replace(/Я(\p{Uppercase})/ug, "ЙА$1")
	.replace(/Я/g, "Йа")
	.replace(/я/g, "йа")
	.replace(/(\p{Uppercase})(\p{Uppercase}) Е/ug, "$1$2 ЙЭ")
	.replace(/(\p{Uppercase})Е/ug, "$1ЙЭ")
	.replace(/Е (\p{Uppercase})(\p{Uppercase})/ug, "ЙЭ $1$2")
	.replace(/Е(\p{Uppercase})/ug, "ЙЭ$1")
	.replace(/Е/g, "Йэ")
	.replace(/е/g, "йэ")
	.replace(/(\p{Uppercase})(\p{Uppercase}) Ё/ug, "$1$2 ЙО")
	.replace(/(\p{Uppercase})Ё/ug, "$1ЙО")
	.replace(/Ё (\p{Uppercase})(\p{Uppercase})/ug, "ЙО $1$2")
	.replace(/Ё(\p{Uppercase})/ug, "ЙО$1")
	.replace(/Ё/g, "Йо")
	.replace(/ё/g, "йо")
	.replace(/(\p{Uppercase})(\p{Uppercase}) Ю/ug, "$1$2 ЙУ")
	.replace(/(\p{Uppercase})Ю/ug, "$1ЙУ")
	.replace(/Ю (\p{Uppercase})(\p{Uppercase})/ug, "ЙУ $1$2")
	.replace(/Ю(\p{Uppercase})/ug, "ЙУ$1")
	.replace(/Ю/g, "Йу")
	.replace(/ю/g, "йу")

	.replace(/аь/g, "ä")
	.replace(/ккъ/g, "qqh")
	.replace(/къ/g, "qh")
	.replace(/ккх/g, "qq")
	.replace(/кх/g, "q")
	.replace(/оь/g, "ö")
	.replace(/уь/g, "ü")
	.replace(/ххь/g, "ħħ")
	.replace(/хь/g, "ħ")
	.replace(/ххӏ/g, "hh")
	.replace(/хӏ/g, "h")
	.replace(/А(Ь|ь)/g, "Ä")
	.replace(/Ккъ/g, "Qqh")
	.replace(/ККЪ/g, "QQH")
	.replace(/Къ/g, "Qh")
	.replace(/КЪ/g, "QH")
	.replace(/Ккх/g, "Qq")
	.replace(/ККХ/g, "QQ")
	.replace(/К(Х|х)/g, "Q")
	.replace(/О(Ь|ь)/g, "Ö")
	.replace(/У(Ь|ь)/g, "Ü")
	.replace(/Ххь/g, "Ħħ")
	.replace(/ХХЬ/g, "ĦĦ")
	.replace(/Х(Ь|ь)/g, "Ħ")
	.replace(/Ххӏ/g, "Hh")
	.replace(/ХХӀ/g, "HH")
	.replace(/Х(Ӏ|ӏ)/g, "H")
    .replace(/([ГКПТЦЧ])Ӏ/g, "$1H")
	.replace(/([ГКПТЦЧгкптцч])ӏ/g, "$1h")

	.replace(/а/g, "a")
	.replace(/б/g, "b")
	.replace(/в/g, "v")
	.replace(/г/g, "g")
	.replace(/д/g, "d")
	.replace(/ж/g, "j")
	.replace(/з/g, "z")
	.replace(/и/g, "i")
	.replace(/й/g, "y")
	.replace(/к/g, "k")
	.replace(/л/g, "l")
	.replace(/м/g, "m")
	.replace(/н/g, "n")
	.replace(/о/g, "o")
	.replace(/п/g, "p")
	.replace(/р/g, "r")
	.replace(/с/g, "s")
	.replace(/т/g, "t")
	.replace(/у/g, "u")
	.replace(/ф/g, "f")
	.replace(/х/g, "x")
	.replace(/ц/g, "c")
	.replace(/ч/g, "ĉ")
	.replace(/ш/g, "ŝ")
	.replace(/ъ/g, "\u02bc")
	.replace(/ы/g, "i")
	.replace(/ь/g, "")
	.replace(/э/g, "e")
	.replace(/ӏ/g, "ĥ")
	.replace(/А/g, "A")
	.replace(/Б/g, "B")
	.replace(/В/g, "V")
	.replace(/Г/g, "G")
	.replace(/Д/g, "D")
	.replace(/Ж/g, "J")
	.replace(/З/g, "Z")
	.replace(/И/g, "I")
	.replace(/Й/g, "Y")
	.replace(/К/g, "K")
	.replace(/Л/g, "L")
	.replace(/М/g, "M")
	.replace(/Н/g, "N")
	.replace(/О/g, "O")
	.replace(/П/g, "P")
	.replace(/Р/g, "R")
	.replace(/С/g, "S")
	.replace(/Т/g, "T")
	.replace(/У/g, "U")
	.replace(/Ф/g, "F")
	.replace(/Х/g, "X")
	.replace(/Ц/g, "C")
	.replace(/Ч/g, "Ĉ")	
	.replace(/Ш/g, "Ŝ")
	.replace(/Ъ/g, "\u02bc")
	.replace(/Ы/g, "I")
	.replace(/Ь/g, "")
	.replace(/Э/g, "E")
	.replace(/Ӏ/g, "Ĥ")

	.replace(/\u2039/g, "\u2018")
	.replace(/\u203a/g, "\u2019")
	.replace(/\u00ab/g, "\u201c")
	.replace(/\u00bb/g, "\u201d");
}

function topright() {
	document.transcription.text1.value = document.transcription.text1.value
	.replace(/(\p{Script=Cyrl})(I|1)/ug, "$1Ӏ")
	.replace(/(I|1)(\p{Script=Cyrl})/ug, "Ӏ$2")
	.replace(/(\p{Script=Cyrl})l/ug, "$1ӏ")
	.replace(/l(\p{Script=Cyrl})/ug, "ӏ$1")
	.replace(/(\p{Lowercase})( )?Ӏ/ug, "$1$2ӏ")
	.replace(/(\p{Uppercase})( )?Ӏ( )?(\p{Lowercase})/ug, "$1$2ӏ$3$4");
	
	document.transcription.text3.value = document.transcription.text1.value
	.replace(/(\p{Uppercase})(\p{Uppercase}) Щ/ug, "$1$2 ШЧ")
	.replace(/(\p{Uppercase})Щ/ug, "$1ШЧ")
	.replace(/Щ (\p{Uppercase})(\p{Uppercase})/ug, "ШЧ $1$2")
	.replace(/Щ(\p{Uppercase})/ug, "ШЧ$1")
	.replace(/Щ/g, "Шч")
	.replace(/щ/g, "шч")
	
	.replace(/(Б|В|Г|Д|Ж|З|Й|К|КЪ|Л|М|Н|П|Р|С|Т|Ф|Х|ХЬ|Ц|Ч|Ш|Ӏ)Е/g, "$1Э")
	.replace(/(Б|В|Г|Д|Ж|З|Й|К|Къ|Л|М|Н|П|Р|С|Т|Ф|Х|Хь|Ц|Ч|Ш|Ӏ|б|в|г|д|ж|з|й|к|къ|л|м|н|п|р|с|т|ф|х|хь|ц|ч|ш|ӏ)е/g, "$1э")

	.replace(/(Б|В|Г|Д|Ж|З|К|Л|М|Н|П|Р|С|Т|Ф|Ц|Ч|Ш)ЬИ/g, "$1ЙИ")
	.replace(/(Б|В|Г|Д|Ж|З|К|Л|М|Н|П|Р|С|Т|Ф|Ц|Ч|Ш|б|в|г|д|ж|з|к|л|м|н|п|р|с|т|ф|ц|ч|ш)ьи/g, "йи")

	.replace(/(\p{Uppercase})(\p{Uppercase}) Я/ug, "$1$2 ЙА")
	.replace(/(\p{Uppercase})Я/ug, "$1ЙА")
	.replace(/Я (\p{Uppercase})(\p{Uppercase})/ug, "ЙА $1$2")
	.replace(/Я(\p{Uppercase})/ug, "ЙА$1")
	.replace(/Я/g, "Йа")
	.replace(/я/g, "йа")
	.replace(/(\p{Uppercase})(\p{Uppercase}) Е/ug, "$1$2 ЙЭ")
	.replace(/(\p{Uppercase})Е/ug, "$1ЙЭ")
	.replace(/Е (\p{Uppercase})(\p{Uppercase})/ug, "ЙЭ $1$2")
	.replace(/Е(\p{Uppercase})/ug, "ЙЭ$1")
	.replace(/Е/g, "Йэ")
	.replace(/е/g, "йэ")
	.replace(/(\p{Uppercase})(\p{Uppercase}) Ё/ug, "$1$2 ЙО")
	.replace(/(\p{Uppercase})Ё/ug, "$1ЙО")
	.replace(/Ё (\p{Uppercase})(\p{Uppercase})/ug, "ЙО $1$2")
	.replace(/Ё(\p{Uppercase})/ug, "ЙО$1")
	.replace(/Ё/g, "Йо")
	.replace(/ё/g, "йо")
	.replace(/(\p{Uppercase})(\p{Uppercase}) Ю/ug, "$1$2 ЙУ")
	.replace(/(\p{Uppercase})Ю/ug, "$1ЙУ")
	.replace(/Ю (\p{Uppercase})(\p{Uppercase})/ug, "ЙУ $1$2")
	.replace(/Ю(\p{Uppercase})/ug, "ЙУ$1")
	.replace(/Ю/g, "Йу")
	.replace(/ю/g, "йу")

	.replace(/аь/g, "ä")
	.replace(/ккъ/g, "q̇q̇")
	.replace(/къ/g, "q̇")
	.replace(/ккх/g, "qq")
	.replace(/кх/g, "q")
	.replace(/оь/g, "ö")
	.replace(/уь/g, "ü")
	.replace(/ххь/g, "ẋẋ")
	.replace(/хь/g, "ẋ")
	.replace(/ххӏ/g, "hh")
	.replace(/гӏ/g, "ġ")
	.replace(/хӏ/g, "h")
	.replace(/цӏ/g, "ċ")
	.replace(/чӏ/g, "ç̇")
	.replace(/А(Ь|ь)/g, "Ä")
	.replace(/Ккъ/g, "Q̇q̇")
	.replace(/ККЪ/g, "Q̇Q̇")
	.replace(/Къ/g, "Q̇")
	.replace(/КЪ/g, "Q̇")
	.replace(/Ккх/g, "Qq")
	.replace(/ККХ/g, "QQ")
	.replace(/К(Х|х)/g, "Q")
	.replace(/О(Ь|ь)/g, "Ö")
	.replace(/У(Ь|ь)/g, "Ü")
	.replace(/Ххь/g, "Ẋẋ")
	.replace(/ХХЬ/g, "ẊẊ")
	.replace(/Х(Ь|ь)/g, "Ẋ")
	.replace(/Ххӏ/g, "Hh")
	.replace(/ХХӀ/g, "HH")
	.replace(/Г(Ӏ|ӏ)/g, "Ġ")
	.replace(/Х(Ӏ|ӏ)/g, "H")
	.replace(/Ц(Ӏ|ӏ)/g, "Ċ")
	.replace(/Ч(Ӏ|ӏ)/g, "Ç̇")
	.replace(/(К|П|Т)Ӏ/g, "$1H")
	.replace(/(К|П|Т|к|п|т)ӏ/g, "$1h")
	
	.replace(/а/g, "a")
	.replace(/б/g, "b")
	.replace(/в/g, "v")
	.replace(/г/g, "g")
	.replace(/д/g, "d")
	.replace(/ж/g, "ƶ")
	.replace(/з/g, "z")
	.replace(/и/g, "i")
	.replace(/й/g, "y")
	.replace(/к/g, "k")
	.replace(/л/g, "l")
	.replace(/м/g, "m")
	.replace(/н/g, "n")
	.replace(/о/g, "o")
	.replace(/п/g, "p")
	.replace(/р/g, "r")
	.replace(/с/g, "s")
	.replace(/т/g, "t")
	.replace(/у/g, "u")
	.replace(/ф/g, "f")
	.replace(/х/g, "x")
	.replace(/ц/g, "c")
	.replace(/ч/g, "ç")
	.replace(/ш/g, "ş")
	.replace(/ъ/g, "\u2019")
	.replace(/ы/g, "i")
	.replace(/ь/g, "")
	.replace(/э/g, "e")
	.replace(/ӏ/g, "j")
	.replace(/А/g, "A")
	.replace(/Б/g, "B")
	.replace(/В/g, "V")
	.replace(/Г/g, "G")
	.replace(/Д/g, "D")
	.replace(/Ж/g, "Ƶ")
	.replace(/З/g, "Z")
	.replace(/И/g, "I")
	.replace(/Й/g, "Y")
	.replace(/К/g, "K")
	.replace(/Л/g, "L")
	.replace(/М/g, "M")
	.replace(/Н/g, "N")
	.replace(/О/g, "O")
	.replace(/П/g, "P")
	.replace(/Р/g, "R")
	.replace(/С/g, "S")
	.replace(/Т/g, "T")
	.replace(/У/g, "U")
	.replace(/Ф/g, "F")
	.replace(/Х/g, "X")
	.replace(/Ц/g, "C")
	.replace(/Ч/g, "Ç")
	.replace(/Ш/g, "Ş")
	.replace(/Ъ/g, "\u2019")
	.replace(/Ы/g, "I")
	.replace(/Ь/g, "")
	.replace(/Э/g, "E")
	.replace(/Ӏ/g, "J")

	.replace(/\u2039/g, "\u2018")
	.replace(/\u203a/g, "\u2019")
	.replace(/\u00ab/g, "\u201c")
	.replace(/\u00bb/g, "\u201d");
}

function copy1()
{ navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2()
{ navigator.clipboard.writeText(document.transcription.text2.value);
}

function copy3()
{ navigator.clipboard.writeText(document.transcription.text3.value);
}
