function latcyr() {}

function cyrlat() {
	document.transcription.text2.value = document.transcription.text1.value

		.replace(/(А|И|Ы|Е|Э|У|О|Ө|Ё|Ү|Ю|Я|а|и|ы|е|э|у|о|ө|ё|ү|ю|я)ц/g, "$1тс")
		.replace(/(А|И|Ы|Е|Э|У|О|Ө|Ё|Ү|Ю|Я)Ц/g, "$1ТС")
		.replace(/(а|и|ы|е|э|у|о|ө|ё|ү|ю|я)Ц/g, "$1Тс")
		.replace(/Ц/g, "С")
		.replace(/ц/g, "с")

		.replace(/(А|Б|В|Г|Д|Е|Ё|Ж|З|И|Й|К|Л|М|Н|Ң|О|Ө|П|Р|С|Т|У|Ү|Ф|Х|Ц|Ч|Ш|Щ|Ъ|Ы|Ь|Э|Ю|Я|а|б|в|г|д|е|ё|ж|з|и|й|к|л|м|н|ң|о|ө|п|р|с|т|у|ү|ф|х|ц|ч|ш|щ|ъ|ы|ь|э|ю|я)Щ(А|Б|В|Г|Д|Е|Ё|Ж|З|И|Й|К|Л|М|Н|Ң|О|Ө|П|Р|С|Т|У|Ү|Ф|Х|Ц|Ч|Ш|Щ|Ъ|Ы|Ь|Э|Ю|Я)/g, "$1ШШ$2")
		.replace(/(А|Б|В|Г|Д|Е|Ё|Ж|З|И|Й|К|Л|М|Н|Ң|О|Ө|П|Р|С|Т|У|Ү|Ф|Х|Ц|Ч|Ш|Щ|Ъ|Ы|Ь|Э|Ю|Я|а|б|в|г|д|е|ё|ж|з|и|й|к|л|м|н|ң|о|ө|п|р|с|т|у|ү|ф|х|ц|ч|ш|щ|ъ|ы|ь|э|ю|я)Щ(а|б|в|г|д|е|ё|ж|з|и|й|к|л|м|н|ң|о|ө|п|р|с|т|у|ү|ф|х|ц|ч|ш|щ|ъ|ы|ь|э|ю|я)/g, "$1Шш$2")
		.replace(/(А|Б|В|Г|Д|Е|Ё|Ж|З|И|Й|К|Л|М|Н|Ң|О|Ө|П|Р|С|Т|У|Ү|Ф|Х|Ц|Ч|Ш|Щ|Ъ|Ы|Ь|Э|Ю|Я|а|б|в|г|д|е|ё|ж|з|и|й|к|л|м|н|ң|о|ө|п|р|с|т|у|ү|ф|х|ц|ч|ш|щ|ъ|ы|ь|э|ю|я)щ(А|Б|В|Г|Д|Е|Ё|Ж|З|И|Й|К|Л|М|Н|Ң|О|Ө|П|Р|С|Т|У|Ү|Ф|Х|Ц|Ч|Ш|Щ|Ъ|Ы|Ь|Э|Ю|Я|а|б|в|г|д|е|ё|ж|з|и|й|к|л|м|н|ң|о|ө|п|р|с|т|у|ү|ф|х|ц|ч|ш|щ|ъ|ы|ь|э|ю|я)/g, "$1шш$2")
		.replace(/Щ/g, "Ш")
		.replace(/щ/g, "ш")

		.replace(/ е/g, " ýe")
		.replace(/\nе/g, "\nýe")
		.replace(/\rе/g, "\rýe")
		.replace(/^е/g, "ýe")

		.replace(/ае/g, "аýe")
		.replace(/ие/g, "иýe")
		.replace(/ые/g, "ыýe")
		.replace(/ее/g, "еýe")
		.replace(/эе/g, "эýe")
		.replace(/уе/g, "уýe")
		.replace(/ое/g, "оýe")
		.replace(/өе/g, "өýe")
		.replace(/ёе/g, "ёýe")
		.replace(/үе/g, "үýe")
		.replace(/йе/g, "йýe")
		.replace(/юе/g, "юýe")
		.replace(/яе/g, "яýe")
		.replace(/ье/g, "ýe")
		.replace(/ъе/g, "ýe")

		.replace(/ Е/g, " Ýe")
		.replace(/\nЕ/g, "\nÝe")
		.replace(/\rЕ/g, "\rÝe")
		.replace(/^Е/g, "Ýe")

		.replace(/Ае/g, "Аýe")
		.replace(/Ие/g, "Иýe")
		.replace(/Ые/g, "Ыýe")
		.replace(/Ее/g, "Еýe")
		.replace(/Эе/g, "Эýe")
		.replace(/Уе/g, "Уýe")
		.replace(/Ое/g, "Оýe")
		.replace(/Өе/g, "Өýe")
		.replace(/Ёе/g, "Ёýe")
		.replace(/Үе/g, "Үýe")
		.replace(/Йе/g, "Йýe")
		.replace(/Юе/g, "Юýe")
		.replace(/Яе/g, "Яýe")

		.replace(/АЕ/g, "АÝE")
		.replace(/ИЕ/g, "ИÝE")
		.replace(/ЫЕ/g, "ЫÝE")
		.replace(/ЕЕ/g, "ЕÝE")
		.replace(/ЭЕ/g, "ЭÝE")
		.replace(/УЕ/g, "УÝE")
		.replace(/ОЕ/g, "ОÝE")
		.replace(/ӨЕ/g, "ӨÝE")
		.replace(/ЁЕ/g, "ЁÝE")
		.replace(/ҮЕ/g, "ҮÝE")
		.replace(/ЙЕ/g, "ЙÝE")
		.replace(/ЮЕ/g, "ЮÝE")
		.replace(/ЯЕ/g, "ЯÝE")
		.replace(/ЬЕ/g, "ÝE")
		.replace(/ЪЕ/g, "ÝE")

		.replace(/а/g, "a")
		.replace(/б/g, "b")
		.replace(/в/g, "w")
		.replace(/г/g, "g")
		.replace(/д/g, "d")
		.replace(/е/g, "e")
		.replace(/ё/g, "ýo")
		.replace(/ж/g, "j")
		.replace(/з/g, "z")
		.replace(/и/g, "i")
		.replace(/й/g, "ý")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/ң/g, "ň")
		.replace(/о/g, "o")
		.replace(/ө/g, "ö")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ү/g, "ü")
		.replace(/ф/g, "f")
		.replace(/х/g, "h")
		.replace(/ч/g, "ç")
		.replace(/ш/g, "ş")
		.replace(/ъ/g, "")
		.replace(/ы/g, "y")
		.replace(/ь/g, "")
		.replace(/э/g, "e")
		.replace(/ю/g, "ýu")
		.replace(/я/g, "ýa")
		.replace(/А/g, "A")
		.replace(/Б/g, "B")
		.replace(/В/g, "W")
		.replace(/Г/g, "G")
		.replace(/Д/g, "D")
		.replace(/Е/g, "E")
		.replace(/Ё/g, "Ýo")
		.replace(/Ж/g, "J")
		.replace(/З/g, "Z")
		.replace(/И/g, "I")
		.replace(/Й/g, "Ý")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/Ң/g, "Ň")
		.replace(/О/g, "O")
		.replace(/Ө/g, "Ö")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ү/g, "Ü")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "H")
		.replace(/Ч/g, "Ç")
		.replace(/Ш/g, "Ş")
		.replace(/Ъ/g, "")
		.replace(/Ы/g, "Y")
		.replace(/Ь/g, "")
		.replace(/Э/g, "E")
		.replace(/Ю/g, "Ýu")
		.replace(/Я/g, "Ýa");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}