var car;

function cyrlat() {
	document.transcription.text1.value = document.transcription.text1.value
		.replace(/ə/g, "ә")
		.replace(/Ə/g, "Ә");

	document.transcription.text2.value = document.transcription.text1.value
		.replace(/а/g, "a")
		.replace(/ә/g, "á")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/ғ/g, "ǵ")
		.replace(/д/g, "d")
		.replace(/е/g, "e")
		.replace(/ё/g, "ıo")
		.replace(/ж/g, "j")
		.replace(/з/g, "z")
		.replace(/и/g, "ı")
		.replace(/й/g, "ı")
		.replace(/к/g, "k")
		.replace(/қ/g, "q")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/ң/g, "ń")
		.replace(/о/g, "o")
		.replace(/ө/g, "ó")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "ý")
		.replace(/ұ/g, "u")
		.replace(/ү/g, "ú")
		.replace(/ф/g, "f")
		.replace(/х/g, "h")
		.replace(/һ/g, "h")
		.replace(/ц/g, "ts")
		.replace(/ч/g, "ch")
		.replace(/ш/g, "sh")
		.replace(/щ/g, "sh")
		.replace(/ъ/g, "")
		.replace(/ы/g, "y")
		.replace(/і/g, "i")
		.replace(/ь/g, "")
		.replace(/э/g, "e")
		.replace(/ю/g, "ıu")
		.replace(/я/g, "ıa")
		.replace(/А/g, "A")
		.replace(/Ә/g, "Á")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Ғ/g, "Ǵ")
		.replace(/Д/g, "D")
		.replace(/Е/g, "E")
		.replace(/Ё/g, "Io")
		.replace(/Ж/g, "J")
		.replace(/З/g, "Z")
		.replace(/И/g, "I")
		.replace(/Й/g, "I")
		.replace(/К/g, "K")
		.replace(/Қ/g, "Q")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/Ң/g, "Ń")
		.replace(/О/g, "O")
		.replace(/Ө/g, "Ó")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "Ý")
		.replace(/Ұ/g, "U")
		.replace(/Ү/g, "Ú")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "H")
		.replace(/Һ/g, "H")
		.replace(/Ц/g, "Ts")
		.replace(/Ч/g, "Ch")
		.replace(/Ш/g, "Sh")
		.replace(/Щ/g, "Sh")
		.replace(/Ъ/g, "")
		.replace(/Ы/g, "Y")
		.replace(/І/g, "I")
		.replace(/Ь/g, "")
		.replace(/Э/g, "E")
		.replace(/Ю/g, "Iu")
		.replace(/Я/g, "Ia")
		.replace(/«/g, "\u201c")
		.replace(/»/g, "\u201d");
}

function latcyr() {
	document.transcription.text1.value; = document.transcription.text2.value
		.replace(/\u201c/g, "«")
		.replace(/\u201d/g, "»")
		.replace(/([AÁEIOÓUÚYÝ])I/g, "$1Й")
		.replace(/([AÁEIOÓUÚYÝ])I/g, "$1й")
		.replace(/([AÁEIOÓUÚYÝAaáeıioóuúyý])ı/g, "$1й")
		.replace(/ıo/g, "ё")
		.replace(/I(O|o)/g, "Ё")
		.replace(/ch/g, "ч")
		.replace(/C(H|h)/g, "Ч")
		.replace(/sh/g, "ш")
		.replace(/S(H|h)/g, "Ш")
		.replace(/ıu/g, "ю")
		.replace(/I(U|u)/g, "Ю")
		.replace(/ıa/g, "я")
		.replace(/I(A|a)/g, "Я")
		.replace(/á/g, "ə")
		.replace(/Á/g, "Ə")
		.replace(/a/g, "а")
		.replace(/A/g, "А")
		.replace(/á/g, "ә")
		.replace(/Á/g, "Ә")
		.replace(/b/g, "б")
		.replace(/B/g, "Б")
		.replace(/v/g, "в")
		.replace(/V/g, "В")
		.replace(/g/g, "г")
		.replace(/G/g, "Г")
		.replace(/ǵ/g, "ғ")
		.replace(/Ǵ/g, "Ғ")
		.replace(/d/g, "д")
		.replace(/D/g, "Д")
		.replace(/e/g, "е")
		.replace(/E/g, "Е")
		.replace(/j/g, "ж")
		.replace(/J/g, "Ж")
		.replace(/z/g, "з")
		.replace(/Z/g, "З")
		.replace(/ı/g, "и")
		.replace(/I/g, "И")
		.replace(/i/g, "і")
		.replace(/I/g, "І")
		.replace(/k/g, "к")
		.replace(/K/g, "К")
		.replace(/q/g, "қ")
		.replace(/Q/g, "Қ")
		.replace(/l/g, "л")
		.replace(/L/g, "Л")
		.replace(/m/g, "м")
		.replace(/M/g, "М")
		.replace(/n/g, "н")
		.replace(/N/g, "Н")
		.replace(/ń/g, "ң")
		.replace(/Ń/g, "Ң")
		.replace(/o/g, "о")
		.replace(/O/g, "О")
		.replace(/ó/g, "ө")
		.replace(/Ó/g, "Ө")
		.replace(/p/g, "п")
		.replace(/P/g, "П")
		.replace(/r/g, "р")
		.replace(/R/g, "Р")
		.replace(/s/g, "с")
		.replace(/S/g, "С")
		.replace(/t/g, "т")
		.replace(/T/g, "Т")
		.replace(/ý/g, "у")
		.replace(/Ý/g, "У")
		.replace(/ú/g, "ү")
		.replace(/Ú/g, "Ү")
		.replace(/u/g, "ұ")
		.replace(/U/g, "Ұ")
		.replace(/f/g, "ф")
		.replace(/F/g, "Ф")
		.replace(/h/g, "х")
		.replace(/H/g, "Х")
		.replace(/y/g, "ы")
		.replace(/Y/g, "Ы")
		.replace(/e/g, "э")
		.replace(/E/g, "Э");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}
