function cyrlat() {
	document.transcription.text2.value = document.transcription.text1.value
		.replace(/(А|Е|Ё|И|Ӣ|О|У|Ӯ|Ы|Э|Ю|Я)Ц/g, "$1ТС")
		.replace(/(А|Е|Ё|И|Ӣ|О|У|Ӯ|Ы|Э|Ю|Я|а|е|ё|и|ӣ|о|у|ӯ|ы|э|ю|я)ц/g, "$1тс")
		.replace(/Ц/g, "С")
		.replace(/ц/g, "с")
		.replace(/Щ/g, "Ш")
		.replace(/щ/g, "ш")
		.replace(/Ы/g, "И")
		.replace(/ы/g, "и")

		.replace(/(Б|В|Г|Ғ|Д|Ж|З|Й|К|Қ|Л|М|Н|П|Р|С|Т|Ф|Х|Ҳ|Ч|Ҷ|Ш)(Э|э)/g, "$1$2\u0300")
		.replace(/(б|в|г|ғ|д|ж|з|й|к|қ|л|м|н|п|р|с|т|ф|х|ҳ|ч|ҷ|ш)э/g, "$1э\u0300")
		.replace(/(Б|В|Г|Ғ|Д|Ж|З|К|Қ|Л|М|Н|П|Р|С|Т|Ф|Х|Ҳ|Ч|Ҷ|Ш)Е/g, "$1Э")
		.replace(/(Б|В|Г|Ғ|Д|Ж|З|К|Қ|Л|М|Н|П|Р|С|Т|Ф|Х|Ҳ|Ч|Ҷ|Ш|б|в|г|ғ|д|ж|з|к|қ|л|м|н|п|р|с|т|ф|х|ҳ|ч|ҷ|ш)е/g, "$1э")
		.replace(/(Э|э)\u0300(Э|э)/g, "$1$2")
		.replace(/(Ь|ь)/g, "")

		.replace(/Й(А|а)/g, "Й$1\u0300")
		.replace(/йа/g, "йа\u0300")
		.replace(/ЙЕ/g, "Й\u0300Э")
		.replace(/Йе/g, "Й\u0300э")
		.replace(/йе/g, "й\u0300э")
		.replace(/(Б|В|Г|Ғ|Д|Ж|З|К|Қ|Л|М|Н|П|Р|С|Т|Ф|Х|Ҳ|Ч|Ҷ|Ш)(Й|й)\u0300/g, "$1$2")
		.replace(/(Б|В|Г|Ғ|Д|Ж|З|К|Қ|Л|М|Н|П|Р|С|Т|Ф|Х|Ҳ|Ч|Ҷ|Ш|б|в|г|ғ|д|ж|з|к|қ|л|м|н|п|р|с|т|ф|х|ҳ|ч|ҷ|ш)й\u0300/g, "$1й")
		.replace(/Й(О|о)/g, "Й$1\u0300")
		.replace(/йо/g, "йо\u0300")
		.replace(/Й(У|у)/g, "Й$1\u0300")
		.replace(/йу/g, "йу\u0300")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Я/ug, "$1$2 ЙА")
		.replace(/Я (\p{Uppercase})(\p{Uppercase})/ug, "ЙА $1$2")
		.replace(/Я(\p{Uppercase})/ug, "ЙА$1")
		.replace(/Я/g, "Йа")
		.replace(/я/g, "йа")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Е/ug, "$1$2 ЙЭ")
		.replace(/Е (\p{Uppercase})(\p{Uppercase})/ug, "ЙЭ $1$2")
		.replace(/Е(\p{Uppercase})/ug, "ЙЭ$1")
		.replace(/Е/g, "Йэ")
		.replace(/е/g, "йэ")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ё/ug, "$1$2 ЙО")
		.replace(/Ё (\p{Uppercase})(\p{Uppercase})/ug, "ЙО $1$2")
		.replace(/Ё(\p{Uppercase})/ug, "ЙО$1")
		.replace(/Ё/g, "Йо")
		.replace(/ё/g, "йо")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ю/ug, "$1$2 ЙУ")
		.replace(/Ю (\p{Uppercase})(\p{Uppercase})/ug, "ЙУ $1$2")
		.replace(/Ю(\p{Uppercase})/ug, "ЙУ$1")
		.replace(/Ю/g, "Йу")
		.replace(/ю/g, "йу")

		.replace(/(А|Э|И|Ӣ|О|У|Ӯ|а|э|и|ӣ|о|у|ӯ)й(и|ӣ)/g, "$1йй$2")
		.replace(/(А|Э|И|Ӣ|О|У|Ӯ)Й(И|Ӣ)/g, "$1ЙЙ$2")
		.replace(/(А|Э|И|Ӣ|О|У|Ӯ|а|э|и|ӣ|о|у|ӯ)(и|ӣ)/g, "$1й$2")
		.replace(/(А|Э|И|Ӣ|О|У|Ӯ)(И|Ӣ)/g, "$1Й$2")

		.replace(/А/g, "A")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Ғ/g, "Ƣ")
		.replace(/Д/g, "D")
		.replace(/Ж/g, "Ƶ")
		.replace(/З/g, "Z")
		.replace(/И/g, "I")
		.replace(/Ӣ/g, "Ī")
		.replace(/Й/g, "J")
		.replace(/К/g, "K")
		.replace(/Қ/g, "Q")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/О/g, "O")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ӯ/g, "Ū")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "X")
		.replace(/Ҳ/g, "H")
		.replace(/Ч/g, "C")
		.replace(/Ҷ/g, "Ç")
		.replace(/Ш/g, "Ş")
		.replace(/(Ъ|ъ)/g, "\u2019")
		.replace(/Э/g, "E")
		.replace(/а/g, "a")
		.replace(/б/g, "ʙ")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/ғ/g, "ƣ")
		.replace(/д/g, "d")
		.replace(/ж/g, "ƶ")
		.replace(/з/g, "z")
		.replace(/и/g, "i")
		.replace(/ӣ/g, "ī")
		.replace(/й/g, "j")
		.replace(/к/g, "k")
		.replace(/қ/g, "q")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/о/g, "o")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ӯ/g, "ū")
		.replace(/ф/g, "f")
		.replace(/х/g, "x")
		.replace(/ҳ/g, "h")
		.replace(/ч/g, "c")
		.replace(/ҷ/g, "ç")
		.replace(/ш/g, "ş")
		.replace(/э/g, "e")
		.normalize('NFC');
}

function latcyr() {
	document.transcription.text1.value = document.transcription.text2.value

		.replace(/(A|E|I|Ī|O|U|Ū|J)J(I|Ī)/g, "$1$2")
		.replace(/(A|E|I|Ī|O|U|Ū|J|a|e|i|ī|o|u|ū|j)j(i|ī)/g, "$1$2")

		.replace(/J(A|a)/g, "Я")
		.replace(/ja/g, "я")
		.replace(/J(E|e)/g, "Е")
		.replace(/je/g, "е")
		.replace(/(B|C|Ç|D|F|G|Ƣ|H|J|K|L|M|N|P|Q|R|S|Ş|T|V|X|Z|Ƶ)Е/g, "$1ЙЕ")
		.replace(/(B|C|Ç|D|F|G|Ƣ|H|J|K|L|M|N|P|Q|R|S|Ş|T|V|X|Z|Ƶ|ʙ|c|ç|d|f|g|ƣ|h|j|k|l|m|n|p|q|r|s|ş|t|v|x|z|ƶ)е/g, "$1йе")
		.replace(/(B|C|Ç|D|F|G|Ƣ|H|J|K|L|M|N|P|Q|R|S|Ş|T|V|X|Z|Ƶ)E/g, "$1Е")
		.replace(/(B|C|Ç|D|F|G|Ƣ|H|J|K|L|M|N|P|Q|R|S|Ş|T|V|X|Z|Ƶ|ʙ|c|ç|d|f|g|ƣ|h|j|k|l|m|n|p|q|r|s|ş|t|v|x|z|ƶ)e/g, "$1е")
		.replace(/J(O|o)/g, "Ё")
		.replace(/jo/g, "ё")
		.replace(/J(U|u)/g, "Ю")
		.replace(/ju/g, "ю")


		.replace(/Ī/g, "Ӣ")
		.replace(/Ū/g, "Ӯ")
		.replace(/Ç/g, "Ҷ")
		.replace(/Ş/g, "Ш")
		.replace(/ƣ/g, "ғ")
		.replace(/ī/g, "ӣ")
		.replace(/ū/g, "ӯ")
		.replace(/ç/g, "ҷ")
		.replace(/ş/g, "ш")

		.normalize('NFD')
		.replace(/A/g, "А")
		.replace(/B/g, "Б")
		.replace(/V/g, "В")
		.replace(/G/g, "Г")
		.replace(/Ƣ/g, "Ғ")
		.replace(/D/g, "Д")
		.replace(/Z/g, "З")
		.replace(/Ƶ/g, "Ж")
		.replace(/I/g, "И")
		.replace(/J/g, "Й")
		.replace(/K/g, "К")
		.replace(/Q/g, "Қ")
		.replace(/L/g, "Л")
		.replace(/M/g, "М")
		.replace(/N/g, "Н")
		.replace(/O/g, "О")
		.replace(/P/g, "П")
		.replace(/R/g, "Р")
		.replace(/S/g, "С")
		.replace(/T/g, "Т")
		.replace(/U/g, "У")
		.replace(/C/g, "Ч")
		.replace(/F/g, "Ф")
		.replace(/X/g, "Х")
		.replace(/H/g, "Ҳ")
		.replace(/a/g, "а")
		.replace(/ʙ/g, "б")
		.replace(/v/g, "в")
		.replace(/g/g, "г")
		.replace(/d/g, "д")
		.replace(/z/g, "з")
		.replace(/ƶ/g, "ж")
		.replace(/i/g, "и")
		.replace(/j/g, "й")
		.replace(/k/g, "к")
		.replace(/q/g, "қ")
		.replace(/l/g, "л")
		.replace(/m/g, "м")
		.replace(/n/g, "н")
		.replace(/o/g, "о")
		.replace(/p/g, "п")
		.replace(/r/g, "р")
		.replace(/s/g, "с")
		.replace(/t/g, "т")
		.replace(/u/g, "у")
		.replace(/c/g, "ч")
		.replace(/f/g, "ф")
		.replace(/x/g, "х")
		.replace(/h/g, "ҳ")

		.replace(/\u2019/g, "ъ")
		.replace(/(\p{Uppercase})ъ/ug, "$1Ъ")
		.replace(/Ъ(\p{Lowercase})/ug, "ъ$1")

		.replace(/Й\u0300Э/g, "ЙЕ")
		.replace(/(Й|й)\u0300э/g, "$1е")
		.replace(/\u0300/g, "")
		.normalize('NFC');
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}