
var car;
function latcyr () {
}
function cyrlat () {
car = document.transcription.text1.value;
translit = document.transcription.text1.value;
translit = translit.replace(/ғ/g, "ҕ");
translit = translit.replace(/Ғ/g, "Ҕ");
translit = translit.replace(/ҳ/g, "һ");
translit = translit.replace(/Ҳ/g, "Һ");
translit = translit.replace(/ң/g, "ҥ");
translit = translit.replace(/Ң/g, "Ҥ");
car = car.replace(/ғ/g, "ҕ");
car = car.replace(/Ғ/g, "Ҕ");
car = car.replace(/ҳ/g, "һ");
car = car.replace(/Ҳ/g, "Һ");
car = car.replace(/ң/g, "ҥ");
car = car.replace(/Ң/g, "Ҥ");
  
car = car.replace(/ е/g, " ye");
car = car.replace(/\nе/g, "\nye");
car = car.replace(/\rе/g, "\rye");
car = car.replace(/^е/g, "ye");

car = car.replace(/ае/g, "аye");
car = car.replace(/ие/g, "иye");
car = car.replace(/ые/g, "ыye");
car = car.replace(/ее/g, "еye");
car = car.replace(/эе/g, "эye");
car = car.replace(/уе/g, "уye");
car = car.replace(/ое/g, "оye");
car = car.replace(/өе/g, "өye");
car = car.replace(/ёе/g, "ёye");
car = car.replace(/үе/g, "үye");
car = car.replace(/йе/g, "йye");
car = car.replace(/юе/g, "юye");
car = car.replace(/яе/g, "яye");

car = car.replace(/ Е/g, " Ye");
car = car.replace(/\nЕ/g, "\nYe");
car = car.replace(/\rЕ/g, "\rYe");
car = car.replace(/^Е/g, "Ye");

car = car.replace(/Ае/g, "Аye");
car = car.replace(/Ие/g, "Иye");
car = car.replace(/Ые/g, "Ыye");
car = car.replace(/Ее/g, "Еye");
car = car.replace(/Эе/g, "Эye");
car = car.replace(/Уе/g, "Уye");
car = car.replace(/Ое/g, "Оye");
car = car.replace(/Өе/g, "Өye");
car = car.replace(/Ёе/g, "Ёye");
car = car.replace(/Үе/g, "Үye");
car = car.replace(/Йе/g, "Йye");
car = car.replace(/Юе/g, "Юye");
car = car.replace(/Яе/g, "Яye");

car = car.replace(/АЕ/g, "АYE");
car = car.replace(/ИЕ/g, "ИYE");
car = car.replace(/ЫЕ/g, "ЫYE");
car = car.replace(/ЕЕ/g, "ЕYE");
car = car.replace(/ЭЕ/g, "ЭYE");
car = car.replace(/УЕ/g, "УYE");
car = car.replace(/ОЕ/g, "ОYE");
car = car.replace(/ӨЕ/g, "ӨYE");
car = car.replace(/ЁЕ/g, "ЁYE");
car = car.replace(/ҮЕ/g, "ҮYE");
car = car.replace(/ЙЕ/g, "ЙYE");
car = car.replace(/ЮЕ/g, "ЮYE");
car = car.replace(/ЯЕ/g, "ЯYE");

  car = car.replace(/а/g, "a");
  car = car.replace(/б/g, "b");
  car = car.replace(/в/g, "v");
  car = car.replace(/г/g, "g");
  car = car.replace(/ҕ/g, "g‘");
  car = car.replace(/д/g, "d");
  car = car.replace(/е/g, "e");
  car = car.replace(/ж/g, "j");
  car = car.replace(/з/g, "z");
  car = car.replace(/и/g, "i");
  car = car.replace(/й/g, "y");
  car = car.replace(/к/g, "k");
  car = car.replace(/л/g, "l");
  car = car.replace(/м/g, "m");
  car = car.replace(/н/g, "n");
  car = car.replace(/ҥ/g, "ng");
  car = car.replace(/о/g, "o");
  car = car.replace(/ө/g, "o‘");
  car = car.replace(/п/g, "p");
  car = car.replace(/р/g, "r");
  car = car.replace(/с/g, "s");
  car = car.replace(/һ/g, "h");
  car = car.replace(/т/g, "t");
  car = car.replace(/у/g, "u");
  car = car.replace(/ү/g, "u‘");
  car = car.replace(/ф/g, "f");
  car = car.replace(/х/g, "x");
  car = car.replace(/ц/g, "ts");
  car = car.replace(/ч/g, "ch");
  car = car.replace(/ш/g, "sh");
  car = car.replace(/щ/g, "shch");
  car = car.replace(/ы/g, "i");
  car = car.replace(/э/g, "e");
  car = car.replace(/ъ/g, "'");
  car = car.replace(/ь/g, "Ь");
  car = car.replace(/ё/g, "yo");
  car = car.replace(/ю/g, "yu");
  car = car.replace(/я/g, "ya");
  car = car.replace(/А/g, "A");
  car = car.replace(/Б/g, "B");
  car = car.replace(/В/g, "V");
  car = car.replace(/Г/g, "G");
  car = car.replace(/Ҕ/g, "G‘");
  car = car.replace(/Д/g, "D");
  car = car.replace(/Е/g, "E");
  car = car.replace(/Ж/g, "J");
  car = car.replace(/З/g, "Z");
  car = car.replace(/И/g, "I");
  car = car.replace(/Й/g, "Y");
  car = car.replace(/К/g, "K");
  car = car.replace(/Л/g, "L");
  car = car.replace(/М/g, "M");
  car = car.replace(/Н/g, "N");
  car = car.replace(/Ҥ/g, "Ng");
  car = car.replace(/О/g, "O");
  car = car.replace(/Ө/g, "O‘");
  car = car.replace(/П/g, "P");
  car = car.replace(/Р/g, "R");
  car = car.replace(/С/g, "S");
  car = car.replace(/Һ/g, "H");
  car = car.replace(/Т/g, "T");
  car = car.replace(/У/g, "U");
  car = car.replace(/Ү/g, "U‘");
  car = car.replace(/Ф/g, "F");
  car = car.replace(/Х/g, "X");
  car = car.replace(/Ц/g, "Ts");
  car = car.replace(/Ч/g, "Ch");
  car = car.replace(/Ш/g, "Sh");
  car = car.replace(/Щ/g, "Shch");
  car = car.replace(/Ы/g, "I");
  car = car.replace(/Э/g, "E");
  car = car.replace(/Ъ/g, "'");
  car = car.replace(/Ё/g, "Yo");
  car = car.replace(/Ю/g, "Yu");
  car = car.replace(/Я/g, "Ya");
  car = car.replace(/dЬ/g, "j");
  car = car.replace(/DЬ/g, "J");
  car = car.replace(/nЬ/g, "n‘");
  car = car.replace(/NЬ/g, "N‘");
  car = car.replace(/Ь/g, "");
  car = car.replace(/»/g, "\u201d");
  car = car.replace(/«/g, "\u201c");
document.transcription.text1.value=translit;
document.transcription.text2.value=car;
}
function copy1()
{ textRange=document.transcription.text1.createTextRange();   textRange.execCommand("Copy");   textRange="";
}
function copy2()
{ textRange=document.transcription.text2.createTextRange();   textRange.execCommand("Copy");   textRange="";
}