function cyrlat() {
	document.transcription.text2.value = document.transcription.text1.value
		.replace(/A/g, 'Ա')
		.replace(/B/g, 'Բ')
		.replace(/C/g, 'Ջ')
		.replace(/Ç/g, 'Չ')
		.replace(/D/g, 'Դ')
		.replace(/E/g, 'Ե')
		.replace(/Ê/g, 'Է')
		.replace(/F/g, 'Ֆ')
		.replace(/G/g, 'Գ')
		.replace(/H/g, 'Հ')
		.replace(/I/g, 'Ը')
		.replace(/Î/g, 'Ի')
		.replace(/J/g, 'Ժ')
		.replace(/K/g, 'Ք')
		.replace(/L/g, 'Լ')
		.replace(/M/g, 'Մ')
		.replace(/N/g, 'Ն')
		.replace(/O/g, 'Ո')
		.replace(/P/g, 'Փ')
		.replace(/Q/g, 'Կ')
		.replace(/R/g, 'Ր')
		.replace(/S/g, 'Ս')
		.replace(/Ş/g, 'Շ')
		.replace(/T/g, 'Թ')
		.replace(/U/g, 'ՈՒ')
		.replace(/Û/g, 'Օ')
		.replace(/V/g, 'Վ')
		.replace(/W/g, 'ՕՒ')
		.replace(/X/g, 'Խ')
		.replace(/Y/g, 'Յ')
		.replace(/Z/g, 'Զ')
		.replace(/a/g, 'ա')
		.replace(/b/g, 'բ')
		.replace(/c/g, 'ջ')
		.replace(/ç/g, 'չ')
		.replace(/d/g, 'դ')
		.replace(/e/g, 'ե')
		.replace(/ê/g, 'է')
		.replace(/f/g, 'ֆ')
		.replace(/g/g, 'գ')
		.replace(/h/g, 'հ')
		.replace(/i/g, 'ը')
		.replace(/î/g, 'ի')
		.replace(/j/g, 'ժ')
		.replace(/k/g, 'ք')
		.replace(/l/g, 'լ')
		.replace(/m/g, 'մ')
		.replace(/n/g, 'ն')
		.replace(/o/g, 'ո')
		.replace(/p/g, 'փ')
		.replace(/q/g, 'կ')
		.replace(/r/g, 'ր')
		.replace(/s/g, 'ս')
		.replace(/ş/g, 'շ')
		.replace(/t/g, 'թ')
		.replace(/u/g, 'ու')
		.replace(/û/g, 'օ')
		.replace(/v/g, 'վ')
		.replace(/w/g, 'օւ')
		.replace(/x/g, 'խ')
		.replace(/y/g, 'յ')
		.replace(/z/g, 'զ')

		.replace(/Ւ( |)(ա|բ|ջ|չ|դ|ե|է|ֆ|գ|հ|ը|ի|ժ|ք|լ|մ|ն|ո|փ|կ|ր|ս|շ|թ|օ|վ|խ|յ|զ)/g, 'ւ$1$2')
		.replace(/(ա|բ|ջ|չ|դ|ե|է|ֆ|գ|հ|ը|ի|ժ|ք|լ|մ|ն|ո|փ|կ|ր|ս|շ|թ|օ|վ|խ|յ|զ)( |)(Ո|Օ)Ւ/g, '$1$2$3ւ');
}

function latcyr() {
	document.transcription.text1.value = document.transcription.text2.value
		.replace(/Ո(Ւ|ւ)/g, 'U')
		.replace(/Օ(Ւ|ւ)/g, 'W')
		.replace(/ու/g, 'u')
		.replace(/օւ/g, 'w')

		.replace(/Ա/g, 'A')
		.replace(/Բ/g, 'B')
		.replace(/Ջ/g, 'C')
		.replace(/Չ/g, 'Ç')
		.replace(/Դ/g, 'D')
		.replace(/Ե/g, 'E')
		.replace(/Է/g, 'Ê')
		.replace(/Ֆ/g, 'F')
		.replace(/Գ/g, 'G')
		.replace(/Հ/g, 'H')
		.replace(/Ը/g, 'I')
		.replace(/Ի/g, 'Î')
		.replace(/Ժ/g, 'J')
		.replace(/Ք/g, 'K')
		.replace(/Լ/g, 'L')
		.replace(/Մ/g, 'M')
		.replace(/Ն/g, 'N')
		.replace(/Ո/g, 'O')
		.replace(/Փ/g, 'P')
		.replace(/Կ/g, 'Q')
		.replace(/Ր/g, 'R')
		.replace(/Ս/g, 'S')
		.replace(/Շ/g, 'Ş')
		.replace(/Թ/g, 'T')
		.replace(/Օ/g, 'Û')
		.replace(/Վ/g, 'V')
		.replace(/Խ/g, 'X')
		.replace(/Յ/g, 'Y')
		.replace(/Զ/g, 'Z')
		.replace(/ա/g, 'a')
		.replace(/բ/g, 'b')
		.replace(/ջ/g, 'c')
		.replace(/չ/g, 'ç')
		.replace(/դ/g, 'd')
		.replace(/ե/g, 'e')
		.replace(/է/g, 'ê')
		.replace(/ֆ/g, 'f')
		.replace(/գ/g, 'g')
		.replace(/հ/g, 'h')
		.replace(/ը/g, 'i')
		.replace(/ի/g, 'î')
		.replace(/ժ/g, 'j')
		.replace(/ք/g, 'k')
		.replace(/լ/g, 'l')
		.replace(/մ/g, 'm')
		.replace(/ն/g, 'n')
		.replace(/ո/g, 'o')
		.replace(/փ/g, 'p')
		.replace(/կ/g, 'q')
		.replace(/ր/g, 'r')
		.replace(/ս/g, 's')
		.replace(/շ/g, 'ş')
		.replace(/թ/g, 't')
		.replace(/օ/g, 'û')
		.replace(/վ/g, 'v')
		.replace(/խ/g, 'x')
		.replace(/յ/g, 'y')
		.replace(/զ/g, 'z');
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}