function cyrlat() {
	document.transcription.text2.value = document.transcription.text1.value
		.replace(/(\p{Lu})X/ug, '$1KZ')
		.replace(/(\p{Lu})(\p{Lu}) X/ug, '$1$2 KZ')
		.replace(/X (\p{Lu})(\p{Lu})/ug, 'KZ $1$2')
		.replace(/X(\p{Lu})/ug, 'KZ$1')
		.replace(/X/g, 'Kz')
		.replace(/x/g, 'kz')
		.replace(/(\p{Lu})Q/ug, '$1КЬ')
		.replace(/(\p{Lu})(\p{Lu}) Q/ug, '$1$2 КЬ')
		.replace(/Q (\p{Lu})(\p{Lu})/ug, 'КЬ $1$2')
		.replace(/Q(\p{Lu})/ug, 'КЬ$1')
		.replace(/Q/g, 'Кь')
		.replace(/q/g, 'кь')
		.replace(/(\p{Lu})Q/ug, '$1ХЬ')
		.replace(/(\p{Lu})(\p{Lu}) Q/ug, '$1$2 ХЬ')
		.replace(/Q (\p{Lu})(\p{Lu})/ug, 'ХЬ $1$2')
		.replace(/Q(\p{Lu})/ug, 'ХЬ$1')
		.replace(/Q/g, 'Хь')
		.replace(/q/g, 'хь')

		.replace(/O[Uu]/g, 'Є')
		.replace(/ou/g, 'є')

		.replace(/A/g, 'У')
		.replace(/B/g, 'Х')
		.replace(/C/g, 'Ј')
		.replace(/D/g, 'М')
		.replace(/E/g, 'И')
		.replace(/É/g, 'Ё')
		.replace(/È/g, 'О')
		.replace(/Ê/g, 'Ӗ')
		.replace(/F/g, 'Г')
		.replace(/G/g, 'Н')
		.replace(/H/g, 'С')
		.replace(/I/g, 'І')
		.replace(/J/g, 'Б')
		.replace(/K/g, 'П')
		.replace(/L/g, 'В')
		.replace(/M/g, 'Т')
		.replace(/N/g, 'Л')
		.replace(/O/g, 'Э')
		.replace(/Ò/g, 'Ю')
		.replace(/Ô/g, 'Ю')
		.replace(/P/g, 'Ц')
		.replace(/S/g, 'Ш')
		.replace(/T/g, 'З')
		.replace(/U/g, 'А')
		.replace(/V/g, 'К')
		.replace(/W/g, 'Ф')
		.replace(/Y/g, 'Д')
		.replace(/Z/g, 'Р')
		.replace(/a/g, 'у')
		.replace(/b/g, 'х')
		.replace(/c/g, 'ј')
		.replace(/d/g, 'м')
		.replace(/e/g, 'и')
		.replace(/é/g, 'ё')
		.replace(/è/g, 'о')
		.replace(/ê/g, 'ё\u0300')
		.replace(/f/g, 'г')
		.replace(/g/g, 'н')
		.replace(/h/g, 'с')
		.replace(/i/g, 'і')
		.replace(/j/g, 'б')
		.replace(/k/g, 'п')
		.replace(/l/g, 'в')
		.replace(/m/g, 'т')
		.replace(/n/g, 'л')
		.replace(/o/g, 'э')
		.replace(/ò/g, 'ю')
		.replace(/ô/g, 'ю\u0300')
		.replace(/p/g, 'ц')
		.replace(/s/g, 'ш')
		.replace(/t/g, 'з')
		.replace(/u/g, 'а')
		.replace(/v/g, 'к')
		.replace(/w/g, 'ф')
		.replace(/y/g, 'д')
		.replace(/z/g, 'р')

		.replace(/Ј[Аа]/g, 'Я')
		.replace(/ја/g, 'я')
		.replace(/Ј[Ээ]/g, 'Е')
		.replace(/јэ/g, 'е')
		.replace(/З(?:ХЬ|хь)/g, 'Ж')
		.replace(/зхь/g, 'ж')
		.replace(/Д[Жж]/g, 'Ч')
		.replace(/дж/g, 'ч')
		.replace(/Ш[Чч]/g, 'Щ')
		.replace(/шч/g, 'щ')

		.normalize('NFC');
}

function latcyr() {
	document.transcription.text1.value = document.transcription.text2.value
		.replace(/(\p{Lu})Я/ug, '$1ЈА')
		.replace(/(\p{Lu})(\p{Lu}) Я/ug, '$1$2 ЈА')
		.replace(/Я (\p{Lu})(\p{Lu})/ug, 'ЈА $1$2')
		.replace(/Я(\p{Lu})/ug, 'ЈА$1')
		.replace(/Я/g, 'Ја')
		.replace(/я/g, 'ја')
		.replace(/(\p{Lu})Е/ug, '$1ЈЭ')
		.replace(/(\p{Lu})(\p{Lu}) Е/ug, '$1$2 ЈЭ')
		.replace(/Е (\p{Lu})(\p{Lu})/ug, 'ЈЭ $1$2')
		.replace(/Е(\p{Lu})/ug, 'ЈЭ$1')
		.replace(/Е/g, 'Јэ')
		.replace(/е/g, 'јэ')
		.replace(/(\p{Lu})Щ/ug, '$1ШЧ')
		.replace(/(\p{Lu})(\p{Lu}) Щ/ug, '$1$2 ШЧ')
		.replace(/Щ (\p{Lu})(\p{Lu})/ug, 'ШЧ $1$2')
		.replace(/Щ(\p{Lu})/ug, 'ШЧ$1')
		.replace(/Щ/g, 'Шч')
		.replace(/щ/g, 'шч')
		.replace(/(\p{Lu})Ч/ug, '$1ДЖ')
		.replace(/(\p{Lu})(\p{Lu}) Ч/ug, '$1$2 ДЖ')
		.replace(/Ч (\p{Lu})(\p{Lu})/ug, 'ДЖ $1$2')
		.replace(/Ч(\p{Lu})/ug, 'ДЖ$1')
		.replace(/Ч/g, 'Дж')
		.replace(/ч/g, 'дж')
		.replace(/(\p{Lu})Ж/ug, '$1ЗХЬ')
		.replace(/(\p{Lu})(\p{Lu}) Ж/ug, '$1$2 ЗХЬ')
		.replace(/Ж (\p{Lu})(\p{Lu})/ug, 'ЗХЬ $1$2')
		.replace(/Ж(\p{Lu})/ug, 'ЗХЬ$1')
		.replace(/Ж/g, 'Зхь')
		.replace(/ж/g, 'зхь')
		.replace(/(\p{Lu})Є/ug, '$1OU')
		.replace(/(\p{Lu})(\p{Lu}) Є/ug, '$1$2 OU')
		.replace(/Є (\p{Lu})(\p{Lu})/ug, 'OU $1$2')
		.replace(/Є(\p{Lu})/ug, 'OU$1')
		.replace(/Є/g, 'Ou')
		.replace(/є/g, 'ou')

		.replace(/А/g, 'U')
		.replace(/Б/g, 'J')
		.replace(/В/g, 'L')
		.replace(/Г/g, 'F')
		.replace(/Д/g, 'Y')
		.replace(/Ё\u0300/g, 'Ê')
		.replace(/Ё/g, 'É')
		.replace(/З/g, 'T')
		.replace(/И/g, 'E')
		.replace(/І/g, 'İ')
		.replace(/Ј/g, 'C')
		.replace(/К[Ьь]/g, 'Q')
		.replace(/К/g, 'V')
		.replace(/Л/g, 'N')
		.replace(/М/g, 'D')
		.replace(/Н/g, 'G')
		.replace(/О/g, 'È')
		.replace(/П/g, 'K')
		.replace(/Р/g, 'Z')
		.replace(/С/g, 'H')
		.replace(/Т/g, 'M')
		.replace(/У/g, 'A')
		.replace(/Ф/g, 'W')
		.replace(/Х[Ьь]/g, 'R')
		.replace(/Х/g, 'B')
		.replace(/Ц/g, 'P')
		.replace(/Ш/g, 'S')
		.replace(/Э/g, 'O')
		.replace(/Ю\u0300/g, 'Ô')
		.replace(/Ю/g, 'Ò')
		.replace(/а/g, 'u')
		.replace(/б/g, 'j')
		.replace(/в/g, 'l')
		.replace(/г/g, 'f')
		.replace(/д/g, 'y')
		.replace(/ё/g, 'é')
		.replace(/ё/g, 'ê')
		.replace(/з/g, 't')
		.replace(/и/g, 'e')
		.replace(/і/g, 'i')
		.replace(/ј/g, 'c')
		.replace(/к/g, 'v')
		.replace(/кь/g, 'q')
		.replace(/л/g, 'n')
		.replace(/м/g, 'd')
		.replace(/н/g, 'g')
		.replace(/о/g, 'è')
		.replace(/п/g, 'k')
		.replace(/р/g, 'z')
		.replace(/с/g, 'h')
		.replace(/т/g, 'm')
		.replace(/у/g, 'a')
		.replace(/ф/g, 'w')
		.replace(/х/g, 'b')
		.replace(/хь/g, 'r')
		.replace(/ц/g, 'p')
		.replace(/ш/g, 's')
		.replace(/э/g, 'o')
		.replace(/ю/g, 'ò')
		.replace(/ю/g, 'ô')
		.normalize('NFC');
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}
