function cyrlat() {
	transcription.text2.value = document.transcription.text1.value
		.normalize('NFD')
		.replace(/ᆪᄉ/g, 'ᆨᄊ')
		.replace(/ᆬᄌ/g, 'ᆫᄍ')
		.replace(/ᆰᄀ/g, 'ᆯᄁ')
		.replace(/ᆲᄇ/g, 'ᆯᄈ')
		.replace(/ᆹᄉ/g, 'ᆸᄊ')
		.replace(/ᆳᄉ/g, 'ᆯᄊ')

		.replace(/ᆪᄋ/g, 'ᆨᄉ')
		.replace(/ᆬᄋ/g, 'ᆫᄌ')
		.replace(/ᆭᄋ/g, 'ᆫᄒ')
		.replace(/ᆰᄋ/g, 'ᆯᄀ')
		.replace(/ᆲᄋ/g, 'ᆯᄇ')
		.replace(/ᆶᄋ/g, 'ᆯᄒ')
		.replace(/ᆱᄋ/g, 'ᆯᄆ')
		.replace(/ᆹᄋ/g, 'ᆸᄉ')
		.replace(/ㄿᄋ/g, 'ᆯᄑ')
		.replace(/ᆳᄋ/g, 'ᆯᄉ')
		.replace(/ㄾᄋ/g, 'ᆯᄐ')

		.replace(/ᆭᄀ/g, 'ᆫᄏ')
		.replace(/ᆭᄃ/g, 'ᆫᄐ')
		.replace(/ᆭᄇ/g, 'ᆫᄑ')
		.replace(/ᆭᄌ/g, 'ᆫᄎ')
		.replace(/ᆶᄀ/g, 'ᆯᄏ')
		.replace(/ᆶᄃ/g, 'ᆯᄐ')
		.replace(/ᆶᄇ/g, 'ᆯᄑ')
		.replace(/ᆶᄌ/g, 'ᆯᄎ')
		.replace(/ᆬᄒ/g, 'ᆫᄎ')
		.replace(/ᆰᄒ/g, 'ᆯᄏ')
		.replace(/ᆲᄒ/g, 'ᆯᄑ')

		.replace(/ᆪ/g, 'ᆨ')
		.replace(/ᆬ/g, 'ᆫ')
		.replace(/ᆭ/g, 'ᆫ')
		.replace(/ᆰ/g, 'ᆨ')
		.replace(/ᆲ/g, 'ᆯ')
		.replace(/ᆶ/g, 'ᆯ')
		.replace(/ᆱ/g, 'ᆷ')
		.replace(/ᆹ/g, 'ᆸ')
		.replace(/ㄿ/g, 'ᇁ')
		.replace(/ᆳ/g, 'ᆯ')
		.replace(/ㄾ/g, 'ᆯ')

		.replace(/ᆮ이/g, '지')
		.replace(/ᆮ히/g, '치')
		.replace(/ᇀ이/g, '치')

		.replace(/ᆨᄋ/g, 'ᄀ')
		.replace(/ᆩᄋ/g, 'ᄁ')
		.replace(/ᆫᄋ/g, 'ᄂ')
		.replace(/ᆮᄋ/g, 'ᄃ')
		.replace(/ᆯᄋ/g, 'ᄅ')
		.replace(/ᆷᄋ/g, 'ᄆ')
		.replace(/ᆸᄋ/g, 'ᄇ')
		.replace(/ᆺᄋ/g, 'ᄉ')
		.replace(/ᆻᄋ/g, 'ᄊ')
		.replace(/ᆽᄋ/g, 'ᄌ')
		.replace(/ᆾᄋ/g, 'ᄎ')
		.replace(/ᆿᄋ/g, 'ᄏ')
		.replace(/ᇀᄋ/g, 'ᄐ')
		.replace(/ᇁᄋ/g, 'ᄑ')
		.replace(/ᇂᄋ/g, 'ᄋ')

		.replace(/(ᆨ|ᆿ)ᄂ/g, 'ᆼᄂ')
		.replace(/(ᆸ|ᇁ)ᄂ/g, 'ᆷᄂ')
		.replace(/(ᆮ|ᆺ|ᆻ|ᆽ|ᆾ|ᇀ|ᇂ)ᄂ/g, 'ᆫᄂ')
		.replace(/(ᆨ|ᆿ)ᄅ/g, 'ᆼᄂ')
		.replace(/ᆫᄅ/g, 'ᆯᄅ')
		.replace(/(ᆷ|ᆸ)ᄅ/g, 'ᆷᄂ')
		.replace(/ᆼᄅ/g, 'ᆼᄂ')
		.replace(/(ᆮ|ᆺ|ᆻ|ᆽ|ᆾ|ᇀ|ᇂ)ᄅ/g, 'ᆫᄂ')
		.replace(/(ᆨ|ᆿ)ᄆ/g, 'ᆼᄆ')
		.replace(/(ᆸ|ᇁ)ᄆ/g, 'ᆷᄆ')
		.replace(/(ᆮ|ᆺ|ᆻ|ᆽ|ᆾ|ᇀ|ᇂ)ᄆ/g, 'ᆫᄆ')

		.replace(/ᇂᄀ/g, 'ᄏ')
		.replace(/ᇂᄃ/g, 'ᄐ')
		.replace(/ᇂᄇ/g, 'ᄑ')
		.replace(/ᇂᄌ/g, 'ᄎ')

		.replace(/ᇂᄂ/g, 'ᆫᄂ')
		.replace(/ᇂ(ᄅ|ᄆ|ᄉ|ᄎ|ᄏ|ᄐ|ᄑ|ᄒ|ᄁ|ᄄ|ᄈ|ᄊ|ᄍ)/g, '$1')

		.replace(/ᆫᄅ/g, 'ᆯᄅ')
		.replace(/ᆯᄂ/g, 'ᆯᄅ')

		.replace(/(ᅡ|ᅪ|ᅣ|ᅩ|ᅭ)에/g, '$1에\u0308')
		.replace(/ᆫᄀ/g, 'ᆫ\u2019ᄀ')
		.replace(/ᆼᄋ/g, 'ᆼ\u2019ᄋ')

		.replace(/(ᅡ|ᅢ|ᅣ|ᅤ|ᅥ|ᅦ|ᅧ|ᅨ|ᅩ|ᅪ|ᅫ|ᅬ|ᅭ|ᅮ|ᅯ|ᅰ|ᅱ|ᅲ|ᅳ|ᅴ|ᅵ|ᆫ\u2019|ᆯ|ᆷ|ᆼ)ᄀ/g, '$1г')
		.replace(/(ᅡ|ᅢ|ᅣ|ᅤ|ᅥ|ᅦ|ᅧ|ᅨ|ᅩ|ᅪ|ᅫ|ᅬ|ᅭ|ᅮ|ᅯ|ᅰ|ᅱ|ᅲ|ᅳ|ᅴ|ᅵ|ᆫ|ᆯ|ᆷ|ᆼ)ᄃ/g, '$1д')
		.replace(/(ᅡ|ᅢ|ᅣ|ᅤ|ᅥ|ᅦ|ᅧ|ᅨ|ᅩ|ᅪ|ᅫ|ᅬ|ᅭ|ᅮ|ᅯ|ᅰ|ᅱ|ᅲ|ᅳ|ᅴ|ᅵ|ᆫ|ᆯ|ᆷ|ᆼ)ᄇ/g, '$1б')
		.replace(/(ᅡ|ᅢ|ᅣ|ᅤ|ᅥ|ᅦ|ᅧ|ᅨ|ᅩ|ᅪ|ᅫ|ᅬ|ᅭ|ᅮ|ᅯ|ᅰ|ᅱ|ᅲ|ᅳ|ᅴ|ᅵ|ᆫ|ᆯ|ᆷ|ᆼ)ᄌ/g, '$1чж')
		.replace(/ᆯᄅ/g, 'лль')
		.replace(/ᄀ/g, 'кх')
		.replace(/ᆨ/g, 'к')
		.replace(/ᄁ/g, 'кк')
		.replace(/ᆩ/g, 'к')
		.replace(/ᄂ/g, 'н')
		.replace(/ᆫ/g, 'н')
		.replace(/ᄃ/g, 'тх')
		.replace(/ᆮ/g, 'т')
		.replace(/ᄄ/g, 'тт')
		.replace(/ᄅ/g, 'р')
		.replace(/ᆯ/g, 'ль')
		.replace(/ᄆ/g, 'м')
		.replace(/ᆷ/g, 'м')
		.replace(/ᄇ/g, 'пх')
		.replace(/ᆸ/g, 'п')
		.replace(/ᄈ/g, 'п')
		.replace(/쉬/g, 'щви')
		.replace(/ᄉ/g, 'с')
		.replace(/ᆺ/g, 'т')
		.replace(/ᄊ/g, 'сс')
		.replace(/ᆻ/g, 'т')
		.replace(/ᄋ/g, '')
		.replace(/ᆼ/g, 'нъ')
		.replace(/ᄌ/g, 'ч')
		.replace(/ᆽ/g, 'т')
		.replace(/ᄍ/g, 'тч')
		.replace(/ᄎ/g, 'чх')
		.replace(/ᆾ/g, 'т')
		.replace(/ᄏ/g, 'кх')
		.replace(/ᆿ/g, 'к')
		.replace(/ᄐ/g, 'тх')
		.replace(/ᇀ/g, 'т')
		.replace(/ᄑ/g, 'пх')
		.replace(/ᇁ/g, 'п')
		.replace(/ᄒ/g, 'х')
		.replace(/ᇂ/g, 'т')

		.replace(/ᅡ/g, 'а')
		.replace(/ᅢ/g, 'э')
		.replace(/ᅣ/g, 'я')
		.replace(/ᅤ/g, 'йэ')
		.replace(/ᅥ/g, 'o')
		.replace(/ᅦ/g, 'е')
		.replace(/ᅧ/g, 'йo')
		.replace(/ᅨ/g, 'йе')
		.replace(/ᅩ/g, 'o')
		.replace(/ᅪ/g, 'ва')
		.replace(/ᅫ/g, 'вэ')
		.replace(/ᅬ/g, 'ве')
		.replace(/ᅭ/g, 'ё')
		.replace(/ᅮ/g, 'у')
		.replace(/ᅯ/g, 'вo')
		.replace(/ᅰ/g, 'ве')
		.replace(/ᅱ/g, 'ви')
		.replace(/ᅲ/g, 'ю')
		.replace(/ᅳ/g, 'ы')
		.replace(/ᅴ/g, 'ый')
		.replace(/ᅵ/g, 'и')

		.replace(/ьа/g, 'я')
		.replace(/ьэ/g, 'е')
		.replace(/ьo/g, 'ё')
		.replace(/ьу/g, 'ю')
		.normalize('NFC');
}


function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}