function cyrlat() {
	document.transcription.text1.value = document.transcription.text1.value

		.replace(/ї/g, "ү")
		.replace(/Ї/g, "Ү")
		.replace(/v/g, "ү")
		.replace(/V/g, "Ү")
		.replace(/ѳ/g, "ө")
		.replace(/Ѳ/g, "Ө")
		.replace(/є/g, "ө")
		.replace(/Є/g, "Ө");

	document.transcription.text2.value = document.transcription.text1.value
		.replace(/а/g, "a")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/д/g, "d")
		.replace(/е/g, "ye")
		.replace(/ё/g, "yo")
		.replace(/ж/g, "j")
		.replace(/з/g, "z")
		.replace(/и/g, "i")
		.replace(/й/g, "i")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/о/g, "o")
		.replace(/ө/g, "ö")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ү/g, "ü")
		.replace(/ф/g, "f")
		.replace(/х/g, "kh")
		.replace(/ц/g, "ts")
		.replace(/ч/g, "ch")
		.replace(/ш/g, "sh")
		.replace(/щ/g, "sh")
		.replace(/ъ/g, "i")
		.replace(/ы/g, "y")
		.replace(/ь/g, "i")
		.replace(/э/g, "e")
		.replace(/ю/g, "yu")
		.replace(/я/g, "ya")
		.replace(/А/g, "A")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Д/g, "D")
		.replace(/Е/g, "Ye")
		.replace(/Ё/g, "Yo")
		.replace(/Ж/g, "J")
		.replace(/З/g, "Z")
		.replace(/К/g, "K")
		.replace(/И/g, "I")
		.replace(/Й/g, "I")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/О/g, "O")
		.replace(/Ө/g, "Ö")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ү/g, "Ü")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "Kh")
		.replace(/Ц/g, "Ts")
		.replace(/Ч/g, "Ch")
		.replace(/Ш/g, "Sh")
		.replace(/Щ/g, "Sh")
		.replace(/Ъ/g, "I")
		.replace(/Ы/g, "Y")
		.replace(/Ь/g, "I")
		.replace(/Э/g, "E")
		.replace(/Ю/g, "Yu")
		.replace(/Я/g, "Ya");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}