function topleft() {
	document.transcription.text2.value = document.transcription.text1.value
		.replace(/(\p{Script=Cyrl})a/ug, "$1а")
		.replace(/a(\p{Script=Cyrl})/ug, "а$1")
		.replace(/(\p{Script=Cyrl})e/ug, "$1е")
		.replace(/e(\p{Script=Cyrl})/ug, "е$1")
		.replace(/(\p{Script=Cyrl})i/ug, "$1і")
		.replace(/i(\p{Script=Cyrl})/ug, "і$1")
		.replace(/(\p{Script=Cyrl})ï/ug, "$1ї")
		.replace(/ï(\p{Script=Cyrl})/ug, "ї$1")
		.replace(/(\p{Script=Cyrl})o/ug, "$1о")
		.replace(/o(\p{Script=Cyrl})/ug, "о$1")
		.replace(/(\p{Script=Cyrl})p/ug, "$1р")
		.replace(/p(\p{Script=Cyrl})/ug, "р$1")
		.replace(/(\p{Script=Cyrl})c/ug, "$1с")
		.replace(/c(\p{Script=Cyrl})/ug, "с$1")
		.replace(/(\p{Script=Cyrl})y/ug, "$1у")
		.replace(/y(\p{Script=Cyrl})/ug, "у$1")
		.replace(/(\p{Script=Cyrl})x/ug, "$1х")
		.replace(/x(\p{Script=Cyrl})/ug, "х$1")
		
		.replace(/(\p{Script=Cyrl})A/ug, "$1А")
		.replace(/A(\p{Script=Cyrl})/ug, "А$1")
		.replace(/(\p{Script=Cyrl})B/ug, "$1В")
		.replace(/B(\p{Script=Cyrl})/ug, "В$1")
		.replace(/(\p{Script=Cyrl})E/ug, "$1Е")
		.replace(/E(\p{Script=Cyrl})/ug, "Е$1")
		.replace(/(\p{Script=Cyrl})I/ug, "$1І")
		.replace(/I(\p{Script=Cyrl})/ug, "І$1")
		.replace(/(\p{Script=Cyrl})Ï/ug, "$1Ї")
		.replace(/Ï(\p{Script=Cyrl})/ug, "Ї$1")
		.replace(/(\p{Script=Cyrl})K/ug, "$1К")
		.replace(/K(\p{Script=Cyrl})/ug, "К$1")
		.replace(/(\p{Script=Cyrl})M/ug, "$1М")
		.replace(/M(\p{Script=Cyrl})/ug, "М$1")
		.replace(/(\p{Script=Cyrl})H/ug, "$1Н")
		.replace(/H(\p{Script=Cyrl})/ug, "Н$1")
		.replace(/(\p{Script=Cyrl})O/ug, "$1О")
		.replace(/O(\p{Script=Cyrl})/ug, "О$1")
		.replace(/(\p{Script=Cyrl})P/ug, "$1Р")
		.replace(/P(\p{Script=Cyrl})/ug, "Р$1")
		.replace(/(\p{Script=Cyrl})C/ug, "$1С")
		.replace(/C(\p{Script=Cyrl})/ug, "С$1")
		.replace(/(\p{Script=Cyrl})T/ug, "$1Т")
		.replace(/T(\p{Script=Cyrl})/ug, "Т$1")
		.replace(/(\p{Script=Cyrl})X/ug, "$1Х")
		.replace(/X(\p{Script=Cyrl})/ug, "Х$1")		
		
		.replace(/Х([0-9])/g, "X$1")
		.replace(/х([0-9])/g, "x$1")
		.replace(/([0-9])Х/g, "$1X")
		.replace(/([0-9])х/g, "$1x")

		.replace(/(\u0027|\u2019|\u02bc)/g, "ъ")

		.replace(/Й([Аа])/g, "Й$1\u0300")
		.replace(/йа/g, "йа\u0300")
		.replace(/Й([Ее])/g, "Й$1\u0300")
		.replace(/йе/g, "йе\u0300")
		.replace(/Й([Іі])/g, "Й$1\u0300")
		.replace(/йі/g, "йі\u0300")
		.replace(/Й([Уу])/g, "Й$1\u0300")
		.replace(/йу/g, "йу\u0300")
		.replace(/Й([Оо])/g, "Й$1\u0300")
		.replace(/йо/g, "йо\u0300")

		.replace(/([БбВвГгҐґДдЖжЗзЙйКкЛлМмНнПпРрСсТтФфХхЦцЧчШшЩщ])И/g, "$1Ɩ")
		.replace(/([БбВвГгҐґДдЖжЗзЙйКкЛлМмНнПпРрСсТтФфХхЦцЧчШшЩщ])и/g, "$1ɩ")
		.replace(/([БбВвГгҐґДдЖжЗзЙйКкЛлМмНнПпРрСсТтФфХхЦцЧчШшЩщ])Ɩ([АаБбВвГгҐґДдЕеЄєЖжЗзИиІіЇїЙйКкЛлМмНнОоПпРрСсТтУуФфХхЦцЧчШшЩщЪъЮюЯя])/g, "$1И$2")
		.replace(/([БбВвГгҐґДдЖжЗзЙйКкЛлМмНнПпРрСсТтФфХхЦцЧчШшЩщ])ɩ([АаБбВвГгҐґДдЕеЄєЖжЗзИиІіЇїЙйКкЛлМмНнОоПпРрСсТтУуФфХхЦцЧчШшЩщЪъЮюЯя])/g, "$1и$2")
		.replace(/([АаБбВвГгҐґДдЕеЄєЖжЗзИиІіЇїЙйКкЛлМмНнОоПпРрСсТтУуФфХхЦцЧчШшЩщЪъЮюЯя])([БбВвГгҐґДдЖжЗзЙйКкЛлМмНнПпРрСсТтФфХхЦцЧчШшЩщ])Ɩ/g, "$1$2И")
		.replace(/([АаБбВвГгҐґДдЕеЄєЖжЗзИиІіЇїЙйКкЛлМмНнОоПпРрСсТтУуФфХхЦцЧчШшЩщЪъЮюЯя])([БбВвГгҐґДдЖжЗзЙйКкЛлМмНнПпРрСсТтФфХхЦцЧчШшЩщ])ɩ/g, "$1$2и")

		.replace(/ɩ/g, "і")
		.replace(/Ɩ/g, "І")

		.replace(/дж/g, "џ")
		.replace(/Д([Жж])/g, "Џ")

		.replace(/([СКЗ])Г/g, "$1\u2019Г")
		.replace(/([СКЗскз])г/g, "$1\u2019г")
		/*
		.replace(/Ш([Чч])/g, "Ш\u2019$1")
		.replace(/шч/g, "ш\u2019ч")
		.replace(/Т([Сс])/g, "Т\u2019$1")
		.replace(/тс/g, "т\u2019с")*/

		.replace(/(\p{Uppercase})(\p{Uppercase}) Я/ug, "$1$2 ЬА")
		.replace(/Я (\p{Uppercase})(\p{Uppercase})/ug, "ЬА $1$2")
		.replace(/Я(\p{Uppercase})/ug, "ЬА$1")
		.replace(/Я/g, "Ьа")
		.replace(/я/g, "ьа")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Є/ug, "$1$2 ЬЕ")
		.replace(/Є (\p{Uppercase})(\p{Uppercase})/ug, "ЬЕ $1$2")
		.replace(/Є(\p{Uppercase})/ug, "ЬЕ$1")
		.replace(/Є/g, "Ье")
		.replace(/є/g, "ье")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ї/ug, "$1$2 ЬІ")
		.replace(/Ї (\p{Uppercase})(\p{Uppercase})/ug, "ЬІ $1$2")
		.replace(/Ї(\p{Uppercase})/ug, "ЬІ$1")
		.replace(/Ї/g, "Ьі")
		.replace(/ї/g, "ьі")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ю/ug, "$1$2 ЬУ")
		.replace(/Ю (\p{Uppercase})(\p{Uppercase})/ug, "ЬУ $1$2")
		.replace(/Ю(\p{Uppercase})/ug, "ЬУ$1")
		.replace(/Ю/g, "Ьу")
		.replace(/ю/g, "ьу")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Щ/ug, "$1$2 ШЧ")
		.replace(/Щ (\p{Uppercase})(\p{Uppercase})/ug, "ШЧ $1$2")
		.replace(/Щ(\p{Uppercase})/ug, "ШЧ$1")
		.replace(/Щ/g, "Шч")
		.replace(/щ/g, "шч")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Х/ug, "$1$2 КГ")
		.replace(/Х (\p{Uppercase})(\p{Uppercase})/ug, "КГ $1$2")
		.replace(/Х(\p{Uppercase})/ug, "КГ$1")
		.replace(/Х/g, "Кг")
		.replace(/х/g, "кг")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ш/ug, "$1$2 СГ")
		.replace(/Ш (\p{Uppercase})(\p{Uppercase})/ug, "СГ $1$2")
		.replace(/Ш(\p{Uppercase})/ug, "СГ$1")
		.replace(/Ш/g, "Сг")
		.replace(/ш/g, "сг")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ж/ug, "$1$2 ЗГ")
		.replace(/Ж (\p{Uppercase})(\p{Uppercase})/ug, "ЗГ $1$2")
		.replace(/Ж(\p{Uppercase})/ug, "ЗГ$1")
		.replace(/Ж/g, "Зг")
		.replace(/ж/g, "зг")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ч/ug, "$1$2 \u0043Г")
		.replace(/Ч (\p{Uppercase})(\p{Uppercase})/ug, "\u0043Г $1$2")
		.replace(/Ч(\p{Uppercase})/ug, "\u0043Г$1")
		.replace(/Ч/g, "\u0043г")
		.replace(/ч/g, "\u0063г")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ц/ug, "$1$2 ТС")
		.replace(/Ц (\p{Uppercase})(\p{Uppercase})/ug, "ТС $1$2")
		.replace(/Ц(\p{Uppercase})/ug, "ТС$1")
		.replace(/Ц/g, "Тс")
		.replace(/ц/g, "тс")

		.replace(/([БВГҐДЏЗКЛМНПРСТФ])Ь([АЕІИОУ])/g, "$1І$2")
		.replace(/([БВГҐДЏЗКЛМНПРСТФбвгґдџзклмнпрстф])ь([аеіиоу])/g, "$1і$2")
		.replace(/Ь([АЕІИОУаеіиоу])/g, "Й$1")
		.replace(/ь([аеіиоу])/g, "й$1")
		.replace(/ЬЬ/g, "Й")
		.replace(/([Ьь])ь/g, "й")

		.replace(/а/g, "a")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "h")
		.replace(/ґ/g, "g")
		.replace(/д/g, "d")
		.replace(/џ/g, "j")
		.replace(/е/g, "e")
		.replace(/з/g, "z")
		.replace(/и/g, "y")
		.replace(/і/g, "i")
		.replace(/й/g, "ẏ")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/о/g, "o")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ф/g, "f")

		.replace(/А/g, "A")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "H")
		.replace(/Ґ/g, "G")
		.replace(/Д/g, "D")
		.replace(/Џ/g, "J")
		.replace(/Е/g, "E")
		.replace(/З/g, "Z")
		.replace(/И/g, "Y")
		.replace(/І/g, "I")
		.replace(/Й/g, "Ẏ")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/О/g, "O")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ф/g, "F")

		.replace(/([ЬЪьъ])/g, "")

		.replace(/ẎY/g, "ẎI")
		.replace(/([Ẏẏ])y/g, "$1i")
		.replace(/Y([Ẏẏ])((?![AEIOUYẎ]))/g, "Y$2")
		.replace(/yẏ((?![aeiouyẏ]))/g, "y$1")
		.replace(/YẎ([AEIOUYẎ])/g, "IẎ$1")
		.replace(/Yẏ([aeiouyẏ])/g, "Iẏ$1")
		.replace(/yẏ([aeiouyẏ])/g, "iẏ$1")

		.replace(/([BCDFGHKLMNPRSTVZ])ẎI/g, "$1I")
		.replace(/([BCDFGHKLMNPRSTVZbcdfghklmnprstvz])ẏi/g, "$1i")

		.replace(/([AEOUYẎ])Ẏ((?![AEIOUYẎ]))/g, "$1I$2")
		.replace(/([AEOUYẎaeouyẏ])ẏ((?![aeiouyẏ]))/g, "$1i$2")
		.replace(/IẎ((?![AEIOUYẎ]))/g, "I$1")
		.replace(/([Ii])ẏ((?![aeiouyẏ]))/g, "$1$2")

		.replace(/Ẏ/g, "Y")
		.replace(/ẏ/g, "y")

		.replace(/«/g, "\u201e")
		.replace(/»/g, "\u201c")
		.normalize('NFC');
}

function topright() {
	document.transcription.text1.value = document.transcription.text1.value
		.replace(/<</g, "«")
		.replace(/>>/g, "»");

	document.transcription.text3.value = document.transcription.text1.value
		.replace(/(\u2019|\u0027)/g, "\u02bc")

		.replace(/(Б|В|Г|Ґ|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|ґ|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)(ь|Ь)О/g, "$1Ó")
		.replace(/(Б|В|Г|Ґ|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|ґ|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)(ь|Ь)о/g, "$1ó")

		.replace(/(Б|В|Г|Ґ|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|ґ|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)Я/g, "$1Á")
		.replace(/(Б|В|Г|Ґ|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|ґ|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)я/g, "$1á")
		.replace(/(Б|В|Г|Ґ|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|ґ|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)Ю/g, "$1Ú")
		.replace(/(Б|В|Г|Ґ|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|ґ|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)ю/g, "$1ú")
		.replace(/(Б|В|Г|Ґ|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|ґ|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)Є/g, "$1É")
		.replace(/(Б|В|Г|Ґ|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|ґ|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)є/g, "$1é")
		.replace(/(Б|В|Г|Ґ|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|ґ|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)Ї/g, "$1Í")
		.replace(/(Б|В|Г|Ґ|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|ґ|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)ї/g, "$1í")

		.replace(/Ь(А|Е|І|У|а|е|і|у)/g, "Ь\u2019$1")
		.replace(/ь(а|е|і|у)/g, "ь\u2019$1")
		.replace(/ЬЯ/g, "ЬA")
		.replace(/ЬЄ/g, "ЬE")
		.replace(/ЬЇ/g, "ЬI")
		.replace(/ЬЮ/g, "ЬU")
		.replace(/(Ь|ь)я/g, "$1a")
		.replace(/(Ь|ь)є/g, "$1e")
		.replace(/(Ь|ь)ї/g, "$1i")
		.replace(/(Ь|ь)ю/g, "$1u")

		.replace(/\u02bc/g, "")

		.replace(/а/g, "a")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "h")
		.replace(/ґ/g, "g")
		.replace(/д/g, "d")
		.replace(/е/g, "e")
		.replace(/ж/g, "ž")
		.replace(/з/g, "z")
		.replace(/и/g, "y")
		.replace(/і/g, "i")
		.replace(/й/g, "j")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/о/g, "o")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ф/g, "f")
		.replace(/х/g, "x")
		.replace(/ц/g, "c")
		.replace(/ч/g, "č")
		.replace(/ш/g, "š")
		.replace(/щ/g, "šč")
		.replace(/ь/g, "j")
		.replace(/є/g, "je")
		.replace(/ї/g, "ji")
		.replace(/ю/g, "ju")
		.replace(/я/g, "ja")

		.replace(/А/g, "A")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "H")
		.replace(/Ґ/g, "G")
		.replace(/Д/g, "D")
		.replace(/Е/g, "E")
		.replace(/Ж/g, "Ž")
		.replace(/З/g, "Z")
		.replace(/И/g, "Y")
		.replace(/І/g, "I")
		.replace(/Й/g, "J")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/О/g, "O")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "X")
		.replace(/Ц/g, "C")
		.replace(/Ч/g, "Č")
		.replace(/Ш/g, "Š")
		.replace(/Щ/g, "Šč")
		.replace(/Ь/g, "J")
		.replace(/Є/g, "Je")
		.replace(/Ї/g, "Ji")
		.replace(/Ю/g, "Ju")
		.replace(/Я/g, "Ja");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}

function copy3() {
	navigator.clipboard.writeText(document.transcription.text3.value);
}
