function cyrlat() {
	document.transcription.text2.value = document.transcription.text1.value
	.replace(/(B|b|C|c|Ç|ç|D|d|F|f|G|g|H|h|J|j|K|k|L|l|M|m|N|n|P|p|R|r|S|s|Ş|ş|T|t|V|v|Y|y|Z|z)Ğ/g, "$1G")
	.replace(/(B|b|C|c|Ç|ç|D|d|F|f|G|g|H|h|J|j|K|k|L|l|M|m|N|n|P|p|R|r|S|s|Ş|ş|T|t|V|v|Y|y|Z|z)ğ/g, "$1g")

	.replace(/(A|a|Â|â|E|e|Ê|ê|I|ı|İ|i|Î|î|O|o|Ö|ö|U|u|Û|û|Ü|ü)(B|b|C|c|Ç|ç|D|d|F|f|G|g|Ğ|ğ|H|h|J|j|K|k|L|l|M|m|N|n|P|p|R|r|S|s|Ş|ş|T|t|V|v|Y|y|Z|z)(B|b|C|c|Ç|ç|D|d|F|f|G|g|Ğ|ğ|H|h|J|j|K|k|L|l|M|m|N|n|P|p|R|r|S|s|Ş|ş|T|t|V|v|Y|y|Z|z)(B|b|C|c|Ç|ç|D|d|F|f|G|g|Ğ|ğ|H|h|J|j|K|k|L|l|M|m|N|n|P|p|R|r|S|s|Ş|ş|T|t|V|v|Y|y|Z|z)(A|a|Â|â|E|e|Ê|ê|I|ı|İ|i|Î|î|O|o|Ö|ö|U|u|Û|û|Ü|ü)/g, "$1$2$3.$4$5")
	.replace(/(A|a|Â|â|E|e|Ê|ê|I|ı|İ|i|Î|î|O|o|Ö|ö|U|u|Û|û|Ü|ü)(B|b|C|c|Ç|ç|D|d|F|f|G|g|Ğ|ğ|H|h|J|j|K|k|L|l|M|m|N|n|P|p|R|r|S|s|Ş|ş|T|t|V|v|Y|y|Z|z)(B|b|C|c|Ç|ç|D|d|F|f|G|g|Ğ|ğ|H|h|J|j|K|k|L|l|M|m|N|n|P|p|R|r|S|s|Ş|ş|T|t|V|v|Y|y|Z|z)(B|b|C|c|Ç|ç|D|d|F|f|G|g|Ğ|ğ|H|h|J|j|K|k|L|l|M|m|N|n|P|p|R|r|S|s|Ş|ş|T|t|V|v|Y|y|Z|z)(A|a|Â|â|E|e|Ê|ê|I|ı|İ|i|Î|î|O|o|Ö|ö|U|u|Û|û|Ü|ü)/g, "$1$2$3.$4$5")
	.replace(/(A|a|Â|â|E|e|Ê|ê|I|ı|İ|i|Î|î|O|o|Ö|ö|U|u|Û|û|Ü|ü)(B|b|C|c|Ç|ç|D|d|F|f|G|g|Ğ|ğ|H|h|J|j|K|k|L|l|M|m|N|n|P|p|R|r|S|s|Ş|ş|T|t|V|v|Y|y|Z|z)(B|b|C|c|Ç|ç|D|d|F|f|G|g|Ğ|ğ|H|h|J|j|K|k|L|l|M|m|N|n|P|p|R|r|S|s|Ş|ş|T|t|V|v|Y|y|Z|z)(A|a|Â|â|E|e|Ê|ê|I|ı|İ|i|Î|î|O|o|Ö|ö|U|u|Û|û|Ü|ü)/g, "$1$2.$3$4")
	.replace(/(A|a|Â|â|E|e|Ê|ê|I|ı|İ|i|Î|î|O|o|Ö|ö|U|u|Û|û|Ü|ü)(B|b|C|c|Ç|ç|D|d|F|f|G|g|Ğ|ğ|H|h|J|j|K|k|L|l|M|m|N|n|P|p|R|r|S|s|Ş|ş|T|t|V|v|Y|y|Z|z)(B|b|C|c|Ç|ç|D|d|F|f|G|g|Ğ|ğ|H|h|J|j|K|k|L|l|M|m|N|n|P|p|R|r|S|s|Ş|ş|T|t|V|v|Y|y|Z|z)(A|a|Â|â|E|e|Ê|ê|I|ı|İ|i|Î|î|O|o|Ö|ö|U|u|Û|û|Ü|ü)/g, "$1$2.$3$4")
	.replace(/(A|a|Â|â|E|e|Ê|ê|I|ı|İ|i|Î|î|O|o|Ö|ö|U|u|Û|û|Ü|ü)(B|b|C|c|Ç|ç|D|d|F|f|G|g|Ğ|ğ|H|h|J|j|K|k|L|l|M|m|N|n|P|p|R|r|S|s|Ş|ş|T|t|V|v|Y|y|Z|z)(A|a|Â|â|E|e|Ê|ê|I|ı|İ|i|Î|î|O|o|Ö|ö|U|u|Û|û|Ü|ü)/g, "$1.$2$3")
	.replace(/(A|a|Â|â|E|e|Ê|ê|I|ı|İ|i|Î|î|O|o|Ö|ö|U|u|Û|û|Ü|ü)(B|b|C|c|Ç|ç|D|d|F|f|G|g|Ğ|ğ|H|h|J|j|K|k|L|l|M|m|N|n|P|p|R|r|S|s|Ş|ş|T|t|V|v|Y|y|Z|z)(A|a|Â|â|E|e|Ê|ê|I|ı|İ|i|Î|î|O|o|Ö|ö|U|u|Û|û|Ü|ü)/g, "$1.$2$3")
	.replace(/(A|a|Â|â|E|e|Ê|ê|I|ı|İ|i|Î|î|O|o|Ö|ö|U|u|Û|û|Ü|ü)(A|a|Â|â|E|e|Ê|ê|I|ı|İ|i|Î|î|O|o|Ö|ö|U|u|Û|û|Ü|ü)/g, "$1.$2")
	.replace(/(A|a|Â|â|E|e|Ê|ê|I|ı|İ|i|Î|î|O|o|Ö|ö|U|u|Û|û|Ü|ü)(A|a|Â|â|E|e|Ê|ê|I|ı|İ|i|Î|î|O|o|Ö|ö|U|u|Û|û|Ü|ü)/g, "$1.$2")

	.replace(/A/g, "a")
	.replace(/B/g, "b")
	.replace(/C|c/g, "ʤ")
	.replace(/Ç|ç/g, "ʧ")
	.replace(/D/g, "d")
	.replace(/E/g, "e")
	.replace(/Ê|ê/g, "eː")
	.replace(/F/g, "f")
	.replace(/G|g/g, "ɡ")
	.replace(/Ğ|ğ/g, "ɰ")
	.replace(/H/g, "h")
	.replace(/I|ı/g, "ɯ")
	.replace(/İ/g, "i")
	.replace(/Î|î/g, "iː")
	.replace(/J|j/g, "ʒ")
	.replace(/K/g, "k")
	.replace(/L|l/g, "ɫ")
	.replace(/M/g, "m")
	.replace(/N/g, "n")
	.replace(/O/g, "o")
	.replace(/Ö|ö/g, "œ")
	.replace(/P/g, "p")
	.replace(/R|r/g, "ɾ")
	.replace(/S/g, "s")
	.replace(/Ş|ş/g, "ʃ")
	.replace(/T/g, "t")
	.replace(/U/g, "u")
	.replace(/Y|y/g, "j")
	.replace(/Ü|ü/g, "y")
	.replace(/V/g, "v")
	.replace(/Z/g, "z")

	.replace(/(b|ʤ|ʧ|d|f|ɡ|h|ʒ|k|ɫ|m|n|p|ɾ|s|ʃ|t|v|j|z)(b|ʤ|ʧ|d|f|ɡ|h|ʒ|k|ɫ|m|n|p|ɾ|s|ʃ|t|v|j|z)(a|â|o|u|û|ɯ|e|ê|i|î|y|œ)/g, "$1ɯ\.$2$3")

	.replace(/Â|â/g, "ʲa")
	.replace(/Û|û/g, "ʲu")

	.replace(/eɰ/g, "eĵ")
	.replace(/ĵ(b|ʤ|ʧ|d|f|ɡ|h|ʒ|k|ɫ|m|n|p|ɾ|s|ʃ|t|v|j|z)/g, "ː$1")
	.replace(/ĵ/g, "j")
	.replace(/(a|i|o|u|y|œ|ɯ)ɰ/g, "$1ː")
 	.replace(/a\.i/g, "aː.i")
	.replace(/a\.ɰɯ/g, "a.ɰa")
	.replace(/ɰ/g, "")

	.replace(/(o|u|y|œ)v/g, "$1β")
	.replace(/v(o|u|y|œ)/g, "β$1")

	.replace(/(e|i|œ|y)ɡ/g, "$1ɟ")
	.replace(/(e|i|œ|y)k/g, "$1c")
	.replace(/(e|i|œ|y)ɫ/g, "$1l")
	.replace(/(e|i|œ|y)(b|ʤ|ʧ|d|f|ɡ|ɟ|ː|h|ʒ|k|c|ɫ|l|m|n|p|ɾ|s|ʃ|t|v|β|j|z)ɡ/g, "$1$2ɟ")
	.replace(/(e|i|œ|y)(b|ʤ|ʧ|d|f|ɡ|ɟ|ː|h|ʒ|k|c|ɫ|l|m|n|p|ɾ|s|ʃ|t|v|β|j|z)k/g, "$1$2c")
	.replace(/(e|i|œ|y)(b|ʤ|ʧ|d|f|ɡ|ɟ|ː|h|ʒ|k|c|ɫ|l|m|n|p|ɾ|s|ʃ|t|v|β|j|z)ɫ/g, "$1$2l")
	.replace(/ɡ(e|i|œ|y|ʲ)/g, "ɟ$1")
	.replace(/k(e|i|œ|y|ʲ)/g, "c$1")
	.replace(/ɫ(e|i|œ|y|ʲ)/g, "l$1")
	.replace(/(ɟ|c|l)ʲ/g, "$1")

	.replace(/ʲ(a|u)(b|ʤ|ʧ|d|f|ɡ|ɟ|ː|h|ʒ|k|c|ɫ|l|m|n|p|ɾ|s|ʃ|t|v|β|j|z)/g, "$1$2")
	.replace(/ʲ(a|u)/g, "$1ː")

	.replace(/n(ɡ|\.ɡ|k|\.k)/g, "ŋ$1")
	.replace(/n(ɟ|\.ɟ|c|\.cc)/g, "ɲ$1")

	.replace(/.mez/g, ".mæz")
	.replace(/e(ɾ|l|m|n)/g, "æ$1")
	.replace(/eː(ɾ|l|m|n)/g, "æː$1")

	.replace(/æɲ(.)?(c|ɟ)/g, "eɲ$1$2")

	.replace(/a/g, "ɑ")
	
	.replace(/([ɑeæɯioœuy])[ː]?h/g, '$1ː')
	.replace(/([ɑeiu])\.([bʤʧdfɡɟʒkclɫmnŋɲɾsʃvβjz])/g, '$1$2\.')
	.replace(/ɟ\.([ɑɯoœuy])/g, 'ɡ.j$1')
	.replace(/c\.([ɑɯoœuy])/g, 'k.j$1')
	.replace(/l\.([ɑɯoœuy])/g, 'ɫ.j$1')
	.replace(/[uy]j\.([ɑeæɯioœuy])/g, "uː\.j$1")
	.replace(/([ʤʧfʒlɫmnŋɲɾsʃvβjz])[uy]j([bʤʧdfɡɟʒkclɫmnŋɲɾsʃvβjz])/g, '$1uː.iː$2')
	.replace(/[uy]j/g, 'wiː')
	.replace(/([ɑeæɯioœuy])β/g, '$1v')
	
	.replace(/([bʤʧfɡɟhʒkclɫmnŋɲpɾʃvβ])(yɾ|yːɾ)/g, '$1URE')
	.replace(/(juɾ|juːɾ|jyɾ|jyːɾ)/g, 'YOOR')
	.replace(/([bʤʧfɡɟhʒkclɫmnŋɲpɾʃvβ])(y|yː)/g, '$1EW')
	.replace(/(juː|ju|jyː|jy)/g, 'YOO')
	.replace(/æɾ/g, 'AIR')
	.replace(/æ/g, 'A')
	.replace(/ɑːɾ/g, 'AR')
	.replace(/ɑː/g, 'AH')
	.replace(/e([bʤʧdfɡɟʒkclɫmnŋɲpɾsʃtvβz])/g, 'E$1')
	.replace(/([bʤʧdfɡɟhʒkclɫmnŋɲpɾsʃtvβz])(ej|eː|e)([bʤʧdfɡɟʒkclɫmnŋɲpɾsʃtvβz])/g, '$1A$2E')
	.replace(/(ej|eː|e)/g, 'AY')
	.replace(/iɾ/g, 'IRR')
	.replace(/i([bʤʧdfɡɟʒkclɫmnŋɲpsʃtvβz])/g, 'I$1')
	.replace(/(iː|ij|ɯj|ɯː|i)/g, 'EE')
	.replace(/ɯːɾ/g, 'EER')
	.replace(/ɑjɾ/g, 'IRE')
	.replace(/([bʤʧdfɡɟhʒkclɫmnŋɲpɾsʃtvβz])ɑj([bʤʧdfɡɟʒkclɫmnŋɲpɾsʃtvβz])/g, '$1Y$2E')
	.replace(/([bʤʧdfɡɟhʒkclɫmnŋɲpɾsʃtvβz])ɑj/g, '$1Y')
	.replace(/ɑj/g, 'EYE')
	.replace(/[oœ]jɾ/g, 'OIR')
	.replace(/[oœ]j/g, 'OY')
	.replace(/œɾ/g, 'UR')
	.replace(/oːɾ|oɾ/g, 'OR')
	.replace(/([bʤʧdfɡɟhʒkclɫmnŋɲpɾsʃtvβz])(oː|o|œː|œ)([bʤʧdfɡɟʒkclɫmnŋɲpɾsʃtvβz])/g, '$1O$2E')
	.replace(/oː|o|œː|œ/g, 'OH')
	.replace(/ɑɾ/g, 'URR')
	.replace(/([bʤʧdfɡhɟʒkclɫmnŋɲpɾsʃtvβjz])ɑ([flɫnstz])([bʤʧdfɡɟʒkclɫmnŋɲpɾsʃtvβjz])/g, '$1U$2$3')
	.replace(/([bʤʧdfɡhɟʒkclɫmnŋɲpɾsʃtvβjz])ɑ([flɫnstz])/g, '$1U$2$2')
	.replace(/([bʤʧdfɡhɟʒkclɫmnŋɲpɾsʃtvβjz])ɑʤ/g, '$1UDGE')
	.replace(/ɑ[kc]/g, 'UCK')
	.replace(/ɑ([bʤʧdfɡɟʒkclɫmnŋɲpɾsʃtvβz])/g, 'U$1')
	.replace(/uɾ/g, 'UURR')
	.replace(/yɾ/g, 'OOR')
	.replace(/u([bʤʧdfɡɟʒkclɫmnŋɲpɾsʃtvβz])/g, 'UU$1')
	.replace(/y([bʤʧdfɡɟʒkclɫmnŋɲpɾsʃtvβz])/g, 'OO$1')
	.replace(/(uː|u|yː|y)/g, 'OO')
	.replace(/ɑ/g, 'UH')
	.replace(/ɯ/g, 'Ə')
	.replace(/ʤ/g, 'J')
	.replace(/([AEIOUYaeuioy])ʧ/g, '$1TCH')
	.replace(/ʧ/g, 'CH')
	.replace(/[ɡɟ]([EIei])/g, 'GH$1')
	.replace(/[ɡɟ]/g, 'G')
	.replace(/ʒ/g, 'ZH')
	.replace(/[lɫ]/g, 'L')
	.replace(/(ŋk|ɲc)/g, 'NK')
	.replace(/[kc]/g, 'K')
	.replace(/ŋɡ/g, 'NG')
	.replace(/[ŋɲ]/g, 'NG')
	.replace(/ɾ/g, 'R')
	.replace(/ʃ/g, 'SH')
	.replace(/hw/g, 'WH')
	.replace(/β/g, 'W')
	.replace(/j/g, 'Y')
	.replace(/\u002e/g, '\u002d')
	.toLowerCase();
}

function copy1()
{ navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2()
{ navigator.clipboard.writeText(document.transcription.text2.value);
}
