//  copyright lexilogos.com
var car;
function latcyr () {
}
function cyrlat () {
car = document.transcription.text1.value;
translit = document.transcription.text1.value;
translit = translit.replace(/Ы/g, "Ъ");
car = car.replace(/Ы/g, "Ъ");
translit = translit.replace(/ы/g, "ъ");
car = car.replace(/ы/g, "ъ");
car = car.replace(/ъ̀/g, "ъ");

car = car.replace(/ияа/g, "ийаа");
car = car.replace(/ияб/g, "ийаб");
car = car.replace(/ияв/g, "ийав");
car = car.replace(/ияг/g, "ийаг");
car = car.replace(/ияд/g, "ийад");
car = car.replace(/ияе/g, "ийае");
car = car.replace(/ияж/g, "ийаж");
car = car.replace(/ияз/g, "ийаз");
car = car.replace(/ияи/g, "ийаи");
car = car.replace(/ияѝ/g, "ийаѝ");
car = car.replace(/ияй/g, "ийай");
car = car.replace(/ияк/g, "ийак");
car = car.replace(/иял/g, "ийал");
car = car.replace(/иям/g, "ийам");
car = car.replace(/иян/g, "ийан");
car = car.replace(/ияо/g, "ийао");
car = car.replace(/ияп/g, "ийап");
car = car.replace(/ияр/g, "ийар");
car = car.replace(/ияс/g, "ийас");
car = car.replace(/ият/g, "ийат");
car = car.replace(/ияу/g, "ийау");
car = car.replace(/ияф/g, "ийаф");
car = car.replace(/иях/g, "ийах");
car = car.replace(/ияц/g, "ийац");
car = car.replace(/ияч/g, "ийач");
car = car.replace(/ияш/g, "ийаш");
car = car.replace(/иящ/g, "ийащ");
car = car.replace(/ияъ/g, "ийаъ");
car = car.replace(/ияь/g, "ийаь");
car = car.replace(/ияю/g, "ийаю");
car = car.replace(/ияя/g, "ийая");

car = car.replace(/Ияа/g, "Ийаа");
car = car.replace(/Ияб/g, "Ийаб");
car = car.replace(/Ияв/g, "Ийав");
car = car.replace(/Ияг/g, "Ийаг");
car = car.replace(/Ияд/g, "Ийад");
car = car.replace(/Ияе/g, "Ийае");
car = car.replace(/Ияж/g, "Ийаж");
car = car.replace(/Ияз/g, "Ийаз");
car = car.replace(/Ияи/g, "Ийаи");
car = car.replace(/Ияѝ/g, "Ийаѝ");
car = car.replace(/Ияй/g, "Ийай");
car = car.replace(/Ияк/g, "Ийак");
car = car.replace(/Иял/g, "Ийал");
car = car.replace(/Иям/g, "Ийам");
car = car.replace(/Иян/g, "Ийан");
car = car.replace(/Ияо/g, "Ийао");
car = car.replace(/Ияп/g, "Ийап");
car = car.replace(/Ияр/g, "Ийар");
car = car.replace(/Ияс/g, "Ийас");
car = car.replace(/Ият/g, "Ийат");
car = car.replace(/Ияу/g, "Ийау");
car = car.replace(/Ияф/g, "Ийаф");
car = car.replace(/Иях/g, "Ийах");
car = car.replace(/Ияц/g, "Ийац");
car = car.replace(/Ияч/g, "Ийач");
car = car.replace(/Ияш/g, "Ийаш");
car = car.replace(/Иящ/g, "Ийащ");
car = car.replace(/Ияъ/g, "Ийаъ");
car = car.replace(/Ияь/g, "Ийаь");
car = car.replace(/Ияю/g, "Ийаю");
car = car.replace(/Ияя/g, "Ийая");

car = car.replace(/ИЯА/g, "ИЙАА");
car = car.replace(/ИЯБ/g, "ИЙАБ");
car = car.replace(/ИЯВ/g, "ИЙАВ");
car = car.replace(/ИЯГ/g, "ИЙАГ");
car = car.replace(/ИЯД/g, "ИЙАД");
car = car.replace(/ИЯЕ/g, "ИЙАЕ");
car = car.replace(/ИЯЖ/g, "ИЙАЖ");
car = car.replace(/ИЯЗ/g, "ИЙАЗ");
car = car.replace(/ИЯИ/g, "ИЙАИ");
car = car.replace(/ИЯЍ/g, "ИЙАЍ");
car = car.replace(/ИЯЙ/g, "ИЙАЙ");
car = car.replace(/ИЯК/g, "ИЙАК");
car = car.replace(/ИЯЛ/g, "ИЙАЛ");
car = car.replace(/ИЯМ/g, "ИЙАМ");
car = car.replace(/ИЯН/g, "ИЙАН");
car = car.replace(/ИЯО/g, "ИЙАО");
car = car.replace(/ИЯП/g, "ИЙАП");
car = car.replace(/ИЯР/g, "ИЙАР");
car = car.replace(/ИЯС/g, "ИЙАС");
car = car.replace(/ИЯТ/g, "ИЙАТ");
car = car.replace(/ИЯУ/g, "ИЙАУ");
car = car.replace(/ИЯФ/g, "ИЙАФ");
car = car.replace(/ИЯХ/g, "ИЙАХ");
car = car.replace(/ИЯЦ/g, "ИЙАЦ");
car = car.replace(/ИЯЧ/g, "ИЙАЧ");
car = car.replace(/ИЯШ/g, "ИЙАШ");
car = car.replace(/ИЯЩ/g, "ИЙАЩ");
car = car.replace(/ИЯЪ/g, "ИЙАЪ");
car = car.replace(/ИЯЬ/g, "ИЙАЬ");
car = car.replace(/ИЯЮ/g, "ИЙАЮ");
car = car.replace(/ИЯЯ/g, "ИЙАЯ");

car = car.replace(/ия/g, "иа");
car = car.replace(/Ия/g, "Иа");
car = car.replace(/ИЯ/g, "ИА");

car = car.replace(/българ/g, "булгар");
car = car.replace(/Българ/g, "Булгар");
car = car.replace(/БЪЛГАР/g, "БУЛГАР");

car = car.replace(/а/g, "a");
car = car.replace(/б/g, "b");
car = car.replace(/в/g, "v");
car = car.replace(/г/g, "g");
car = car.replace(/д/g, "d");
car = car.replace(/е/g, "e");
car = car.replace(/ж/g, "zh");
car = car.replace(/з/g, "z");
car = car.replace(/и/g, "i");
car = car.replace(/ѝ/g, "i");
car = car.replace(/й/g, "y");
car = car.replace(/к/g, "k");
car = car.replace(/л/g, "l");
car = car.replace(/м/g, "m");
car = car.replace(/н/g, "n");
car = car.replace(/о/g, "o");
car = car.replace(/п/g, "p");
car = car.replace(/р/g, "r");
car = car.replace(/с/g, "s");
car = car.replace(/т/g, "t");
car = car.replace(/у/g, "u");
car = car.replace(/ф/g, "f");
car = car.replace(/х/g, "h");
car = car.replace(/ц/g, "ts");
car = car.replace(/ч/g, "ch");
car = car.replace(/ш/g, "sh");
car = car.replace(/щ/g, "sht");
car = car.replace(/ъ/g, "a");
car = car.replace(/ь/g, "y");
car = car.replace(/ю/g, "yu");
car = car.replace(/я/g, "ya");

car = car.replace(/А/g, "A");
car = car.replace(/Б/g, "B");
car = car.replace(/В/g, "V");
car = car.replace(/Г/g, "G");
car = car.replace(/Д/g, "D");
car = car.replace(/Е/g, "E");
car = car.replace(/Ж/g, "Zh");
car = car.replace(/З/g, "Z");
car = car.replace(/И/g, "I");
car = car.replace(/Ѝ/g, "I");
car = car.replace(/Й/g, "Y");
car = car.replace(/К/g, "K");
car = car.replace(/Л/g, "L");
car = car.replace(/М/g, "M");
car = car.replace(/Н/g, "N");
car = car.replace(/О/g, "O");
car = car.replace(/П/g, "P");
car = car.replace(/Р/g, "R");
car = car.replace(/С/g, "S");
car = car.replace(/Т/g, "T");
car = car.replace(/У/g, "U");
car = car.replace(/Ф/g, "F");
car = car.replace(/Х/g, "H");
car = car.replace(/Ц/g, "Ts");
car = car.replace(/Ч/g, "Ch");
car = car.replace(/Ш/g, "Sh");
car = car.replace(/Щ/g, "Sht");
car = car.replace(/Ъ/g, "A");
car = car.replace(/Ь/g, "Y");
car = car.replace(/Ю/g, "Yu");
car = car.replace(/Я/g, "Ya");
document.transcription.text1.value=translit;
document.transcription.text2.value=car;
}
function copy1()
{ textRange=document.transcription.text1.createTextRange();   textRange.execCommand("Copy");   textRange="";
}
function copy2()
{ textRange=document.transcription.text2.createTextRange();   textRange.execCommand("Copy");   textRange="";
}