function latcyr() {}

function cyrlat() {
	document.transcription.text1.value = document.transcription.text1.value
		.replace(/ö/g, "ӧ")
		.replace(/Ö/g, "Ӧ")
		.replace(/ÿ/g, "ӱ")
		.replace(/Ÿ/g, "Ӱ")
		.replace(/j/g, "ј")
		.replace(/J/g, "Ј");

	document.transcription.text2.value = document.transcription.text1.value
		.replace(/ е/g, " ýe")
		.replace(/\nе/g, "\nýe")
		.replace(/\rе/g, "\rýe")
		.replace(/^е/g, "ýe")

		.replace(/ае/g, "аýe")
		.replace(/ие/g, "иýe")
		.replace(/ые/g, "ыýe")
		.replace(/ее/g, "еýe")
		.replace(/эе/g, "эýe")
		.replace(/уе/g, "уýe")
		.replace(/ое/g, "оýe")
		.replace(/ӧе/g, "ӧýe")
		.replace(/ёе/g, "ёýe")
		.replace(/ӱе/g, "ӱýe")
		.replace(/йе/g, "йýe")
		.replace(/юе/g, "юýe")
		.replace(/яе/g, "яýe")
		.replace(/ье/g, "ýe")

		.replace(/ Е/g, " Ýe")
		.replace(/\nЕ/g, "\nÝe")
		.replace(/\rЕ/g, "\rÝe")
		.replace(/^Е/g, "Ýe")

		.replace(/Ае/g, "Аýe")
		.replace(/Ие/g, "Иýe")
		.replace(/Ые/g, "Ыýe")
		.replace(/Ее/g, "Еýe")
		.replace(/Эе/g, "Эýe")
		.replace(/Уе/g, "Уýe")
		.replace(/Ое/g, "Оýe")
		.replace(/Ӧе/g, "Ӧýe")
		.replace(/Ёе/g, "Ёýe")
		.replace(/Ӱе/g, "Ӱýe")
		.replace(/Йе/g, "Йýe")
		.replace(/Юе/g, "Юýe")
		.replace(/Яе/g, "Яýe")
		.replace(/Ье/g, "Ýe")

		.replace(/АЕ/g, "АÝE")
		.replace(/ИЕ/g, "ИÝE")
		.replace(/ЫЕ/g, "ЫÝE")
		.replace(/ЕЕ/g, "ЕÝE")
		.replace(/ЭЕ/g, "ЭÝE")
		.replace(/УЕ/g, "УÝE")
		.replace(/ОЕ/g, "ОÝE")
		.replace(/ӦЕ/g, "ӦÝE")
		.replace(/ЁЕ/g, "ЁÝE")
		.replace(/ӰЕ/g, "ӰÝE")
		.replace(/ЙЕ/g, "ЙÝE")
		.replace(/ЮЕ/g, "ЮÝE")
		.replace(/ЯЕ/g, "ЯÝE")
		.replace(/ЬЕ/g, "ÝE")

		.replace(/а/g, "a")
		.replace(/б/g, "b")
		.replace(/в/g, "w")
		.replace(/г/g, "g")
		.replace(/д/g, "d")
		.replace(/е/g, "e")
		.replace(/ё/g, "ýo")
		.replace(/ж/g, "ž")
		.replace(/ј/g, "j")
		.replace(/з/g, "z")
		.replace(/и/g, "i")
		.replace(/й/g, "ý")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/ҥ/g, "ň")
		.replace(/о/g, "o")
		.replace(/ӧ/g, "ö")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ӱ/g, "ü")
		.replace(/ф/g, "f")
		.replace(/х/g, "h")
		.replace(/ц/g, "ts")
		.replace(/ч/g, "ç")
		.replace(/ш/g, "ş")
		.replace(/щ/g, "şç")
		.replace(/ъ/g, "ʼ")
		.replace(/ы/g, "y")
		.replace(/ь/g, "")
		.replace(/э/g, "e")
		.replace(/ю/g, "ýu")
		.replace(/я/g, "ýa")
		.replace(/А/g, "A")
		.replace(/Б/g, "B")
		.replace(/В/g, "W")
		.replace(/Г/g, "G")
		.replace(/Д/g, "D")
		.replace(/Е/g, "E")
		.replace(/Ё/g, "Ýo")
		.replace(/Ж/g, "Ž")
		.replace(/Ј/g, "J")
		.replace(/З/g, "Z")
		.replace(/И/g, "I")
		.replace(/Й/g, "Ý")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/Ҥ/g, "Ň")
		.replace(/О/g, "O")
		.replace(/Ӧ/g, "Ö")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ӱ/g, "Ü")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "H")
		.replace(/Ц/g, "Ts")
		.replace(/Ч/g, "Ç")
		.replace(/Ш/g, "Ş")
		.replace(/Щ/g, "Şç")
		.replace(/Ъ/g, "ʼ")
		.replace(/Ы/g, "Y")
		.replace(/Ь/g, "")
		.replace(/Э/g, "E")
		.replace(/Ю/g, "Ýu")
		.replace(/Я/g, "Ýa");
}

function copy1()
{ navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2()
{ navigator.clipboard.writeText(document.transcription.text2.value);
}
