function cyrlat() {
	document.transcription.text2.value = document.transcription.text1.value

		.replace(/j/g, "ј")
		.replace(/J/g, "Ј")
		.replace(/ö/g, "ӧ")
		.replace(/ÿ/g, "ӱ")
		.replace(/Ö/g, "Ӧ")
		.replace(/Ÿ/g, "Ӱ")

		.replace(/([АЕЁИОӦУӰЫЮЯ])Ц/g, "$1ТС")
		.replace(/([аеёиоӧуӱыюя])Ц/g, "$1Тс")
		.replace(/([аеёиоӧуӱыюя])ц/g, "$1тс")
		.replace(/Ц/g, "С")
		.replace(/ц/g, "с")

		.replace(/([АЕЁИОӦУӰЫЮЯ])Щ([АЕЁИОӦУӰЫЮЯ])/g, "$1ШШ$2")
		.replace(/([АЕЁИОӦУӰЫЮЯ])Щ([аеёиоӧуӱыюя])/g, "$1Шш$2")
		.replace(/([аеёиоӧуӱыюя])щ([аеёиоӧуӱыюя])/g, "$1шш$2")
		.replace(/щ/g, "ш")
		.replace(/Щ/g, "Ш")

		.replace(/([БВГДЈЖЗКЛМНҤПРСТФХЧШ])Я/g, "$1ЬА")
		.replace(/([бвгдјжзклмнҥпрстфхчш])Я/g, "$1ьА")
		.replace(/([БВГДЈЖЗКЛМНҤПРСТФХЧШЩбвгдјжзклмнҥпрстфхчш])я/g, "$1ьа")
		.replace(/([БВГДЈЖЗКЛМНҤПРСТФХЧШЩбвгдјжзклмнҥпрстфхчш])Ю/g, "$1Ӱ")
		.replace(/([БВГДЈЖЗКЛМНҤПРСТФХЧШЩбвгдјжзклмнҥпрстфхчш])ю/g, "$1ӱ")
		.replace(/([БВГДЈЖЗЙКЛМНҤПРСТФХЧШЩбвгдјжзйклмнҥпрстфхчш])Е/g, "$1Э")
		.replace(/([БВГДЈЖЗЙКЛМНҤПРСТФХЧШЩбвгдјжзйклмнҥпрстфхчш])е/g, "$1э")
		.replace(/([БВГДЈЖЗКЛМНҤПРСТФХЧШЩбвгдјжзклмнҥпрстфхчш])Ё/g, "$1Ӧ")
		.replace(/([БВГДЈЖЗКЛМНҤПРСТФХЧШЩбвгдјжзклмнҥпрстфхчш])ё/g, "$1ӧ")

		.replace(/Ь([Ии])/g, "Й$1")
		.replace(/ьи/g, "йи")

		.replace(/(\p{Lu})(\p{Lu}) Я/ug, "$1$2 ЙА")
		.replace(/(\p{Lu})Я/ug, "$1ЙА")
		.replace(/Я (\p{Lu})(\p{Lu})/ug, "ЙА $1$2")
		.replace(/Я(\p{Lu})/ug, "ЙА$1")
		.replace(/Я/g, "Йа")
		.replace(/я/g, "йа")
		.replace(/(\p{Lu})(\p{Lu}) Е/ug, "$1$2 ЙЭ")
		.replace(/(\p{Lu})Е/ug, "$1ЙЭ")
		.replace(/Е (\p{Lu})(\p{Lu})/ug, "ЙЭ $1$2")
		.replace(/Е(\p{Lu})/ug, "ЙЭ$1")
		.replace(/Е/g, "Йэ")
		.replace(/е/g, "йэ")
		.replace(/(\p{Lu})(\p{Lu}) Ё/ug, "$1$2 ЙО")
		.replace(/(\p{Lu})Ё/ug, "$1ЙО")
		.replace(/Ё (\p{Lu})(\p{Lu})/ug, "ЙО $1$2")
		.replace(/Ё(\p{Lu})/ug, "ЙО$1")
		.replace(/Ё/g, "Йо")
		.replace(/ё/g, "йо")
		.replace(/(\p{Lu})(\p{Lu}) Ю/ug, "$1$2 ЙУ")
		.replace(/(\p{Lu})Ю/ug, "$1ЙУ")
		.replace(/Ю (\p{Lu})(\p{Lu})/ug, "ЙУ $1$2")
		.replace(/Ю(\p{Lu})/ug, "ЙУ$1")
		.replace(/Ю/g, "Йу")
		.replace(/ю/g, "йу")

		.replace(/([Ъъ])/g, "")

		.replace(/а/g, "a")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/д/g, "d")
		.replace(/ј/g, "c")
		.replace(/е/g, "e")
		.replace(/ж/g, "j")
		.replace(/з/g, "z")
		.replace(/и/g, "i")
		.replace(/й/g, "y")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/ҥ/g, "ñ")
		.replace(/о/g, "o")
		.replace(/ӧ/g, "ö")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ӱ/g, "ü")
		.replace(/ф/g, "f")
		.replace(/х/g, "h")
		.replace(/ч/g, "ç")
		.replace(/ш/g, "ş")
		.replace(/ь/g, "")
		.replace(/ы/g, "ı")
		.replace(/э/g, "e")

		.replace(/А/g, "A")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Д/g, "D")
		.replace(/Ј/g, "C")
		.replace(/Е/g, "E")
		.replace(/Ж/g, "J")
		.replace(/З/g, "Z")
		.replace(/И/g, "İ")
		.replace(/Й/g, "Y")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/Ҥ/g, "Ñ")
		.replace(/О/g, "O")
		.replace(/Ӧ/g, "Ö")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ӱ/g, "Ü")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "H")
		.replace(/Ч/g, "Ç")
		.replace(/Ш/g, "Ş")
		.replace(/Ь/g, "")
		.replace(/Ы/g, "I")
		.replace(/Э/g, "E")

		.replace(/\u2039/g, "\u2018")
		.replace(/\u203a/g, "\u2019")
		.replace(/\u00ab/g, "\u201c")
		.replace(/\u00bb/g, "\u201d")

		.normalize('NFC');
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}
