function latcyr() {
	document.transcription.text1.value = document.transcription.text2.value
		.replace(/о/g, "ô")
		.replace(/О/g, "Ô")
		.replace(/я/g, "á")
		.replace(/Я/g, "Á")
		.replace(/є/g, "é")
		.replace(/Є/g, "É")
		.replace(/ю/g, "ú")
		.replace(/Ю/g, "Ú")
		.replace(/і/g, "í")
		.replace(/І/g, "Í")
		.replace(/ј/g, "y")
		.replace(/Ј/g, "Y")
		.replace(/ч/g, "j")
		.replace(/Ч/g, "J")
		.replace(/щ/g, "č")
		.replace(/Щ/g, "Č")
		.replace(/ш/g, "š")
		.replace(/Ш/g, "Š")
		.replace(/ж/g, "ž")
		.replace(/Ж/g, "Ž")
		.replace(/х/g, "x")
		.replace(/Х/g, "X")
		.replace(/ѕ/g, "ź")
		.replace(/Ѕ/g, "Ź")

		.replace(/а/g, "a")
		.replace(/А/g, "A")
		.replace(/б/g, "b")
		.replace(/Б/g, "B")
		.replace(/в/g, "v")
		.replace(/В/g, "V")
		.replace(/г/g, "g")
		.replace(/Г/g, "G")
		.replace(/д/g, "d")
		.replace(/Д/g, "D")
		.replace(/е/g, "o")
		.replace(/Е/g, "O")
		.replace(/ё/g, "o")
		.replace(/Ё/g, "O")
		.replace(/з/g, "z")
		.replace(/З/g, "Z")
		.replace(/и/g, "i")
		.replace(/И/g, "I")
		.replace(/к/g, "q")
		.replace(/К/g, "Q")
		.replace(/qь/g, "k")
		.replace(/QЬ/g, "K")
		.replace(/л/g, "l")
		.replace(/Л/g, "L")
		.replace(/м/g, "m")
		.replace(/М/g, "M")
		.replace(/н/g, "n")
		.replace(/Н/g, "N")
		.replace(/п/g, "p")
		.replace(/П/g, "P")
		.replace(/р/g, "r")
		.replace(/Р/g, "R")
		.replace(/с/g, "s")
		.replace(/С/g, "S")
		.replace(/т/g, "t")
		.replace(/Т/g, "T")
		.replace(/ў/g, "w")
		.replace(/Ў/g, "W")
		.replace(/у/g, "u")
		.replace(/У/g, "U")
		.replace(/ф/g, "f")
		.replace(/Ф/g, "F")
		.replace(/xь/g, "h")
		.replace(/XЬ/g, "H")
		.replace(/ц/g, "c")
		.replace(/Ц/g, "C")
		.replace(/э/g, "e")
		.replace(/Э/g, "E");
}

function cyrlat() {
	document.transcription.text2.value = document.transcription.text1.value
		.replace(/â/g, "о")
		.replace(/Â/g, "О")
		.replace(/á/g, "я")
		.replace(/Á/g, "Я")
		.replace(/é/g, "є")
		.replace(/É/g, "Є")
		.replace(/ú/g, "ю")
		.replace(/Ú/g, "Ю")
		.replace(/ŏ/g, "о")
		.replace(/Ŏ/g, "О")
		.replace(/ô/g, "о")
		.replace(/Ô/g, "О")
		.replace(/X/g, "Х")
		.replace(/x/g, "х")
		.replace(/Š/g, "Ш")
		.replace(/š/g, "ш")
		.replace(/J/g, "Ч")
		.replace(/j/g, "ч")
		.replace(/Č/g, "Щ")
		.replace(/č/g, "щ")
		.replace(/Ź/g, "Ѕ")
		.replace(/ź/g, "ѕ")
		.replace(/Y/g, "Ј")
		.replace(/y/g, "ј")
		.replace(/Í/g, "І")
		.replace(/í/g, "і")
		.replace(/Ž/g, "Ж")
		.replace(/ž/g, "ж")

		.replace(/a/g, "а")
		.replace(/A/g, "А")
		.replace(/b/g, "б")
		.replace(/B/g, "Б")
		.replace(/v/g, "в")
		.replace(/V/g, "В")
		.replace(/g/g, "г")
		.replace(/G/g, "Г")
		.replace(/d/g, "д")
		.replace(/D/g, "Д")
		.replace(/o/g, "ё")
		.replace(/O/g, "Ё")
		.replace(/z/g, "з")
		.replace(/Z/g, "З")
		.replace(/i/g, "и")
		.replace(/I/g, "И")
		.replace(/q/g, "к")
		.replace(/Q/g, "К")
		.replace(/k/g, "кь")
		.replace(/K/g, "КЬ")
		.replace(/l/g, "л")
		.replace(/L/g, "Л")
		.replace(/m/g, "м")
		.replace(/M/g, "М")
		.replace(/n/g, "н")
		.replace(/N/g, "Н")
		.replace(/p/g, "п")
		.replace(/P/g, "П")
		.replace(/r/g, "р")
		.replace(/R/g, "Р")
		.replace(/s/g, "с")
		.replace(/S/g, "С")
		.replace(/t/g, "т")
		.replace(/T/g, "Т")
		.replace(/w/g, "ў")
		.replace(/W/g, "Ў")
		.replace(/u/g, "у")
		.replace(/U/g, "У")
		.replace(/f/g, "ф")
		.replace(/F/g, "Ф")
		.replace(/h/g, "хь")
		.replace(/H/g, "ХЬ")
		.replace(/c/g, "ц")
		.replace(/C/g, "Ц")
		.replace(/e/g, "э")
		.replace(/E/g, "Э");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}