function cyrlat() {
	document.transcription.text2.value = document.transcription.text1.value
		.replace(/DZSZ/g, "DZ\u200bSZ")
		.replace(/Dzsz/g, "Dz\u200bsz")
		.replace(/dzsz/g, "dz\u200bsz")

		.replace(/SZS/g, "SZ\u200bS")
		.replace(/Szs/g, "Sz\u200bs")
		.replace(/szs/g, "sz\u200bs")

		.replace(/ZSZ/g, "Z\u200bSZ")
		.replace(/Zsz/g, "Z\u200bsz")
		.replace(/zsz/g, "z\u200bsz")

		.replace(/CSZ/g, "CS\u200bZ")
		.replace(/Csz/g, "Cs\u200bz")
		.replace(/csz/g, "cs\u200bz")

		.replace(/TTY/g, "ĆĆ")
		.replace(/Tty/g, "Ćć")
		.replace(/tty/g, "ćć")
		.replace(/GGY/g, "ĐĐ")
		.replace(/Ggy/g, "Đđ")
		.replace(/ggy/g, "đđ")
		.replace(/CCS/g, "ÇÇ")
		.replace(/Ccs/g, "Çç")
		.replace(/ccs/g, "çç")
		.replace(/SSZ/g, "ṠṠ")
		.replace(/Ssz/g, "Ṡṡ")
		.replace(/ssz/g, "ṡṡ")
		.replace(/ZZS/g, "ĴĴ")
		.replace(/Zzs/g, "Ĵĵ")
		.replace(/zzs/g, "ĵĵ")
		.replace(/DDZS/g, "ĊĊ")
		.replace(/Ddzs/g, "Ċċ")
		.replace(/ddzs/g, "ċċ")
		.replace(/NNY/g, "ŃŃ")
		.replace(/Nny/g, "Ńń")
		.replace(/nny/g, "ńń")
		.replace(/LLY/g, "ĹĹ")
		.replace(/Lly/g, "Ĺĺ")
		.replace(/lly/g, "ĺĺ")
		.replace(/DDZ/g, "ƵƵ")
		.replace(/Ddz/g, "Ƶƶ")
		.replace(/ddz/g, "ƶƶ")

		.replace(/DZS/g, "Ċ")
		.replace(/Dzs/g, "Ċ")
		.replace(/dzs/g, "ċ")
		.replace(/ZS/g, "Ĵ")
		.replace(/Zs/g, "Ĵ")
		.replace(/zs/g, "ĵ")
		.replace(/SZ/g, "Ṡ")
		.replace(/Sz/g, "Ṡ")
		.replace(/sz/g, "ṡ")
		.replace(/DZ/g, "Ƶ")
		.replace(/Dz/g, "Ƶ")
		.replace(/dz/g, "ƶ")
		.replace(/CS/g, "Ç")
		.replace(/Cs/g, "Ç")
		.replace(/cs/g, "ç")
		.replace(/GY/g, "Đ")
		.replace(/Gy/g, "Đ")
		.replace(/gy/g, "đ")
		.replace(/NY/g, "Ń")
		.replace(/Ny/g, "Ń")
		.replace(/ny/g, "ń")
		.replace(/LY/g, "Ĺ")
		.replace(/Ly/g, "Ĺ")
		.replace(/ly/g, "ĺ")
		.replace(/TY/g, "Ć")
		.replace(/Ty/g, "Ć")
		.replace(/ty/g, "ć")
		.replace(/C/g, "Ţ")
		.replace(/c/g, "ţ")
		.replace(/Ċ/g, "C")
		.replace(/ċ/g, "c")
		.replace(/S/g, "Ş")
		.replace(/s/g, "ş")
		.replace(/Ṡ/g, "S")
		.replace(/ṡ/g, "s")
		.replace(/I/g, "İ")
		.replace(/Y/g, "İ")
		.replace(/y/g, "i")
		.replace(/J/g, "Y")
		.replace(/j/g, "y")
		.replace(/Ĵ/g, "J")
		.replace(/ĵ/g, "j")

		.replace(/\u200b/g, "")

		.replace(/P(B|D|Ƶ|C|G|Đ|Z|J|b|d|ƶ|c|g|đ|z|j)/g, "B$1")
		.replace(/T(B|D|Ƶ|C|G|Đ|Z|J|b|d|ƶ|c|g|đ|z|j)/g, "D$1")
		.replace(/Ţ(B|D|Ƶ|C|G|Đ|Z|J|b|d|ƶ|c|g|đ|z|j)/g, "Ƶ$1")
		.replace(/Ç(B|D|Ƶ|C|G|Đ|Z|J|b|d|ƶ|c|g|đ|z|j)/g, "C$1")
		.replace(/K(B|D|Ƶ|C|G|Đ|Z|J|b|d|ƶ|c|g|đ|z|j)/g, "G$1")
		.replace(/Ć(B|D|Ƶ|C|G|Đ|Z|J|b|d|ƶ|c|g|đ|z|j)/g, "Đ$1")
		.replace(/F(B|D|Ƶ|C|G|Đ|Z|J|b|d|ƶ|c|g|đ|z|j)/g, "V$1")
		.replace(/S(B|D|Ƶ|C|G|Đ|Z|J|b|d|ƶ|c|g|đ|z|j)/g, "Z$1")
		.replace(/Ş(B|D|Ƶ|C|G|Đ|Z|J|b|d|ƶ|c|g|đ|z|j)/g, "J$1")
		.replace(/p(b|d|ƶ|c|g|đ|z|j)/g, "b$1")
		.replace(/t(b|d|ƶ|c|g|đ|z|j)/g, "d$1")
		.replace(/ţ(b|d|ƶ|c|g|đ|z|j)/g, "ƶ$1")
		.replace(/ç(b|d|ƶ|c|g|đ|z|j)/g, "c$1")
		.replace(/k(b|d|ƶ|c|g|đ|z|j)/g, "g$1")
		.replace(/ć(b|d|ƶ|c|g|đ|z|j)/g, "đ$1")
		.replace(/f(b|d|ƶ|c|g|đ|z|j)/g, "v$1")
		.replace(/s(b|d|ƶ|c|g|đ|z|j)/g, "z$1")
		.replace(/ş(b|d|ƶ|c|g|đ|z|j)/g, "j$1")

		.replace(/B(P|T|Ţ|Ç|K|Ć|S|Ş|H|p|t|ţ|ç|k|ć|s|ş|h)/g, "P$1")
		.replace(/D(P|T|Ţ|Ç|K|Ć|S|Ş|H|p|t|ţ|ç|k|ć|s|ş|h)/g, "T$1")
		.replace(/Ƶ(P|T|Ţ|Ç|K|Ć|S|Ş|H|p|t|ţ|ç|k|ć|s|ş|h)/g, "Ţ$1")
		.replace(/C(P|T|Ţ|Ç|K|Ć|S|Ş|H|p|t|ţ|ç|k|ć|s|ş|h)/g, "Ç$1")
		.replace(/G(P|T|Ţ|Ç|K|Ć|S|Ş|H|p|t|ţ|ç|k|ć|s|ş|h)/g, "K$1")
		.replace(/Đ(P|T|Ţ|Ç|K|Ć|S|Ş|H|p|t|ţ|ç|k|ć|s|ş|h)/g, "Ć$1")
		.replace(/V(P|T|Ţ|Ç|K|Ć|S|Ş|H|p|t|ţ|ç|k|ć|s|ş|h)/g, "F$1")
		.replace(/Z(P|T|Ţ|Ç|K|Ć|S|Ş|H|p|t|ţ|ç|k|ć|s|ş|h)/g, "S$1")
		.replace(/J(P|T|Ţ|Ç|K|Ć|S|Ş|H|p|t|ţ|ç|k|ć|s|ş|h)/g, "Ş$1")
		.replace(/b(p|t|ţ|ç|k|ć|s|ş|h)/g, "p$1")
		.replace(/d(p|t|ţ|ç|k|ć|s|ş|h)/g, "t$1")
		.replace(/ƶ(p|t|ţ|ç|k|ć|s|ş|h)/g, "ţ$1")
		.replace(/c(p|t|ţ|ç|k|ć|s|ş|h)/g, "ç$1")
		.replace(/g(p|t|ţ|ç|k|ć|s|ş|h)/g, "k$1")
		.replace(/đ(p|t|ţ|ç|k|ć|s|ş|h)/g, "ć$1")
		.replace(/v(p|t|ţ|ç|k|ć|s|ş|h)/g, "f$1")
		.replace(/z(p|t|ţ|ç|k|ć|s|ş|h)/g, "s$1")
		.replace(/j(p|t|ţ|ç|k|ć|s|ş|h)/g, "ş$1")

		.replace(/DY/g, "ĐĐ")
		.replace(/ĐY/g, "ĐĐ")
		.replace(/LY/g, "ĹĹ")
		.replace(/ĹY/g, "ĹĹ")
		.replace(/NY/g, "ŃŃ")
		.replace(/ŃY/g, "ŃŃ")
		.replace(/TY/g, "ĆĆ")
		.replace(/ĆY/g, "ĆĆ")
		.replace(/Dy/g, "Đđ")
		.replace(/Đy/g, "Đđ")
		.replace(/Ly/g, "Ĺĺ")
		.replace(/Ĺy/g, "Ĺĺ")
		.replace(/Ny/g, "Ńń")
		.replace(/Ńy/g, "Ńń")
		.replace(/Ty/g, "Ćć")
		.replace(/Ćy/g, "Ćć")
		.replace(/dy/g, "đđ")
		.replace(/đy/g, "đđ")
		.replace(/ly/g, "ĺĺ")
		.replace(/ĺy/g, "ĺĺ")
		.replace(/ny/g, "ńń")
		.replace(/ńy/g, "ńń")
		.replace(/ty/g, "ćć")
		.replace(/ćy/g, "ćć")

		.replace(/Á/g, "A")
		.replace(/É/g, "E")
		.replace(/Í/g, "İ")
		.replace(/Ó/g, "O")
		.replace(/Ő/g, "Ö")
		.replace(/Ú/g, "U")
		.replace(/Ű/g, "Ü")
		.replace(/á/g, "a")
		.replace(/é/g, "e")
		.replace(/í/g, "i")
		.replace(/ó/g, "o")
		.replace(/ő/g, "ö")
		.replace(/ú/g, "u")
		.replace(/ű/g, "ü")

		.replace(/(E|e|İ|i|Ö|ö|Ü|ü)Đ/g, "$1Ǵ")
		.replace(/(E|e|İ|i|Ö|ö|Ü|ü)đ/g, "$1ǵ")
		.replace(/(E|e|İ|i|Ö|ö|Ü|ü)Ć/g, "$1Ḱ")
		.replace(/(E|e|İ|i|Ö|ö|Ü|ü)ć/g, "$1ḱ")

		.replace(/ĐĐ(A|a|E|e|İ|i|Ö|ö|U|u|Ü|ü| A| a| U| u| E| e| İ| i| Ö| ö| Ü| ü)/g, "ǴǴ$1")
		.replace(/Đđ(A|a|E|e|İ|i|Ö|ö|U|u|Ü|ü| A| a| U| u| E| e| İ| i| Ö| ö| Ü| ü)/g, "Ǵǵ$1")
		.replace(/đđ(A|a|E|e|İ|i|Ö|ö|U|u|Ü|ü| A| a| U| u| E| e| İ| i| Ö| ö| Ü| ü)/g, "ǵǵ$1")
		.replace(/ĆĆ(A|a|E|e|İ|i|Ö|ö|U|u|Ü|ü| A| a| U| u| E| e| İ| i| Ö| ö| Ü| ü)/g, "ḰḰ$1")
		.replace(/Ćć(A|a|E|e|İ|i|Ö|ö|U|u|Ü|ü| A| a| U| u| E| e| İ| i| Ö| ö| Ü| ü)/g, "Ḱḱ$1")
		.replace(/ćć(A|a|E|e|İ|i|Ö|ö|U|u|Ü|ü| A| a| U| u| E| e| İ| i| Ö| ö| Ü| ü)/g, "ḱḱ$1")
		.replace(/đ(A|a|E|e|İ|i|Ö|ö|U|u|Ü|ü| A| a| U| u| E| e| İ| i| Ö| ö| Ü| ü)/g, "ǵ$1")
		.replace(/Ć(A|a|E|e|İ|i|Ö|ö|U|u|Ü|ü| A| a| U| u| E| e| İ| i| Ö| ö| Ü| ü)/g, "Ḱ$1")
		.replace(/ć(A|a|E|e|İ|i|Ö|ö|U|u|Ü|ü| A| a| U| u| E| e| İ| i| Ö| ö| Ü| ü)/g, "ḱ$1")

		.replace(/Đ(A|a|E|e|İ|i|Ö|ö|U|u|Ü|ü| A| a| U| u| E| e| İ| i| Ö| ö| Ü| ü)/g, "Ǵ$1")
		.replace(/đ(A|a|E|e|İ|i|Ö|ö|U|u|Ü|ü| A| a| U| u| E| e| İ| i| Ö| ö| Ü| ü)/g, "ǵ$1")
		.replace(/Ć(A|a|E|e|İ|i|Ö|ö|U|u|Ü|ü| A| a| U| u| E| e| İ| i| Ö| ö| Ü| ü)/g, "Ḱ$1")
		.replace(/ć(A|a|E|e|İ|i|Ö|ö|U|u|Ü|ü| A| a| U| u| E| e| İ| i| Ö| ö| Ü| ü)/g, "ḱ$1")
		.replace(/Đ/g, "C")
		.replace(/đ/g, "c")
		.replace(/Ć/g, "Ç")
		.replace(/ć/g, "ç")

		.replace(/Ĺ/g, "Y")
		.replace(/ĺ/g, "y")

		.replace(/(Ǵ|ǵ|Ḱ|ḱ)(A|a|U|u)/g, "$1$2\u0302")
		.normalize('NFD')
		.replace(/\u0301/g, "")
		.normalize('NFC')

		.replace(/(A|Â|E|İ|O|U|Û|Ö|Ü|a|â|e|i|o|u|û|ö|ü)ŢŢ/g, "$1TTS")
		.replace(/(a|â|e|i|o|u|û|ö|ü)Ţţ/g, "$1Tts")
		.replace(/(a|â|e|i|o|u|û|ö|ü)ţŢ/g, "$1tTs")
		.replace(/(a|â|e|i|o|u|û|ö|ü)ţţ/g, "$1tts")
		.replace(/(A|Â|E|İ|O|U|Û|Ö|Ü)Ţţ/g, "$1Tts")
		.replace(/(A|Â|E|İ|O|U|Û|Ö|Ü)ţŢ/g, "$1tTS")
		.replace(/(A|Â|E|İ|O|U|Û|Ö|Ü)ţţ/g, "$1tts")

		.replace(/(a|â|e|i|o|u|û|ö|ü)Ţ/g, "$1Ts")
		.replace(/(A|Â|E|İ|O|U|Û|Ö|Ü)Ţ/g, "$1TS")
		.replace(/(A|Â|E|İ|O|U|Û|Ö|Ü|a|â|e|i|o|u|û|ö|ü)ţ/g, "$1ts")
		.replace(/Ţ/g, "S")
		.replace(/ţ/g, "s")

		.replace(/(A|Â|E|İ|O|U|Û|Ö|Ü|a|â|e|i|o|u|û|ö|ü)ƵƵ/g, "$1DDZ")
		.replace(/(a|â|e|i|o|u|û|ö|ü)Ƶƶ/g, "$1Ddz")
		.replace(/(a|â|e|i|o|u|û|ö|ü)ƶƵ/g, "$1tDz")
		.replace(/(a|â|e|i|o|u|û|ö|ü)ƶƶ/g, "$1ddz")
		.replace(/(A|Â|E|İ|O|U|Û|Ö|Ü)Ƶƶ/g, "$1Ddz")
		.replace(/(A|Â|E|İ|O|U|Û|Ö|Ü)ƶƵ/g, "$1tDZ")
		.replace(/(A|Â|E|İ|O|U|Û|Ö|Ü)ƶƶ/g, "$1ddz")

		.replace(/(a|â|e|i|o|u|û|ö|ü)Ƶ/g, "$1Dz")
		.replace(/(A|Â|E|İ|O|U|Û|Ö|Ü)Ƶ/g, "$1DZ")
		.replace(/(A|Â|E|İ|O|U|Û|Ö|Ü|a|â|e|i|o|u|û|ö|ü)ƶ/g, "$1dz")
		.replace(/Ƶ/g, "Z")
		.replace(/ƶ/g, "z");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}
