function topright() {
	// --- INPUT NORMALIZATION & MIXED SCRIPT FIXES ---
	document.transcription.text1.value = document.transcription.text1.value

		// Convert homoglyphic Latin letters to Cyrillic when adjacent to Cyrillic (right side)
		.replace(/(\p{Script=Cyrl})A/ug, "$1А")
		.replace(/(\p{Script=Cyrl})B/ug, "$1В")
		.replace(/(\p{Script=Cyrl})C/ug, "$1С")
		.replace(/(\p{Script=Cyrl})E/ug, "$1Е")
		.replace(/(\p{Script=Cyrl})Ë/ug, "$1Ё")
		.replace(/(\p{Script=Cyrl})H/ug, "$1Н")
		.replace(/(\p{Script=Cyrl})I/ug, "$1І")
		.replace(/(\p{Script=Cyrl})Ï/ug, "$1Ї")
		.replace(/(\p{Script=Cyrl})J/ug, "$1Ј")
		.replace(/(\p{Script=Cyrl})K/ug, "$1К")
		.replace(/(\p{Script=Cyrl})M/ug, "$1М")
		.replace(/(\p{Script=Cyrl})O/ug, "$1О")
		.replace(/(\p{Script=Cyrl})P/ug, "$1Р")
		.replace(/(\p{Script=Cyrl})T/ug, "$1Т")
		.replace(/(\p{Script=Cyrl})X/ug, "$1Х")
		.replace(/(\p{Script=Cyrl})Y/ug, "$1Ү")

		// Same as above for lowercase
		.replace(/(\p{Script=Cyrl})a/ug, "$1а")
		.replace(/(\p{Script=Cyrl})c/ug, "$1с")
		.replace(/(\p{Script=Cyrl})e/ug, "$1е")
		.replace(/(\p{Script=Cyrl})ë/ug, "$1ё")
		.replace(/(\p{Script=Cyrl})h/ug, "$1һ")
		.replace(/(\p{Script=Cyrl})i/ug, "$1і")
		.replace(/(\p{Script=Cyrl})ï/ug, "$1ї")
		.replace(/(\p{Script=Cyrl})j/ug, "$1ј")
		.replace(/(\p{Script=Cyrl})o/ug, "$1о")
		.replace(/(\p{Script=Cyrl})p/ug, "$1р")
		.replace(/(\p{Script=Cyrl})x/ug, "$1х")
		.replace(/(\p{Script=Cyrl})y/ug, "$1у")

		// Convert homoglyphic Latin letters to Cyrillic when adjacent to Cyrillic (left side)
		.replace(/A(\p{Script=Cyrl})/ug, "А$1")
		.replace(/C(\p{Script=Cyrl})/ug, "С$1")
		.replace(/E(\p{Script=Cyrl})/ug, "Е$1")
		.replace(/Ë(\p{Script=Cyrl})/ug, "Ё$1")
		.replace(/H(\p{Script=Cyrl})/ug, "Н$1")
		.replace(/I(\p{Script=Cyrl})/ug, "І$1")
		.replace(/Ï(\p{Script=Cyrl})/ug, "Ї$1")
		.replace(/J(\p{Script=Cyrl})/ug, "Ј$1")
		.replace(/K(\p{Script=Cyrl})/ug, "К$1")
		.replace(/M(\p{Script=Cyrl})/ug, "М$1")
		.replace(/O(\p{Script=Cyrl})/ug, "О$1")
		.replace(/P(\p{Script=Cyrl})/ug, "Р$1")
		.replace(/T(\p{Script=Cyrl})/ug, "Т$1")
		.replace(/X(\p{Script=Cyrl})/ug, "Х$1")
		.replace(/Y(\p{Script=Cyrl})/ug, "Ү$1")

		// Same as above for lowercase
		.replace(/a(\p{Script=Cyrl})/ug, "а$1")
		.replace(/c(\p{Script=Cyrl})/ug, "с$1")
		.replace(/e(\p{Script=Cyrl})/ug, "е$1")
		.replace(/ë(\p{Script=Cyrl})/ug, "ё$1")
		.replace(/h(\p{Script=Cyrl})/ug, "һ$1")
		.replace(/i(\p{Script=Cyrl})/ug, "і$1")
		.replace(/ï(\p{Script=Cyrl})/ug, "ї$1")
		.replace(/j(\p{Script=Cyrl})/ug, "ј$1")
		.replace(/o(\p{Script=Cyrl})/ug, "о$1")
		.replace(/p(\p{Script=Cyrl})/ug, "р$1")
		.replace(/x(\p{Script=Cyrl})/ug, "х$1")
		.replace(/y(\p{Script=Cyrl})/ug, "у$1")

		// Normalize archaic / variant Cyrillic letters to standard ones
		.replace(/(є|ѳ)/g, "ө")
		.replace(/ї/g, "ү")
		.replace(/(\p{Script=Cyrl})v/g, "$1ү")
		.replace(/v(\p{Script=Cyrl})/g, "ү$1")
		.replace(/(Є|Ѳ)/g, "Ө")
		.replace(/Ї/g, "Ү")
		.replace(/(\p{Script=Cyrl})V/g, "$1Ү")
		.replace(/V(\p{Script=Cyrl})/g, "Ү$1");

	// --- MAIN TRANSFORMATION PIPELINE ---
	document.transcription.text3.value = document.transcription.text1.value
		.normalize('NFC') // Normalize Unicode composition

		// --- Й + VOWEL DIACRITIC MARKING ---
		.replace(/Й([АаЭэИиОоӨөУуҮү])/g, "Й$1\u0308")
		.replace(/й([аэиоөуү])/g, "й$1\u0308")

		// --- VOWEL COLLISION / RESOLUTION RULES ---
		.replace(/ЕЭ/g, "ЙЭЭ")
		.replace(/Еэ/g, "Йээ")
		.replace(/еэ/g, "йээ")
		.replace(/ЭЕ/g, "ЭЙЭ")
		.replace(/([Ээ])е/g, "$1йэ")
		.replace(/ЮҮ/g, "ЙҮҮ")
		.replace(/Юү/g, "Йүү")
		.replace(/юү/g, "йүү")
		.replace(/ҮЮ/g, "ҮЙҮ")
		.replace(/([Үү])ю/g, "$1йү")

		// --- PALATALIZATION MARKING (CONSONANT + IOTATED VOWEL) ---
		.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩ])Я/g, "$1ЬА")
		.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩбвгджзклмнпрстфхцчшщ])я/g, "$1ьа")
		.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩ])Е/g, "$1ЬЭ")
		.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩбвгджзклмнпрстфхцчшщ])е/g, "$1ьэ")
		.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩ])Ё/g, "$1ЬО")
		.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩбвгджзклмнпрстфхцчшщ])ё/g, "$1ьо")
		.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩ])Ю/g, "$1ЬУ")
		.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩбвгджзклмнпрстфхцчшщ])ю/g, "$1ьу")

		// --- IOTATED VOWELS → Й + VOWEL (CASE-SENSITIVE HANDLING) ---
		.replace(/(\p{Lu})Я/ug, "$1ЙА")
		.replace(/(\p{Lu})(\p{Lu}) Я/ug, "$1$2 ЙА")
		.replace(/Я (\p{Lu})(\p{Lu})/ug, "ЙА $1$2")
		.replace(/Я(\p{Lu})/ug, "ЙА$1")
		.replace(/Я/ug, "Йа")
		.replace(/я/ug, "йа")

		.replace(/(\p{Lu})Е/ug, "$1ЙӨ")
		.replace(/(\p{Lu})(\p{Lu}) Е/ug, "$1$2 ЙӨ")
		.replace(/Е (\p{Lu})(\p{Lu})/ug, "ЙӨ $1$2")
		.replace(/Е(\p{Lu})/ug, "ЙӨ$1")
		.replace(/Е/ug, "Йө")
		.replace(/е/ug, "йө")

		.replace(/(\p{Lu})Ё/ug, "$1ЙО")
		.replace(/(\p{Lu})(\p{Lu}) Ё/ug, "$1$2 ЙО")
		.replace(/Ё (\p{Lu})(\p{Lu})/ug, "ЙО $1$2")
		.replace(/Ё(\p{Lu})/ug, "ЙО$1")
		.replace(/Ё/ug, "Йо")
		.replace(/ё/ug, "йо")

		.replace(/(\p{Lu})Ю/ug, "$1ЙУ")
		.replace(/(\p{Lu})(\p{Lu}) Ю/ug, "$1$2 ЙУ")
		.replace(/Ю (\p{Lu})(\p{Lu})/ug, "ЙУ $1$2")
		.replace(/Ю(\p{Lu})/ug, "ЙУ$1")
		.replace(/Ю/ug, "Йу")
		.replace(/ю/ug, "йу")

		// --- FINAL Й SIMPLIFICATION (NON-VOWEL CONTEXT) ---
		.replace(/([АИОӨУҮЫЭ])И(?![АИОӨУҮЫЭ])/g, "$1И\u0308")
		.replace(/([АИОӨУҮЫЭаиоөуүыэ])и(?![аиоөуүыэ])/g, "$1и\u0308")
		.replace(/([АИОӨУҮЫЭ])(\u0308)?Й(?![АИОӨУҮЫЭ])/g, "$1$2И")
		.replace(/([АИОӨУҮЫЭаиоөуүыэ])(\u0308)?й(?![аиоөуүыэ])/g, "$1$2и")

		// Handle YYỌ TO YÉ transformation
		.replace(/ьйө/g, "йэ\u0301")
		.replace(/ЬЙӨ/g, "ЙЭ\u0301")

		// Handle soft sign before Й
		.replace(/ьй([аэоуү])/g, "й$1\u0301")
		.replace(/ЬЙ([АЭОУҮ])/g, "Й$1\u0301")
		
		// Handle palatalizing vowels
		.replace(/ь([аэоу])/g, "$1\u0301")
		.replace(/Ь([АЭОУ])/g, "$1\u0301")

		// --- CYRILLIC → LATIN TRANSLITERATION (LOWERCASE) ---
		.replace(/а/g, "a")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/д/g, "d")
		.replace(/е/g, "yọ")
		.replace(/ж/g, "j")
		.replace(/з/g, "z")
		.replace(/и/g, "i")
		.replace(/й/g, "y")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/о/g, "o")
		.replace(/ө/g, "ọ")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ү/g, "ụ")
		.replace(/ф/g, "f")
		.replace(/х/g, "h")
		.replace(/ц/g, "c")
		.replace(/ч/g, "č")
		.replace(/ш/g, "š")
		.replace(/щ/g, "ś")
		.replace(/ы/g, "ị")
		.replace(/ь/g, "y")
		.replace(/ъ/g, "")
		.replace(/э/g, "e")
		.replace(/ю/g, "yu")
		.replace(/ё/g, "yo")
		.replace(/я/g, "ya")

		// --- CYRILLIC → LATIN TRANSLITERATION (UPPERCASE) ---
		.replace(/А/g, "A")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Д/g, "D")
		.replace(/Е/g, "Yọ")
		.replace(/Ж/g, "J")
		.replace(/З/g, "Z")
		.replace(/И/g, "I")
		.replace(/Й/g, "Y")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/О/g, "O")
		.replace(/Ө/g, "Ọ")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ү/g, "Ụ")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "H")
		.replace(/Ц/g, "C")
		.replace(/Ч/g, "Č")
		.replace(/Ш/g, "Š")
		.replace(/Щ/g, "Ś")
		.replace(/Ы/g, "Ị")
		.replace(/Ь/g, "Y")
		.replace(/Ъ/g, "")
		.replace(/Э/g, "E")
		.replace(/Ю/g, "Yu")
		.replace(/Ё/g, "Yo")
		.replace(/Я/g, "Ya")

		// --- TYPOGRAPHIC QUOTES ---
		.replace(/«/g, "\u201e") // low double quote
		.replace(/»/g, "\u201c") // high double quote

		.normalize('NFC'); // Final normalization

	topleft();
}

function topleft() {
	// --- INPUT NORMALIZATION & MIXED SCRIPT FIXES ---
	document.transcription.text1.value = document.transcription.text1.value
		// Normalize archaic / variant Cyrillic letters to standard ones
		.replace(/(є|ѳ)/g, "ө")
		.replace(/(Є|Ѳ)/g, "Ө")

		// Convert homoglyphic Latin letters to Cyrillic when adjacent to Cyrillic (right side)
		.replace(/(\p{Script=Cyrl})A/ug, "$1А")
		.replace(/(\p{Script=Cyrl})C/ug, "$1С")
		.replace(/(\p{Script=Cyrl})E/ug, "$1Е")
		.replace(/(\p{Script=Cyrl})Ë/ug, "$1Ё")
		.replace(/(\p{Script=Cyrl})Ї/ug, "$1Ү")
		.replace(/(\p{Script=Cyrl})O/ug, "$1О")
		.replace(/(\p{Script=Cyrl})P/ug, "$1Р")
		.replace(/(\p{Script=Cyrl})X/ug, "$1Х")

		// Same as above for lowercase
		.replace(/(\p{Script=Cyrl})a/ug, "$1а")
		.replace(/(\p{Script=Cyrl})c/ug, "$1с")
		.replace(/(\p{Script=Cyrl})e/ug, "$1е")
		.replace(/(\p{Script=Cyrl})ë/ug, "$1ё")
		.replace(/(\p{Script=Cyrl})ї/ug, "$1ү")
		.replace(/(\p{Script=Cyrl})o/ug, "$1о")
		.replace(/(\p{Script=Cyrl})p/ug, "$1р")
		.replace(/(\p{Script=Cyrl})x/ug, "$1х")

		// Convert homoglyphic Latin letters to Cyrillic when adjacent to Cyrillic (left side)
		.replace(/A(\p{Script=Cyrl})/ug, "А$1")
		.replace(/C(\p{Script=Cyrl})/ug, "С$1")
		.replace(/E(\p{Script=Cyrl})/ug, "Е$1")
		.replace(/Ë(\p{Script=Cyrl})/ug, "Ё$1")
		.replace(/Ї(\p{Script=Cyrl})/ug, "Ү$1")
		.replace(/O(\p{Script=Cyrl})/ug, "О$1")
		.replace(/P(\p{Script=Cyrl})/ug, "Р$1")
		.replace(/X(\p{Script=Cyrl})/ug, "Х$1")

		// Same as above for lowercase
		.replace(/a(\p{Script=Cyrl})/ug, "а$1")
		.replace(/c(\p{Script=Cyrl})/ug, "с$1")
		.replace(/e(\p{Script=Cyrl})/ug, "е$1")
		.replace(/ë(\p{Script=Cyrl})/ug, "ё$1")
		.replace(/ї(\p{Script=Cyrl})/ug, "ү$1")
		.replace(/o(\p{Script=Cyrl})/ug, "о$1")
		.replace(/p(\p{Script=Cyrl})/ug, "р$1")
		.replace(/x(\p{Script=Cyrl})/ug, "х$1");

	// --- MAIN TRANSFORMATION PIPELINE ---
	document.transcription.text2.value = document.transcription.text1.value
		.replace(/(\p{Lu})(\p{Lu}) Я/ug, "$1$2 YA")
		.replace(/(\p{Lu})Я/ug, "$1YA")
		.replace(/Я (\p{Lu})(\p{Lu})/ug, "YA $1$2")
		.replace(/Я(\p{Lu})/ug, "YA$1")
		.replace(/Я/g, "Ya")
		.replace(/я/g, "ya")
		.replace(/(\p{Lu})(\p{Lu}) Е/ug, "$1$2 YE")
		.replace(/(\p{Lu})Е/ug, "$1YE")
		.replace(/Е (\p{Lu})(\p{Lu})/ug, "YE $1$2")
		.replace(/Е(\p{Lu})/ug, "YE$1")
		.replace(/Е/g, "Ye")
		.replace(/е/g, "ye")
		.replace(/(\p{Lu})(\p{Lu}) Ё/ug, "$1$2 YO")
		.replace(/(\p{Lu})Ё/ug, "$1YO")
		.replace(/Ё (\p{Lu})(\p{Lu})/ug, "YO $1$2")
		.replace(/Ё(\p{Lu})/ug, "YO$1")
		.replace(/Ё/g, "Yo")
		.replace(/ё/g, "yo")
		.replace(/(\p{Lu})(\p{Lu}) Ю/ug, "$1$2 YU")
		.replace(/(\p{Lu})Ю/ug, "$1YU")
		.replace(/Ю (\p{Lu})(\p{Lu})/ug, "YU $1$2")
		.replace(/Ю(\p{Lu})/ug, "YU$1")
		.replace(/Ю/g, "Yu")
		.replace(/ю/g, "yu")
		.replace(/(\p{Lu})(\p{Lu}) Х/ug, "$1$2 KH")
		.replace(/(\p{Lu})Х/ug, "$1KH")
		.replace(/Х (\p{Lu})(\p{Lu})/ug, "KH $1$2")
		.replace(/Х(\p{Lu})/ug, "KH$1")
		.replace(/Х/g, "Kh")
		.replace(/х/g, "kh")
		.replace(/(\p{Lu})(\p{Lu}) Ц/ug, "$1$2 TS")
		.replace(/(\p{Lu})Ц/ug, "$1TS")
		.replace(/Ц (\p{Lu})(\p{Lu})/ug, "TS $1$2")
		.replace(/Ц(\p{Lu})/ug, "TS$1")
		.replace(/Ц/g, "Ts")
		.replace(/ц/g, "ts")
		.replace(/(\p{Lu})(\p{Lu}) Ч/ug, "$1$2 CH")
		.replace(/(\p{Lu})Ч/ug, "$1CH")
		.replace(/Ч (\p{Lu})(\p{Lu})/ug, "CH $1$2")
		.replace(/Ч(\p{Lu})/ug, "CH$1")
		.replace(/Ч/g, "Ch")
		.replace(/ч/g, "ch")
		.replace(/(\p{Lu})(\p{Lu}) [ШЩ]/ug, "$1$2 SH")
		.replace(/(\p{Lu})[ШЩ]/ug, "$1SH")
		.replace(/[ШЩ] (\p{Lu})(\p{Lu})/ug, "SH $1$2")
		.replace(/[ШЩ](\p{Lu})/ug, "SH$1")
		.replace(/[ШЩ]/g, "Sh")
		.replace(/[шщ]/g, "sh")

		.replace(/а/g, "a")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/д/g, "d")
		.replace(/е/g, "ye")
		.replace(/ж/g, "j")
		.replace(/з/g, "z")
		.replace(/и/g, "i")
		.replace(/й/g, "i")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/о/g, "o")
		.replace(/ө/g, "ö")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ү/g, "ü")
		.replace(/ф/g, "f")
		.replace(/х/g, "kh")
		.replace(/ц/g, "ts")
		.replace(/ч/g, "ch")
		.replace(/ш/g, "sh")
		.replace(/щ/g, "sh")
		.replace(/ъ/g, "i")
		.replace(/ы/g, "y")
		.replace(/ь/g, "i")
		.replace(/э/g, "e")
		.replace(/ю/g, "yu")
		.replace(/я/g, "ya")

		.replace(/А/g, "A")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Д/g, "D")
		.replace(/Е/g, "Ye")
		.replace(/Ж/g, "J")
		.replace(/З/g, "Z")
		.replace(/И/g, "I")
		.replace(/Й/g, "I")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/О/g, "O")
		.replace(/Ө/g, "Ö")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ү/g, "Ü")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "Kh")
		.replace(/Ц/g, "Ts")
		.replace(/Ч/g, "Ch")
		.replace(/Ш/g, "Sh")
		.replace(/Щ/g, "Sh")
		.replace(/Ъ/g, "I")
		.replace(/Ы/g, "Y")
		.replace(/Ь/g, "I")
		.replace(/Э/g, "E")
		.replace(/Ю/g, "Yu")
		.replace(/Я/g, "Ya");
}

function righttop() {
	document.transcription.text3.value = document.transcription.text3.value
		.normalize('NFD')
		.replace(/([CcSs])\u0327/g, "$1\u030c")
		.replace(/([IiOoUu])\u0300/g, "$1\u0323")
		.normalize('NFC');
		
	document.transcription.text1.value = document.transcription.text3.value
		.normalize('NFD')
		.replace(/([aeou])\u0301/g, "ь$1")
		.replace(/([AEOU])\u0301/g, "Ь$1")
		.normalize('NFC')

		.replace(/([BCČDFGHJKLMNPRSŠŚTVYZbcčdfghjklmnprsšśtvyz])y([aeoọuụ])/g, "$1ъy$2")
		.replace(/([BCČDFGHJKLMNPRSŠŚTVYZ])Y([AEOỌUỤ])/g, "$1ЪY$2")

		.replace(/a/g, "а")
		.replace(/b/g, "б")
		.replace(/c/g, "ц")
		.replace(/č/g, "ч")
		.replace(/d/g, "д")
		.replace(/e/g, "э")
		.replace(/f/g, "ф")
		.replace(/g/g, "г")
		.replace(/h/g, "х")
		.replace(/i/g, "и")
		.replace(/ị/g, "ы")
		.replace(/j/g, "ж")
		.replace(/k/g, "к")
		.replace(/l/g, "л")
		.replace(/m/g, "м")
		.replace(/n/g, "н")
		.replace(/o/g, "о")
		.replace(/ọ/g, "ө")
		.replace(/p/g, "п")
		.replace(/r/g, "р")
		.replace(/s/g, "с")
		.replace(/š/g, "ш")
		.replace(/ś/g, "щ")
		.replace(/t/g, "т")
		.replace(/u/g, "у")
		.replace(/ụ/g, "ү")
		.replace(/v/g, "в")
		.replace(/y/g, "ь")
		.replace(/z/g, "з")
		.replace(/A/g, "А")
		.replace(/B/g, "Б")
		.replace(/C/g, "Ц")
		.replace(/Č/g, "Ч")
		.replace(/D/g, "Д")
		.replace(/E/g, "Э")
		.replace(/F/g, "Ф")
		.replace(/G/g, "Г")
		.replace(/H/g, "Х")
		.replace(/I/g, "И")
		.replace(/Ị/g, "Ы")
		.replace(/J/g, "Ж")
		.replace(/K/g, "К")
		.replace(/L/g, "Л")
		.replace(/M/g, "М")
		.replace(/N/g, "Н")
		.replace(/O/g, "О")
		.replace(/Ọ/g, "Ө")
		.replace(/P/g, "П")
		.replace(/R/g, "Р")
		.replace(/S/g, "С")
		.replace(/Š/g, "Ш")
		.replace(/Ś/g, "Щ")
		.replace(/T/g, "Т")
		.replace(/U/g, "У")
		.replace(/Ụ/g, "Ү")
		.replace(/V/g, "В")
		.replace(/Y/g, "Ь")
		.replace(/Z/g, "З")
		.replace(/(\p{Lu})\u2019/ug, "Ъ")
		.replace(/\u2019/g, "ъ")
		.replace(/ьа/g, "я")
		.replace(/ь[эө]/g, "е")
		.replace(/ьо/g, "ё")
		.replace(/ь[уү]/g, "ю")
		.replace(/[ЬЪ][Аа]/g, "Я")
		.replace(/[ЬЪ][ЭӨэө]/g, "Е")
		.replace(/[ЬЪ][Оо]/g, "Ё")
		.replace(/[ЬЪ][УҮуү]/g, "Ю")

		.replace(/ь([äëïöü])/g, "й$1")
		.replace(/Ь([ÄËÏÖÜäëïöü])/g, "Й$1")

		.replace(/([ӨөYy])\u0308/g, "$1")
		.replace(/ä/g, "а")
		.replace(/ë/g, "э")
		.replace(/ö/g, "о")
		.replace(/ü/g, "у")
		.replace(/Ä/g, "А")
		.replace(/Ë/g, "Э")
		.replace(/Ö/g, "О")
		.replace(/Ü/g, "У")

		.replace(/([АЕЁИЙОӨУҮЫЭЮЯЪЬаеёийоөуүыэюяъь])[иь]/g, "$1й")
		.replace(/([АЕЁИЙОӨУҮЫЭЮЯЪЬ])[ИЬ]/g, "$1Й")
		.replace(/ï[иь]/g, "ий")
		.replace(/Ï[ИЬ]/g, "ИЙ")
		.replace(/ï/g, "и")
		.replace(/Ï/g, "И")

		.replace(/ьъ/g, "ь")
		.replace(/ЬЪ/g, "Ь")

		.replace(/\u201e/g, "«") // low double quote
		.replace(/\u201c/g, "»") // high double quote

		.normalize('NFC'); // Final normalization

	topleft();
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}

function copy3() {
	navigator.clipboard.writeText(document.transcription.text3.value);
}