function cyrlat() {
	document.transcription.text1.value = document.transcription.text1.value
		.replace(/(є|ѳ)/g, "ө")
		.replace(/(Є|Ѳ)/g, "Ө")
		.replace(/(\p{Script=Cyrl})A/ug, "$1А")
		.replace(/(\p{Script=Cyrl})C/ug, "$1С")
		.replace(/(\p{Script=Cyrl})E/ug, "$1Е")
		.replace(/(\p{Script=Cyrl})Ë/ug, "$1Ё")
		.replace(/(\p{Script=Cyrl})Ї/ug, "$1Ү")
		.replace(/(\p{Script=Cyrl})O/ug, "$1О")
		.replace(/(\p{Script=Cyrl})P/ug, "$1Р")
		.replace(/(\p{Script=Cyrl})X/ug, "$1Х")
		.replace(/(\p{Script=Cyrl})a/ug, "$1а")
		.replace(/(\p{Script=Cyrl})c/ug, "$1с")
		.replace(/(\p{Script=Cyrl})e/ug, "$1е")
		.replace(/(\p{Script=Cyrl})ë/ug, "$1ё")
		.replace(/(\p{Script=Cyrl})ї/ug, "$1ү")
		.replace(/(\p{Script=Cyrl})o/ug, "$1о")
		.replace(/(\p{Script=Cyrl})p/ug, "$1р")
		.replace(/(\p{Script=Cyrl})x/ug, "$1х")
		.replace(/A(\p{Script=Cyrl})/ug, "А$1")
		.replace(/C(\p{Script=Cyrl})/ug, "С$1")
		.replace(/E(\p{Script=Cyrl})/ug, "Е$1")
		.replace(/Ë(\p{Script=Cyrl})/ug, "Ё$1")
		.replace(/Ї(\p{Script=Cyrl})/ug, "Ү$1")
		.replace(/O(\p{Script=Cyrl})/ug, "О$1")
		.replace(/P(\p{Script=Cyrl})/ug, "Р$1")
		.replace(/X(\p{Script=Cyrl})/ug, "Х$1")
		.replace(/a(\p{Script=Cyrl})/ug, "а$1")
		.replace(/c(\p{Script=Cyrl})/ug, "с$1")
		.replace(/e(\p{Script=Cyrl})/ug, "е$1")
		.replace(/ë(\p{Script=Cyrl})/ug, "ё$1")
		.replace(/ї(\p{Script=Cyrl})/ug, "ү$1")
		.replace(/o(\p{Script=Cyrl})/ug, "о$1")
		.replace(/p(\p{Script=Cyrl})/ug, "р$1")
		.replace(/x(\p{Script=Cyrl})/ug, "х$1");

	document.transcription.text2.value = document.transcription.text1.value
		.normalize('NFC')

		.replace(/([ЪЬ])([АОУ])/g, "$1\u2019$2")
		.replace(/([ЪЬъь])([аоу])/g, "$1\u2019$2")
		.replace(/ЪЕ/g, "ЙЭ")
		.replace(/([Ъъ])е/g, "йэ")
		.replace(/([ЬЪ])Э/g, "$1\u2019Э")
		.replace(/([ЬЪьъ])э/g, "$1\u2019э")
		
		.replace(/Й([Аа])/g, "Й$1\u0308")
		.replace(/йа/g, "йа\u0308")
		.replace(/Й([Ээ])/g, "Й$1\u0308")
		.replace(/йэ/g, "йэ\u0308")
		.replace(/Й([Уу])/g, "Й$1\u0308")
		.replace(/йу/g, "йу\u0308")
		.replace(/Й([Оо])/g, "Й$1\u0308")
		.replace(/йо/g, "йо\u0308")

		.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩ])Я/g, "$1Á")
		.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩбвгджзклмнпрстфхцчшщ])я/g, "$1á")
		.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩ])Е/g, "$1É")
		.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩбвгджзклмнпрстфхцчшщ])е/g, "$1é")
		.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩ])Ё/g, "$1Ó")
		.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩбвгджзклмнпрстфхцчшщ])ё/g, "$1ó")
		.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩ])Ю/g, "$1Ú")
		.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩбвгджзклмнпрстфхцчшщ])ю/g, "$1ú")
		
		.replace(/ЕЭ/g, "ЙЭЭ")
		.replace(/Еэ/g, "Йээ")
		.replace(/еэ/g, "йээ")
		.replace(/ЭЕ/g, "ЭЙЭ")
		.replace(/([Ээ])е/g, "$1йэ")
		.replace(/ЮҮ/g, "ЙҮҮ")
		.replace(/Юү/g, "Йүү")
		.replace(/юү/g, "йүү")
		.replace(/ҮЮ/g, "ҮЙҮ")
		.replace(/([Үү])ю/g, "$1йү")

		.replace(/(\p{Uppercase})Я/ug, "$1ЙА")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Я/ug, "$1$2 ЙА")
		.replace(/Я (\p{Uppercase})(\p{Uppercase})/ug, "ЙА $1$2")
		.replace(/Я(\p{Uppercase})/ug, "ЙА$1")
		.replace(/Я/g, "Йа")
		.replace(/я/g, "йа")
		.replace(/(\p{Uppercase})Е/ug, "$1ЙӨ")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Е/ug, "$1$2 ЙӨ")
		.replace(/Е (\p{Uppercase})(\p{Uppercase})/ug, "ЙӨ $1$2")
		.replace(/Е(\p{Uppercase})/ug, "ЙӨ$1")
		.replace(/Е/g, "Йө")
		.replace(/е/g, "йө")
		.replace(/(\p{Uppercase})Ё/ug, "$1ЙО")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ё/ug, "$1$2 ЙО")
		.replace(/Ё (\p{Uppercase})(\p{Uppercase})/ug, "ЙО $1$2")
		.replace(/Ё(\p{Uppercase})/ug, "ЙО$1")
		.replace(/Ё/g, "Йо")
		.replace(/ё/g, "йо")
		.replace(/(\p{Uppercase})Ю/ug, "$1ЙУ")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ю/ug, "$1$2 ЙУ")
		.replace(/Ю (\p{Uppercase})(\p{Uppercase})/ug, "ЙУ $1$2")
		.replace(/Ю(\p{Uppercase})/ug, "ЙУ$1")
		.replace(/Ю/g, "Йу")
		.replace(/ю/g, "йу")

		.replace(/([АЕЁИОӨУҮЫЭЮЯ])Й(?![АЕЁИЙОӨУҮЫЭЮЯ])/g, "$1И")
		.replace(/([АЕЁИОӨУҮЫЭЮЯаеёиоөуүыэюя])й(?![аеёийоөуүыэюя])/g, "$1и")
		
		.replace(/ьй/g, "й")
		.replace(/ЬЙ/g, "Й")

		.replace(/а/g, "a")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/д/g, "d")
		.replace(/е/g, "yọ")
		.replace(/ж/g, "j")
		.replace(/з/g, "z")
		.replace(/и/g, "i")
		.replace(/й/g, "y")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/о/g, "o")
		.replace(/ө/g, "ọ")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ү/g, "ụ")
		.replace(/ф/g, "f")
		.replace(/х/g, "h")
		.replace(/ц/g, "c")
		.replace(/ч/g, "č")
		.replace(/ш/g, "š")
		.replace(/щ/g, "ś")
		.replace(/ы/g, "ị")
		.replace(/ь/g, "y")
		.replace(/ъ/g, "")
		.replace(/э/g, "e")
		.replace(/ю/g, "yu")
		.replace(/ё/g, "yo")
		.replace(/я/g, "ya")

		.replace(/А/g, "A")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Д/g, "D")
		.replace(/Е/g, "Yọ")
		.replace(/Ж/g, "J")
		.replace(/З/g, "Z")
		.replace(/И/g, "I")
		.replace(/Й/g, "Y")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/О/g, "O")
		.replace(/Ө/g, "Ọ")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ү/g, "Ụ")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "H")
		.replace(/Ц/g, "C")
		.replace(/Ч/g, "Č")
		.replace(/Ш/g, "Š")
		.replace(/Щ/g, "Ś")
		.replace(/Ы/g, "Ị")
		.replace(/Ь/g, "Y")
		.replace(/Ъ/g, "")
		.replace(/Э/g, "E")
		.replace(/Ю/g, "Yu")
		.replace(/Ё/g, "Yo")
		.replace(/Я/g, "Ya")

		.replace(/«/g, "\u201e")
		.replace(/»/g, "\u201c")
		.normalize('NFC');
}

function latcyr() {
document.transcription.text1.value = document.transcription.text2.value
		.replace(/e/g, "е")
		.replace(/r/g, "р")
		.replace(/t/g, "т")
		.replace(/y/g, "й")
		.replace(/u/g, "у")
		.replace(/ı/g, "ы")
		.replace(/o/g, "о")
		.replace(/p/g, "п")
		.replace(/ü/g, "ү")
		.replace(/a/g, "а")
		.replace(/s/g, "с")
		.replace(/d/g, "д")
		.replace(/f/g, "ф")
		.replace(/g/g, "г")
		.replace(/[hx]/g, "х")
		.replace(/j/g, "ж")
		.replace(/k/g, "к")
		.replace(/l/g, "л")
		.replace(/ş/g, "ш")
		.replace(/i/g, "и")
		.replace(/z/g, "з")
		.replace(/c/g, "ц")
		.replace(/v/g, "в")
		.replace(/b/g, "б")
		.replace(/n/g, "н")
		.replace(/m/g, "м")
		.replace(/ö/g, "ө")
		.replace(/ç/g, "ч")
		.replace(/â/g, "я")
		.replace(/ô/g, "ё")
		.replace(/ë/g, "ё")
		.replace(/û/g, "ю")
		.replace(/ê/g, "э")
		.replace(/E/g, "Е")
		.replace(/R/g, "Р")
		.replace(/T/g, "Т")
		.replace(/Y/g, "Й")
		.replace(/U/g, "У")
		.replace(/I/g, "Ы")
		.replace(/O/g, "О")
		.replace(/P/g, "П")
		.replace(/Ü/g, "Ү")
		.replace(/A/g, "А")
		.replace(/S/g, "С")
		.replace(/D/g, "Д")
		.replace(/F/g, "Ф")
		.replace(/G/g, "Г")
		.replace(/[HX]/g, "Х")
		.replace(/J/g, "Ж")
		.replace(/K/g, "К")
		.replace(/L/g, "Л")
		.replace(/Ş/g, "Ш")
		.replace(/İ/g, "И")
		.replace(/Z/g, "З")
		.replace(/X/g, "Х")
		.replace(/C/g, "Ц")
		.replace(/V/g, "В")
		.replace(/B/g, "Б")
		.replace(/N/g, "Н")
		.replace(/M/g, "М")
		.replace(/Ö/g, "Ө")
		.replace(/Ç/g, "Ч")
		.replace(/Â/g, "Я")
		.replace(/Ô/g, "Ё")
		.replace(/Ë/g, "Ё")
		.replace(/Û/g, "Ю")
		.replace(/Ê/g, "Э")
		.replace(/\u0027/g, "ь")
		.replace(/\u0022/g, "ъ")
		.replace(/<</g, "«")
		.replace(/>>/g, "»")

		.replace(/е(\u002a|\u005c)/g, "э")
		.replace(/Е(\u002a|\u005c)/g, "Э")
		.replace(/э(\u002a|\u005c)/g, "е")
		.replace(/Э(\u002a|\u005c)/g, "Е")
	
		.replace(/ш(\u002a|\u005c)/g, "щ")
		.replace(/Ш(\u002a|\u005c)/g, "Щ")
		.replace(/щ(\u002a|\u005c)/g, "ш")
		.replace(/Щ(\u002a|\u005c)/g, "Ш")

		.replace(/ь(\u002a|\u005c)/g, "Ь")
		.replace(/Ь(\u002a|\u005c)/g, "ь")

		.replace(/ъ(\u002a|\u005c)/g, "Ъ")
		.replace(/Ъ(\u002a|\u005c)/g, "ъ");
	    cyrlat();
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}
