function cyrlat() {
	document.transcription.text2.value = document.transcription.text1.value
		.replace(/ЬЯ/g, "ИА")
		.replace(/Ья/g, "Иa")
		.replace(/ья/g, "иa")
		.replace(/ИЯ/g, "ИА")
		.replace(/(И|и)я/g, "$1a")
		.replace(/(А|Е|Ё|О|У|Ы|Э|Ю|Я)Я/g, "$1ИА")
		.replace(/(А|Е|Ё|О|У|Ы|Э|Ю|Я|а|е|ё|о|у|ы|э|ю|я)я/g, "$1иа")
		.replace(/(\p{Lu})(\p{Lu}) Я/ug, "$1$2 ЕА")
		.replace(/Я (\p{Lu})(\p{Lu})/ug, "ЕА $1$2")
		.replace(/Я(\p{Lu})/ug, "ЕА$1")
		.replace(/Я/g, "Еа")
		.replace(/я/g, "еа")

		.replace(/ЬЁ/g, "ИО")
		.replace(/Ьё/g, "Ио")
		.replace(/ьё/g, "ио")
		.replace(/ИЁ/g, "ИО")
		.replace(/(И|и)ё/g, "$1о")
		.replace(/(\p{Lu})(\p{Lu}) Ё/ug, "$1$2 ИО")
		.replace(/Ё (\p{Lu})(\p{Lu})/ug, "ИО $1$2")
		.replace(/Ё(\p{Lu})/ug, "ИО$1")
		.replace(/Ё/g, "Ио")
		.replace(/ё/g, "ио")

		.replace(/ЬЮ/g, "ИУ")
		.replace(/Ью/g, "Иу")
		.replace(/ью/g, "иу")
		.replace(/ИЮ/g, "ИУ")
		.replace(/(И|и)ю/g, "$1у")
		.replace(/(\p{Lu})(\p{Lu}) Ю/ug, "$1$2 ИУ")
		.replace(/Ю (\p{Lu})(\p{Lu})/ug, "ИУ $1$2")
		.replace(/Ю(\p{Lu})/ug, "ИУ$1")
		.replace(/Ю/g, "Иу")
		.replace(/ю/g, "иу")

		.replace(/(Ь|ь)(А|а|Б|б|В|в|Г|г|Д|д|Е|е|Ё|ё|Ж|ж|Ӂ|ӂ|З|з|И|и|Й|й|К|к|Л|л|М|м|Н|н|О|о|П|п|Р|р|С|с|Т|т|У|у|Ф|ф|Х|х|Ц|ц|Ч|ч|Ш|ш|Щ|щ|Ъ|ъ|Ы|ы|Ь|ь|Э|э|Ю|ю|Я|я)/g, "$2")

		.replace(/Й/g, "И")
		.replace(/й/g, "и")

		.replace(/Г(Е|И)/g, "ГХ$1")
		.replace(/(Г|г)(е|и)/g, "$1х$2")

		.replace(/К(Е|И)/g, "КХ$1")
		.replace(/(К|к)(е|и)/g, "$1х$2")

		.replace(/ӁА/g, "ГЕА")
		.replace(/Ӂа/g, "Геа")
		.replace(/ӂа/g, "геа")
		.replace(/Ӂ(Е|И|е|и)/g, "Г$1")
		.replace(/ӂ(е|и)/g, "г$1")
		.replace(/(\p{Lu})(\p{Lu}) Ӂ/ug, "$1$2 ГИ")
		.replace(/Ӂ (\p{Lu})(\p{Lu})/ug, "ГИ $1$2")
		.replace(/Ӂ(\p{Lu})/ug, "ГИ$1")
		.replace(/Ӂ/g, "Ги")
		.replace(/ӂ/g, "ги")

		.replace(/ЧА/g, "КЕА")
		.replace(/Ча/g, "Кеа")
		.replace(/ча/g, "кеа")
		.replace(/Ч(Е|И|е|и)/g, "К$1")
		.replace(/ч(е|и)/g, "к$1")
		.replace(/(\p{Lu})(\p{Lu}) Ч/ug, "$1$2 КИ")
		.replace(/Ч (\p{Lu})(\p{Lu})/ug, "КИ $1$2")
		.replace(/Ч(\p{Lu})/ug, "КИ$1")
		.replace(/Ч/g, "Ки")
		.replace(/ч/g, "ки")

		.replace(/(И|и)(Ь|ь)/g, "$1")

		.replace(/Ь/g, "И")
		.replace(/ь/g, "и")

		.replace(/А/g, "A")
		.replace(/а/g, "a")
		.replace(/Б/g, "B")
		.replace(/б/g, "b")
		.replace(/В/g, "V")
		.replace(/в/g, "v")
		.replace(/Г/g, "G")
		.replace(/г/g, "g")
		.replace(/Д/g, "D")
		.replace(/д/g, "d")
		.replace(/Е/g, "E")
		.replace(/е/g, "e")
		.replace(/Ж/g, "J")
		.replace(/ж/g, "j")
		.replace(/З/g, "Z")
		.replace(/з/g, "z")
		.replace(/И/g, "I")
		.replace(/и/g, "i")
		.replace(/К/g, "C")
		.replace(/к/g, "c")
		.replace(/Л/g, "L")
		.replace(/л/g, "l")
		.replace(/М/g, "M")
		.replace(/м/g, "m")
		.replace(/Н/g, "N")
		.replace(/н/g, "n")
		.replace(/О/g, "O")
		.replace(/о/g, "o")
		.replace(/П/g, "P")
		.replace(/п/g, "p")
		.replace(/Р/g, "R")
		.replace(/р/g, "r")
		.replace(/С/g, "S")
		.replace(/с/g, "s")
		.replace(/Т/g, "T")
		.replace(/т/g, "t")
		.replace(/У/g, "U")
		.replace(/у/g, "u")
		.replace(/Ф/g, "F")
		.replace(/ф/g, "f")
		.replace(/Х/g, "H")
		.replace(/х/g, "h")
		.replace(/Ц/g, "Ț")
		.replace(/ц/g, "ț")
		.replace(/Ш/g, "Ș")
		.replace(/ш/g, "ș")
		.replace(/Щ/g, "Ș")
		.replace(/щ/g, "ș")
		.replace(/Ъ/g, "")
		.replace(/ъ/g, "")
		.replace(/Ы/g, "Î")
		.replace(/ы/g, "î")
		.replace(/Э/g, "Ă")
		.replace(/э/g, "ă")

		.replace(/(A|Â|Ă|B|C|D|E|F|G|H|I|Î|J|K|L|M|N|O|P|R|S|Ș|T|Ț|U|V|X|Z)Î(A|Â|Ă|B|C|D|E|F|G|H|I|Î|J|K|L|M|N|O|P|R|S|Ș|T|Ț|U|V|X|Z)/g, "$1Â$2")
		.replace(/(A|Â|Ă|B|C|D|E|F|G|H|I|Î|J|K|L|M|N|O|P|R|S|Ș|T|Ț|U|V|X|Z|a|â|ă|b|c|d|e|f|g|h|i|î|j|k|l|m|n|o|p|r|s|ș|t|ț|u|v|x|z)î(a|â|ă|b|c|d|e|f|g|h|i|î|j|k|l|m|n|o|p|r|s|ș|t|ț|u|v|x|z)/g, "$1â$2");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}