function cyrlat() {
	document.transcription.text2.value = document.transcription.text1.value
		.replace(/\u0301/g, "")
		.replace(/Ь/g, "ь")

		.replace(/(Б|В|Г|Ґ|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|ґ|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)Я/g, "$1ьA")
		.replace(/(Б|В|Г|Ґ|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|ґ|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)я/g, "$1ьa")
		.replace(/(Б|В|Г|Ґ|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|ґ|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)Є/g, "$1ьE")
		.replace(/(Б|В|Г|Ґ|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|ґ|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)є/g, "$1ьe")
		.replace(/(Б|В|Г|Ґ|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|ґ|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)Ї/g, "$1ьİ")
		.replace(/(Б|В|Г|Ґ|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|ґ|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)ї/g, "$1ьi")
		.replace(/(Б|В|Г|Ґ|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|ґ|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)Ю/g, "$1ьU")
		.replace(/(Б|В|Г|Ґ|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|ґ|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)ю/g, "$1ьu")

		.replace(/ьa/g, "à")
		.replace(/ьA/g, "À")
		.replace(/ьu/g, "ù")
		.replace(/ьU/g, "Ù")

		.replace(/Д(Ж|ж)/g, "C")
		.replace(/дж/g, "c")

		.replace(/ʼ/g, "ъ")
		.replace(/’/g, "ъ")
		.replace(/'/g, "ъ")
		.replace(/а/g, "a")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "h")
		.replace(/ґ/g, "g")
		.replace(/д/g, "d")
		.replace(/є/g, "ye")
		.replace(/е/g, "e")
		.replace(/ж/g, "j")
		.replace(/з/g, "z")
		.replace(/и/g, "ı")
		.replace(/і/g, "i")
		.replace(/ї/g, "yi")
		.replace(/й/g, "y")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/о/g, "o")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ф/g, "f")
		.replace(/х/g, "h")
		.replace(/ч/g, "ç")
		.replace(/ш/g, "ş")
		.replace(/щ/g, "şç")
		.replace(/ь/g, "")
		.replace(/ю/g, "yu")
		.replace(/я/g, "ya")

		.replace(/А/g, "A")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "H")
		.replace(/Ґ/g, "G")
		.replace(/Д/g, "D")
		.replace(/Е/g, "E")
		.replace(/Є/g, "Ye")
		.replace(/Ж/g, "J")
		.replace(/З/g, "Z")
		.replace(/И/g, "I")
		.replace(/І/g, "İ")
		.replace(/Ї/g, "Yi")
		.replace(/Й/g, "Y")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/О/g, "O")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "H")
		.replace(/Ч/g, "Ç")
		.replace(/Ш/g, "Ş")
		.replace(/Щ/g, "Şç")
		.replace(/Ь/g, "")
		.replace(/Ю/g, "Yu")
		.replace(/Я/g, "Ya")

		.replace(/(A|E|I|İ|O|U|a|e|ı|i|o|u)ц/g, "$1ts")
		.replace(/(A|E|I|İ|O|U)Ц/g, "$1TS")
		.replace(/ц/g, "s")
		.replace(/Ц/g, "S")

		.replace(/(G|g|K|k|L|l)à/g, "$1â")
		.replace(/(G|g|K|k|L|l)À/g, "$1Â")
		.replace(/(G|g|K|k|L|l)ù/g, "$1û")
		.replace(/(G|g|K|k|L|l)ù/g, "$1Û")
		.replace(/à/g, "a")
		.replace(/À/g, "A")
		.replace(/ù/g, "u")
		.replace(/Ù/g, "U")

		.replace(/«/g, "\u201e")
		.replace(/»/g, "\u201c");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}