//  zaciatocne e musi byt ye
var translit;

function cyrlat () {
translit = document.transcription.text1.value;

translit = translit.replace(/бе/g, "be");
translit = translit.replace(/ве/g, "ve");
translit = translit.replace(/ге/g, "ge");
translit = translit.replace(/же/g, "zhe");
translit = translit.replace(/ӝе/g, "dzhe");
translit = translit.replace(/ӟе/g, "je");
translit = translit.replace(/ке/g, "ke");
translit = translit.replace(/ме/g, "me");
translit = translit.replace(/пе/g, "pe");
translit = translit.replace(/ре/g, "re");
translit = translit.replace(/фе/g, "fe");
translit = translit.replace(/хе/g, "khe");
translit = translit.replace(/це/g, "tse");
translit = translit.replace(/че/g, "che");
translit = translit.replace(/ӵе/g, "tshe");
translit = translit.replace(/ше/g, "she");
translit = translit.replace(/ще/g, "shche");

translit = translit.replace(/Бе/g, "Be");
translit = translit.replace(/Ве/g, "Ve");
translit = translit.replace(/Ге/g, "Ge");
translit = translit.replace(/Же/g, "Zhe");
translit = translit.replace(/Ӝе/g, "Dzhe");
translit = translit.replace(/Ӟе/g, "Je");
translit = translit.replace(/Ке/g, "Ke");
translit = translit.replace(/Ме/g, "Me");
translit = translit.replace(/Пе/g, "Pe");
translit = translit.replace(/Ре/g, "Re");
translit = translit.replace(/Фе/g, "Fe");
translit = translit.replace(/Хе/g, "Khe");
translit = translit.replace(/Це/g, "Tse");
translit = translit.replace(/Че/g, "Che");
translit = translit.replace(/Ӵе/g, "Tshe");
translit = translit.replace(/Ше/g, "She");
translit = translit.replace(/Ще/g, "Shche");

translit = translit.replace(/БЕ/g, "BE");
translit = translit.replace(/ВЕ/g, "VE");
translit = translit.replace(/ГЕ/g, "GE");
translit = translit.replace(/ЖЕ/g, "ZHE");
translit = translit.replace(/ӜЕ/g, "DZHE");
translit = translit.replace(/ӞЕ/g, "JE");
translit = translit.replace(/КЕ/g, "KE");
translit = translit.replace(/МЕ/g, "ME");
translit = translit.replace(/ПЕ/g, "PE");
translit = translit.replace(/РЕ/g, "RE");
translit = translit.replace(/ФЕ/g, "FE");
translit = translit.replace(/ХЕ/g, "KHE");
translit = translit.replace(/ЦЕ/g, "TSE");
translit = translit.replace(/ЧЕ/g, "CHE");
translit = translit.replace(/ӴЕ/g, "TSHE");
translit = translit.replace(/ШЕ/g, "SHE");
translit = translit.replace(/ЩЕ/g, "SHCHE");

translit = translit.replace(/бйе/g, "bye");
translit = translit.replace(/вйе/g, "vye");
translit = translit.replace(/гйе/g, "gye");
translit = translit.replace(/жйе/g, "zhye");
translit = translit.replace(/ӝйе/g, "dzhye");
translit = translit.replace(/ӟйе/g, "jye");
translit = translit.replace(/кйе/g, "kye");
translit = translit.replace(/мйе/g, "mye");
translit = translit.replace(/пйе/g, "pye");
translit = translit.replace(/рйе/g, "rye");
translit = translit.replace(/фйе/g, "fye");
translit = translit.replace(/хйе/g, "khye");
translit = translit.replace(/цйе/g, "tsye");
translit = translit.replace(/чйе/g, "chye");
translit = translit.replace(/ӵйе/g, "tshye");
translit = translit.replace(/шйе/g, "shye");
translit = translit.replace(/щйе/g, "shchye");

translit = translit.replace(/Бйе/g, "Bye");
translit = translit.replace(/Вйе/g, "Vye");
translit = translit.replace(/Гйе/g, "Gye");
translit = translit.replace(/Жйе/g, "Zhye");
translit = translit.replace(/Ӝйе/g, "Dzhye");
translit = translit.replace(/Ӟйе/g, "Jye");
translit = translit.replace(/Кйе/g, "Kye");
translit = translit.replace(/Мйе/g, "Mye");
translit = translit.replace(/Пйе/g, "Pye");
translit = translit.replace(/Рйе/g, "Rye");
translit = translit.replace(/Фйе/g, "Fye");
translit = translit.replace(/Хйе/g, "Khye");
translit = translit.replace(/Цйе/g, "Tsye");
translit = translit.replace(/Чйе/g, "Chye");
translit = translit.replace(/Ӵйе/g, "Tshye");
translit = translit.replace(/Шйе/g, "Shye");
translit = translit.replace(/Щйе/g, "Shchye");

translit = translit.replace(/БЙЕ/g, "BYE");
translit = translit.replace(/ВЙЕ/g, "VYE");
translit = translit.replace(/ГЙЕ/g, "GYE");
translit = translit.replace(/ЖЙЕ/g, "ZHYE");
translit = translit.replace(/ӜЙЕ/g, "DZHYE");
translit = translit.replace(/ӞЙЕ/g, "JYE");
translit = translit.replace(/КЙЕ/g, "KYE");
translit = translit.replace(/МЙЕ/g, "MYE");
translit = translit.replace(/ПЙЕ/g, "PYE");
translit = translit.replace(/РЙЕ/g, "RYE");
translit = translit.replace(/ФЙЕ/g, "FYE");
translit = translit.replace(/ХЙЕ/g, "KHYE");
translit = translit.replace(/ЦЙЕ/g, "TSYE");
translit = translit.replace(/ЧЙЕ/g, "CHYE");
translit = translit.replace(/ӴЙЕ/g, "TSHYE");
translit = translit.replace(/ШЙЕ/g, "SHYE");
translit = translit.replace(/ЩЙЕ/g, "SHCHYE");

translit = translit.replace(/ый/g, "ыý");
translit = translit.replace(/йы/g, "ýы");
translit = translit.replace(/Ый/g, "Ыý");
translit = translit.replace(/Йы/g, "Ýы");
translit = translit.replace(/ЫЙ/g, "ЫÝ");
translit = translit.replace(/ЙЫ/g, "ÝЫ");
translit = translit.replace(/ыё/g, "ыýо");
translit = translit.replace(/Ыё/g, "Ыýо");
translit = translit.replace(/ЫЁ/g, "ЫÝО");
translit = translit.replace(/ыя/g, "ыýа");
translit = translit.replace(/Ыя/g, "Ыýа");
translit = translit.replace(/ЫЯ/g, "ЫÝА");
translit = translit.replace(/ыю/g, "ыýу");
translit = translit.replace(/Ыю/g, "Ыýу");
translit = translit.replace(/ЫЮ/g, "ЫÝУ");
translit = translit.replace(/ые/g, "ыýэ");
translit = translit.replace(/Ые/g, "Ыýэ");
translit = translit.replace(/ЫЕ/g, "ЫÝЭ");

translit = translit.replace(/а/g, "a");
translit = translit.replace(/б/g, "b");
translit = translit.replace(/в/g, "v");
translit = translit.replace(/г/g, "g");
translit = translit.replace(/д/g, "d");
translit = translit.replace(/е/g, "ye");
translit = translit.replace(/ё/g, "yo");
translit = translit.replace(/ж/g, "zh");
translit = translit.replace(/ӝ/g, "dzh");
translit = translit.replace(/з/g, "z");
translit = translit.replace(/ӟ/g, "j");
translit = translit.replace(/и/g, "i");
translit = translit.replace(/ӥ/g, "ï");
translit = translit.replace(/й/g, "y");
translit = translit.replace(/к/g, "k");
translit = translit.replace(/л/g, "l");
translit = translit.replace(/м/g, "m");
translit = translit.replace(/н/g, "n");
translit = translit.replace(/о/g, "o");
translit = translit.replace(/ӧ/g, "ö");
translit = translit.replace(/п/g, "p");
translit = translit.replace(/р/g, "r");
translit = translit.replace(/с/g, "s");
translit = translit.replace(/т/g, "t");
translit = translit.replace(/у/g, "u");
translit = translit.replace(/ф/g, "f");
translit = translit.replace(/х/g, "kh");
translit = translit.replace(/ц/g, "ts");
translit = translit.replace(/ч/g, "ch");
translit = translit.replace(/ӵ/g, "tsh");
translit = translit.replace(/ш/g, "sh");
translit = translit.replace(/щ/g, "shch");
translit = translit.replace(/ъ/g, "ʺ");
translit = translit.replace(/ы/g, "y");
translit = translit.replace(/ь/g, "ʹ");
translit = translit.replace(/э/g, "e");
translit = translit.replace(/ю/g, "yu");
translit = translit.replace(/я/g, "ya");

translit = translit.replace(/А/g, "A");
translit = translit.replace(/Б/g, "B");
translit = translit.replace(/В/g, "V");
translit = translit.replace(/Г/g, "G");
translit = translit.replace(/Д/g, "D");
translit = translit.replace(/Е/g, "E");
translit = translit.replace(/Ё/g, "Yo");
translit = translit.replace(/Ж/g, "Zh");
translit = translit.replace(/Ӝ/g, "Dzh");
translit = translit.replace(/З/g, "Z");
translit = translit.replace(/Ӟ/g, "J");
translit = translit.replace(/И/g, "I");
translit = translit.replace(/Ӥ/g, "Ï");
translit = translit.replace(/Й/g, "Y");
translit = translit.replace(/К/g, "K");
translit = translit.replace(/Л/g, "L");
translit = translit.replace(/М/g, "M");
translit = translit.replace(/Н/g, "N");
translit = translit.replace(/О/g, "O");
translit = translit.replace(/Ӧ/g, "Ö");
translit = translit.replace(/П/g, "P");
translit = translit.replace(/Р/g, "R");
translit = translit.replace(/С/g, "S");
translit = translit.replace(/Т/g, "T");
translit = translit.replace(/У/g, "U");
translit = translit.replace(/Ф/g, "F");
translit = translit.replace(/Х/g, "Kh");
translit = translit.replace(/Ц/g, "Ts");
translit = translit.replace(/Ч/g, "Ch");
translit = translit.replace(/Ӵ/g, "Tsh");
translit = translit.replace(/Ш/g, "Sh");
translit = translit.replace(/Щ/g, "Shch");
translit = translit.replace(/Ъ/g, "ʺ");
translit = translit.replace(/Ы/g, "Y");
translit = translit.replace(/Ь/g, "ʹ");
translit = translit.replace(/Э/g, "E");
translit = translit.replace(/Ю/g, "Yu");
translit = translit.replace(/Я/g, "Ya");
translit = translit.replace(/«/g, "\u201c");
translit = translit.replace(/»/g, "\u201d");


document.transcription.text2.value = translit;
}

function copy1()
{ textRange=document.transcription.text1.createTextRange();
textRange.execCommand("Copy");
textRange="";
}
function copy2()
{ textRange=document.transcription.text2.createTextRange();
textRange.execCommand("Copy");
textRange="";
}
