function cyrlat() {
	document.transcription.text2.value = document.transcription.text1.value
		.replace(/(А|Е|Ё|И|О|Ө|У|Ү|Ы|Ю|Я)Ц/g, "$1ТС")
		.replace(/(а|е|ё|и|о|ө|у|ү|ы|ю|я)Ц/g, "$1Тс")
		.replace(/(а|е|ё|и|о|ө|у|ү|ы|ю|я)ц/g, "$1тс")
		.replace(/Ц/g, "С")
		.replace(/ц/g, "с")

		.replace(/(А|Е|Ё|И|О|Ө|У|Ү|Ы|Ю|Я)Щ(А|Е|Ё|И|О|Ө|У|Ү|Ы|Ю|Я)/g, "$1ШШ$2")
		.replace(/(А|Е|Ё|И|О|Ө|У|Ү|Ы|Ю|Я)щ(а|е|ё|и|о|ө|у|ү|ы|ю|я)/g, "$1Шш$2")
		.replace(/(а|е|ё|и|о|ө|у|ү|ы|ю|я)щ(а|е|ё|и|о|ө|у|ү|ы|ю|я)/g, "$1шш$2")
		.replace(/щ/g, "ш")
		.replace(/Щ/g, "Ш")

		.replace(/(Б|В|Г|Ҕ|Д|Ж|З|К|Л|М|Н|Ҥ|П|Р|С|Һ|Т|Ф|Х|Ч|Ш)Я/g, "$1ЬА")
		.replace(/(б|в|г|ҕ|д|ж|з|к|л|м|н|ҥ|п|р|с|һ|т|ф|х|ч|ш)Я/g, "$1ьА")
		.replace(/(Б|В|Г|Ҕ|Д|Ж|З|К|Л|М|Н|Ҥ|П|Р|С|Һ|Т|Ф|Х|Ч|Ш|б|в|г|ҕ|д|ж|з|к|л|м|н|ҥ|п|р|с|һ|т|ф|х|ч|ш)я/g, "$1ьа")
		.replace(/(Б|В|Г|Ҕ|Д|Ж|З|К|Л|М|Н|Ҥ|П|Р|С|Һ|Т|Ф|Х|Ч|Ш)Ю/g, "$1ЬҮ")
		.replace(/(б|в|г|ҕ|д|ж|з|к|л|м|н|ҥ|п|р|с|һ|т|ф|х|ч|ш)Ю/g, "$1ьҮ")
		.replace(/(Б|В|Г|Ҕ|Д|Ж|З|К|Л|М|Н|Ҥ|П|Р|С|Һ|Т|Ф|Х|Ч|Ш|б|в|г|ҕ|д|ж|з|к|л|м|н|ҥ|п|р|с|һ|т|ф|х|ч|ш)ю/g, "$1ьү")
		.replace(/(Б|В|Г|Ҕ|Д|Ж|З|К|Л|М|Н|Ҥ|П|Р|С|Һ|Т|Ф|Х|Ч|Ш)Е/g, "$1ЬЄ")
		.replace(/(б|в|г|ҕ|д|ж|з|к|л|м|н|ҥ|п|р|с|һ|т|ф|х|ч|ш)Е/g, "$1ьЄ")
		.replace(/(Б|В|Г|Ҕ|Д|Ж|З|К|Л|М|Н|Ҥ|П|Р|С|Һ|Т|Ф|Х|Ч|Ш|б|в|г|ҕ|д|ж|з|к|л|м|н|ҥ|п|р|с|һ|т|ф|х|ч|ш)е/g, "$1ьє")
		.replace(/(Б|В|Г|Ҕ|Д|Ж|З|К|Л|М|Н|Ҥ|П|Р|С|Һ|Т|Ф|Х|Ч|Ш)Ё/g, "$1ЬӨ")
		.replace(/(б|в|г|ҕ|д|ж|з|к|л|м|н|ҥ|п|р|с|һ|т|ф|х|ч|ш)Ё/g, "$1ьӨ")
		.replace(/(Б|В|Г|Ҕ|Д|Ж|З|К|Л|М|Н|Ҥ|П|Р|С|Һ|Т|Ф|Х|Ч|Ш|б|в|г|ҕ|д|ж|з|к|л|м|н|ҥ|п|р|с|һ|т|ф|х|ч|ш)ё/g, "$1ьө")


		.replace(/Д(Ь|ь)/g, "Ђ")
		.replace(/дь/g, "ђ")
		.replace(/НЬ/g, "$1Й")
		.replace(/(Н|н)ь/g, "$1й")
		.replace(/Ь(И|и)/g, "Й$1")
		.replace(/ьи/g, "йи")

		.replace(/(\p{Uppercase})(\p{Uppercase}) Я/ug, "$1$2 ЙА")
		.replace(/(\p{Uppercase})Я/ug, "$1ЙА")
		.replace(/Я (\p{Uppercase})(\p{Uppercase})/ug, "ЙА $1$2")
		.replace(/Я(\p{Uppercase})/ug, "ЙА$1")
		.replace(/Я/g, "Йа")
		.replace(/я/g, "йа")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Е/ug, "$1$2 ЙЭ")
		.replace(/(\p{Uppercase})Е/ug, "$1ЙЭ")
		.replace(/Е (\p{Uppercase})(\p{Uppercase})/ug, "ЙЭ $1$2")
		.replace(/Е(\p{Uppercase})/ug, "ЙЭ$1")
		.replace(/Е/g, "Йэ")
		.replace(/е/g, "йэ")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ё/ug, "$1$2 ЙО")
		.replace(/(\p{Uppercase})Ё/ug, "$1ЙО")
		.replace(/Ё (\p{Uppercase})(\p{Uppercase})/ug, "ЙО $1$2")
		.replace(/Ё(\p{Uppercase})/ug, "ЙО$1")
		.replace(/Ё/g, "Йо")
		.replace(/ё/g, "йо")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ю/ug, "$1$2 ЙУ")
		.replace(/(\p{Uppercase})Ю/ug, "$1ЙУ")
		.replace(/Ю (\p{Uppercase})(\p{Uppercase})/ug, "ЙУ $1$2")
		.replace(/Ю(\p{Uppercase})/ug, "ЙУ$1")
		.replace(/Ю/g, "Йу")
		.replace(/ю/g, "йу")

		.replace(/(Ъ|ъ)/g, "")

		.replace(/а/g, "a")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/ҕ/g, "ğ")
		.replace(/д/g, "d")
		.replace(/ђ/g, "c")
		.replace(/е/g, "e")
		.replace(/є/g, "ë")
		.replace(/ж/g, "j")
		.replace(/з/g, "z")
		.replace(/и/g, "i")
		.replace(/й/g, "y")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/ҥ/g, "ñ")
		.replace(/о/g, "o")
		.replace(/ө/g, "ö")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/һ/g, "h")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ү/g, "ü")
		.replace(/ф/g, "f")
		.replace(/х/g, "q")
		.replace(/ч/g, "ç")
		.replace(/ш/g, "ş")
		.replace(/ь/g, "")
		.replace(/ы/g, "ı")
		.replace(/э/g, "e")

		.replace(/А/g, "A")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Ҕ/g, "Ğ")
		.replace(/Д/g, "D")
		.replace(/Ђ/g, "C")
		.replace(/Е/g, "E")
		.replace(/Є/g, "Ë")
		.replace(/Ж/g, "J")
		.replace(/З/g, "Z")
		.replace(/И/g, "İ")
		.replace(/Й/g, "Y")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/Ҥ/g, "Ñ")
		.replace(/О/g, "O")
		.replace(/Ө/g, "Ö")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Һ/g, "H")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ү/g, "Ü")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "Q")
		.replace(/Ч/g, "Ç")
		.replace(/Ш/g, "Ş")
		.replace(/Ь/g, "")
		.replace(/Ы/g, "I")
		.replace(/Э/g, "E")

		.replace(/\u2039/g, "\u2018")
		.replace(/\u203a/g, "\u2019")
		.replace(/\u00ab/g, "\u201c")
		.replace(/\u00bb/g, "\u201d")

		.normalize('NFC');
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}