var car;

function cyrlat() {
	document.transcription.text1.value = document.transcription.text1.value.replace(/<</g, "«")
	.replace(/>>/g, "»")
	.replace(/(\p{Script=Cyrl})A/ug, "$1А")
	.replace(/(\p{Script=Cyrl})C/ug, "$1С")
	.replace(/(\p{Script=Cyrl})E/ug, "$1Е")
	.replace(/(\p{Script=Cyrl})Ë/ug, "$1Ё")
	.replace(/(\p{Script=Cyrl})O/ug, "$1О")
	.replace(/(\p{Script=Cyrl})P/ug, "$1Р")
	.replace(/(\p{Script=Cyrl})X/ug, "$1Х")
	.replace(/(\p{Script=Cyrl})a/ug, "$1а")
	.replace(/(\p{Script=Cyrl})c/ug, "$1с")
	.replace(/(\p{Script=Cyrl})e/ug, "$1е")
	.replace(/(\p{Script=Cyrl})ë/ug, "$1ё")
	.replace(/(\p{Script=Cyrl})o/ug, "$1о")
	.replace(/(\p{Script=Cyrl})p/ug, "$1р")
	.replace(/(\p{Script=Cyrl})x/ug, "$1х")
	.replace(/A(\p{Script=Cyrl})/ug, "А$1")
	.replace(/C(\p{Script=Cyrl})/ug, "С$1")
	.replace(/E(\p{Script=Cyrl})/ug, "Е$1")
	.replace(/Ë(\p{Script=Cyrl})/ug, "Ё$1")
	.replace(/O(\p{Script=Cyrl})/ug, "О$1")
	.replace(/P(\p{Script=Cyrl})/ug, "Р$1")
	.replace(/X(\p{Script=Cyrl})/ug, "Х$1")
	.replace(/a(\p{Script=Cyrl})/ug, "а$1")
	.replace(/c(\p{Script=Cyrl})/ug, "с$1")
	.replace(/e(\p{Script=Cyrl})/ug, "е$1")
	.replace(/ë(\p{Script=Cyrl})/ug, "ё$1")
	.replace(/o(\p{Script=Cyrl})/ug, "о$1")
	.replace(/p(\p{Script=Cyrl})/ug, "р$1")
	.replace(/x(\p{Script=Cyrl})/ug, "х$1");
	car = document.transcription.text1.value;
	car = car.replace(/([ЪЬ])([АОУ])/g, "$1\u2019$2");
	car = car.replace(/([ЪЬъь])([аоу])/g, "$1\u2019$2");
	car = car.replace(/ЪЕ/g, "ЙÈ");
	car = car.replace(/([Ъъ])е/g, "йè");
	car = car.replace(/([ЬЪ])Э/g, "$1\u2019Э");
	car = car.replace(/([ЬЪьъ])э/g, "$1\u2019э");

	car = car.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])Я/g, "$1Ä");
	car = car.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])я/g, "$1ä");
	car = car.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])Э/g, "$1È");
	car = car.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])э/g, "$1è");
	car = car.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])Е/g, "$1E");
	car = car.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])е/g, "$1e");
	car = car.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])Ё/g, "$1Ö");
	car = car.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])ё/g, "$1ö");
	car = car.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])Ю/g, "$1Ü");
	car = car.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])ю/g, "$1ü");

	car = car.replace(/(\p{Uppercase})Я/ug, "$1ЙА");
	car = car.replace(/(\p{Uppercase})(\p{Uppercase}) Я/ug, "$1$2 ЙА");
	car = car.replace(/Я (\p{Uppercase})(\p{Uppercase})/ug, "ЙА $1$2");
	car = car.replace(/Я(\p{Uppercase})/ug, "ЙА$1");
	car = car.replace(/Я/g, "Йа");
	car = car.replace(/я/g, "йа");
	car = car.replace(/(\p{Uppercase})Е/ug, "$1ЙЭ");
	car = car.replace(/(\p{Uppercase})(\p{Uppercase}) Е/ug, "$1$2 ЙЭ");
	car = car.replace(/Е (\p{Uppercase})(\p{Uppercase})/ug, "ЙЭ $1$2");
	car = car.replace(/Е(\p{Uppercase})/ug, "ЙЭ$1");
	car = car.replace(/Е/g, "Йэ");
	car = car.replace(/е/g, "йэ");
	car = car.replace(/(\p{Uppercase})Ё/ug, "$1ЙО");
	car = car.replace(/(\p{Uppercase})(\p{Uppercase}) Ё/ug, "$1$2 ЙО");
	car = car.replace(/Ё (\p{Uppercase})(\p{Uppercase})/ug, "ЙО $1$2");
	car = car.replace(/Ё(\p{Uppercase})/ug, "ЙО$1");
	car = car.replace(/Ё/g, "Йо");
	car = car.replace(/ё/g, "йо");
	car = car.replace(/(\p{Uppercase})Ю/ug, "$1ЙУ");
	car = car.replace(/(\p{Uppercase})(\p{Uppercase}) Ю/ug, "$1$2 ЙУ");
	car = car.replace(/Ю (\p{Uppercase})(\p{Uppercase})/ug, "ЙУ $1$2");
	car = car.replace(/Ю(\p{Uppercase})/ug, "ЙУ$1");
	car = car.replace(/Ю/g, "Йу");
	car = car.replace(/ю/g, "йу");

	car = car.replace(/а/g, "a");
	car = car.replace(/б/g, "b");
	car = car.replace(/в/g, "v");
	car = car.replace(/г/g, "g");
	car = car.replace(/д/g, "d");
	car = car.replace(/е/g, "je");
	car = car.replace(/ж/g, "ž");
	car = car.replace(/з/g, "z");
	car = car.replace(/и/g, "i");
	car = car.replace(/й/g, "j");
	car = car.replace(/к/g, "k");
	car = car.replace(/л/g, "l");
	car = car.replace(/м/g, "m");
	car = car.replace(/н/g, "n");
	car = car.replace(/о/g, "o");
	car = car.replace(/п/g, "p");
	car = car.replace(/р/g, "r");
	car = car.replace(/с/g, "s");
	car = car.replace(/т/g, "t");
	car = car.replace(/у/g, "u");
	car = car.replace(/ф/g, "f");
	car = car.replace(/х/g, "h");
	car = car.replace(/ц/g, "c");
	car = car.replace(/ч/g, "č");
	car = car.replace(/ш/g, "š");
	car = car.replace(/щ/g, "ś");
	car = car.replace(/ы/g, "y");
	car = car.replace(/ь/g, "j");
	car = car.replace(/ъ/g, "");
	car = car.replace(/э/g, "e");
	car = car.replace(/ю/g, "ju");
	car = car.replace(/ё/g, "jo");
	car = car.replace(/я/g, "ja");

	car = car.replace(/А/g, "A");
	car = car.replace(/Б/g, "B");
	car = car.replace(/В/g, "V");
	car = car.replace(/Г/g, "G");
	car = car.replace(/Д/g, "D");
	car = car.replace(/Е/g, "Je");
	car = car.replace(/Ж/g, "Ž");
	car = car.replace(/З/g, "Z");
	car = car.replace(/И/g, "I");
	car = car.replace(/Й/g, "J");
	car = car.replace(/К/g, "K");
	car = car.replace(/Л/g, "L");
	car = car.replace(/М/g, "M");
	car = car.replace(/Н/g, "N");
	car = car.replace(/О/g, "O");
	car = car.replace(/П/g, "P");
	car = car.replace(/Р/g, "R");
	car = car.replace(/С/g, "S");
	car = car.replace(/Т/g, "T");
	car = car.replace(/У/g, "U");
	car = car.replace(/Ф/g, "F");
	car = car.replace(/Х/g, "H");
	car = car.replace(/Ц/g, "C");
	car = car.replace(/Ч/g, "Č");
	car = car.replace(/Ш/g, "Š");
	car = car.replace(/Щ/g, "Ś");
	car = car.replace(/Ы/g, "Y");
	car = car.replace(/Ь/g, "J");
	car = car.replace(/Ъ/g, "");
	car = car.replace(/Э/g, "E");
	car = car.replace(/Ю/g, "Ju");
	car = car.replace(/Ё/g, "Jo");
	car = car.replace(/Я/g, "Ja");
	document.transcription.text2.value = car;
}
/*
function latcyr() {
	car = document.transcription.text2.value;
	car = car.replace(/je/g, "е");
	car = car.replace(/jo/g, "ё");
	car = car.replace(/ju/g, "ю");
	car = car.replace(/ja/g, "я");
	car = car.replace(/J[Ee]/g, "Е");
	car = car.replace(/J[Oo]/g, "Ё");
	car = car.replace(/J[Uu]/g, "Ю");
	car = car.replace(/J[Aa]/g, "Я");
	car = car.replace(/a/g, "а");
	car = car.replace(/b/g, "б");
	car = car.replace(/v/g, "в");
	car = car.replace(/g/g, "г");
	car = car.replace(/d/g, "д");
	car = car.replace(/ž/g, "ж");
	car = car.replace(/z/g, "з");
	car = car.replace(/i/g, "и");
	car = car.replace(/k/g, "к");
	car = car.replace(/l/g, "л");
	car = car.replace(/m/g, "м");
	car = car.replace(/n/g, "н");
	car = car.replace(/o/g, "о");
	car = car.replace(/p/g, "п");
	car = car.replace(/r/g, "р");
	car = car.replace(/s/g, "с");
	car = car.replace(/t/g, "т");
	car = car.replace(/u/g, "у");
	car = car.replace(/f/g, "ф");
	car = car.replace(/h/g, "х");
	car = car.replace(/c/g, "ц");
	car = car.replace(/č/g, "ч");
	car = car.replace(/š/g, "ш");
	car = car.replace(/ś/g, "щ");
	car = car.replace(/y/g, "ы");
	car = car.replace(/j/g, "ь");
	car = car.replace(/e/g, "э");
	car = car.replace(/A/g, "А");
	car = car.replace(/B/g, "Б");
	car = car.replace(/V/g, "В");
	car = car.replace(/G/g, "Г");
	car = car.replace(/D/g, "Д");
	car = car.replace(/Ž/g, "Ж");
	car = car.replace(/Z/g, "З");
	car = car.replace(/I/g, "И");
	car = car.replace(/K/g, "К");
	car = car.replace(/L/g, "Л");
	car = car.replace(/M/g, "М");
	car = car.replace(/N/g, "Н");
	car = car.replace(/O/g, "О");
	car = car.replace(/P/g, "П");
	car = car.replace(/R/g, "Р");
	car = car.replace(/S/g, "С");
	car = car.replace(/T/g, "Т");
	car = car.replace(/U/g, "У");
	car = car.replace(/F/g, "Ф");
	car = car.replace(/H/g, "Х");
	car = car.replace(/C/g, "Ц");
	car = car.replace(/Č/g, "Ч");
	car = car.replace(/Š/g, "Ш");
	car = car.replace(/Ś/g, "Щ");
	car = car.replace(/Y/g, "Ы");
	car = car.replace(/J/g, "Ь");
	car = car.replace(/E/g, "Э");
	
    car = car.replace(/([АЕИЙОУЫЭ])Ь/g, "$1Й");
	car = car.replace(/([АЕИЙОУЫЭаеийоуыэ])ь/g, "$1й");

	car = car.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])ü/g, "$1ю");
	car = car.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])Ü/g, "$1Ю");
	car = car.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])ö/g, "$1ё");
	car = car.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])Ö/g, "$1Ё");
	car = car.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])e/g, "$1е");
	car = car.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])E/g, "$1Е");
	car = car.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])è/g, "$1э");
	car = car.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])È/g, "$1Э");
	car = car.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])ä/g, "$1я");
	car = car.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])Ä/g, "$1Я");

	car = car.replace(/([ЬЪьъ])\u2019э/g, "$1э");
	car = car.replace(/([ЬЪ])\u2019Э/g, "$1Э");
	car = car.replace(/йè/g, "ъе");
	car = car.replace(/Йè/g, "Ъе");
	car = car.replace(/ЙÈ/g, "ЪЕ");
	car = car.replace(/([ЪЬъь])\u2019([аоу])/g, "$1$2");
	car = car.replace(/([ЪЬ])\u2019([АОУ])/g, "$1$2");
	document.transcription.text1.value = car;
}
*/
function copy1() {
	textRange = document.transcription.text1.createTextRange();
	textRange.execCommand("Copy");
	textRange = "";
}

function copy2() {
	textRange = document.transcription.text2.createTextRange();
	textRange.execCommand("Copy");
	textRange = "";
}
