function cyrsimp() {
	document.transcription.text1.value = document.transcription.text1.value
	    .replace(/(?<=\p{Script=Cyrl})a/ug, "а")
		.replace(/a(?=\p{Script=Cyrl})/ug, "а")
		.replace(/(?<=\p{Script=Cyrl})e/ug, "е")
		.replace(/e(?=\p{Script=Cyrl})/ug, "е")
		.replace(/(?<=\p{Script=Cyrl})ë/ug, "ё")
		.replace(/ë(?=\p{Script=Cyrl})/ug, "ё")
		.replace(/(?<=\p{Script=Cyrl})o/ug, "о")
		.replace(/o(?=\p{Script=Cyrl})/ug, "о")
		.replace(/(?<=\p{Script=Cyrl})p/ug, "р")
		.replace(/p(?=\p{Script=Cyrl})/ug, "р")
		.replace(/(?<=\p{Script=Cyrl})c/ug, "с")
		.replace(/c(?=\p{Script=Cyrl})/ug, "с")
		.replace(/(?<=\p{Script=Cyrl})y/ug, "у")
		.replace(/y(?=\p{Script=Cyrl})/ug, "у")
		.replace(/(?<=\p{Script=Cyrl})x/ug, "х")
		.replace(/x(?=\p{Script=Cyrl})/ug, "х")
		
		.replace(/(?<=\p{Script=Cyrl})A/ug, "А")
		.replace(/A(?=\p{Script=Cyrl})/ug, "А")
		.replace(/(?<=\p{Script=Cyrl})B/ug, "В")
		.replace(/B(?=\p{Script=Cyrl})/ug, "В")
		.replace(/(?<=\p{Script=Cyrl})E/ug, "Е")
		.replace(/E(?=\p{Script=Cyrl})/ug, "Е")
		.replace(/(?<=\p{Script=Cyrl})Ë/ug, "Ё")
		.replace(/Ë(?=\p{Script=Cyrl})/ug, "Ё")
		.replace(/(?<=\p{Script=Cyrl})K/ug, "К")
		.replace(/K(?=\p{Script=Cyrl})/ug, "К")
		.replace(/(?<=\p{Script=Cyrl})M/ug, "М")
		.replace(/M(?=\p{Script=Cyrl})/ug, "М")
		.replace(/(?<=\p{Script=Cyrl})H/ug, "Н")
		.replace(/H(?=\p{Script=Cyrl})/ug, "Н")
		.replace(/(?<=\p{Script=Cyrl})O/ug, "О")
		.replace(/O(?=\p{Script=Cyrl})/ug, "О")
		.replace(/(?<=\p{Script=Cyrl})P/ug, "Р")
		.replace(/P(?=\p{Script=Cyrl})/ug, "Р")
		.replace(/(?<=\p{Script=Cyrl})C/ug, "С")
		.replace(/C(?=\p{Script=Cyrl})/ug, "С")
		.replace(/(?<=\p{Script=Cyrl})T/ug, "Т")
		.replace(/T(?=\p{Script=Cyrl})/ug, "Т")
		.replace(/(?<=\p{Script=Cyrl})X/ug, "Х")
		.replace(/X(?=\p{Script=Cyrl})/ug, "Х")		
		
		.replace(/Х(?=[0-9])/g, "X")
		.replace(/х(?=[0-9])/g, "x")
		.replace(/(?<=[0-9])Х/g, "X")
		.replace(/(?<=[0-9])х/g, "x")

	document.transcription.text2.value = document.transcription.text1.value
		.replace(/Й([Аа])/g, "Й$1\u0300")
		.replace(/йа/g, "йа\u0300")
		.replace(/Й([Ээ])/g, "Й$1\u0300")
		.replace(/йэ/g, "йэ\u0300")
		.replace(/Й([Уу])/g, "Й$1\u0300")
		.replace(/йу/g, "йу\u0300")
		.replace(/Й([Оо])/g, "Й$1\u0300")
		.replace(/йо/g, "йо\u0300")

		.replace(/(?<=[БбВвГгДдЖжЗзЙйКкЛлМмНнПпРрСсТтФфХхЦцЧчШшЩщ])Ы/g, "Ɩ")
		.replace(/(?<=[БбВвГгДдЖжЗзЙйКкЛлМмНнПпРрСсТтФфХхЦцЧчШшЩщ])ы/g, "ɩ")
		.replace(/(?<=[БбВвГгДдЖжЗзЙйКкЛлМмНнПпРрСсТтФфХхЦцЧчШшЩщ])Ɩ(?=[АаБбВвГгДдЕеЁёЖжЗзИиЙйКкЛлМмНнОоПпРрСсТтУуФфХхЦцЧчШшЩщЪъЫыЬьЭэЮюЯя])/g, "Ы")
		.replace(/(?<=[БбВвГгДдЖжЗзЙйКкЛлМмНнПпРрСсТтФфХхЦцЧчШшЩщ])ɩ(?=[АаБбВвГгДдЕеЁёЖжЗзИиЙйКкЛлМмНнОоПпРрСсТтУуФфХхЦцЧчШшЩщЪъЫыЬьЭэЮюЯя])/g, "ы")
		.replace(/(?<=[АаБбВвГгДдЕеЁёЖжЗзИиЙйКкЛлМмНнОоПпРрСсТтУуФфХхЦцЧчШшЩщЪъЫыЬьЭэЮюЯя][БбВвГгДдЖжЗзЙйКкЛлМмНнПпРрСсТтФфХхЦцЧчШшЩщ])Ɩ/g, "Ы")
		.replace(/(?<=[АаБбВвГгДдЕеЁёЖжЗзИиЙйКкЛлМмНнОоПпРрСсТтУуФфХхЦцЧчШшЩщЪъЫыЬьЭэЮюЯя][БбВвГгДдЖжЗзЙйКкЛлМмНнПпРрСсТтФфХхЦцЧчШшЩщ])ɩ/g, "ы")
		.replace(/ɩ/g, "и")
		.replace(/Ɩ/g, "И")

		/*.replace(/Т([Сс])/g, "Т\u2019$1")
		.replace(/тс/g, "т\u2019с")*/

		.replace(/дж/g, "џ")
		.replace(/Д([Жж])/g, "Џ")
		
		.replace(/(?<=\p{Lu}|\p{Lu}\p{Lu} )Я/ug, "ЬА")
		.replace(/Я(?=\p{Lu}| \p{Lu}\p{Lu})/ug, "ЬА")
		.replace(/Я/g, "Ьа")
		.replace(/я/g, "ьа")
		.replace(/(?<=\p{Lu}|\p{Lu}\p{Lu} )Е/ug, "ЬЭ")
		.replace(/Е(?=\p{Lu}| \p{Lu}\p{Lu})/ug, "ЬЭ")
		.replace(/Е/g, "Ьэ")
		.replace(/е/g, "ьэ")
		.replace(/(?<=\p{Lu}|\p{Lu}\p{Lu} )Ё/ug, "ЬО")
		.replace(/Ё(?=\p{Lu}| \p{Lu}\p{Lu})/ug, "ЬО")
		.replace(/Ё/g, "Ьо")
		.replace(/ё/g, "ьо")
		.replace(/(?<=\p{Lu}|\p{Lu}\p{Lu} )Ю/ug, "ЬУ")
		.replace(/Ю(?=\p{Lu}| \p{Lu}\p{Lu})/ug, "ЬУ")
		.replace(/Ю/g, "Ьу")
		.replace(/ю/g, "ьу")
		.replace(/(?<=\p{Lu}|\p{Lu}\p{Lu} )Щ/ug, "Ш\u0048")
		.replace(/Щ(?=\p{Lu}| \p{Lu}\p{Lu})/ug, "Ш\u0048")
		.replace(/Щ(?=\p{Ll})/ug, "Ш\u0068")
		.replace(/Щ/g, "Ш")
		.replace(/щ(?=\p{Ll})/ug, "ш\u0068")
		.replace(/щ/g, "ш")
		.replace(/(?<=\p{Lu}|\p{Lu}\p{Lu} )Ш/ug, "С\u0048")
		.replace(/Ш(?=\p{Lu}| \p{Lu}\p{Lu})/ug, "С\u0048")
		.replace(/Ш/g, "С\u0068")
		.replace(/ш/g, "с\u0068")
		.replace(/(?<=\p{Lu}|\p{Lu}\p{Lu} )Ж/ug, "З\u0048")
		.replace(/Ж(?=\p{Lu}| \p{Lu}\p{Lu})/ug, "З\u0048")
		.replace(/Ж/g, "З\u0068")
		.replace(/ж/g, "з\u0068")
		.replace(/(?<=\p{Lu}|\p{Lu}\p{Lu} )Ч/ug, "\u0043\u0048")
		.replace(/Ч(?=\p{Lu}| \p{Lu}\p{Lu})/ug, "\u0043\u0048")
		.replace(/Ч/g, "\u0043\u0068")
		.replace(/ч/g, "\u0063\u0068")
		.replace(/(?<=\p{Lu}|\p{Lu}\p{Lu} )Ц/ug, "ТС")
		.replace(/Ц(?=\p{Lu}| \p{Lu}\p{Lu})/ug, "ТС")
		.replace(/Ц/g, "Тс")
		.replace(/ц/g, "тс")

		.replace(/(?<=[АИОУЭЫ])Х/g, "К\u0048")
		.replace(/(?<=[АИОУЭЫаиоуэы])х/g, "к\u0068")
		.replace(/К(?:\u0048(?=[АИОУЭЫ])|\u0068(?=[аиоуэы]))/g, "Х")
		.replace(/к\u0068(?=[аиоуэы])/g, "х")

		.replace(/(?<=[БВГДЏЗКЛМНПРСТФХ\u0048])Ь(?=[АОУ])/g, "И")
		.replace(/(?<=[БВГДЏЗКЛМНПРСТФХ\u0048бвгдџзклмнпрстфх\u0068])ь(?=[аоу])/g, "и")
		.replace(/(?<=[БВГДЏЗКЛМНПРСТФХ\u0048])ЬЭ/g, "Э")
		.replace(/(?<=[БВГДЏЗКЛМНПРСТФХ\u0048бвгдџзклмнпрстфх\u0068])ьэ/g, "э")
		.replace(/Ь(?=[АЭИЫОУаэиыоу])/g, "Й")
		.replace(/ь(?=[аэиыоу])/g, "й")
		.replace(/ЬЬ/g, "Й")
		.replace(/[Ьь]ь/g, "й")

		.replace(/а/g, "a")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/д/g, "d")
		.replace(/џ/g, "j")
		.replace(/з/g, "z")
		.replace(/и/g, "i")
		.replace(/й/g, "ẏ")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/о/g, "o")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ф/g, "f")
		.replace(/х/g, "h")
		.replace(/ы/g, "y")
		.replace(/э/g, "e")

		.replace(/А/g, "A")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Д/g, "D")
		.replace(/Џ/g, "J")
		.replace(/З/g, "Z")
		.replace(/И/g, "I")
		.replace(/Й/g, "Ẏ")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/О/g, "O")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "H")
		.replace(/Ы/g, "Y")
		.replace(/Э/g, "E")

		.replace(/[ЬЪьъ]/g, "")

		.replace(/ẎY/g, "ẎI")
		.replace(/(?<=[Ẏẏ])y/g, "i")
		.replace(/Y[Ẏẏ](?![AEIOUYẎ])/g, "Y")
		.replace(/yẏ(?![aeiouyẏ])/g, "y")
		.replace(/YẎ(?=[AEIOUYẎ])/g, "IẎ")
		.replace(/Yẏ(?=[aeiouyẏ])/g, "Iẏ")
		.replace(/yẏ(?=[aeiouyẏ])/g, "iẏ")

		.replace(/(?<=[BCDFGHKLMNPRSTVZ])ẎI/g, "I")
		.replace(/(?<=[BCDFGHKLMNPRSTVZbcdfghklmnprstvz])ẏi/g, "i")

		.replace(/(?<=[AEOUYẎ])Ẏ(?![AEIOUYẎ])/g, "I")
		.replace(/(?<=[AEOUYẎaeouyẏ])ẏ(?![aeiouyẏ])/g, "i")
		.replace(/IẎ(?![AEIOUYẎ])/g, "I")
		.replace(/(?<=[Ii])ẏ(?![aeiouyẏ])/g, "")

		.replace(/Ẏ/g, "Y")
		.replace(/ẏ/g, "y")

		.replace(/\u2039/g, "\u2018")
		.replace(/\u203a/g, "\u2019")
		.replace(/\u00ab/g, "\u201c")
		.replace(/\u00bb/g, "\u201d")
		.normalize('NFC');
}

function cyrstr() {
	document.transcription.text1.value = document.transcription.text1.value
		.replace(/(?<=\p{Script=Cyrl})a/ug, "а")
		.replace(/a(?=\p{Script=Cyrl})/ug, "а")
		.replace(/(?<=\p{Script=Cyrl})e/ug, "е")
		.replace(/e(?=\p{Script=Cyrl})/ug, "е")
		.replace(/(?<=\p{Script=Cyrl})ë/ug, "ё")
		.replace(/ë(?=\p{Script=Cyrl})/ug, "ё")
		.replace(/(?<=\p{Script=Cyrl})o/ug, "о")
		.replace(/o(?=\p{Script=Cyrl})/ug, "о")
		.replace(/(?<=\p{Script=Cyrl})p/ug, "р")
		.replace(/p(?=\p{Script=Cyrl})/ug, "р")
		.replace(/(?<=\p{Script=Cyrl})c/ug, "с")
		.replace(/c(?=\p{Script=Cyrl})/ug, "с")
		.replace(/(?<=\p{Script=Cyrl})y/ug, "у")
		.replace(/y(?=\p{Script=Cyrl})/ug, "у")
		.replace(/(?<=\p{Script=Cyrl})x/ug, "х")
		.replace(/x(?=\p{Script=Cyrl})/ug, "х")
		
		.replace(/(?<=\p{Script=Cyrl})A/ug, "А")
		.replace(/A(?=\p{Script=Cyrl})/ug, "А")
		.replace(/(?<=\p{Script=Cyrl})B/ug, "В")
		.replace(/B(?=\p{Script=Cyrl})/ug, "В")
		.replace(/(?<=\p{Script=Cyrl})E/ug, "Е")
		.replace(/E(?=\p{Script=Cyrl})/ug, "Е")
		.replace(/(?<=\p{Script=Cyrl})Ë/ug, "Ё")
		.replace(/Ë(?=\p{Script=Cyrl})/ug, "Ё")
		.replace(/(?<=\p{Script=Cyrl})K/ug, "К")
		.replace(/K(?=\p{Script=Cyrl})/ug, "К")
		.replace(/(?<=\p{Script=Cyrl})M/ug, "М")
		.replace(/M(?=\p{Script=Cyrl})/ug, "М")
		.replace(/(?<=\p{Script=Cyrl})H/ug, "Н")
		.replace(/H(?=\p{Script=Cyrl})/ug, "Н")
		.replace(/(?<=\p{Script=Cyrl})O/ug, "О")
		.replace(/O(?=\p{Script=Cyrl})/ug, "О")
		.replace(/(?<=\p{Script=Cyrl})P/ug, "Р")
		.replace(/P(?=\p{Script=Cyrl})/ug, "Р")
		.replace(/(?<=\p{Script=Cyrl})C/ug, "С")
		.replace(/C(?=\p{Script=Cyrl})/ug, "С")
		.replace(/(?<=\p{Script=Cyrl})T/ug, "Т")
		.replace(/T(?=\p{Script=Cyrl})/ug, "Т")
		.replace(/(?<=\p{Script=Cyrl})X/ug, "Х")
		.replace(/X(?=\p{Script=Cyrl})/ug, "Х")		
		
		.replace(/Х(?=[0-9])/g, "X")
		.replace(/х(?=[0-9])/g, "x")
		.replace(/(?<=[0-9])Х/g, "X")
		.replace(/(?<=[0-9])х/g, "x");

	document.transcription.text3.value = document.transcription.text1.value
		.replace(/(?<=\p{Script=Cyrl})\u0301/ug, "")
		
		.replace(/([ЪЬ])(?=[АОУ])/g, "$1\u2019")
		.replace(/([ЪЬъь])(?=[аоу])/g, "$1\u2019")
		.replace(/ЪЕ/g, "ЙË")
		.replace(/[Ъъ]е/g, "йë")
		.replace(/(?<=[ЬЪ])Э/g, "\u2019Э")
		.replace(/(?<=[ЬЪьъ])э/g, "\u2019э")
		
		.replace(/Й([Аа])/g, "Й$1\u0308")
		.replace(/йа/g, "йа\u0308")
		.replace(/Й([Ээ])/g, "Й$1\u0308")
		.replace(/йэ/g, "йэ\u0308")
		.replace(/Й([Уу])/g, "Й$1\u0308")
		.replace(/йу/g, "йу\u0308")
		.replace(/Й([Оо])/g, "Й$1\u0308")
		.replace(/йо/g, "йо\u0308")

		.replace(/(?<=[БВГДЖЗКЛМНПРСТФХЦЧШЩЬ])Я/g, "Á")
		.replace(/(?<=[БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])я/g, "á")
		.replace(/(?<=[БВГДЖЗКЛМНПРСТФХЦЧШЩЬ])Э/g, "Ë")
		.replace(/(?<=[БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])э/g, "ë")
		.replace(/(?<=[БВГДЖЗКЛМНПРСТФХЦЧШЩЬ])Е/g, "E")
		.replace(/(?<=[БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])е/g, "e")
		.replace(/(?<=[БВГДЖЗКЛМНПРСТФХЦЧШЩЬ])Ё/g, "Ó")
		.replace(/(?<=[БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])ё/g, "ó")
		.replace(/(?<=[БВГДЖЗКЛМНПРСТФХЦЧШЩЬ])Ю/g, "Ú")
		.replace(/(?<=[БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])ю/g, "ú")

		.replace(/(?<=\p{Lu}|\p{Lu}\p{Lu} )Я/ug, "ЙА")
		.replace(/Я(?=\p{Lu}| \p{Lu}\p{Lu})/ug, "ЙА")
		.replace(/Я/g, "Йа")
		.replace(/я/g, "йа")
		.replace(/(?<=\p{Lu}|\p{Lu}\p{Lu} )Е/ug, "ЙЭ")
		.replace(/Е(?=\p{Lu}| \p{Lu}\p{Lu})/ug, "ЙЭ")
		.replace(/Е/g, "Йэ")
		.replace(/е/g, "йэ")
		.replace(/(?<=\p{Lu}|\p{Lu}\p{Lu} )Ё/ug, "ЙО")
		.replace(/Ё(?=\p{Lu}| \p{Lu}\p{Lu})/ug, "ЙО")
		.replace(/Ё/g, "Йо")
		.replace(/ё/g, "йо")
		.replace(/(?<=\p{Lu}|\p{Lu}\p{Lu} )Ю/ug, "ЙУ")
		.replace(/Ю(?=\p{Lu}| \p{Lu}\p{Lu})/ug, "ЙУ")
		.replace(/Ю/g, "Йу")
		.replace(/ю/g, "йу")

		.replace(/а/g, "a")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/д/g, "d")
		.replace(/е/g, "je")
		.replace(/ж/g, "ž")
		.replace(/з/g, "z")
		.replace(/и/g, "i")
		.replace(/й/g, "j")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/о/g, "o")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ф/g, "f")
		.replace(/х/g, "h")
		.replace(/ц/g, "c")
		.replace(/ч/g, "č")
		.replace(/ш/g, "š")
		.replace(/щ/g, "ś")
		.replace(/ы/g, "y")
		.replace(/ь/g, "j")
		.replace(/ъ/g, "")
		.replace(/э/g, "e")
		.replace(/ю/g, "ju")
		.replace(/ё/g, "jo")
		.replace(/я/g, "ja")

		.replace(/А/g, "A")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Д/g, "D")
		.replace(/Е/g, "Je")
		.replace(/Ж/g, "Ž")
		.replace(/З/g, "Z")
		.replace(/И/g, "I")
		.replace(/Й/g, "J")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/О/g, "O")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "H")
		.replace(/Ц/g, "C")
		.replace(/Ч/g, "Č")
		.replace(/Ш/g, "Š")
		.replace(/Щ/g, "Ś")
		.replace(/Ы/g, "Y")
		.replace(/Ь/g, "J")
		.replace(/Ъ/g, "")
		.replace(/Э/g, "E")
		.replace(/Ю/g, "Ju")
		.replace(/Ё/g, "Jo")
		.replace(/Я/g, "Ja")

		.replace(/\u2039/g, "\u201a")
		.replace(/\u203a/g, "\u2018")
		.replace(/\u00ab/g, "\u201e")
		.replace(/\u00bb/g, "\u201c")
		.normalize('NFC');
}

function simpcyr() {}

function strcyr() {
	document.transcription.text1.value = document.transcription.text3.value
		.normalize('NFD')
		.replace(/([aou])\u0301/g, "ь$1")
		.replace(/([AOU])\u0301/g, "Ь$1")
		.normalize('NFC')
		
		.replace(/(?<=[BCČDFGHJKLMNPRSŠŚTVZŽbcčdfghjklmnprsšśtvzž])j(?=[aou])/g, "ъj")
		.replace(/(?<=[BCČDFGHJKLMNPRSŠŚTVZŽbcčdfghjklmnprsšśtvzž])jë/g, "ъje")
		.replace(/(?<=[BCČDFGHJKLMNPRSŠŚTVZŽ])J(?=[AOU])/g, "ЪJ")
		.replace(/(?<=[BCČDFGHJKLMNPRSŠŚTVZŽ])JË/g, "ЪJE")
		
		.replace(/a/g, "а")
		.replace(/b/g, "б")
		.replace(/c/g, "ц")
		.replace(/č/g, "ч")
		.replace(/d/g, "д")
		.replace(/e/g, "э")
		.replace(/f/g, "ф")
		.replace(/g/g, "г")
		.replace(/h/g, "х")
		.replace(/i/g, "и")
		.replace(/j/g, "ь")
		.replace(/k/g, "к")
		.replace(/l/g, "л")
		.replace(/m/g, "м")
		.replace(/n/g, "н")
		.replace(/o/g, "о")
		.replace(/p/g, "п")
		.replace(/r/g, "р")
		.replace(/s/g, "с")
		.replace(/š/g, "ш")
		.replace(/ś/g, "щ")
		.replace(/t/g, "т")
		.replace(/u/g, "у")
		.replace(/v/g, "в")
		.replace(/y/g, "ы")
		.replace(/z/g, "з")
		.replace(/ž/g, "ж")
		.replace(/A/g, "А")
		.replace(/B/g, "Б")
		.replace(/C/g, "Ц")
		.replace(/Č/g, "Ч")
		.replace(/D/g, "Д")
		.replace(/E/g, "Э")
		.replace(/F/g, "Ф")
		.replace(/G/g, "Г")
		.replace(/H/g, "Х")
		.replace(/I/g, "И")
		.replace(/J/g, "Ь")
		.replace(/K/g, "К")
		.replace(/L/g, "Л")
		.replace(/M/g, "М")
		.replace(/N/g, "Н")
		.replace(/O/g, "О")
		.replace(/P/g, "П")
		.replace(/R/g, "Р")
		.replace(/S/g, "С")
		.replace(/Š/g, "Ш")
		.replace(/Ś/g, "Щ")
		.replace(/T/g, "Т")
		.replace(/U/g, "У")
		.replace(/V/g, "В")
		.replace(/Y/g, "Ы")
		.replace(/Z/g, "З")
		.replace(/Ž/g, "Ж")
		.replace(/(\p{Lu})\u2019/ug, "Ъ")
		.replace(/\u2019/g, "ъ")
		
		.replace(/ьа/g, "я")
		.replace(/ьэ/g, "е")
		.replace(/ьо/g, "ё")
		.replace(/ьу/g, "ю")
		.replace(/[ЬЪ][Аа]/g, "Я")
		.replace(/[ЬЪ][Ээ]/g, "Е")
		.replace(/[ЬЪ][Оо]/g, "Ё")
		.replace(/[ЬЪ][Уу]/g, "Ю")
		
		.replace(/(?<=[БВГДЖЗКЛМНПРСТФХЦЧШЩбвгджзклмнпрстфхцчшщ])е/g, "ье")
		.replace(/(?<=[БВГДЖЗКЛМНПРСТФХЦЧШЩ])Е/g, "ЬЕ")
		.replace(/(?<=[БВГДЖЗКЛМНПРСТФХЦЧШЩбвгджзклмнпрстфхцчшщ])э/g, "е")
		.replace(/(?<=[БВГДЖЗКЛМНПРСТФХЦЧШЩ])Э/g, "Е")
		
		.replace(/ä/g, "а")
		.replace(/ë/g, "э")
		.replace(/ö/g, "о")
		.replace(/ü/g, "у")
		.replace(/Ä/g, "А")
		.replace(/Ë/g, "Э")
		.replace(/Ö/g, "О")
		.replace(/Ü/g, "У")
		
		.replace(/(?<=[АЕЁИЙОУЫЭЮЯЪЬаеёийоуыэюяъь])ь/g, "й")
		.replace(/(?<=[АЕЁИЙОУЫЭЮЯЪЬ])Ь/g, "Й")
		
		.replace(/ьъ/g, "ь")
		.replace(/ЬЪ/g, "Ь");
}

function cyrest() {
	document.transcription.text1.value = document.transcription.text1.value
		.replace(/(?<=\p{Script=Cyrl})a/ug, "а")
		.replace(/a(?=\p{Script=Cyrl})/ug, "а")
		.replace(/(?<=\p{Script=Cyrl})e/ug, "е")
		.replace(/e(?=\p{Script=Cyrl})/ug, "е")
		.replace(/(?<=\p{Script=Cyrl})ë/ug, "ё")
		.replace(/ë(?=\p{Script=Cyrl})/ug, "ё")
		.replace(/(?<=\p{Script=Cyrl})o/ug, "о")
		.replace(/o(?=\p{Script=Cyrl})/ug, "о")
		.replace(/(?<=\p{Script=Cyrl})p/ug, "р")
		.replace(/p(?=\p{Script=Cyrl})/ug, "р")
		.replace(/(?<=\p{Script=Cyrl})c/ug, "с")
		.replace(/c(?=\p{Script=Cyrl})/ug, "с")
		.replace(/(?<=\p{Script=Cyrl})y/ug, "у")
		.replace(/y(?=\p{Script=Cyrl})/ug, "у")
		.replace(/(?<=\p{Script=Cyrl})x/ug, "х")
		.replace(/x(?=\p{Script=Cyrl})/ug, "х")
		
		.replace(/(?<=\p{Script=Cyrl})A/ug, "А")
		.replace(/A(?=\p{Script=Cyrl})/ug, "А")
		.replace(/(?<=\p{Script=Cyrl})B/ug, "В")
		.replace(/B(?=\p{Script=Cyrl})/ug, "В")
		.replace(/(?<=\p{Script=Cyrl})E/ug, "Е")
		.replace(/E(?=\p{Script=Cyrl})/ug, "Е")
		.replace(/(?<=\p{Script=Cyrl})Ë/ug, "Ё")
		.replace(/Ë(?=\p{Script=Cyrl})/ug, "Ё")
		.replace(/(?<=\p{Script=Cyrl})K/ug, "К")
		.replace(/K(?=\p{Script=Cyrl})/ug, "К")
		.replace(/(?<=\p{Script=Cyrl})M/ug, "М")
		.replace(/M(?=\p{Script=Cyrl})/ug, "М")
		.replace(/(?<=\p{Script=Cyrl})H/ug, "Н")
		.replace(/H(?=\p{Script=Cyrl})/ug, "Н")
		.replace(/(?<=\p{Script=Cyrl})O/ug, "О")
		.replace(/O(?=\p{Script=Cyrl})/ug, "О")
		.replace(/(?<=\p{Script=Cyrl})P/ug, "Р")
		.replace(/P(?=\p{Script=Cyrl})/ug, "Р")
		.replace(/(?<=\p{Script=Cyrl})C/ug, "С")
		.replace(/C(?=\p{Script=Cyrl})/ug, "С")
		.replace(/(?<=\p{Script=Cyrl})T/ug, "Т")
		.replace(/T(?=\p{Script=Cyrl})/ug, "Т")
		.replace(/(?<=\p{Script=Cyrl})X/ug, "Х")
		.replace(/X(?=\p{Script=Cyrl})/ug, "Х");
	
	document.transcription.text4.value = document.transcription.text1.value
		
		.replace(/(?<=[БВГДЖЗКЛМНПРСТФХЦЧШЩ])Е/g, "Э")
		.replace(/(?<=[БВГДЖЗКЛМНПРСТФХЦЧШЩбвгджзклмнпрстфхцчшщ])е/g, "э")
		
		.replace(/(?<=\p{Lu}|\p{Lu}\p{Lu} )Я/ug, "ЙА")
		.replace(/Я(?=\p{Lu}| \p{Lu}\p{Lu})/ug, "ЙА")
		.replace(/Я/g, "Йа")
		.replace(/я/g, "йа")
		.replace(/(?<=\p{Lu}|\p{Lu}\p{Lu} )Е/ug, "ЙЭ")
		.replace(/Е(?=\p{Lu}| \p{Lu}\p{Lu})/ug, "ЙЭ")
		.replace(/Е/g, "Йэ")
		.replace(/е/g, "йэ")
		.replace(/(?<=\p{Lu}|\p{Lu}\p{Lu} )Ё/ug, "ЙО")
		.replace(/Ё(?=\p{Lu}| \p{Lu}\p{Lu})/ug, "ЙО")
		.replace(/Ё/g, "Йо")
		.replace(/ё/g, "йо")
		.replace(/(?<=\p{Lu}|\p{Lu}\p{Lu} )Ю/ug, "ЙУ")
		.replace(/Ю(?=\p{Lu}| \p{Lu}\p{Lu})/ug, "ЙУ")
		.replace(/Ю/g, "Йу")
		.replace(/ю/g, "йу")
		.replace(/(?<=\p{Lu}|\p{Lu}\p{Lu} )Щ/ug, "ШЧ")
		.replace(/Щ(?=\p{Lu}| \p{Lu}\p{Lu})/ug, "ШЧ")
		.replace(/Щ/g, "Шч")
		.replace(/щ/g, "шч")

		.replace(/а/g, "a")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/д/g, "d")
		.replace(/е/g, "je")
		.replace(/ж/g, "ž")
		.replace(/з/g, "z")
		.replace(/и/g, "i")
		.replace(/й/g, "j")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/о/g, "o")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ф/g, "f")
		.replace(/х/g, "h")
		.replace(/ц/g, "c")
		.replace(/ч/g, "č")
		.replace(/ш/g, "š")
		.replace(/щ/g, "ŝ")
		.replace(/ы/g, "y")
		.replace(/ь/g, "\u2019")
		.replace(/ъ/g, "\u201d")
		.replace(/э/g, "e")
		.replace(/ю/g, "ju")
		.replace(/ё/g, "jo")
		.replace(/я/g, "ja")

		.replace(/А/g, "A")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Д/g, "D")
		.replace(/Е/g, "Je")
		.replace(/Ж/g, "Ž")
		.replace(/З/g, "Z")
		.replace(/И/g, "I")
		.replace(/Й/g, "J")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/О/g, "O")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "H")
		.replace(/Ц/g, "C")
		.replace(/Ч/g, "Č")
		.replace(/Ш/g, "Š")
		.replace(/Щ/g, "Ŝ")
		.replace(/Ы/g, "Y")
		.replace(/Ь/g, "\u2019")
		.replace(/Ъ/g, "\u201d")
		.replace(/Э/g, "E")
		.replace(/Ю/g, "Ju")
		.replace(/Ё/g, "Jo")
		.replace(/Я/g, "Ja")

		.replace(/\u2039/g, "\u201a")
		.replace(/\u203a/g, "\u2018")
		.replace(/\u00ab/g, "\u201e")
		.replace(/\u00bb/g, "\u201c")
		.normalize('NFC');
}

function simpstr() {}

function strsimp() {}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}

function copy3() {
	navigator.clipboard.writeText(document.transcription.text3.value);
}

function copy4() {
	navigator.clipboard.writeText(document.transcription.text4.value);
}
