var car;
var fix;

function cyrlat() {
	car = document.transcription.text1.value;	
	fix = car;
	fix = fix.replace(/<</g, "«");
	fix = fix.replace(/>>/g, "»");
	fix = fix.replace(/(\p{Script=Cyrl})A/ug, "$1А");
	fix = fix.replace(/(\p{Script=Cyrl})C/ug, "$1С");
	fix = fix.replace(/(\p{Script=Cyrl})E/ug, "$1Е");
	fix = fix.replace(/(\p{Script=Cyrl})Ë/ug, "$1Ё");
	fix = fix.replace(/(\p{Script=Cyrl})O/ug, "$1О");
	fix = fix.replace(/(\p{Script=Cyrl})P/ug, "$1Р");
	fix = fix.replace(/(\p{Script=Cyrl})X/ug, "$1Х");
	fix = fix.replace(/(\p{Script=Cyrl})a/ug, "$1а");
	fix = fix.replace(/(\p{Script=Cyrl})c/ug, "$1с");
	fix = fix.replace(/(\p{Script=Cyrl})e/ug, "$1е");
	fix = fix.replace(/(\p{Script=Cyrl})ë/ug, "$1ё");
	fix = fix.replace(/(\p{Script=Cyrl})o/ug, "$1о");
	fix = fix.replace(/(\p{Script=Cyrl})p/ug, "$1р");
	fix = fix.replace(/(\p{Script=Cyrl})x/ug, "$1х");
	fix = fix.replace(/A(\p{Script=Cyrl})/ug, "А$1");
	fix = fix.replace(/C(\p{Script=Cyrl})/ug, "С$1");
	fix = fix.replace(/E(\p{Script=Cyrl})/ug, "Е$1");
	fix = fix.replace(/Ë(\p{Script=Cyrl})/ug, "Ё$1");
	fix = fix.replace(/O(\p{Script=Cyrl})/ug, "О$1");
	fix = fix.replace(/P(\p{Script=Cyrl})/ug, "Р$1");
	fix = fix.replace(/X(\p{Script=Cyrl})/ug, "Х$1");
	fix = fix.replace(/a(\p{Script=Cyrl})/ug, "а$1");
	fix = fix.replace(/c(\p{Script=Cyrl})/ug, "с$1");
	fix = fix.replace(/e(\p{Script=Cyrl})/ug, "е$1");
	fix = fix.replace(/ë(\p{Script=Cyrl})/ug, "ё$1");
	fix = fix.replace(/o(\p{Script=Cyrl})/ug, "о$1");
	fix = fix.replace(/p(\p{Script=Cyrl})/ug, "р$1");
	fix = fix.replace(/x(\p{Script=Cyrl})/ug, "х$1");
	document.transcription.text1.value = fix;
	car = car.replace(/([ЪЬ])([АОУ])/g, "$1\u2019$2");
	car = car.replace(/([ЪЬъь])([аоу])/g, "$1\u2019$2");
	car = car.replace(/ЪЕ/g, "ЙÈ");
	car = car.replace(/([Ъъ])е/g, "йè");
	car = car.replace(/([ЬЪ])Э/g, "$1\u2019Э");
	car = car.replace(/([ЬЪьъ])э/g, "$1\u2019э");

	car = car.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])Я/g, "$1Ä");
	car = car.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])я/g, "$1ä");
	car = car.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])Э/g, "$1È");
	car = car.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])э/g, "$1è");
	car = car.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])Е/g, "$1E");
	car = car.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])е/g, "$1e");
	car = car.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])Ё/g, "$1Ö");
	car = car.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])ё/g, "$1ö");
	car = car.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])Ю/g, "$1Ü");
	car = car.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])ю/g, "$1ü");

	car = car.replace(/(\p{Uppercase})Я/ug, "$1ЙА");
	car = car.replace(/(\p{Uppercase})(\p{Uppercase}) Я/ug, "$1$2 ЙА");
	car = car.replace(/Я (\p{Uppercase})(\p{Uppercase})/ug, "ЙА $1$2");
	car = car.replace(/Я(\p{Uppercase})/ug, "ЙА$1");
	car = car.replace(/Я/g, "Йа");
	car = car.replace(/я/g, "йа");
	car = car.replace(/(\p{Uppercase})Е/ug, "$1ЙЭ");
	car = car.replace(/(\p{Uppercase})(\p{Uppercase}) Е/ug, "$1$2 ЙЭ");
	car = car.replace(/Е (\p{Uppercase})(\p{Uppercase})/ug, "ЙЭ $1$2");
	car = car.replace(/Е(\p{Uppercase})/ug, "ЙЭ$1");
	car = car.replace(/Е/g, "Йэ");
	car = car.replace(/е/g, "йэ");
	car = car.replace(/(\p{Uppercase})Ё/ug, "$1ЙО");
	car = car.replace(/(\p{Uppercase})(\p{Uppercase}) Ё/ug, "$1$2 ЙО");
	car = car.replace(/Ё (\p{Uppercase})(\p{Uppercase})/ug, "ЙО $1$2");
	car = car.replace(/Ё(\p{Uppercase})/ug, "ЙО$1");
	car = car.replace(/Ё/g, "Йо");
	car = car.replace(/ё/g, "йо");
	car = car.replace(/(\p{Uppercase})Ю/ug, "$1ЙУ");
	car = car.replace(/(\p{Uppercase})(\p{Uppercase}) Ю/ug, "$1$2 ЙУ");
	car = car.replace(/Ю (\p{Uppercase})(\p{Uppercase})/ug, "ЙУ $1$2");
	car = car.replace(/Ю(\p{Uppercase})/ug, "ЙУ$1");
	car = car.replace(/Ю/g, "Йу");
	car = car.replace(/ю/g, "йу");

	car = car.replace(/а/g, "a");
	car = car.replace(/б/g, "b");
	car = car.replace(/в/g, "v");
	car = car.replace(/г/g, "g");
	car = car.replace(/д/g, "d");
	car = car.replace(/е/g, "je");
	car = car.replace(/ж/g, "ž");
	car = car.replace(/з/g, "z");
	car = car.replace(/и/g, "i");
	car = car.replace(/й/g, "j");
	car = car.replace(/к/g, "k");
	car = car.replace(/л/g, "l");
	car = car.replace(/м/g, "m");
	car = car.replace(/н/g, "n");
	car = car.replace(/о/g, "o");
	car = car.replace(/п/g, "p");
	car = car.replace(/р/g, "r");
	car = car.replace(/с/g, "s");
	car = car.replace(/т/g, "t");
	car = car.replace(/у/g, "u");
	car = car.replace(/ф/g, "f");
	car = car.replace(/х/g, "h");
	car = car.replace(/ц/g, "c");
	car = car.replace(/ч/g, "č");
	car = car.replace(/ш/g, "š");
	car = car.replace(/щ/g, "ś");
	car = car.replace(/ы/g, "y");
	car = car.replace(/ь/g, "j");
	car = car.replace(/ъ/g, "");
	car = car.replace(/э/g, "e");
	car = car.replace(/ю/g, "ju");
	car = car.replace(/ё/g, "jo");
	car = car.replace(/я/g, "ja");

	car = car.replace(/А/g, "A");
	car = car.replace(/Б/g, "B");
	car = car.replace(/В/g, "V");
	car = car.replace(/Г/g, "G");
	car = car.replace(/Д/g, "D");
	car = car.replace(/Е/g, "Je");
	car = car.replace(/Ж/g, "Ž");
	car = car.replace(/З/g, "Z");
	car = car.replace(/И/g, "I");
	car = car.replace(/Й/g, "J");
	car = car.replace(/К/g, "K");
	car = car.replace(/Л/g, "L");
	car = car.replace(/М/g, "M");
	car = car.replace(/Н/g, "N");
	car = car.replace(/О/g, "O");
	car = car.replace(/П/g, "P");
	car = car.replace(/Р/g, "R");
	car = car.replace(/С/g, "S");
	car = car.replace(/Т/g, "T");
	car = car.replace(/У/g, "U");
	car = car.replace(/Ф/g, "F");
	car = car.replace(/Х/g, "H");
	car = car.replace(/Ц/g, "C");
	car = car.replace(/Ч/g, "Č");
	car = car.replace(/Ш/g, "Š");
	car = car.replace(/Щ/g, "Ś");
	car = car.replace(/Ы/g, "Y");
	car = car.replace(/Ь/g, "J");
	car = car.replace(/Ъ/g, "");
	car = car.replace(/Э/g, "E");
	car = car.replace(/Ю/g, "Ju");
	car = car.replace(/Ё/g, "Jo");
	car = car.replace(/Я/g, "Ja");
	document.transcription.text2.value = car;
}

function copy1() {
	textRange = document.transcription.text1.createTextRange();
	textRange.execCommand("Copy");
	textRange = "";
}

function copy2() {
	textRange = document.transcription.text2.createTextRange();
	textRange.execCommand("Copy");
	textRange = "";
}
