function cyrlat() {
	document.transcription.text2.value = document.transcription.text1.value
		.replace(/(Ь|Ъ|ь|ъ)(е|и|о)/g, "$1й$2")
		.replace(/(Ь|Ъ)(Е|И|О)/g, "$1Й$2")

		.replace(/а/g, "a")
		.replace(/ә/g, "ä")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/ғ/g, "ğ")
		.replace(/д/g, "d")
		.replace(/е/g, "e")
		.replace(/ё/g, "yo")
		.replace(/ж/g, "j")
		.replace(/з/g, "z")
		.replace(/и/g, "i")
		.replace(/й/g, "y")
		.replace(/к/g, "k")
		.replace(/қ/g, "q")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/ң/g, "ñ")
		.replace(/о/g, "o")
		.replace(/ө/g, "ö")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ү/g, "ü")
		.replace(/ў/g, "w")
		.replace(/ф/g, "f")
		.replace(/х/g, "x")
		.replace(/ҳ/g, "h")
		.replace(/ц/g, "c")
		.replace(/ч/g, "ç")
		.replace(/ш/g, "ş")
		.replace(/щ/g, "ş")
		.replace(/ъ/g, "")
		.replace(/ы/g, "ı")
		.replace(/ь/g, "")
		.replace(/э/g, "e")
		.replace(/ю/g, "yu")
		.replace(/я/g, "ya")
		.replace(/А/g, "A")
		.replace(/Ә/g, "Ä")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Ғ/g, "Ğ")
		.replace(/Д/g, "D")
		.replace(/Е/g, "E")
		.replace(/Ё/g, "Yo")
		.replace(/Ж/g, "J")
		.replace(/З/g, "Z")
		.replace(/И/g, "İ")
		.replace(/Й/g, "Y")
		.replace(/К/g, "K")
		.replace(/Қ/g, "Q")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/Ң/g, "Ñ")
		.replace(/О/g, "O")
		.replace(/Ө/g, "Ö")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ү/g, "Ü")
		.replace(/Ў/g, "W")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "X")
		.replace(/Ҳ/g, "H")
		.replace(/Ц/g, "C")
		.replace(/Ч/g, "Ç")
		.replace(/Ш/g, "Ş")
		.replace(/Щ/g, "Ş")
		.replace(/Ъ/g, "")
		.replace(/Ы/g, "I")
		.replace(/Ь/g, "")
		.replace(/Э/g, "E")
		.replace(/Ю/g, "Yu")
		.replace(/Я/g, "Ya")
		.replace(/«/g, "\u201c")
		.replace(/»/g, "\u201d");
}

function latcyr() {
	document.transcription.text2.value = document.transcription.text2.value
		.replace(/í/g, "ı");

	document.transcription.text1.value = document.transcription.text2.value
		.replace(/A/g, "А")
		.replace(/(Á|Ä)/g, "Ә")
		.replace(/B/g, "Б")
		.replace(/V/g, "В")
		.replace(/G/g, "Г")
		.replace(/(Ǵ|Ğ)/g, "Ғ")
		.replace(/D/g, "Д")
		.replace(/E/g, "Е")
		.replace(/J/g, "Ж")
		.replace(/Z/g, "З");

	if (/Ä|ä|Ç|ç|Ğ|ğ|İ|Ñ|ñ|Ö|ö|Ş|ş|Ü|ü/.test(document.transcription.text2.value)) {
		document.transcription.text1.value = document.transcription.text1.value
			.replace(/I/g, "Ы");
	}

	document.transcription.text1.value = document.transcription.text1.value
		.replace(/(I|İ)/g, "И")
		.replace(/Y/g, "Й")
		.replace(/K/g, "К")
		.replace(/Q/g, "Қ")
		.replace(/L/g, "Л")
		.replace(/M/g, "М")
		.replace(/N/g, "Н")
		.replace(/(Ń|Ñ)/g, "Ң")
		.replace(/O/g, "О")
		.replace(/(Ó|Ö)/g, "Ө")
		.replace(/P/g, "П")
		.replace(/R/g, "Р")
		.replace(/S/g, "С")
		.replace(/T/g, "Т")
		.replace(/U/g, "У")
		.replace(/W/g, "Ў")
		.replace(/(Ú|Ü)/g, "Ү")
		.replace(/F/g, "Ф")
		.replace(/H/g, "Ҳ")
		.replace(/X/g, "Х")
		.replace(/C/g, "Ц")
		.replace(/Ç/g, "Ч")
		.replace(/Ş/g, "Ш")
		.replace(/Í/g, "Ы")
		.replace(/a/g, "а")
		.replace(/(á|ä)/g, "ә")
		.replace(/b/g, "б")
		.replace(/v/g, "в")
		.replace(/g/g, "г")
		.replace(/(ǵ|ğ)/g, "ғ")
		.replace(/d/g, "д")
		.replace(/j/g, "ж")
		.replace(/z/g, "з")
		.replace(/i/g, "и")
		.replace(/y/g, "й")
		.replace(/k/g, "к")
		.replace(/q/g, "қ")
		.replace(/l/g, "л")
		.replace(/m/g, "м")
		.replace(/n/g, "н")
		.replace(/(ń|ñ)/g, "ң")
		.replace(/o/g, "о")
		.replace(/ó/g, "ө")
		.replace(/p/g, "п")
		.replace(/r/g, "р")
		.replace(/s/g, "с")
		.replace(/t/g, "т")
		.replace(/u/g, "у")
		.replace(/w/g, "ў")
		.replace(/(ú|ü)/g, "ү")
		.replace(/f/g, "ф")
		.replace(/h/g, "ҳ")
		.replace(/x/g, "х")
		.replace(/c/g, "ц")
		.replace(/ç/g, "ч")
		.replace(/ş/g, "ш")
		.replace(/i/g, "и")
		.replace(/(ı|í)/g, "ы")
		.replace(/Й(А|а)/g, "Я")
		.replace(/Й(У|у)/g, "Ю")
		.replace(/йа/g, "я")
		.replace(/йу/g, "ю");

	if (/Ä|ä|Ç|ç|Ğ|ğ|İ|Ñ|ñ|Ö|ö|Ş|ş|Ü|ü/.test(document.transcription.text2.value) == false || /Á|á|Ǵ|ǵ|Í|Ń|ń|Ó|ó|Ú|ú/.test(document.transcription.text2.value)) {
		document.transcription.text1.value = document.transcription.text1.value
			.replace(/цҳ/g, "ч")
			.replace(/Ц(Ҳ|ҳ)/g, "Ч")
			.replace(/сҳ/g, "ш")
			.replace(/С(Ҳ|ҳ)/g, "Ш");
	}
	document.transcription.text1.value = document.transcription.text1.value
		.replace(/\u201c/g, "«")
		.replace(/\u201d/g, "»");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}
