function cyrlat() {
	document.transcription.text2.value = document.transcription.text1.value
		.replace(/(А|Е|Ё|И|О|Ө|У|Ү|Ы|Ю|Я|Э)Ц/g, "$1ТС")
		.replace(/(а|е|ё|и|о|ө|у|ү|ы|ю|я|э)Ц/g, "$1Тс")
		.replace(/(а|е|ё|и|о|ө|у|ү|ы|ю|я|э)ц/g, "$1тс")
		.replace(/Ц/g, "С")
		.replace(/ц/g, "с")

		.replace(/(А|Е|Ё|И|О|Ө|У|Ү|Ы|Ю|Я|Э)Щ(А|Е|Ё|И|О|Ө|У|Ү|Ы|Ю|Я|Э)/g, "$1ШШ$2")
		.replace(/(А|Е|Ё|И|О|Ө|У|Ү|Ы|Ю|Я|Э)щ(а|е|ё|и|о|ө|у|ү|ы|ю|я|э)/g, "$1Шш$2")
		.replace(/(а|е|ё|и|о|ө|у|ү|ы|ю|я|э)щ(а|е|ё|и|о|ө|у|ү|ы|ю|я|э)/g, "$1шш$2")
		.replace(/щ/g, "ш")
		.replace(/Щ/g, "Ш")

		.replace(/(Б|В|Г|Д|Ж|З|К|Л|М|Н|Ң|П|Р|С|Т|Ф|Х|Ч|Ш)Я/g, "$1ЬА")
		.replace(/(б|в|г|д|ж|з|к|л|м|н|ң|п|р|с|т|ф|х|ч|ш)Я/g, "$1ьА")
		.replace(/(Б|В|Г|Д|Ж|З|К|Л|М|Н|Ң|П|Р|С|Т|Ф|Х|Ч|Ш|б|в|г|д|ж|з|к|л|м|н|ң|п|р|с|т|ф|х|ч|ш)я/g, "$1ьа")
		.replace(/(Б|В|Г|Д|Ж|З|К|Л|М|Н|Ң|П|Р|С|Т|Ф|Х|Ч|Ш|б|в|г|д|ж|з|к|л|м|н|ң|п|р|с|т|ф|х|ч|ш)Ю/g, "$1Ү")
		.replace(/(Б|В|Г|Д|Ж|З|К|Л|М|Н|Ң|П|Р|С|Т|Ф|Х|Ч|Ш|б|в|г|д|ж|з|к|л|м|н|ң|п|р|с|т|ф|х|ч|ш)ю/g, "$1ү")
		.replace(/(Б|В|Г|Д|Ж|З|Й|К|Л|М|Н|Ң|П|Р|С|Т|Ф|Х|Ч|Ш|б|в|г|д|ж|з|й|к|л|м|н|ң|п|р|с|т|ф|х|ч|ш)Е/g, "$1Э")
		.replace(/(Б|В|Г|Д|Ж|З|Й|К|Л|М|Н|Ң|П|Р|С|Т|Ф|Х|Ч|Ш|б|в|г|д|ж|з|й|к|л|м|н|ң|п|р|с|т|ф|х|ч|ш)е/g, "$1э")
		.replace(/(Б|В|Г|Д|Ж|З|К|Л|М|Н|Ң|П|Р|С|Т|Ф|Х|Ч|Ш|б|в|г|д|ж|з|к|л|м|н|ң|п|р|с|т|ф|х|ч|ш)Ё/g, "$1Ө")
		.replace(/(Б|В|Г|Д|Ж|З|К|Л|М|Н|Ң|П|Р|С|Т|Ф|Х|Ч|Ш|б|в|г|д|ж|з|к|л|м|н|ң|п|р|с|т|ф|х|ч|ш)ё/g, "$1ө")

		.replace(/Ь(И|и)/g, "Й$1")
		.replace(/ьи/g, "йи")

		.replace(/(\p{Uppercase})(\p{Uppercase}) Я/ug, "$1$2 ЙА")
		.replace(/(\p{Uppercase})Я/ug, "$1ЙА")
		.replace(/Я (\p{Uppercase})(\p{Uppercase})/ug, "ЙА $1$2")
		.replace(/Я(\p{Uppercase})/ug, "ЙА$1")
		.replace(/Я/g, "Йа")
		.replace(/я/g, "йа")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Е/ug, "$1$2 ЙЭ")
		.replace(/(\p{Uppercase})Е/ug, "$1ЙЭ")
		.replace(/Е (\p{Uppercase})(\p{Uppercase})/ug, "ЙЭ $1$2")
		.replace(/Е(\p{Uppercase})/ug, "ЙЭ$1")
		.replace(/Е/g, "Йэ")
		.replace(/е/g, "йэ")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ё/ug, "$1$2 ЙО")
		.replace(/(\p{Uppercase})Ё/ug, "$1ЙО")
		.replace(/Ё (\p{Uppercase})(\p{Uppercase})/ug, "ЙО $1$2")
		.replace(/Ё(\p{Uppercase})/ug, "ЙО$1")
		.replace(/Ё/g, "Йо")
		.replace(/ё/g, "йо")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ю/ug, "$1$2 ЙУ")
		.replace(/(\p{Uppercase})Ю/ug, "$1ЙУ")
		.replace(/Ю (\p{Uppercase})(\p{Uppercase})/ug, "ЙУ $1$2")
		.replace(/Ю(\p{Uppercase})/ug, "ЙУ$1")
		.replace(/Ю/g, "Йу")
		.replace(/ю/g, "йу")

		.replace(/(Ъ|ъ)/g, "")

		.replace(/аа/g, "á")
		.replace(/ээ/g, "é")
		.replace(/ыы/g, "í")
		.replace(/оо/g, "ó")
		.replace(/өө/g, "ő")
		.replace(/уу/g, "ú")
		.replace(/үү/g, "ű")
		.replace(/А(А|а)/g, "Á")
		.replace(/Э(Э|э)/g, "É")
		.replace(/Ы(Ы|ы)/g, "Í")
		.replace(/О(О|о)/g, "Ó")
		.replace(/Ө(Ө|ө)/g, "Ő")
		.replace(/У(У|у)/g, "Ú")
		.replace(/Ү(Ү|ү)/g, "Ű")

		.replace(/а/g, "a")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/д/g, "d")
		.replace(/е/g, "e")
		.replace(/ж/g, "j")
		.replace(/з/g, "z")
		.replace(/и/g, "i")
		.replace(/й/g, "y")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/ң/g, "ñ")
		.replace(/о/g, "o")
		.replace(/ө/g, "ö")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ү/g, "ü")
		.replace(/ф/g, "f")
		.replace(/х/g, "h")
		.replace(/ч/g, "ç")
		.replace(/ш/g, "ş")
		.replace(/ь/g, "")
		.replace(/ы/g, "ı")
		.replace(/э/g, "e")

		.replace(/А/g, "A")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Д/g, "D")
		.replace(/Е/g, "E")
		.replace(/Ж/g, "J")
		.replace(/З/g, "Z")
		.replace(/И/g, "İ")
		.replace(/Й/g, "Y")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/Ң/g, "Ñ")
		.replace(/О/g, "O")
		.replace(/Ө/g, "Ö")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ү/g, "Ü")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "H")
		.replace(/Ч/g, "Ç")
		.replace(/Ш/g, "Ş")
		.replace(/Ь/g, "")
		.replace(/Ы/g, "I")
		.replace(/Э/g, "E")

		.replace(/\u2039/g, "\u2018")
		.replace(/\u203a/g, "\u2019")
		.replace(/\u00ab/g, "\u201c")
		.replace(/\u00bb/g, "\u201d")

		.normalize('NFC');
}

function latcyr() {
	const orig = document.transcription.text2.value;
	if (/[Jj]/.test(orig) == true) {
		document.transcription.text2.value = document.transcription.text2.value
		.replace(/C/g, "Ç")
		.replace(/c/g, "ç");
		}
		else {
		document.transcription.text2.value = document.transcription.text2.value
		.replace(/C/g, "J")
		.replace(/c/g, "j");
		}
		document.transcription.text2.value = document.transcription.text2.value
		.replace(/Ğ/g, "G")
		.replace(/ğ/g, "g")
		.replace(/Ŋ/g, "Ñ")
		.replace(/ŋ/g, "ñ")
		.replace(/Q/g, "K")
		.replace(/q/g, "k")
		.replace(/A[Aa]/g, "Á")
		.replace(/E[Ee]/g, "É")
		.replace(/İ[İi]/g, "Í")
		.replace(/O[Oo]/g, "Ó")
		.replace(/Ö[Öö]/g, "Ő")
		.replace(/U[Uu]/g, "Ú")
		.replace(/Ü[Üü]/g, "Ű")
		.replace(/aa/g, "á")
		.replace(/ee/g, "é")
		.replace(/ii/g, "í")
		.replace(/oo/g, "ó")
		.replace(/öö/g, "ő")
		.replace(/uu/g, "ú")
		.replace(/üü/g, "ű")
		
	document.transcription.text1.value = document.transcription.text2.value
		.replace(/(\p{Uppercase})(\p{Uppercase}) Á/ug, "$1$2 АА")
		.replace(/(\p{Uppercase})Á/ug, "$1АА")
		.replace(/Á (\p{Uppercase})(\p{Uppercase})/ug, "АА $1$2")
		.replace(/Á(\p{Uppercase})/ug, "АА$1")
		.replace(/Á/g, "Аа")
		.replace(/á/g, "аа")
		.replace(/(\p{Uppercase})(\p{Uppercase}) É/ug, "$1$2 ЭЭ")
		.replace(/(\p{Uppercase})É/ug, "$1ЭЭ")
		.replace(/É (\p{Uppercase})(\p{Uppercase})/ug, "ЭЭ $1$2")
		.replace(/É(\p{Uppercase})/ug, "ЭЭ$1")
		.replace(/É/g, "Ээ")
		.replace(/é/g, "ээ")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Í/ug, "$1$2 ИИ")
		.replace(/(\p{Uppercase})Í/ug, "$1ИИ")
		.replace(/Í (\p{Uppercase})(\p{Uppercase})/ug, "ИИ $1$2")
		.replace(/Í(\p{Uppercase})/ug, "ИИ$1")
		.replace(/Í/g, "Ии")
		.replace(/í/g, "ии")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ó/ug, "$1$2 ОО")
		.replace(/(\p{Uppercase})Ó/ug, "$1ОО")
		.replace(/Ó (\p{Uppercase})(\p{Uppercase})/ug, "ОО $1$2")
		.replace(/Ó(\p{Uppercase})/ug, "ОО$1")
		.replace(/Ó/g, "Оо")
		.replace(/ó/g, "оо")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ő/ug, "$1$2 ӨӨ")
		.replace(/(\p{Uppercase})Ő/ug, "$1ӨӨ")
		.replace(/Ő (\p{Uppercase})(\p{Uppercase})/ug, "ӨӨ $1$2")
		.replace(/Ő(\p{Uppercase})/ug, "ӨӨ$1")
		.replace(/Ő/g, "Өө")
		.replace(/ő/g, "өө")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ú/ug, "$1$2 УУ")
		.replace(/(\p{Uppercase})Ú/ug, "$1УУ")
		.replace(/Ú (\p{Uppercase})(\p{Uppercase})/ug, "УУ $1$2")
		.replace(/Ú(\p{Uppercase})/ug, "УУ$1")
		.replace(/Ú/g, "Уу")
		.replace(/ú/g, "уу")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ű/ug, "$1$2 ҮҮ")
		.replace(/(\p{Uppercase})Ű/ug, "$1ҮҮ")
		.replace(/Ű (\p{Uppercase})(\p{Uppercase})/ug, "ҮҮ $1$2")
		.replace(/Ű(\p{Uppercase})/ug, "ҮҮ$1")
		.replace(/Ű/g, "Үү")
		.replace(/ű/g, "үү")
	
		.replace(/a/g, "а")
		.replace(/b/g, "б")
		.replace(/ç/g, "ч")
		.replace(/d/g, "д")
		.replace(/e/g, "э")
		.replace(/f/g, "ф")
		.replace(/g/g, "г")
		.replace(/h/g, "х")
		.replace(/i/g, "и")
		.replace(/j/g, "ж")
		.replace(/k/g, "к")
		.replace(/l/g, "л")
		.replace(/m/g, "м")
		.replace(/n/g, "н")
		.replace(/ñ/g, "ң")
		.replace(/o/g, "о")
		.replace(/ö/g, "ө")
		.replace(/p/g, "п")
		.replace(/r/g, "р")
		.replace(/s/g, "с")
		.replace(/ş/g, "ш")
		.replace(/t/g, "т")
		.replace(/u/g, "у")
		.replace(/ü/g, "ү")
		.replace(/v/g, "в")
		.replace(/ı/g, "ы")
		.replace(/y/g, "й")
		.replace(/z/g, "з")
		.replace(/A/g, "А")
		.replace(/B/g, "Б")
		.replace(/Ç/g, "Ч")
		.replace(/D/g, "Д")
		.replace(/E/g, "Э")
		.replace(/F/g, "Ф")
		.replace(/G/g, "Г")
		.replace(/H/g, "Х")
		.replace(/İ/g, "И")
		.replace(/J/g, "Ж")
		.replace(/K/g, "К")
		.replace(/L/g, "Л")
		.replace(/M/g, "М")
		.replace(/N/g, "Н")
		.replace(/Ñ/g, "Ң")
		.replace(/O/g, "О")
		.replace(/Ö/g, "Ө")
		.replace(/P/g, "П")
		.replace(/R/g, "Р")
		.replace(/S/g, "С")
		.replace(/Ş/g, "Ш")
		.replace(/T/g, "Т")
		.replace(/U/g, "У")
		.replace(/Ü/g, "Ү")
		.replace(/V/g, "В")
		.replace(/I/g, "Ы")
		.replace(/Y/g, "Й")
		.replace(/Z/g, "З")

		.replace(/йа/g, "я")
		.replace(/йэ/g, "е")
		.replace(/йу/g, "ю")
		.replace(/Й([Аа])/g, "Я")
		.replace(/Й([Ээ])/g, "Е")
		.replace(/Й([Уу])/g, "Ю")

		.replace(/([БЦЧДФГХЖКЛМНҢПРСШТВЗбцчдфгхжклмнңпрсштвз])е/g, "$1ье")
		.replace(/([БЦЧДФГХЖКЛМНҢПРСШТВЗ])Е/g, "$1ЬЕ")
		.replace(/([БЦЧДФГХЖКЛМНҢПРСШТВЗбцчдфгхжклмнңпрсштвз])э/g, "$1е")
		.replace(/([БЦЧДФГХЖКЛМНҢПРСШТВЗ])Э/g, "$1Е")
		
		.replace(/йье/g, "ййе")
		.replace(/ЙЬЕ/g, "ЙЙЕ")

		.replace(/\u201c/g, "\u00ab")
		.replace(/\u201d/g, "\u00bb");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}
