function cyrlat() {
	document.transcription.text2.value = document.transcription.text1.value
		.replace(/(А|Е|Ё|И|О|Ө|У|Ү|Ы|Ю|Я|Э)Ц/g, "$1ТС")
		.replace(/(а|е|ё|и|о|ө|у|ү|ы|ю|я|э)Ц/g, "$1Тс")
		.replace(/(а|е|ё|и|о|ө|у|ү|ы|ю|я|э)ц/g, "$1тс")
		.replace(/Ц/g, "С")
		.replace(/ц/g, "с")

		.replace(/(А|Е|Ё|И|О|Ө|У|Ү|Ы|Ю|Я|Э)Щ(А|Е|Ё|И|О|Ө|У|Ү|Ы|Ю|Я|Э)/g, "$1ШШ$2")
		.replace(/(А|Е|Ё|И|О|Ө|У|Ү|Ы|Ю|Я|Э)щ(а|е|ё|и|о|ө|у|ү|ы|ю|я|э)/g, "$1Шш$2")
		.replace(/(а|е|ё|и|о|ө|у|ү|ы|ю|я|э)щ(а|е|ё|и|о|ө|у|ү|ы|ю|я|э)/g, "$1шш$2")
		.replace(/щ/g, "ш")
		.replace(/Щ/g, "Ш")

		.replace(/(Б|В|Г|Д|Ж|З|К|Л|М|Н|Ң|П|Р|С|Т|Ф|Х|Ч|Ш)Я/g, "$1ЬА")
		.replace(/(б|в|г|д|ж|з|к|л|м|н|ң|п|р|с|т|ф|х|ч|ш)Я/g, "$1ьА")
		.replace(/(Б|В|Г|Д|Ж|З|К|Л|М|Н|Ң|П|Р|С|Т|Ф|Х|Ч|Ш|б|в|г|д|ж|з|к|л|м|н|ң|п|р|с|т|ф|х|ч|ш)я/g, "$1ьа")
		.replace(/(Б|В|Г|Д|Ж|З|К|Л|М|Н|Ң|П|Р|С|Т|Ф|Х|Ч|Ш|б|в|г|д|ж|з|к|л|м|н|ң|п|р|с|т|ф|х|ч|ш)Ю/g, "$1Ү")
		.replace(/(Б|В|Г|Д|Ж|З|К|Л|М|Н|Ң|П|Р|С|Т|Ф|Х|Ч|Ш|б|в|г|д|ж|з|к|л|м|н|ң|п|р|с|т|ф|х|ч|ш)ю/g, "$1ү")
		.replace(/(Б|В|Г|Д|Ж|З|Й|К|Л|М|Н|Ң|П|Р|С|Т|Ф|Х|Ч|Ш|б|в|г|д|ж|з|й|к|л|м|н|ң|п|р|с|т|ф|х|ч|ш)Е/g, "$1Э")
		.replace(/(Б|В|Г|Д|Ж|З|Й|К|Л|М|Н|Ң|П|Р|С|Т|Ф|Х|Ч|Ш|б|в|г|д|ж|з|й|к|л|м|н|ң|п|р|с|т|ф|х|ч|ш)е/g, "$1э")
		.replace(/(Б|В|Г|Д|Ж|З|К|Л|М|Н|Ң|П|Р|С|Т|Ф|Х|Ч|Ш|б|в|г|д|ж|з|к|л|м|н|ң|п|р|с|т|ф|х|ч|ш)Ё/g, "$1Ө")
		.replace(/(Б|В|Г|Д|Ж|З|К|Л|М|Н|Ң|П|Р|С|Т|Ф|Х|Ч|Ш|б|в|г|д|ж|з|к|л|м|н|ң|п|р|с|т|ф|х|ч|ш)ё/g, "$1ө")

		.replace(/Ь(И|и)/g, "Й$1")
		.replace(/ьи/g, "йи")

		.replace(/(\p{Uppercase})(\p{Uppercase}) Я/ug, "$1$2 ЙА")
		.replace(/(\p{Uppercase})Я/ug, "$1ЙА")
		.replace(/Я (\p{Uppercase})(\p{Uppercase})/ug, "ЙА $1$2")
		.replace(/Я(\p{Uppercase})/ug, "ЙА$1")
		.replace(/Я/g, "Йа")
		.replace(/я/g, "йа")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Е/ug, "$1$2 ЙЭ")
		.replace(/(\p{Uppercase})Е/ug, "$1ЙЭ")
		.replace(/Е (\p{Uppercase})(\p{Uppercase})/ug, "ЙЭ $1$2")
		.replace(/Е(\p{Uppercase})/ug, "ЙЭ$1")
		.replace(/Е/g, "Йэ")
		.replace(/е/g, "йэ")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ё/ug, "$1$2 ЙО")
		.replace(/(\p{Uppercase})Ё/ug, "$1ЙО")
		.replace(/Ё (\p{Uppercase})(\p{Uppercase})/ug, "ЙО $1$2")
		.replace(/Ё(\p{Uppercase})/ug, "ЙО$1")
		.replace(/Ё/g, "Йо")
		.replace(/ё/g, "йо")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ю/ug, "$1$2 ЙУ")
		.replace(/(\p{Uppercase})Ю/ug, "$1ЙУ")
		.replace(/Ю (\p{Uppercase})(\p{Uppercase})/ug, "ЙУ $1$2")
		.replace(/Ю(\p{Uppercase})/ug, "ЙУ$1")
		.replace(/Ю/g, "Йу")
		.replace(/ю/g, "йу")

		.replace(/(Ъ|ъ)/g, "")

		.replace(/аа/g, "á")
		.replace(/ээ/g, "é")
		.replace(/ыы/g, "í")
		.replace(/оо/g, "ó")
		.replace(/өө/g, "ő")
		.replace(/уу/g, "ú")
		.replace(/үү/g, "ű")
		.replace(/А(А|а)/g, "Á")
		.replace(/Э(Э|э)/g, "É")
		.replace(/Ы(Ы|ы)/g, "Í")
		.replace(/О(О|о)/g, "Ó")
		.replace(/Ө(Ө|ө)/g, "Ő")
		.replace(/У(У|у)/g, "Ú")
		.replace(/Ү(Ү|ү)/g, "Ű")

		.replace(/а/g, "a")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/д/g, "d")
		.replace(/е/g, "e")
		.replace(/ж/g, "j")
		.replace(/з/g, "z")
		.replace(/и/g, "i")
		.replace(/й/g, "y")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/ң/g, "ñ")
		.replace(/о/g, "o")
		.replace(/ө/g, "ö")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ү/g, "ü")
		.replace(/ф/g, "f")
		.replace(/х/g, "h")
		.replace(/ч/g, "ç")
		.replace(/ш/g, "ş")
		.replace(/ь/g, "")
		.replace(/ы/g, "ı")
		.replace(/э/g, "e")

		.replace(/А/g, "A")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Д/g, "D")
		.replace(/Е/g, "E")
		.replace(/Ж/g, "J")
		.replace(/З/g, "Z")
		.replace(/И/g, "İ")
		.replace(/Й/g, "Y")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/Ң/g, "Ñ")
		.replace(/О/g, "O")
		.replace(/Ө/g, "Ö")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ү/g, "Ü")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "H")
		.replace(/Ч/g, "Ç")
		.replace(/Ш/g, "Ş")
		.replace(/Ь/g, "")
		.replace(/Ы/g, "I")
		.replace(/Э/g, "E")

		.replace(/\u2039/g, "\u2018")
		.replace(/\u203a/g, "\u2019")
		.replace(/\u00ab/g, "\u201c")
		.replace(/\u00bb/g, "\u201d")

		.normalize('NFC');
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}