function cyrlat() {
	document.transcription.text1.value = document.transcription.text1.value
		.replace(/<</g, "«")
		.replace(/>>/g, "»");

	document.transcription.text2.value = document.transcription.text1.value
		.replace(/Ъ/g, "ъ")

		.replace(/(Б|В|Г|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)Е/g, "$1ЬE")
		.replace(/(Б|В|Г|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)е/g, "$1ьe")
		.replace(/(Б|В|Г|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)Э/g, "$1E")
		.replace(/(Б|В|Г|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)э/g, "$1e")
		.replace(/(Б|В|Г|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)И/g, "$1ЬI")
		.replace(/(Б|В|Г|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)и/g, "$1ьi")
		.replace(/(Б|В|Г|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)Ы/g, "$1I")
		.replace(/(Б|В|Г|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)ы/g, "$1i")

		.replace(/(Б|В|Г|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)Я/g, "$1ЬA")
		.replace(/(Б|В|Г|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)я/g, "$1ьa")
		.replace(/(Б|В|Г|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)Ё/g, "$1ЬO")
		.replace(/(Б|В|Г|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)ё/g, "$1ьo")
		.replace(/(Б|В|Г|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)Ю/g, "$1ЬU")
		.replace(/(Б|В|Г|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)ю/g, "$1ьu")

		.replace(/гь/g, "ǵ")
		.replace(/зь/g, "ź")
		.replace(/ль/g, "l")
		.replace(/мь/g, "ḿ")
		.replace(/нь/g, "ń")
		.replace(/пь/g, "ṕ")
		.replace(/рь/g, "ŕ")
		.replace(/сь/g, "ś")
		.replace(/ць/g, "ć")
		.replace(/Г(Ь|ь)/g, "Ǵ")
		.replace(/З(Ь|ь)/g, "Ź")
		.replace(/Л(Ь|ь)/g, "L")
		.replace(/М(Ь|ь)/g, "Ḿ")
		.replace(/Н(Ь|ь)/g, "Ń")
		.replace(/П(Ь|ь)/g, "Ṕ")
		.replace(/Р(Ь|ь)/g, "Ŕ")
		.replace(/С(Ь|ь)/g, "Ś")
		.replace(/Ц(Ь|ь)/g, "Ć")

		.replace(/а/g, "a")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/д/g, "d")
		.replace(/е/g, "je")
		.replace(/ж/g, "ž")
		.replace(/з/g, "z")
		.replace(/и/g, "i")
		.replace(/й/g, "j")
		.replace(/к/g, "k")
		.replace(/л/g, "ł")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/о/g, "o")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ф/g, "f")
		.replace(/х/g, "h")
		.replace(/ц/g, "c")
		.replace(/ч/g, "č")
		.replace(/ш/g, "š")
		.replace(/щ/g, "ș")
		.replace(/ъ/g, "\u02bc")
		.replace(/ы/g, "ï")
		.replace(/ь/g, "y")
		.replace(/э/g, "e")
		.replace(/ю/g, "ju")
		.replace(/ё/g, "jo")
		.replace(/я/g, "ja")

		.replace(/А/g, "A")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Д/g, "D")
		.replace(/Е/g, "Je")
		.replace(/Ж/g, "Ž")
		.replace(/З/g, "Z")
		.replace(/И/g, "I")
		.replace(/Й/g, "J")
		.replace(/К/g, "K")
		.replace(/Л/g, "Ł")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/О/g, "O")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "H")
		.replace(/Ц/g, "C")
		.replace(/Ч/g, "Č")
		.replace(/Ш/g, "Š")
		.replace(/Щ/g, "Ș")
		.replace(/Ы/g, "Ï")
		.replace(/Ь/g, "Y")
		.replace(/Э/g, "E")
		.replace(/Ю/g, "Ju")
		.replace(/Ё/g, "Jo")
		.replace(/Я/g, "Ja")

		.replace(/ǵ\u02bc/g, "g")
		.replace(/ź\u02bc/g, "z")
		.replace(/l\u02bc/g, "ł")
		.replace(/ḿ\u02bc/g, "m")
		.replace(/ń\u02bc/g, "n")
		.replace(/ṕ\u02bc/g, "p")
		.replace(/ŕ\u02bc/g, "r")
		.replace(/ś\u02bc/g, "s")
		.replace(/ć\u02bc/g, "c")
		.replace(/y\u02bc/g, "")
		.replace(/Ǵ\u02bc/g, "G")
		.replace(/Ź\u02bc/g, "Z")
		.replace(/L\u02bc/g, "Ł")
		.replace(/Ḿ\u02bc/g, "M")
		.replace(/Ń\u02bc/g, "N")
		.replace(/Ṕ\u02bc/g, "P")
		.replace(/Ŕ\u02bc/g, "R")
		.replace(/Ś\u02bc/g, "S")
		.replace(/Y\u02bc/g, "");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}