function leftright() {
	document.transcription.text2.value = document.transcription.text1.value
		.replace(/Щ/g, "Ш")
		.replace(/щ/g, "ш")
		.replace(/Ц/g, "С")
		.replace(/ц/g, "с")

		.replace(/([БВГДЖҖЗКЛМНҢПРСТФХЦЧШЩ])Е/g, "$1Э")
		.replace(/([БВГДЖҖЗКЛМНҢПРСТФХЦЧШЩбвгджҗзклмнңпрстфхцчшщ])е/g, "$1э")
		.replace(/(\p{Lu})Я/ug, "$1ЙА")
		.replace(/(\p{Lu})(\p{Lu}) Я/ug, "$1$2 ЙА")
		.replace(/Я (\p{Lu})(\p{Lu})/ug, "ЙА $1$2")
		.replace(/Я(\p{Lu})/ug, "ЙА$1")
		.replace(/Я/g, "Йа")
		.replace(/я/g, "йа")
		.replace(/(\p{Lu})Е/ug, "$1ЙЭ")
		.replace(/(\p{Lu})(\p{Lu}) Е/ug, "$1$2 ЙЭ")
		.replace(/Е (\p{Lu})(\p{Lu})/ug, "ЙЭ $1$2")
		.replace(/Е(\p{Lu})/ug, "ЙЭ$1")
		.replace(/Е/g, "Йэ")
		.replace(/е/g, "йэ")
		.replace(/(\p{Lu})Ё/ug, "$1ЙО")
		.replace(/(\p{Lu})(\p{Lu}) Ё/ug, "$1$2 ЙО")
		.replace(/Ё (\p{Lu})(\p{Lu})/ug, "ЙО $1$2")
		.replace(/Ё(\p{Lu})/ug, "ЙО$1")
		.replace(/Ё/g, "Йо")
		.replace(/ё/g, "йо")
		.replace(/(\p{Lu})Ю/ug, "$1ЙУ")
		.replace(/(\p{Lu})(\p{Lu}) Ю/ug, "$1$2 ЙУ")
		.replace(/Ю (\p{Lu})(\p{Lu})/ug, "ЙУ $1$2")
		.replace(/Ю(\p{Lu})/ug, "ЙУ$1")
		.replace(/Ю/g, "Йу")
		.replace(/ю/g, "йу")

		.replace(/а/g, "a")
		.replace(/ә/g, "ä")
		.replace(/б/g, "b")
		.replace(/в/g, "w")
		.replace(/г/g, "g")
		.replace(/д/g, "d")
		.replace(/ж/g, "ž")
		.replace(/җ/g, "j")
		.replace(/з/g, "z")
		.replace(/и/g, "i")
		.replace(/й/g, "ý")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/ң/g, "ň")
		.replace(/о/g, "o")
		.replace(/ө/g, "ö")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ү/g, "ü")
		.replace(/ф/g, "f")
		.replace(/х/g, "h")
		.replace(/ч/g, "ç")
		.replace(/ш/g, "ş")
		.replace(/ъ/g, "")
		.replace(/ы/g, "y")
		.replace(/ь/g, "")
		.replace(/э/g, "e")
		.replace(/А/g, "A")
		.replace(/Ә/g, "Ä")
		.replace(/Б/g, "B")
		.replace(/В/g, "W")
		.replace(/Г/g, "G")
		.replace(/Д/g, "D")
		.replace(/Ж/g, "Ž")
		.replace(/Җ/g, "J")
		.replace(/З/g, "Z")
		.replace(/И/g, "I")
		.replace(/Й/g, "Ý")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/Ң/g, "Ň")
		.replace(/О/g, "O")
		.replace(/Ө/g, "Ö")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ү/g, "Ü")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "H")
		.replace(/Ч/g, "Ç")
		.replace(/Ш/g, "Ş")
		.replace(/Ъ/g, "")
		.replace(/Ы/g, "Y")
		.replace(/Ь/g, "")
		.replace(/Э/g, "E")

		.replace(/\u2039/g, "\u2018")
		.replace(/\u203a/g, "\u2019")
		.replace(/\u00ab/g, "\u201c")
		.replace(/\u00bb/g, "\u201d");
}

function rightleft() {
	document.transcription.text2.value = document.transcription.text2.value
		.replace(/C/g, "Ç")
		.replace(/c/g, "ç")
		.replace(/V/g, "W")
		.replace(/v/g, "w")
		.replace(/Ñ/g, "Ň")
		.replace(/ñ/g, "ň")
		.replace(/Ÿ/g, "Ý")
		.replace(/ÿ/g, "ý")
		.replace(/İ/g, "I")
		.replace(/(\p{Script=Latn})[¥Ұ]/ug, "$1Ý")
		.replace(/[¥Ұ](\p{Script=Latn})/ug, "Ý$1")
		.replace(/(\p{Script=Latn})\$/ug, "$1Ş")
		.replace(/\$(\p{Script=Latn})/ug, "Ş$1")
		.replace(/(\p{Script=Latn})¢/ug, "$1ş")
		.replace(/¢(\p{Script=Latn})/ug, "ş$1")
		.replace(/(\p{Script=Latn})£/ug, "$1Ž")
		.replace(/£(\p{Script=Latn})/ug, "Ž$1")
		.replace(/(\p{Script=Latn})ſ/ug, "$1ž")
		.replace(/ſ(\p{Script=Latn})/ug, "ž$1");

	document.transcription.text1.value = document.transcription.text2.value
		.replace(/a/g, "а")
		.replace(/b/g, "б")
		.replace(/ç/g, "ч")
		.replace(/d/g, "д")
		.replace(/e/g, "э")
		.replace(/ä/g, "ә")
		.replace(/f/g, "ф")
		.replace(/g/g, "г")
		.replace(/h/g, "х")
		.replace(/i/g, "и")
		.replace(/j/g, "җ")
		.replace(/ž/g, "ж")
		.replace(/k/g, "к")
		.replace(/l/g, "л")
		.replace(/m/g, "м")
		.replace(/n/g, "н")
		.replace(/ň/g, "ң")
		.replace(/o/g, "о")
		.replace(/ö/g, "ө")
		.replace(/p/g, "п")
		.replace(/r/g, "р")
		.replace(/s/g, "с")
		.replace(/ş/g, "ш")
		.replace(/t/g, "т")
		.replace(/u/g, "у")
		.replace(/ü/g, "ү")
		.replace(/w/g, "в")
		.replace(/y/g, "ы")
		.replace(/ý/g, "й")
		.replace(/z/g, "з")
		.replace(/A/g, "А")
		.replace(/B/g, "Б")
		.replace(/Ç/g, "Ч")
		.replace(/D/g, "Д")
		.replace(/E/g, "Э")
		.replace(/Ä/g, "Ә")
		.replace(/F/g, "Ф")
		.replace(/G/g, "Г")
		.replace(/H/g, "Х")
		.replace(/I/g, "И")
		.replace(/J/g, "Җ")
		.replace(/Ž/g, "Ж")
		.replace(/K/g, "К")
		.replace(/L/g, "Л")
		.replace(/M/g, "М")
		.replace(/N/g, "Н")
		.replace(/Ň/g, "Ң")
		.replace(/O/g, "О")
		.replace(/Ö/g, "Ө")
		.replace(/P/g, "П")
		.replace(/R/g, "Р")
		.replace(/S/g, "С")
		.replace(/Ş/g, "Ш")
		.replace(/T/g, "Т")
		.replace(/U/g, "У")
		.replace(/Ü/g, "Ү")
		.replace(/W/g, "В")
		.replace(/Y/g, "Ы")
		.replace(/Ý/g, "Й")
		.replace(/Z/g, "З")

		.replace(/йа/g, "я")
		.replace(/йэ/g, "е")
		.replace(/йо/g, "ё")
		.replace(/йу/g, "ю")
		.replace(/Й([Аа])/g, "Я")
		.replace(/Й([Ээ])/g, "Е")
		.replace(/Й([Оо])/g, "Ё")
		.replace(/Й([Уу])/g, "Ю")

		.replace(/([БВГДЖҖЗКЛМНҢПРСТУФХЦЧШЩбвгджҗзйклмнңпрстуфхцчшщ])е/g, "$1ье")
		.replace(/([БВГДЖҖЗКЛМНҢПРСТУФХЦЧШЩ])Е/g, "$1ЬЕ")
		.replace(/([БВГДЖҖЗКЛМНҢПРСТУФХЦЧШЩбвгджҗзйклмнңпрстуфхцчшщ])э/g, "$1е")
		.replace(/([БВГДЖҖЗКЛМНҢПРСТУФХЦЧШЩ])Э/g, "$1Е")

		.replace(/йье/g, "ййе")
		.replace(/ЙЬЕ/g, "ЙЙЕ")

		.replace(/\u2018/g, "\u2039")
		.replace(/\u2019/g, "\u203a")
		.replace(/\u201c/g, "\u00ab")
		.replace(/\u201d/g, "\u00bb");
}

function leftbottom() {}

function rightbottom() {
	document.transcription.text3.value = (() => {
		let s = document.transcription.text2.value
			.replace(/J/g, "C")
			.replace(/Ž/g, "J")
			.replace(/Ň/g, "Ñ")
			.replace(/I/g, "İ")
			.replace(/Y/g, "I")
			.replace(/Ý/g, "Y")
			.replace(/W/g, "V")
			.replace(/j/g, "c")
			.replace(/ž/g, "j")
			.replace(/ň/g, "ñ")
			.replace(/y/g, "ı")
			.replace(/ý/g, "y")
			.replace(/w/g, "v")
			.replace(/([AÄBCÇDEFGHIİJLMNÑOÖPRSŞTUÜVYZ])G/g, "$1Ğ")
			.replace(/([AÄBCÇDEFGHIİJLMNÑOÖPRSŞTUÜVYZaäbcçdefghıijlmnñoöprsştuüvyz])g/g, "$1ğ");

		let prev;
		do {
			prev = s;
			s = s
				// Assimilation rules
				.replace(/ç([dls])/g, "ş$1")
				.replace(/[çş]c/g, "şş")
				.replace(/[ÇŞ]c/g, "Şş")
				.replace(/Gb/g, "Gv")
				.replace(/gb/g, "gv")
				.replace(/Kb/g, "Kv")
				.replace(/kb/g, "kv")
				.replace(/([Ll])d/g, "$1l")
				.replace(/([Nn])d/g, "$1n")
				.replace(/([Ss])[dt]/g, "$1s")
				.replace(/Tç/g, "Çç")
				.replace(/tç/g, "çç")
				.replace(/[TZ]s/g, "ss")
				.replace(/[tz]s/g, "ss")
				.replace(/Zd/g, "Zz")
				.replace(/Ç([DLSdls])/g, "Ş$1")
				.replace(/[ÇŞ]C/g, "ŞŞ")
				.replace(/GB/g, "GV")
				.replace(/KB/g, "KV")
				.replace(/LD/g, "LL")
				.replace(/ND/g, "NN")
				.replace(/S[DT]/g, "SS")
				.replace(/TÇ/g, "ÇÇ")
				.replace(/[TZ]S/g, "SS")
				.replace(/ZD/g, "ZZ")

				.replace(/(?<=[ÇFHKPSŞT])B/g, "P")
				.replace(/(?<=[ÇFHKPSŞT])D/g, "T")
				.replace(/(?<=[ÇFHKPSŞT])G/g, "K")
				.replace(/(?<=[ÇFHKPSŞT])C/g, "Ç")
				.replace(/(?<=[ÇFHKPSŞTçfhkpsşt])b/g, "p")
				.replace(/(?<=[ÇFHKPSŞTçfhkpsşt])d/g, "t")
				.replace(/(?<=[ÇFHKPSŞTçfhkpsşt])g/g, "k")
				.replace(/(?<=[ÇFHKPSŞTçfhkpsşt])c/g, "ç")

				// Harmony rules
				.replace(/([OU](?:-|[^\p{P}\p{Z}\r\nAÄEIİOÖUÜaäeiıioöuü])*)A/gu, "$1O")
				.replace(/([ÖÜ](?:-|[^\p{P}\p{Z}\r\nAÄEIİOÖUÜaäeiıioöuü])*)E/gu, "$1Ö")
				.replace(/([ÖÜ](?:-|[^\p{P}\p{Z}\r\nAÄEIİOÖUÜaäeiıioöuü])*)İ/gu, "$1Ü")
				.replace(/([OU](?:-|[^\p{P}\p{Z}\r\nAÄEIİOÖUÜaäeiıioöuü])*)I/gu, "$1U")
				.replace(/([OUou](?:-|[^\p{P}\p{Z}\r\nAÄEIİOÖUÜaäeiıioöuü])*)a/gu, "$1o")
				.replace(/([ÖÜöü](?:-|[^\p{P}\p{Z}\r\nAÄEIİOÖUÜaäeiıioöuü])*)e/gu, "$1ö")
				.replace(/([ÖÜöü](?:-|[^\p{P}\p{Z}\r\nAÄEIİOÖUÜaäeiıioöuü])*)i/gu, "$1ü")
				.replace(/([OUou](?:-|[^\p{P}\p{Z}\r\nAÄEIİOÖUÜaäeiıioöuü])*)ı/gu, "$1u");
		} while (s !== prev);

		return s;
	})();
}

function bottomleft() {}

function bottomright() {
	document.transcription.text3.value = document.transcription.text3.value
		.replace(/Ə/g, "Ä")
		.replace(/ə/g, "ä");

	document.transcription.text2.value = document.transcription.text3.value
		.replace(/V/g, "W")
		.replace(/Y/g, "Ý")
		.replace(/I/g, "Y")
		.replace(/İ/g, "I")
		.replace(/Ñ/g, "Ň")
		.replace(/J/g, "Ž")
		.replace(/C/g, "J")
		.replace(/Ğ/g, "G")
		.replace(/v/g, "w")
		.replace(/y/g, "ý")
		.replace(/ı/g, "y")
		.replace(/ñ/g, "ň")
		.replace(/j/g, "ž")
		.replace(/c/g, "j")
		.replace(/ğ/g, "g");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}

function copy3() {
	navigator.clipboard.writeText(document.transcription.text3.value);
}