function cyrlat() {
	document.transcription.text1.value = document.transcription.text1.value
		.replace(/ə/g, "ә")
		.replace(/Ə/g, "Ә");

	document.transcription.text2.value = document.transcription.text1.value

		.replace(/Х([0-9])/g, "X$1")
		.replace(/х([0-9])/g, "x$1")
		.replace(/([0-9])Х/g, "$1X")
		.replace(/([0-9])х/g, "$1x")

		//Я, Ё, Ю 
		.replace(/(\p{Lu})(\p{Lu}) Я/ug, "$1$2 ЬА")
		.replace(/(\p{Lu})Я/ug, "$1ЬА")
		.replace(/Я (\p{Lu})(\p{Lu})/ug, "ЬА $1$2")
		.replace(/Я(\p{Lu})/ug, "ЬА$1")
		.replace(/Я/g, "Ьа")
		.replace(/я/g, "ьа")
		.replace(/(\p{Lu})(\p{Lu}) Ё/ug, "$1$2 ЬО")
		.replace(/(\p{Lu})Ё/ug, "$1ЬО")
		.replace(/Ё (\p{Lu})(\p{Lu})/ug, "ЬО $1$2")
		.replace(/Ё(\p{Lu})/ug, "ЬО$1")
		.replace(/Ё/g, "Ьо")
		.replace(/ё/g, "ьо")
		.replace(/(\p{Lu})(\p{Lu}) Ю/ug, "$1$2 ЬУ")
		.replace(/(\p{Lu})Ю/ug, "$1ЬУ")
		.replace(/Ю (\p{Lu})(\p{Lu})/ug, "ЬУ $1$2")
		.replace(/Ю(\p{Lu})/ug, "ЬУ$1")
		.replace(/Ю/g, "Ьу")
		.replace(/ю/g, "ьу")

		//Ц
		.replace(/([АӘЕИОӨУҰҮЫІЭаәеиоөуұүыіэ])Ц/g, "$1ТС")
		.replace(/([АӘЕИОӨУҰҮЫІЭаәеиоөуұүыіэ])ц/g, "$1тс")
		.replace(/Ц/g, "С")
		.replace(/ц/g, "с")

		//Ч
		.replace(/([АӘЕИОӨУҰҮЫІЭаәеиоөуұүыіэ])Ч/g, "$1ТШ")
		.replace(/([АӘЕИОӨУҰҮЫІЭаәеиоөуұүыіэ])ч/g, "$1тш")
		.replace(/Ч/g, "Ш")
		.replace(/ч/g, "ш")

		//Щ
		.replace(/([АӘЕИОӨУҰҮЫІЭаәеиоөуұүыіэ])щ([аәеиоөуұүыіэ])/g, "$1шш$2")
		.replace(/([АӘЕИОӨУҰҮЫІЭаәеиоөуұүыіэ])Щ([АӘЕИОӨУҰҮЫІЭ])/g, "$1ШШ$2")
		.replace(/щ/g, "ш")
		.replace(/Щ/g, "Ш")

		.replace(/Э/g, "Е")
		.replace(/э/g, "е")

		.replace(/Һ/g, "Х")
		.replace(/һ/g, "х")

		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХШ])ЬА/g, "$1Ә")
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХШ])([Ьь])а/g, "$1ә")
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХШбвгғджзйкқлмнңпрстфхш])ьа/g, "$1ә")
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХШ])ЬЫ/g, "$1І")
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХШ])([Ьь])ы/g, "$1і")
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХШбвгғджзйкқлмнңпрстфхш])ьы/g, "$1і")
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХШ])ЬО/g, "$1Ө")
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХШ])([Ьь])о/g, "$1ө")
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХШбвгғджзйкқлмнңпрстфхш])ьо/g, "$1ө")
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХШ])ЬУ/g, "$1Ү")
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХШ])([Ьь])у/g, "$1ү")
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХШбвгғджзйкқлмнңпрстфхш])ьу/g, "$1ү")

		//У
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХШЬЪ])У([АОҰЫ])/g, "$1ҰЎ$2")
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХШЬЪ])УУ/g, "$1УЎУ")
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХШЬЪ])У([ӘЕӨҮІ])/g, "$1ҮЎ$2")
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХШЬЪ])УИ/g, "$1УЎИ")
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХШЬЪбвгғджзйкқлмнңпрстфхшьъ])у([аоұы])/g, "$1ұў$2")
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХШЬЪбвгғджзйкқлмнңпрстфхшьъ])уу/g, "$1уўу")
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХШЬЪбвгғджзйкқлмнңпрстфхшьъ])у([әеөүі])/g, "$1үў$2")
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХШЬЪбвгғджзйкқлмнңпрстфхшьъ])уи/g, "$1уўи")
		.replace(/([АОУҰЫӘЕИӨУҮІ])У/g, "$1Ў")
		.replace(/([АОУҰЫӘЕИӨУҮІаоуұыәеиөуүі])у/g, "$1ў")
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХШЬЪ])У([БВГҒДЖЗЙКҚЛМНҢПРСТФХШ])/g, "$1Ұ$2")
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХШЬЪбвгғджзйкқлмнңпрстфхшьъ])у([бвгғджзйкқлмнңпрстфхш])/g, "$1ұ$2")
		.replace(/У([БВГҒДЖЗЙКҚЛМНҢПРСТФХШбвгғджзйкқлмнңпрстфхш])/g, "Ұ$1")
		.replace(/у([бвгғджзйкқлмнңпрстфхш])/g, "ұ$1")
		.replace(/([АЫ])([БВГҒДЖЗЙКҚЛМНҢПРСТФХШ]){1,3}У/g, "$1$2ЫЎ")
		.replace(/([ОҰ])([БВГҒДЖЗЙКҚЛМНҢПРСТФХШ]){1,3}У/g, "$1$2ҰЎ")
		.replace(/([АЫаы])([бвгғджзйкқлмнңпрстфхш]){1,3}у/g, "$1$2ыў")
		.replace(/([ОҰоұ])([бвгғджзйкқлмнңпрстфхш]){1,3}у/g, "$1$2ұў")
		.replace(/([ӘЕІ])([БВГҒДЖЗЙКҚЛМНҢПРСТФХШ]){1,3}У/g, "$1$2ІЎ")
		.replace(/([ӨҮ])([БВГҒДЖЗЙКҚЛМНҢПРСТФХШ]){1,3}У/g, "$1$2ҮЎ")
		.replace(/([ӘЕІәеі])([бвгғджзйкқлмнңпрстфхш]){1,3}у/g, "$1$2іў")
		.replace(/([ӨҮөү])([бвгғджзйкқлмнңпрстфхш]){1,3}у/g, "$1$2үў")
		.replace(/У/g, "Ў")
		.replace(/у/g, "ў")

		.replace(/Ь([АӘЕИОӨУҰҮЫІЭаәеиоөуұүыіэ])/g, "Й$1")
		.replace(/ь([аәеиоөуұүыіэ])/g, "й$1")
		.replace(/([Ьь])/g, "")

		.replace(/И([АОҰЫ])/g, "ЫЙ$1")
		.replace(/И([аоұы])/g, "Ый$1")
		.replace(/и([аоұы])/g, "ый$1")
		.replace(/И([ӘЕИӨҮІЭ])/g, "ІЙ$1")
		.replace(/И([әеиөүіэ])/g, "Ій$1")
		.replace(/и([әеиөүіэ])/g, "ій$1")

		.replace(/а/g, "a")
		.replace(/ә/g, "ä")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/ғ/g, "ğ")
		.replace(/д/g, "d")
		.replace(/е/g, "e")
		.replace(/ж/g, "j")
		.replace(/з/g, "z")
		.replace(/и/g, "i")
		.replace(/й/g, "y")
		.replace(/к/g, "k")
		.replace(/қ/g, "q")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/ң/g, "ń")
		.replace(/о/g, "o")
		.replace(/ө/g, "ö")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/ў/g, "w")
		.replace(/ұ/g, "u")
		.replace(/ү/g, "ü")
		.replace(/ф/g, "f")
		.replace(/х/g, "h")
		.replace(/ш/g, "c")
		.replace(/ъ/g, "")
		.replace(/ы/g, "ı")
		.replace(/і/g, "i")
		.replace(/э/g, "e")
		.replace(/А/g, "A")
		.replace(/Ә/g, "Ä")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Ғ/g, "Ğ")
		.replace(/Д/g, "D")
		.replace(/Е/g, "E")
		.replace(/Ж/g, "J")
		.replace(/З/g, "Z")
		.replace(/И/g, "İ")
		.replace(/Й/g, "Y")
		.replace(/К/g, "K")
		.replace(/Қ/g, "Q")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/Ң/g, "Ń")
		.replace(/О/g, "O")
		.replace(/Ө/g, "Ö")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/Ў/g, "W")
		.replace(/Ұ/g, "U")
		.replace(/Ү/g, "Ü")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "H")
		.replace(/Ш/g, "C")
		.replace(/Ъ/g, "")
		.replace(/Ы/g, "I")
		.replace(/І/g, "İ")

		.replace(/«/g, "\u201c")
		.replace(/»/g, "\u201d")

		.normalize('NFC');
}

function latcyr() {
	document.transcription.text1.value = document.transcription.text2.value
		.replace(/[Iİ]Y([AEIİÎOÖUÛÜ])/g, "Î$1")
		.replace(/[Iİ]y([aeıiîoöuûü])/g, "Î$1")
		.replace(/[ıi]y([aeıiîoöuûü])/g, "î$1")

		.replace(/[UÜ]W([AEIİÎOÖUÛÜ])/g, "Û$1")
		.replace(/[UÜ]w([aeıiîoöuûü])/g, "Û$1")
		.replace(/[uü]w([aeıiîoöuûü])/g, "û$1")

		.replace(/Y[Aa]/g, "Я")
		.replace(/ya/g, "я")
		.replace(/Y[Ûû]/g, "Ю")
		.replace(/yû/g, "ю")

		.replace(/a/g, "а")
		.replace(/ä/g, "ә")
		.replace(/b/g, "б")
		.replace(/d/g, "д")
		.replace(/e/g, "е")
		.replace(/f/g, "ф")
		.replace(/g/g, "г")
		.replace(/ğ/g, "ғ")
		.replace(/h/g, "х")
		.replace(/ı/g, "ы")
		.replace(/i/g, "і")
		.replace(/î/g, "и")
		.replace(/j/g, "ж")
		.replace(/k/g, "к")
		.replace(/l/g, "л")
		.replace(/m/g, "м")
		.replace(/n/g, "н")
		.replace(/ñ/g, "ң")
		.replace(/o/g, "о")
		.replace(/ö/g, "ө")
		.replace(/p/g, "п")
		.replace(/q/g, "қ")
		.replace(/r/g, "р")
		.replace(/s/g, "с")
		.replace(/ş/g, "ш")
		.replace(/t/g, "т")
		.replace(/u/g, "ұ")
		.replace(/û/g, "у")
		.replace(/ü/g, "ү")
		.replace(/v/g, "в")
		.replace(/w/g, "у")
		.replace(/y/g, "й")
		.replace(/z/g, "з")
		.replace(/A/g, "А")
		.replace(/Ä/g, "Ә")
		.replace(/B/g, "Б")
		.replace(/D/g, "Д")
		.replace(/E/g, "Е")
		.replace(/F/g, "Ф")
		.replace(/G/g, "Г")
		.replace(/Ğ/g, "Ғ")
		.replace(/H/g, "Х")
		.replace(/I/g, "Ы")
		.replace(/İ/g, "І")
		.replace(/Î/g, "И")
		.replace(/J/g, "Ж")
		.replace(/K/g, "К")
		.replace(/L/g, "Л")
		.replace(/M/g, "М")
		.replace(/N/g, "Н")
		.replace(/Ñ/g, "Ң")
		.replace(/O/g, "О")
		.replace(/Ö/g, "Ө")
		.replace(/P/g, "П")
		.replace(/Q/g, "Қ")
		.replace(/R/g, "Р")
		.replace(/S/g, "С")
		.replace(/Ş/g, "Ш")
		.replace(/T/g, "Т")
		.replace(/U/g, "Ұ")
		.replace(/Û/g, "У")
		.replace(/Ü/g, "Ү")
		.replace(/V/g, "В")
		.replace(/W/g, "У")
		.replace(/Y/g, "Й")
		.replace(/Z/g, "З");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}
