function latcyr() {

	document.transcription.text2.value = document.transcription.text2.value
		.replace(/´/g, "ʹ")
		.replace(/´´/g, "ʺ")
		.replace(/ʹ´/g, "ʺ")
		.replace(/`/g, "ʹ")
		.replace(/``/g, "ʺ")
		.replace(/ʹ`/g, "ʺ")
		.replace(/ʹʹ/g, "ʺ")
		.replace(/ǧ/g, "ğ")
		.replace(/Ǧ/g, "Ğ")
		.replace(/ī/g, "î")
		.replace(/Ī/g, "Î")
		.replace(/ş/g, "ș")
		.replace(/Ş/g, "Ș");

	document.transcription.text1.value = document.transcription.text2.value
		.replace(/ya/g, "я")
		.replace(/yo/g, "ё")
		.replace(/yû/g, "ю")
		.replace(/yw/g, "ю")
		.replace(/Ya/g, "Я")
		.replace(/Yo/g, "Ё")
		.replace(/Yû/g, "ю")
		.replace(/Yw/g, "Ю")
		.replace(/YA/g, "Я")
		.replace(/YO/g, "Ё")
		.replace(/YÛ/g, "Ю")
		.replace(/YW/g, "Ю")
		.replace(/a/g, "а")
		.replace(/ä/g, "ә")
		.replace(/b/g, "б")
		.replace(/v/g, "в")
		.replace(/g/g, "г")
		.replace(/ğ/g, "ғ")
		.replace(/d/g, "д")
		.replace(/e/g, "е")
		.replace(/j/g, "ж")
		.replace(/z/g, "з")
		.replace(/î/g, "и")
		.replace(/y/g, "й")
		.replace(/ý/g, "й")
		.replace(/k/g, "к")
		.replace(/q/g, "қ")
		.replace(/l/g, "л")
		.replace(/m/g, "м")
		.replace(/n/g, "н")
		.replace(/ņ/g, "ң")
		.replace(/o/g, "о")
		.replace(/ö/g, "ө")
		.replace(/p/g, "п")
		.replace(/r/g, "р")
		.replace(/s/g, "с")
		.replace(/t/g, "т")
		.replace(/û/g, "у")
		.replace(/w/g, "у")
		.replace(/u/g, "ұ")
		.replace(/ü/g, "ү")
		.replace(/f/g, "ф")
		.replace(/x/g, "х")
		.replace(/h/g, "һ")
		.replace(/ć/g, "ч")
		.replace(/c/g, "ц")
		.replace(/ș/g, "ш")
		.replace(/ś/g, "щ")
		.replace(/ʺ/g, "ъ")
		.replace(/ı/g, "ы")
		.replace(/i/g, "і")
		.replace(/ʹ/g, "ь")
		.replace(/ẹ/g, "э")
		.replace(/é/g, "э")
		.replace(/A/g, "А")
		.replace(/Ä/g, "Ә")
		.replace(/B/g, "Б")
		.replace(/V/g, "В")
		.replace(/G/g, "Г")
		.replace(/Ğ/g, "Ғ")
		.replace(/D/g, "Д")
		.replace(/E/g, "Е")
		.replace(/J/g, "Ж")
		.replace(/Z/g, "З")
		.replace(/Î/g, "И")
		.replace(/Y/g, "Й")
		.replace(/Ý/g, "Й")
		.replace(/K/g, "К")
		.replace(/Q/g, "Қ")
		.replace(/L/g, "Л")
		.replace(/M/g, "М")
		.replace(/N/g, "Н")
		.replace(/Ņ/g, "Ң")
		.replace(/O/g, "О")
		.replace(/Ö/g, "Ө")
		.replace(/P/g, "П")
		.replace(/R/g, "Р")
		.replace(/S/g, "С")
		.replace(/T/g, "Т")
		.replace(/Û/g, "У")
		.replace(/W/g, "У")
		.replace(/U/g, "Ұ")
		.replace(/Ü/g, "Ү")
		.replace(/F/g, "Ф")
		.replace(/X/g, "Х")
		.replace(/H/g, "Һ")
		.replace(/Ć/g, "Ч")
		.replace(/C/g, "Ц")
		.replace(/Ș/g, "Ш")
		.replace(/Ś/g, "Щ")
		.replace(/I/g, "Ы")
		.replace(/İ/g, "І")
		.replace(/É/g, "Э")
		.replace(/\u201c/g, "«")
		.replace(/\u201d/g, "»");
}

function cyrlat() {
	document.transcription.text1.value = document.transcription.text1.value
		.replace(/ə/g, "ә")
		.replace(/Ə/g, "Ә");

	document.transcription.text2.value = document.transcription.text1.value
		.replace(/Я(А|Ә|Б|В|Г|Ғ|Д|Е|Ё|Ж|З|И|Й|К|Қ|Л|М|Н|Ң|О|Ө|П|Р|С|Т|У|Ұ|Ү|Ф|Х|Һ|Ц|Ч|Ш|Щ|Ъ|Ы|І|Ь|Э|Я|Ю)/g, "ЙА$1")
		.replace(/Ё(А|Ә|Б|В|Г|Ғ|Д|Е|Ё|Ж|З|И|Й|К|Қ|Л|М|Н|Ң|О|Ө|П|Р|С|Т|У|Ұ|Ү|Ф|Х|Һ|Ц|Ч|Ш|Щ|Ъ|Ы|І|Ь|Э|Я|Ю)/g, "ЙО$1")
		.replace(/Ю(А|Ә|Б|В|Г|Ғ|Д|Е|Ё|Ж|З|И|Й|К|Қ|Л|М|Н|Ң|О|Ө|П|Р|С|Т|У|Ұ|Ү|Ф|Х|Һ|Ц|Ч|Ш|Щ|Ъ|Ы|І|Ь|Э|Я|Ю)/g, "ЙУ$1")
		.replace(/(А|Ә|Б|В|Г|Ғ|Д|Е|Ё|Ж|З|И|Й|К|Қ|Л|М|Н|Ң|О|Ө|П|Р|С|Т|У|Ұ|Ү|Ф|Х|Һ|Ц|Ч|Ш|Щ|Ъ|Ы|І|Ь|Э|Я|Ю)Я/g, "$1ЙА")
		.replace(/(А|Ә|Б|В|Г|Ғ|Д|Е|Ё|Ж|З|И|Й|К|Қ|Л|М|Н|Ң|О|Ө|П|Р|С|Т|У|Ұ|Ү|Ф|Х|Һ|Ц|Ч|Ш|Щ|Ъ|Ы|І|Ь|Э|Я|Ю)Ё/g, "$1ЙО")
		.replace(/(А|Ә|Б|В|Г|Ғ|Д|Е|Ё|Ж|З|И|Й|К|Қ|Л|М|Н|Ң|О|Ө|П|Р|С|Т|У|Ұ|Ү|Ф|Х|Һ|Ц|Ч|Ш|Щ|Ъ|Ы|І|Ь|Э|Я|Ю)Ю/g, "$1ЙУ")
		.replace(/я/g, "йа")
		.replace(/ё/g, "йо")
		.replace(/ю/g, "йу")
		.replace(/Я/g, "Йа")
		.replace(/Ё/g, "Йо")
		.replace(/Ю/g, "Йу")

		.replace(/уу/g, "ӯӯ")
		.replace(/Уу/g, "Ӯӯ")
		.replace(/УУ/g, "ӮӮ")

		.replace(/(Б|В|Г|Ғ|Д|Ж|З|И|Й|К|Қ|Л|М|Н|Ң|П|Р|С|Т|У|Ф|Х|Һ|Ч|Ш|Щ|Ъ|Ь|Ю|б|в|г|ғ|д|ж|з|и|й|к|қ|л|м|н|ң|п|р|с|т|у|ф|х|һ|ч|ш|щ|ъ|ь|ю)у/g, "$1ӯ")
		.replace(/(Б|В|Г|Ғ|Д|Ж|З|И|Й|К|Қ|Л|М|Н|Ң|П|Р|С|Т|У|Ф|Х|Һ|Ч|Ш|Щ|Ъ|Ь|Ю|б|в|г|ғ|д|ж|з|и|й|к|қ|л|м|н|ң|п|р|с|т|у|ф|х|һ|ч|ш|щ|ъ|ь|ю)У/g, "$1Ӯ")
		.replace(/у(Б|В|Г|Ғ|Д|Ж|З|Й|К|Қ|Л|М|Н|Ң|П|Р|С|Т|Ф|Х|Һ|Ч|Ш|Щ|Ъ|Ь|Ю|б|в|г|ғ|д|ж|з|й|к|қ|л|м|н|ң|п|р|с|т|ф|х|һ|ч|ш|щ|ъ|ь|ю)/g, "ӯ$1")
		.replace(/У(Б|В|Г|Ғ|Д|Ж|З|Й|К|Қ|Л|М|Н|Ң|П|Р|С|Т|Ф|Х|Һ|Ч|Ш|Щ|Ъ|Ь|Ю|б|в|г|ғ|д|ж|з|й|к|қ|л|м|н|ң|п|р|с|т|ф|х|һ|ч|ш|щ|ъ|ь|ю)/g, "Ӯ$1")
		.replace(/(А|Я|Е|Э|Ә|Ы|І|О|Ё|Ө|Ұ|Ү|а|я|е|э|ә|ы|і|о|ё|ө|ұ|ү)ӯ/g, "$1у")
		.replace(/(А|Я|Е|Э|Ә|Ы|І|О|Ё|Ө|Ұ|Ү|а|я|е|э|ә|ы|і|о|ё|ө|ұ|ү)Ӯ/g, "$1У")

		.replace(/а/g, "a")
		.replace(/ә/g, "ä")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/ғ/g, "ğ")
		.replace(/д/g, "d")
		.replace(/е/g, "e")
		.replace(/ж/g, "j")
		.replace(/з/g, "z")
		.replace(/и/g, "î")
		.replace(/й/g, "y")
		.replace(/к/g, "k")
		.replace(/қ/g, "q")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/ң/g, "ņ")
		.replace(/о/g, "o")
		.replace(/ө/g, "ö")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/ӯ/g, "û")
		.replace(/у/g, "w")
		.replace(/ұ/g, "u")
		.replace(/ү/g, "ü")
		.replace(/ф/g, "f")
		.replace(/х/g, "x")
		.replace(/һ/g, "h")
		.replace(/ц/g, "c")
		.replace(/ч/g, "ć")
		.replace(/ш/g, "ș")
		.replace(/щ/g, "ś")
		.replace(/ъ/g, "")
		.replace(/ы/g, "ı")
		.replace(/і/g, "i")
		.replace(/ь/g, "")
		.replace(/э/g, "é")
		.replace(/А/g, "A")
		.replace(/Ә/g, "Ä")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Ғ/g, "Ğ")
		.replace(/Д/g, "D")
		.replace(/Е/g, "E")
		.replace(/Ж/g, "J")
		.replace(/З/g, "Z")
		.replace(/И/g, "Î")
		.replace(/Й/g, "Y")
		.replace(/К/g, "K")
		.replace(/Қ/g, "Q")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/Ң/g, "Ņ")
		.replace(/О/g, "O")
		.replace(/Ө/g, "Ö")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/Ӯ/g, "Û")
		.replace(/У/g, "W")
		.replace(/Ұ/g, "U")
		.replace(/Ү/g, "Ü")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "X")
		.replace(/Һ/g, "H")
		.replace(/Ц/g, "C")
		.replace(/Ч/g, "Ć")
		.replace(/Ш/g, "Ș")
		.replace(/Щ/g, "Ś")
		.replace(/Ъ/g, "")
		.replace(/Ы/g, "I")
		.replace(/І/g, "İ")
		.replace(/Ь/g, "")
		.replace(/Э/g, "É")

		.replace(/«/g, "\u201c")
		.replace(/»/g, "\u201d");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}
