function cyrlat() {
	document.transcription.text2.value = document.transcription.text1.value
		.replace(/Щ/g, "Ш")
		.replace(/щ/g, "ш")
		.replace(/Ы/g, "И")
		.replace(/ы/g, "и")

		.replace(/([БВГҒДЖЗКҚЛМНПРСТФХҲЦЧШЩбвгғджзкқлмнпрстфхҳцчшщ])Е/g, "$1Э")
		.replace(/([БВГҒДЖЗКҚЛМНПРСТФХҲЦЧШЩбвгғджзкқлмнпрстфхҳцчшщ])е/g, "$1э")
		.replace(/(\p{Uppercase})Я/ug, "$1ЙА")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Я/ug, "$1$2 ЙА")
		.replace(/Я (\p{Uppercase})(\p{Uppercase})/ug, "ЙА $1$2")
		.replace(/Я(\p{Uppercase})/ug, "ЙА$1")
		.replace(/Я/g, "Йа")
		.replace(/я/g, "йа")
		.replace(/(\p{Uppercase})Е/ug, "$1ЙЭ")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Е/ug, "$1$2 ЙЭ")
		.replace(/Е (\p{Uppercase})(\p{Uppercase})/ug, "ЙЭ $1$2")
		.replace(/Е(\p{Uppercase})/ug, "ЙЭ$1")
		.replace(/Е/g, "Йэ")
		.replace(/е/g, "йэ")
		.replace(/(\p{Uppercase})Ё/ug, "$1ЙО")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ё/ug, "$1$2 ЙО")
		.replace(/Ё (\p{Uppercase})(\p{Uppercase})/ug, "ЙО $1$2")
		.replace(/Ё(\p{Uppercase})/ug, "ЙО$1")
		.replace(/Ё/g, "Йо")
		.replace(/ё/g, "йо")
		.replace(/(\p{Uppercase})Ю/ug, "$1ЙУ")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ю/ug, "$1$2 ЙУ")
		.replace(/Ю (\p{Uppercase})(\p{Uppercase})/ug, "ЙУ $1$2")
		.replace(/Ю(\p{Uppercase})/ug, "ЙУ$1")
		.replace(/Ю/g, "Йу")
		.replace(/ю/g, "йу")

		.replace(/([АЭИОУЎ])Ц([ЪЬ])?([АБВГҒДЖЗИЙКҚЛМНОПРСТУЎФХҲЦЧШЭ])/g, "$1ТС$2$3")
		.replace(/([АЭИОУЎаэиоуў])ц([ъь])?([абвгғджзийкқлмнопрстуўфхҳцчшэ])/g, "$1тс$2$3")
		.replace(/Ц/g, "С")
		.replace(/ц/g, "с")

		.replace(/СҲ/g, "СЪҲ")
		.replace(/([Сс])ҳ/g, "$1ъҳ")

		.replace(/Ў([Ъъ])/g, "Ў")
		.replace(/ўъ/g, "ў")

		.replace(/(\p{Uppercase})Ч/ug, "$1CH")
		.replace(/Ч (\p{Uppercase})(\p{Uppercase})/ug, "CH $1$2")
		.replace(/Ч(\p{Uppercase})/ug, "CH$1")
		.replace(/(\p{Uppercase})Ш/ug, "$1SH")
		.replace(/Ш (\p{Uppercase})(\p{Uppercase})/ug, "SH $1$2")
		.replace(/Ш(\p{Uppercase})/ug, "SH$1")

		.replace(/а/g, "a")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/ғ/g, "g\u2018")
		.replace(/д/g, "d")
		.replace(/ж/g, "j")
		.replace(/з/g, "z")
		.replace(/и/g, "i")
		.replace(/й/g, "y")
		.replace(/к/g, "k")
		.replace(/қ/g, "q")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/о/g, "o")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ў/g, "o\u2018")
		.replace(/ф/g, "f")
		.replace(/х/g, "x")
		.replace(/ҳ/g, "h")
		.replace(/ч/g, "ch")
		.replace(/ш/g, "sh")
		.replace(/ъ/g, "\u2019")
		.replace(/ь/g, "")
		.replace(/э/g, "e")
		.replace(/А/g, "A")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Ғ/g, "G\u2018")
		.replace(/Д/g, "D")
		.replace(/Ж/g, "J")
		.replace(/З/g, "Z")
		.replace(/И/g, "I")
		.replace(/Й/g, "Y")
		.replace(/К/g, "K")
		.replace(/Қ/g, "Q")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/О/g, "O")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ў/g, "O\u2018")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "X")
		.replace(/Ҳ/g, "H")
		.replace(/Ч/g, "Ch")
		.replace(/Ш/g, "Sh")
		.replace(/Ъ/g, "\u2019")
		.replace(/Ь/g, "")
		.replace(/Э/g, "E");
}

function latcyr() {
	document.transcription.text2.value = document.transcription.text2.value
		.replace(/['ˈ’‘ʻʼ´`ʿʹˊ׳′ʽߵ՚ߴ᾿ՙ῾‛ʾ՛ˋ]/g, "’")
		.replace(/([OoGg])’/g, "$1‘");

	document.transcription.text1.value = document.transcription.text2.value
		.replace(/(\u0027|\u2018|\u2019|\u02bb|\u02bc|\u00b4|\u0060)/g, "ъ")
		.replace(/a/g, "а")
		.replace(/b/g, "б")
		.replace(/c/g, "ц")
		.replace(/d/g, "д")
		.replace(/e/g, "э")
		.replace(/f/g, "ф")
		.replace(/g/g, "г")
		.replace(/h/g, "ҳ")
		.replace(/i/g, "и")
		.replace(/j/g, "ж")
		.replace(/k/g, "к")
		.replace(/l/g, "л")
		.replace(/m/g, "м")
		.replace(/n/g, "н")
		.replace(/o/g, "о")
		.replace(/p/g, "п")
		.replace(/q/g, "қ")
		.replace(/r/g, "р")
		.replace(/s/g, "с")
		.replace(/t/g, "т")
		.replace(/u/g, "у")
		.replace(/v/g, "в")
		.replace(/x/g, "х")
		.replace(/y/g, "й")
		.replace(/z/g, "з")
		.replace(/A/g, "А")
		.replace(/B/g, "Б")
		.replace(/C/g, "Ц")
		.replace(/D/g, "Д")
		.replace(/E/g, "Э")
		.replace(/F/g, "Ф")
		.replace(/G/g, "Г")
		.replace(/H/g, "Ҳ")
		.replace(/I/g, "И")
		.replace(/J/g, "Ж")
		.replace(/K/g, "К")
		.replace(/L/g, "Л")
		.replace(/M/g, "М")
		.replace(/N/g, "Н")
		.replace(/O/g, "О")
		.replace(/P/g, "П")
		.replace(/Q/g, "Қ")
		.replace(/R/g, "Р")
		.replace(/S/g, "С")
		.replace(/T/g, "Т")
		.replace(/U/g, "У")
		.replace(/V/g, "В")
		.replace(/X/g, "Х")
		.replace(/Y/g, "Й")
		.replace(/Z/g, "З")

		.replace(/цҳ/g, "ч")
		.replace(/сҳ/g, "ш")
		.replace(/Ц([Ҳҳ])/g, "Ч")
		.replace(/С([Ҳҳ])/g, "Ш")
		.replace(/С([Ҳҳ])/g, "Ш")
		.replace(/съҳ/g, "сҳ")
		.replace(/Съ([Ҳҳ])/g, "С$1")
		.replace(/гъ/g, "ғ")
		.replace(/Гъ/g, "Ғ")
		.replace(/оъ/g, "ў")
		.replace(/Оъ/g, "Ў")

		.replace(/йа/g, "я")
		.replace(/йо/g, "ё")
		.replace(/йу/g, "ю")
		.replace(/Й([Аа])/g, "Я")
		.replace(/Й([Оо])/g, "Ё")
		.replace(/Й([Уу])/g, "Ю")

		.replace(/ййэ/g, "ййе")
		.replace(/ЙЙЭ/g, "ЙЙЕ")

		.replace(/([БЦЧДФГҒХҲЖКҚЛМНПРСШТВЗбцчдфгғхҳжкқлмнпрсштвз])йэ/g, "$1ье")
		.replace(/([БЦЧДФГҒХҲЖКҚЛМНПРСШТВЗ])ЙЭ/g, "$1ЬЕ")
		.replace(/([БЦЧДФГҒХҲЖКҚЛМНПРСШТВЗбцчдфгғхҳжкқлмнпрсштвз])э/g, "$1е")
		.replace(/([БЦЧДФГҒХҲЖКҚЛМНПРСШТВЗ])Э/g, "$1Е")

		.replace(/йэ/g, "е")
		.replace(/Й(Э|э)/g, "Е")

		.replace(/лўбат/g, "лўъбат")
		.replace(/мўжаз/g, "мўъжаз")
		.replace(/мўжиза/g, "мўъжиза")
		.replace(/мўтабар/g, "мўътабар")
		.replace(/мўтад/g, "мўътад")
		.replace(/мўтазила/g, "мўътазила")
		.replace(/мўтариза/g, "мўътариза")
		.replace(/Лўбат/g, "Лўъбат")
		.replace(/Мўжаз/g, "Мўъжаз")
		.replace(/Мўжиза/g, "Мўъжиза")
		.replace(/Мўтабар/g, "Мўътабар")
		.replace(/Мўтад/g, "Мўътад")
		.replace(/Мўтазила/g, "Мўътазила")
		.replace(/Мўтариза/g, "Мўътариза")
		.replace(/ЛЎБАТ/g, "ЛЎЪБАТ")
		.replace(/МЎЖАЗ/g, "МЎЪЖАЗ")
		.replace(/МЎЖИЗА/g, "МЎЪЖИЗА")
		.replace(/МЎТАБАР/g, "МЎЪТАБАР")
		.replace(/МЎТАД/g, "МЎЪТАД")
		.replace(/МЎТАЗИЛА/g, "МЎЪТАЗИЛА")
		.replace(/МЎТАРИЗА/g, "МЎЪТАРИЗА")

		.replace(/(\p{Uppercase})ъ/ug, "$1Ъ")

		.replace(/\u201e/g, "\u00ab")
		.replace(/\u201c/g, "\u00bb");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}