function cyrlat() {
	document.transcription.text1.value = document.transcription.text1.value
		.replace(/(\p{Script=Cyrl})( )?Æ/ug, "$1$2Ӕ")
		.replace(/Æ( )?(\p{Script=Cyrl})/ug, "Ӕ$1$2")
		.replace(/(\p{Script=Cyrl})( )?æ/ug, "$1$2ӕ")
		.replace(/æ( )?(\p{Script=Cyrl})/ug, "ӕ$1$2");

	document.transcription.text2.value = document.transcription.text1.value
		.replace(/(А|Ӕ|Е|Ё|И|О|У|Ы|Ю|Я|Э)Щ(А|Ӕ|Е|Ё|И|О|У|Ы|Ю|Я|Э)/g, "$1СС$2")
		.replace(/(А|Ӕ|Е|Ё|И|О|У|Ы|Ю|Я|Э)щ(а|ӕ|е|ё|и|о|у|ы|ю|я|э)/g, "$1Сс$2")
		.replace(/(а|ӕ|е|ё|и|о|у|ы|ю|я|э)щ(а|ӕ|е|ё|и|о|у|ы|ю|я|э)/g, "$1сс$2")
		.replace(/щ/g, "с")
		.replace(/Щ/g, "С")
		.replace(/ш/g, "с")
		.replace(/Ш/g, "С")
		.replace(/ж/g, "з")
		.replace(/Ж/g, "З")
		.replace(/э/g, "е")
		.replace(/Э/g, "Е")

		.replace(/Ь(И|и)/g, "Й$1")
		.replace(/ьи/g, "йи")
		.replace(/Ь(О|о)/g, "Й$1")
		.replace(/ьо/g, "йо")

		.replace(/(\p{Uppercase})(\p{Uppercase}) Я/ug, "$1$2 ЙА")
		.replace(/(\p{Uppercase})Я/ug, "$1ЙА")
		.replace(/Я (\p{Uppercase})(\p{Uppercase})/ug, "ЙА $1$2")
		.replace(/Я(\p{Uppercase})/ug, "ЙА$1")
		.replace(/Я/g, "Йа")
		.replace(/я/g, "йа")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ё/ug, "$1$2 ЙО")
		.replace(/(\p{Uppercase})Ё/ug, "$1ЙО")
		.replace(/Ё (\p{Uppercase})(\p{Uppercase})/ug, "ЙО $1$2")
		.replace(/Ё(\p{Uppercase})/ug, "ЙО$1")
		.replace(/Ё/g, "Йо")
		.replace(/ё/g, "йо")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ю/ug, "$1$2 ЙУ")
		.replace(/(\p{Uppercase})Ю/ug, "$1ЙУ")
		.replace(/Ю (\p{Uppercase})(\p{Uppercase})/ug, "ЙУ $1$2")
		.replace(/Ю(\p{Uppercase})/ug, "ЙУ$1")
		.replace(/Ю/g, "Йу")
		.replace(/ю/g, "йу")

		.replace(/у(а|ӕ|е|и|о|у|ы)/g, "ў$1")
		.replace(/У(А|Ӕ|Е|И|О|У|Ы|а|ӕ|е|и|о|у|ы)/g, "Ў$1")
		.replace(/(А|Ӕ|Е|И|О|У|Ы|а|ӕ|е|и|о|у|ы)у/g, "$1ў")
		.replace(/(А|Ӕ|Е|И|О|У|Ы)У/g, "$1Ў")

		.replace(/(К|П|Т|Ц|Ч)ГЪ/g, "$1\u2019H")
		.replace(/(К|П|Т|Ц|Ч|к|п|т|ц|ч)гъ/g, "$1\u2019h")
		.replace(/Г(Ъ|ъ)/g, "H")
		.replace(/гъ/g, "h")
		.replace(/Х(Ъ|ъ)/g, "Q")
		.replace(/хъ/g, "q")
		.replace(/Д(Ж|ж)/g, "J")
		.replace(/дж/g, "j")
		.replace(/Д(З|з)/g, "Ź")
		.replace(/дз/g, "ź")
		.replace(/(К|П|Т|Ц|Ч)Ъ/g, "$1H")
		.replace(/(К|П|Т|Ц|Ч|к|п|т|ц|ч)ъ/g, "$1h")

		.replace(/а/g, "a")
		.replace(/ӕ/g, "ă")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/д/g, "d")
		.replace(/е/g, "e")
		.replace(/ж/g, "z")
		.replace(/з/g, "z")
		.replace(/и/g, "i")
		.replace(/й/g, "y")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/о/g, "o")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ў/g, "w")
		.replace(/ф/g, "f")
		.replace(/х/g, "x")
		.replace(/ц/g, "ś")
		.replace(/ч/g, "c")
		.replace(/ь/g, "")
		.replace(/ы/g, "ĕ")

		.replace(/А/g, "A")
		.replace(/Ӕ/g, "Ă")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Д/g, "D")
		.replace(/Е/g, "E")
		.replace(/Ж/g, "Z")
		.replace(/З/g, "Z")
		.replace(/И/g, "I")
		.replace(/Й/g, "Y")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/О/g, "O")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ў/g, "W")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "X")
		.replace(/Ц/g, "Ś")
		.replace(/Ч/g, "C")
		.replace(/Ь/g, "")
		.replace(/Ы/g, "Ĕ")

		.replace(/\u2039/g, "\u2018")
		.replace(/\u203a/g, "\u2019")
		.replace(/\u00ab/g, "\u201c")
		.replace(/\u00bb/g, "\u201d")

		.replace(/(Ъ|ъ)/g, "");
}

function latcyr() {}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}