
var translit;
var car;

function cyrlat () {
translit = document.transcription.text1.value;
car = document.transcription.text1.value;
car = car.replace(/æ/g, "ӕ");
car = car.replace(/Æ/g, "Ӕ");
translit = translit.replace(/æ/g, "ӕ");
translit = translit.replace(/Æ/g, "Ӕ");

translit = translit.replace(/уа/g, "ўа");
translit = translit.replace(/уӕ/g, "ўӕ");
translit = translit.replace(/уе/g, "ўе");
translit = translit.replace(/уё/g, "ўё");
translit = translit.replace(/уэ/g, "ўэ");
translit = translit.replace(/уы/g, "ўы");
translit = translit.replace(/уи/g, "ўи");
translit = translit.replace(/уо/g, "ўо");
translit = translit.replace(/уу/g, "ўу");
translit = translit.replace(/ау/g, "аў");
translit = translit.replace(/яу/g, "яў");
translit = translit.replace(/ӕу/g, "ӕў");
translit = translit.replace(/еу/g, "еў");
translit = translit.replace(/ёу/g, "ёў");
translit = translit.replace(/эу/g, "эў");
translit = translit.replace(/ыу/g, "ыў");
translit = translit.replace(/иу/g, "иў");
translit = translit.replace(/оу/g, "оў");
translit = translit.replace(/уу/g, "уў");
translit = translit.replace(/юу/g, "юў");
translit = translit.replace(/ўў/g, "уў");

translit = translit.replace(/Уа/g, "Ўа");
translit = translit.replace(/Уӕ/g, "Ўӕ");
translit = translit.replace(/Уе/g, "Ўе");
translit = translit.replace(/Уё/g, "Ўё");
translit = translit.replace(/Уэ/g, "Ўэ");
translit = translit.replace(/Уы/g, "Ўы");
translit = translit.replace(/Уи/g, "Ўи");
translit = translit.replace(/Уо/g, "Ўо");
translit = translit.replace(/Уу/g, "Ўу");
translit = translit.replace(/Ау/g, "Аў");
translit = translit.replace(/Яу/g, "Яў");
translit = translit.replace(/Ӕу/g, "Ӕў");
translit = translit.replace(/Еу/g, "Еў");
translit = translit.replace(/Ёу/g, "Ёў");
translit = translit.replace(/Эу/g, "Эў");
translit = translit.replace(/Ыу/g, "Ыў");
translit = translit.replace(/Иу/g, "Иў");
translit = translit.replace(/Оу/g, "Оў");
translit = translit.replace(/Уу/g, "Уў");
translit = translit.replace(/Юу/g, "Юў");
translit = translit.replace(/Ўў/g, "Уў");

translit = translit.replace(/УА/g, "ЎА");
translit = translit.replace(/УӔ/g, "ЎӔ");
translit = translit.replace(/УЕ/g, "ЎЕ");
translit = translit.replace(/УЁ/g, "ЎЁ");
translit = translit.replace(/УЭ/g, "ЎЭ");
translit = translit.replace(/УЫ/g, "ЎЫ");
translit = translit.replace(/УИ/g, "ЎИ");
translit = translit.replace(/УО/g, "ЎО");
translit = translit.replace(/УУ/g, "ЎУ");
translit = translit.replace(/АУ/g, "АЎ");
translit = translit.replace(/ЯУ/g, "ЯЎ");
translit = translit.replace(/ӔУ/g, "ӔЎ");
translit = translit.replace(/ЕУ/g, "ЕЎ");
translit = translit.replace(/ЁУ/g, "ЁЎ");
translit = translit.replace(/ЭУ/g, "ЭЎ");
translit = translit.replace(/ЫУ/g, "ЫЎ");
translit = translit.replace(/ИУ/g, "ИЎ");
translit = translit.replace(/ОУ/g, "ОЎ");
translit = translit.replace(/УУ/g, "УЎ");
translit = translit.replace(/ЮУ/g, "ЮЎ");
translit = translit.replace(/ЎЎ/g, "УЎ");

translit = translit.replace(/дж/g, "j");
translit = translit.replace(/дз/g, "ƶ");
translit = translit.replace(/гъ/g, "h");
translit = translit.replace(/къ/g, "ķ");
translit = translit.replace(/пъ/g, "ṕ");
translit = translit.replace(/тъ/g, "ț");
translit = translit.replace(/хъ/g, "q");
translit = translit.replace(/цъ/g, "ć");
translit = translit.replace(/чъ/g, "čʻ");
translit = translit.replace(/Дж/g, "J");
translit = translit.replace(/Дз/g, "Ƶ");
translit = translit.replace(/Гъ/g, "H");
translit = translit.replace(/Къ/g, "Ķ");
translit = translit.replace(/Пъ/g, "Ṕ");
translit = translit.replace(/Тъ/g, "Ț");
translit = translit.replace(/Хъ/g, "Q");
translit = translit.replace(/Цъ/g, "Ć");
translit = translit.replace(/Чъ/g, "Čʻ");
translit = translit.replace(/ДЖ/g, "J");
translit = translit.replace(/ДЗ/g, "Ƶ");
translit = translit.replace(/ГЪ/g, "H");
translit = translit.replace(/КЪ/g, "Ķ");
translit = translit.replace(/ПЪ/g, "Ṕ");
translit = translit.replace(/ТЪ/g, "Ț");
translit = translit.replace(/ХЪ/g, "Q");
translit = translit.replace(/ЦЪ/g, "Ć");
translit = translit.replace(/ЧЪ/g, "Čʻ");

translit = translit.replace(/а/g, "a");
translit = translit.replace(/ӕ/g, "ă");
translit = translit.replace(/б/g, "b");
translit = translit.replace(/в/g, "v");
translit = translit.replace(/г/g, "g");
translit = translit.replace(/д/g, "d");
translit = translit.replace(/е/g, "e");
translit = translit.replace(/ё/g, "ë");
translit = translit.replace(/ж/g, "ž");
translit = translit.replace(/з/g, "z");
translit = translit.replace(/и/g, "i");
translit = translit.replace(/й/g, "y");
translit = translit.replace(/к/g, "k");
translit = translit.replace(/л/g, "l");
translit = translit.replace(/м/g, "m");
translit = translit.replace(/н/g, "n");
translit = translit.replace(/о/g, "o");
translit = translit.replace(/п/g, "p");
translit = translit.replace(/р/g, "r");
translit = translit.replace(/с/g, "s");
translit = translit.replace(/т/g, "t");
translit = translit.replace(/у/g, "u");
translit = translit.replace(/ў/g, "w");
translit = translit.replace(/ф/g, "f");
translit = translit.replace(/х/g, "x");
translit = translit.replace(/ц/g, "c");
translit = translit.replace(/ч/g, "č");
translit = translit.replace(/ш/g, "š");
translit = translit.replace(/щ/g, "šč");
translit = translit.replace(/ъ/g, "\u0022");
translit = translit.replace(/ы/g, "ĭ");
translit = translit.replace(/ь/g, "\u0027");
translit = translit.replace(/э/g, "è");
translit = translit.replace(/ю/g, "yu");
translit = translit.replace(/я/g, "ya");
translit = translit.replace(/А/g, "A");
translit = translit.replace(/Ӕ/g, "Ă");
translit = translit.replace(/Б/g, "B");
translit = translit.replace(/В/g, "V");
translit = translit.replace(/Г/g, "G");
translit = translit.replace(/Д/g, "D");
translit = translit.replace(/Е/g, "E");
translit = translit.replace(/Ё/g, "Ë");
translit = translit.replace(/Ж/g, "Ž");
translit = translit.replace(/З/g, "Z");
translit = translit.replace(/И/g, "I");
translit = translit.replace(/Й/g, "Y");
translit = translit.replace(/К/g, "K");
translit = translit.replace(/Л/g, "L");
translit = translit.replace(/М/g, "M");
translit = translit.replace(/Н/g, "N");
translit = translit.replace(/О/g, "O");
translit = translit.replace(/П/g, "P");
translit = translit.replace(/Р/g, "R");
translit = translit.replace(/С/g, "S");
translit = translit.replace(/Т/g, "T");
translit = translit.replace(/У/g, "U");
translit = translit.replace(/Ў/g, "W");
translit = translit.replace(/Ф/g, "F");
translit = translit.replace(/Х/g, "X");
translit = translit.replace(/Ц/g, "C");
translit = translit.replace(/Ч/g, "Č");
translit = translit.replace(/Ш/g, "Š");
translit = translit.replace(/Щ/g, "Šč");
translit = translit.replace(/Ъ/g, "\u0022");
translit = translit.replace(/Ы/g, "Ĭ");
translit = translit.replace(/Ь/g, "\u0027");
translit = translit.replace(/Э/g, "È");
translit = translit.replace(/Ю/g, "Yu");
translit = translit.replace(/Я/g, "Ya");
translit = translit.replace(/«/g, "\u201c");
translit = translit.replace(/»/g, "\u201d");
document.transcription.text1.value = car;
document.transcription.text2.value = translit;
}

function latcyr () {
}

function copy1()
{ textRange=document.transcription.text1.createTextRange();
textRange.execCommand("Copy");
textRange="";
}
function copy2()
{ textRange=document.transcription.text2.createTextRange();
textRange.execCommand("Copy");
textRange="";
}
