function cyrlat() {
	document.transcription.text2.value = document.transcription.text1.value
		.replace(/(0|1|2|3|4|5|6|7|8|9)Х/g, "$1X")
		.replace(/(0|1|2|3|4|5|6|7|8|9)х/g, "$1x")
		.replace(/Х(0|1|2|3|4|5|6|7|8|9)/g, "X$1")
		.replace(/х(0|1|2|3|4|5|6|7|8|9)/g, "x$1")

		.replace(/(Б|В|Г|Ж|Ӝ|Ӟ|К|М|П|Р|Ф|Х|Ц|Ч|Ӵ|Ш|Щ|б|в|г|ж|ӝ|ӟ|к|м|п|р|ф|х|ц|ч|ӵ|ш|щ)Е/g, "$1Э")
		.replace(/(Б|В|Г|Ж|Ӝ|Ӟ|К|М|П|Р|Ф|Х|Ц|Ч|Ӵ|Ш|Щ|б|в|г|ж|ӝ|ӟ|к|м|п|р|ф|х|ц|ч|ӵ|ш|щ)е/g, "$1э")
		.replace(/(Д|С|З|Л|Н|Т)Е/g, "$1ЬЭ")
		.replace(/(д|с|з|л|н|т)Е/g, "$1ьЭ")
		.replace(/(Д|С|З|Л|Н|Т|д|с|з|л|н|т)е/g, "$1ьэ")
		.replace(/(Д|С|З|Л|Н|Т)Ё/g, "$1ЬО")
		.replace(/(д|с|з|л|н|т)Ё/g, "$1ьО")
		.replace(/(Д|С|З|Л|Н|Т|д|с|з|л|н|т)ё/g, "$1ьо")
		.replace(/(Д|С|З|Л|Н|Т)Я/g, "$1ЬА")
		.replace(/(д|с|з|л|н|т)Я/g, "$1ьА")
		.replace(/(Д|С|З|Л|Н|Т|д|с|з|л|н|т)я/g, "$1ьа")
		.replace(/(Д|С|З|Л|Н|Т)Ю/g, "$1ЬУ")
		.replace(/(д|с|з|л|н|т)Ю/g, "$1ьУ")
		.replace(/(Д|С|З|Л|Н|Т|д|с|з|л|н|т)ю/g, "$1ьу")
		.replace(/(Д|С|З|Л|Н|Т)И/g, "$1ЬӤ")
		.replace(/(д|с|з|л|н|т)И/g, "$1ьӤ")
		.replace(/(Д|С|З|Л|Н|Т|д|с|з|л|н|т)и/g, "$1ьӥ")

		.replace(/Ь(Д|С|З|Л|Н|Т)Ь/g, "$1Ь")
		.replace(/Ь(д|с|з|л|н|т)Ь/g, "$1ь")
		.replace(/ь(д|с|з|л|н|т)ь/g, "$1ь")

		.replace(/ДЬ/g, "ГЬ")
		.replace(/Дь/g, "Гь")
		.replace(/дь/g, "гь")

		.replace(/СЬ/g, "Щ")
		.replace(/Сь/g, "Щ")
		.replace(/сь/g, "щ")

		.replace(/ЖЖ/g, "ZZS")
		.replace(/ӜӜ/g, "DDZS")
		.replace(/ӞӞ/g, "DDZY")
		.replace(/СС/g, "SSZ")
		.replace(/ЧЧ/g, "CCY")
		.replace(/ӴӴ/g, "CCS")
		.replace(/ЩЩ/g, "SSY")

		.replace(/Жж/g, "Zzs")
		.replace(/Ӝӝ/g, "Ddzs")
		.replace(/Ӟӟ/g, "Ddzy")
		.replace(/Сс/g, "Ssz")
		.replace(/Чч/g, "Ccy")
		.replace(/Ӵӵ/g, "Ccs")
		.replace(/Щщ/g, "Ssy")

		.replace(/жж/g, "zzs")
		.replace(/ӝӝ/g, "ddzs")
		.replace(/ӟӟ/g, "ddzy")
		.replace(/сс/g, "ssz")
		.replace(/чч/g, "ccy")
		.replace(/ӵӵ/g, "ccs")
		.replace(/щщ/g, "ssy")

		.replace(/а/g, "a")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/д/g, "d")
		.replace(/е/g, "je")
		.replace(/ё/g, "jo")
		.replace(/ж/g, "zs")
		.replace(/ӝ/g, "dzs")
		.replace(/з/g, "z")
		.replace(/ӟ/g, "dzy")
		.replace(/и/g, "i")
		.replace(/ӥ/g, "i")
		.replace(/й/g, "j")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/о/g, "o")
		.replace(/ӧ/g, "ö")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "sz")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ф/g, "f")
		.replace(/х/g, "h")
		.replace(/ц/g, "c")
		.replace(/ч/g, "cy")
		.replace(/ӵ/g, "cs")
		.replace(/ш/g, "s")
		.replace(/щ/g, "sy")
		.replace(/ъ/g, "")
		.replace(/ы/g, "ï")
		.replace(/ь/g, "y")
		.replace(/э/g, "e")
		.replace(/ю/g, "ju")
		.replace(/я/g, "ja")

		.replace(/А/g, "A")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Д/g, "D")
		.replace(/Е/g, "Je")
		.replace(/Ё/g, "Jo")
		.replace(/Ж/g, "Zs")
		.replace(/Ӝ/g, "Dzs")
		.replace(/З/g, "Z")
		.replace(/Ӟ/g, "Dzy")
		.replace(/И/g, "I")
		.replace(/Ӥ/g, "I")
		.replace(/Й/g, "J")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/О/g, "O")
		.replace(/Ӧ/g, "Ö")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "Sz")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "H")
		.replace(/Ц/g, "C")
		.replace(/Ч/g, "Cy")
		.replace(/Ӵ/g, "Cs")
		.replace(/Ш/g, "S")
		.replace(/Щ/g, "Sy")
		.replace(/Ы/g, "Ï")
		.replace(/Ь/g, "Y")
		.replace(/Э/g, "E")
		.replace(/Ю/g, "Ju")
		.replace(/Я/g, "Ja")
		.replace(/«/g, "\u201c")
		.replace(/»/g, "\u201d")

		.replace(/G(Y|y)(Ъ|ъ)/g, "D")
		.replace(/gy(Ъ|ъ)/g, "d")
		.replace(/(Y|y)(Ъ|ъ)/g, "")
		.replace(/Ъ/g, "")
		.replace(/ъ/g, "");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}