function cyrlat() {
	document.transcription.text2.value = document.transcription.text1.value
		.normalize('NFD')
		.replace(/(\u0300|\u0301|\u0304|\u030c)/g, "")
		.normalize('NFC')
		.replace(/Ĉ/g, "Ch")
		.replace(/Ŋ/g, "Ng")
		.replace(/Ŝ/g, "Sh")
		.replace(/Ẑ/g, "Zh")
		.replace(/ĉ/g, "ch")
		.replace(/ŋ/g, "ng")
		.replace(/ŝ/g, "sh")
		.replace(/ẑ/g, "zh")

		.replace(/(B|P|M|F)O/g, "$1UO")
		.replace(/(B|P|M|F|b|p|m|f)o/g, "$1uo")
		.replace(/(Z|C|S|ZH|CH|SH|R)I/g, "$1I")
		.replace(/(Z|C|S|Zh|Ch|Sh|R|z|c|s|zh|ch|sh|r)i/g, "$1і")

		.replace(/WENG/g, "ЎӘҢ")
		.replace(/WEN/g, "'UN")
		.replace(/WEI/g, "'UI")
		.replace(/YOU/g, "'IU")
		.replace(/Y(U|Ü)/g, "'Ü")
		.replace(/JU/g, "JÜ")
		.replace(/QU/g, "QÜ")
		.replace(/XU/g, "XÜ")
		.replace(/YI/g, "'I")
		.replace(/WU/g, "'U")
		.replace(/Weng/g, "Ўәң")
		.replace(/Wen/g, "'Un")
		.replace(/Wei/g, "'Ui")
		.replace(/You/g, "'Iu")
		.replace(/Y(u|ü)/g, "'Ü")
		.replace(/Ju/g, "Jü")
		.replace(/Qu/g, "Qü")
		.replace(/Xu/g, "Xü")
		.replace(/Yi/g, "'I")
		.replace(/Wu/g, "'U")
		.replace(/weng/g, "ўәң")
		.replace(/wen/g, "'un")
		.replace(/wei/g, "'ui")
		.replace(/you/g, "'iu")
		.replace(/y(u|ü)/g, "'ü")
		.replace(/ju/g, "jü")
		.replace(/qu/g, "qü")
		.replace(/xu/g, "xü")
		.replace(/yi/g, "'i")
		.replace(/y/g, "'i")
		.replace(/wu/g, "'u")
		.replace(/w/g, "'u")
		.replace(/Y/g, "'I")
		.replace(/W/g, "'U")

		.replace(/ER(A|E|I|O|U|Ü)/g, "E'R$1")
		.replace(/Er(a|e|i|o|u|ü)/g, "E'r$1")
		.replace(/er(a|e|i|o|u|ü)/g, "e'r$1")


		.replace(/IANG/g, "ЙАҢ")
		.replace(/IONG/g, "ЙҰҢ")
		.replace(/UANG/g, "ЎАҢ")
		.replace(/ANG/g, "АҢ")
		.replace(/ENG/g, "ӘҢ")
		.replace(/ONG/g, "ҰҢ")
		.replace(/IAO/g, "ЙАУ\u032f")
		.replace(/IAN/g, "ЙЭН")
		.replace(/ING/g, "ИҢ")
		.replace(/UAI/g, "ЎАИ\u032f")
		.replace(/UAN/g, "ЎАН")
		.replace(/ÜAN/g, "ӮЭН")
		.replace(/AI/g, "АИ\u032f")
		.replace(/EI/g, "ЕИ\u032f")
		.replace(/AO/g, "АУ\u032f")
		.replace(/OU/g, "ОУ\u032f")
		.replace(/EN/g, "ӘН")
		.replace(/IA/g, "ЙА")
		.replace(/IE/g, "ЙЕ")
		.replace(/IU/g, "ЙОУ\u032f")
		.replace(/UA/g, "ЎА")
		.replace(/UO/g, "ЎО")
		.replace(/UI/g, "ЎЕИ\u032f")
		.replace(/UN/g, "ЎӘН")
		.replace(/ÜE/g, "ӮЕ")
		.replace(/ÜN/g, "ҮН")
		.replace(/IO/g, "ЙӦ")
		.replace(/ER/g, "АҖ\u032f")

		.replace(/Iang/g, "Йаң")
		.replace(/Iong/g, "Йұң")
		.replace(/Uang/g, "Ўаң")
		.replace(/Ang/g, "Аң")
		.replace(/Eng/g, "Әң")
		.replace(/Ong/g, "Ұң")
		.replace(/Iao/g, "Йау\u032f")
		.replace(/Ian/g, "Йэн")
		.replace(/Ing/g, "Иң")
		.replace(/Uai/g, "Ўаи\u032f")
		.replace(/Uan/g, "Ўан")
		.replace(/Üan/g, "Ӯэн")
		.replace(/Ai/g, "Аи\u032f")
		.replace(/Ei/g, "Еи\u032f")
		.replace(/Ao/g, "Ау\u032f")
		.replace(/Ou/g, "Оу\u032f")
		.replace(/En/g, "Ән")
		.replace(/Ia/g, "Йа")
		.replace(/Ie/g, "Йе")
		.replace(/Iu/g, "Йоу\u032f")
		.replace(/Ua/g, "Ўа")
		.replace(/Uo/g, "Ўо")
		.replace(/Ui/g, "Ўеи\u032f")
		.replace(/Un/g, "Ўән")
		.replace(/Üe/g, "Ӯе")
		.replace(/Ün/g, "Үн")
		.replace(/Io/g, "Йӧ")
		.replace(/Er/g, "Аҗ\u032f")
		.replace(/I/g, "И")
		.replace(/E/g, "Ы")
		.replace(/Ü/g, "Ү")
		.replace(/Ê/g, "Э")
		.replace(/O/g, "Ӧ")

		.replace(/iang/g, "йаң")
		.replace(/iong/g, "йұң")
		.replace(/uang/g, "ўаң")
		.replace(/ang/g, "аң")
		.replace(/eng/g, "әң")
		.replace(/ong/g, "ұң")
		.replace(/iao/g, "йау\u032f")
		.replace(/ian/g, "йэн")
		.replace(/ing/g, "иң")
		.replace(/uai/g, "ўаи\u032f")
		.replace(/uan/g, "ўан")
		.replace(/üan/g, "ӯэн")
		.replace(/ai/g, "аи\u032f")
		.replace(/ei/g, "еи\u032f")
		.replace(/ao/g, "ау\u032f")
		.replace(/ou/g, "оу\u032f")
		.replace(/en/g, "ән")
		.replace(/ia/g, "йа")
		.replace(/ie/g, "йе")
		.replace(/iu/g, "йоу\u032f")
		.replace(/ua/g, "ўа")
		.replace(/uo/g, "ўо")
		.replace(/ui/g, "ўеи\u032f")
		.replace(/un/g, "ўән")
		.replace(/üe/g, "ӯе")
		.replace(/ün/g, "үн")
		.replace(/io/g, "йӧ")
		.replace(/er/g, "аҗ\u032f")
		.replace(/i/g, "и")
		.replace(/e/g, "ы")
		.replace(/ü/g, "ү")
		.replace(/ê/g, "э")
		.replace(/o/g, "ӧ")

		.replace(/ZH/g, "Џ")
		.replace(/CH/g, "Ч")
		.replace(/SH/g, "Ш")
		.replace(/Zh/g, "Џ")
		.replace(/Ch/g, "Ч")
		.replace(/Sh/g, "Ш")
		.replace(/zh/g, "џ")
		.replace(/ch/g, "ч")
		.replace(/sh/g, "ш")

		.replace(/P/g, "П")
		.replace(/B/g, "Б")
		.replace(/T/g, "Т")
		.replace(/D/g, "Д")
		.replace(/Z/g, "З")
		.replace(/C/g, "Ц")
		.replace(/R/g, "Ж")
		.replace(/J/g, "Ђ")
		.replace(/Q/g, "Ћ")
		.replace(/X/g, "Щ")
		.replace(/K/g, "К")
		.replace(/G/g, "Г")
		.replace(/H/g, "Х")
		.replace(/Ĵ/g, "Й")
		.replace(/F/g, "Ф")
		.replace(/L/g, "Л")
		.replace(/M/g, "М")
		.replace(/N/g, "Н")
		.replace(/S/g, "С")

		.replace(/p/g, "п")
		.replace(/b/g, "б")
		.replace(/t/g, "т")
		.replace(/d/g, "д")
		.replace(/z/g, "з")
		.replace(/c/g, "ц")
		.replace(/r/g, "ж")
		.replace(/j/g, "ђ")
		.replace(/q/g, "ћ")
		.replace(/x/g, "щ")
		.replace(/k/g, "к")
		.replace(/g/g, "г")
		.replace(/h/g, "х")
		.replace(/ĵ/g, "й")
		.replace(/f/g, "ф")
		.replace(/l/g, "л")
		.replace(/m/g, "м")
		.replace(/n/g, "н")
		.replace(/s/g, "с")

		.replace(/'/g, "")

		.replace(/(Б|П|М|Ф|Ў)ӘҢ/g, "$1ОҢ")
		.replace(/(Б|П|М|Ф|Ў|б|п|м|ф|ў)әң/g, "$1оң")

		.replace(/У\u032f/g, "Ğ")
		.replace(/у\u032f/g, "ğ")
		.replace(/(І|Ы|Ә)/g, "I")
		.replace(/Ү/g, "Ü")
		.replace(/(Й|И\u032f)/g, "Y")
		.replace(/И/g, "İ")
		.replace(/Ң/g, "NĞ")
		.replace(/Ұ/g, "U")
		.replace(/У/g, "U")
		.replace(/(Э|Е)/g, "E")
		.replace(/(Ў|Ӯ)/g, "V")
		.replace(/(О|Ӧ)/g, "O")
		.replace(/А/g, "A")

		.replace(/(і|ы|ә)/g, "ı")
		.replace(/ү/g, "ü")
		.replace(/(й|и\u032f)/g, "y")
		.replace(/и/g, "i")
		.replace(/ң/g, "nğ")
		.replace(/ұ/g, "u")
		.replace(/у/g, "u")
		.replace(/(э|е)/g, "e")
		.replace(/(ў|ӯ)/g, "v")
		.replace(/(о|ӧ)/g, "o")
		.replace(/а/g, "a")

		.replace(/(Ч|Ћ)/g, "Ç")
		.replace(/(Ђ|Џ)/g, "C")
		.replace(/Ц/g, "Ć")
		.replace(/З/g, "Ź")
		.replace(/(Ш|Щ)/g, "Ş")
		.replace(/Б/g, "B")
		.replace(/П/g, "P")
		.replace(/Д/g, "D")
		.replace(/Т/g, "T")
		.replace(/Г/g, "G")
		.replace(/К/g, "K")
		.replace(/Х/g, "H")
		.replace(/(Ж|Җ\u032f)/g, "R")
		.replace(/Ф/g, "F")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/С/g, "S")

		.replace(/(ч|ћ)/g, "ç")
		.replace(/(ђ|џ)/g, "c")
		.replace(/ц/g, "ć")
		.replace(/з/g, "ź")
		.replace(/(ш|щ)/g, "ş")
		.replace(/б/g, "b")
		.replace(/п/g, "p")
		.replace(/д/g, "d")
		.replace(/т/g, "t")
		.replace(/г/g, "g")
		.replace(/к/g, "k")
		.replace(/х/g, "h")
		.replace(/(ж|җ\u032f)/g, "r")
		.replace(/ф/g, "f")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/с/g, "s")

		.replace(/(A|E|İ|I|O|U|Ü)Ź/g, "$1DZ")
		.replace(/(A|E|İ|I|O|U|Ü)Ć/g, "$1TS")

		.replace(/(A|E|İ|I|O|U|Ü)ź/g, "$1dz")
		.replace(/(A|E|İ|I|O|U|Ü)ć/g, "$1ts")

		.replace(/(a|e|ı|i|o|u|ü)ź/g, "$1dz")
		.replace(/(a|e|ı|i|o|u|ü)ć/g, "$1ts")

		.replace(/Ź/g, "Z")
		.replace(/Ć/g, "S")

		.replace(/ź/g, "z")
		.replace(/ć/g, "s")

		.replace(/(A|E|İ|I|O|U|Ü)(A|E|İ|I|O|U|Ü)/g, "$1\u2019$2")
		.replace(/(A|E|İ|I|O|U|Ü)(a|e|ı|i|o|u|ü)/g, "$1\u2019ğ$2")
		.replace(/(a|e|ı|i|o|u|ü)(a|e|ı|i|o|u|ü)/g, "$1\u2019ğ$2")

		.replace(/\u032f/g, "");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}