function cyrlat() {
	document.transcription.text1.value = document.transcription.text1.value
		.replace(/ă/g, "ӑ")
		.replace(/Ă/g, "Ӑ")
		.replace(/ĕ/g, "ӗ")
		.replace(/Ĕ/g, "Ӗ")
		.replace(/ç/g, "ҫ")
		.replace(/Ç/g, "Ҫ")
		.replace(/ÿ/g, "ӳ")
		.replace(/Ÿ/g, "Ӳ");

	document.transcription.text2.value = document.transcription.text1.value
		.replace(/ă/g, "ӑ")
		.replace(/Ă/g, "Ӑ")
		.replace(/ĕ/g, "ӗ")
		.replace(/Ĕ/g, "Ӗ")
		.replace(/ç/g, "ҫ")
		.replace(/Ç/g, "Ҫ")
		.replace(/ÿ/g, "ӳ")
		.replace(/Ÿ/g, "Ӳ")

		.replace(/а/g, "a")
		.replace(/ӑ/g, "ĭ")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/д/g, "d")
		.replace(/е/g, "e")
		.replace(/ё/g, "yo")
		.replace(/ӗ/g, "í")
		.replace(/ж/g, "j")
		.replace(/з/g, "z")
		.replace(/и/g, "i")
		.replace(/й/g, "y")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/о/g, "o")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/ҫ/g, "ś")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ӳ/g, "ü")
		.replace(/ф/g, "f")
		.replace(/х/g, "h")
		.replace(/ц/g, "ts")
		.replace(/ч/g, "ç")
		.replace(/ш/g, "ş")
		.replace(/щ/g, "şç")
		.replace(/ъ/g, "ʼ")
		.replace(/ы/g, "ı")
		.replace(/ь/g, "")
		.replace(/э/g, "e")
		.replace(/ю/g, "yu")
		.replace(/я/g, "ya")

		.replace(/А/g, "A")
		.replace(/Ӑ/g, "Ĭ")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Д/g, "D")
		.replace(/Е/g, "E")
		.replace(/Ё/g, "Yo")
		.replace(/Ӗ/g, "Í")
		.replace(/Ж/g, "J")
		.replace(/З/g, "Z")
		.replace(/И/g, "İ")
		.replace(/Й/g, "Y")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/О/g, "O")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Ҫ/g, "Ś")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ӳ/g, "Ü")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "H")
		.replace(/Ц/g, "Ts")
		.replace(/Ч/g, "Ç")
		.replace(/Ш/g, "Ş")
		.replace(/Щ/g, "Şç")
		.replace(/Ъ/g, "ʼ")
		.replace(/Ы/g, "I")
		.replace(/Ь/g, "")
		.replace(/Э/g, "E")
		.replace(/Ю/g, "Yu")
		.replace(/Я/g, "Ya")
		.replace(/«/g, "\u201c")
		.replace(/»/g, "\u201d");
}

function latcyr() {}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}