function latcyr() {
	document.transcription.text1.value = document.transcription.text2.value
		.replace(/a/g, "а")
		.replace(/b/g, "б")
		.replace(/v/g, "в")
		.replace(/h/g, "г")
		.replace(/g/g, "ґ")
		.replace(/d/g, "д")
		.replace(/e/g, "е")
		.replace(/ê/g, "є")
		.replace(/ż/g, "ж")
		.replace(/z/g, "з")
		.replace(/i/g, "і")
		.replace(/y/g, "и")
		.replace(/ĩ/g, "ї\u0301")
		.replace(/î/g, "ї")
		.replace(/j/g, "й")
		.replace(/k/g, "к")
		.replace(/l/g, "л")
		.replace(/m/g, "м")
		.replace(/n/g, "н")
		.replace(/o/g, "о")
		.replace(/p/g, "п")
		.replace(/r/g, "р")
		.replace(/s/g, "с")
		.replace(/t/g, "т")
		.replace(/u/g, "у")
		.replace(/f/g, "ф")
		.replace(/x/g, "х")
		.replace(/c/g, "ц")
		.replace(/ċ/g, "ч")
		.replace(/ṡ/g, "ш")
		.replace(/ŝ/g, "щ")
		.replace(/\u02bc|\u2019/g, "ъ")
		.replace(/ĵ/g, "ь")
		.replace(/û/g, "ю")
		.replace(/â/g, "я")

		.replace(/A/g, "А")
		.replace(/B/g, "Б")
		.replace(/V/g, "В")
		.replace(/H/g, "Г")
		.replace(/G/g, "Ґ")
		.replace(/D/g, "Д")
		.replace(/E/g, "Е")
		.replace(/Ê/g, "Є")
		.replace(/Ż/g, "Ж")
		.replace(/Z/g, "З")
		.replace(/Y/g, "И")
		.replace(/I/g, "І")
		.replace(/Ĩ/g, "Ї\u0301")
		.replace(/Î/g, "Ї")
		.replace(/J/g, "Й")
		.replace(/K/g, "К")
		.replace(/L/g, "Л")
		.replace(/M/g, "М")
		.replace(/N/g, "Н")
		.replace(/O/g, "О")
		.replace(/P/g, "П")
		.replace(/R/g, "Р")
		.replace(/S/g, "С")
		.replace(/T/g, "Т")
		.replace(/U/g, "У")
		.replace(/F/g, "Ф")
		.replace(/X/g, "Х")
		.replace(/C/g, "Ц")
		.replace(/Ċ/g, "Ч")
		.replace(/Ṡ/g, "Ш")
		.replace(/Ŝ/g, "Щ")
		.replace(/Ĵ/g, "Ь")
		.replace(/Û/g, "Ю")
		.replace(/Â/g, "Я")
		.replace(/\u201e/g, "«")
		.replace(/\u201c/g, "»")


		.replace(/(А|Б|В|Г|Д|Е|Ж|З|И|Й|К|Л|М|Н|О|П|Р|С|Т|У|Ф|Х|Ц|Ч|Ш|Щ|Ы|Ь|Э|Ю|Ё|Я)ъ/g, "$1Ъ");
}

function cyrlat() {
	document.transcription.text2.value = document.transcription.text1.value
		.normalize('NFC')
		.replace(/ʼ/g, "ъ")
		.replace(/’/g, "ъ")
		.replace(/'/g, "ъ")
		.replace(/а/g, "a")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "h")
		.replace(/ґ/g, "g")
		.replace(/д/g, "d")
		.replace(/е/g, "e")
		.replace(/є/g, "ê")
		.replace(/ж/g, "ż")
		.replace(/з/g, "z")
		.replace(/и/g, "y")
		.replace(/і/g, "i")
		.replace(/ї\u0301/g, "ĩ")
		.replace(/ї/g, "î")
		.replace(/й/g, "j")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/о/g, "o")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ф/g, "f")
		.replace(/х/g, "x")
		.replace(/ц/g, "c")
		.replace(/ч/g, "ċ")
		.replace(/ш/g, "ṡ")
		.replace(/щ/g, "ŝ")
		.replace(/ь/g, "ĵ")
		.replace(/ю/g, "û")
		.replace(/я/g, "â")
		.replace(/ъ/g, "ʼ")

		.replace(/А/g, "A")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "H")
		.replace(/Ґ/g, "G")
		.replace(/Д/g, "D")
		.replace(/Е/g, "E")
		.replace(/Є/g, "Ê")
		.replace(/Ж/g, "Ż")
		.replace(/З/g, "Z")
		.replace(/И/g, "Y")
		.replace(/І/g, "I")
		.replace(/Ї\u0301/g, "Ĩ")
		.replace(/Ї/g, "Î")
		.replace(/Й/g, "J")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/О/g, "O")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "X")
		.replace(/Ц/g, "C")
		.replace(/Ч/g, "Ċ")
		.replace(/Ш/g, "Ṡ")
		.replace(/Щ/g, "Ŝ")
		.replace(/Ь/g, "Ĵ")
		.replace(/Ю/g, "Û")
		.replace(/Я/g, "Â")
		.replace(/«/g, "\u201e")
		.replace(/»/g, "\u201c")
		.normalize('NFC');
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}