function cyrlat() {
	document.transcription.text2.value = document.transcription.text1.value
		.normalize('NFD')
		.replace(/(\u0300|\u0301|\u0304|\u030c)/g, "")
		.normalize('NFC')
		.replace(/Ĉ/g, "Ch")
		.replace(/Ŋ/g, "Ng")
		.replace(/Ŝ/g, "Sh")
		.replace(/Ẑ/g, "Zh")
		.replace(/ĉ/g, "ch")
		.replace(/ŋ/g, "ng")
		.replace(/ŝ/g, "sh")
		.replace(/ẑ/g, "zh")

		.replace(/A/g, "a")
		.replace(/B/g, "b")
		.replace(/C/g, "c")
		.replace(/D/g, "d")
		.replace(/E/g, "e")
		.replace(/Ê/g, "ê")
		.replace(/F/g, "f")
		.replace(/G/g, "g")
		.replace(/H/g, "h")
		.replace(/I/g, "i")
		.replace(/J/g, "j")
		.replace(/K/g, "k")
		.replace(/L/g, "l")
		.replace(/M/g, "m")
		.replace(/N/g, "n")
		.replace(/O/g, "o")
		.replace(/P/g, "p")
		.replace(/Q/g, "q")
		.replace(/R/g, "r")
		.replace(/S/g, "s")
		.replace(/T/g, "t")
		.replace(/U/g, "u")
		.replace(/W/g, "w")
		.replace(/X/g, "x")
		.replace(/Y/g, "y")
		.replace(/Z/g, "z")
		.replace(/Ü/g, "ü")

		.replace(/(b|p|m|f)o/g, "$1uo")
		.replace(/(z|c|s|zh|ch|sh|r)i/g, "$1ɨ")

		.replace(/weng/g, "ẃəŋ")
		.replace(/wen/g, "'un")
		.replace(/wei/g, "'ui")
		.replace(/you/g, "'iu")
		.replace(/y(u|ü)/g, "'ü")
		.replace(/ju/g, "jü")
		.replace(/qu/g, "qü")
		.replace(/xu/g, "xü")
		.replace(/yi/g, "'i")
		.replace(/y/g, "'i")
		.replace(/wu/g, "'u")
		.replace(/w/g, "'u")
		.replace(/ẃ/g, "w")

		.replace(/er(a|e|i|o|u|ü)/g, "e'r$1")

		.replace(/iang/g, "ĵaŋ")
		.replace(/iong/g, "ĵʊŋ")
		.replace(/uang/g, "waŋ")
		.replace(/ang/g, "aŋ")
		.replace(/eng/g, "əŋ")
		.replace(/ong/g, "ʊŋ")
		.replace(/iao/g, "ĵau̯")
		.replace(/ian/g, "ĵɛn")
		.replace(/ing/g, "iŋ")
		.replace(/uai/g, "wai̯")
		.replace(/uan/g, "wan")
		.replace(/üan/g, "ɥɛn")
		.replace(/ai/g, "ai̯")
		.replace(/ei/g, "ěi̯")
		.replace(/ao/g, "au̯")
		.replace(/ou/g, "ôu̯")
		.replace(/en/g, "ən")
		.replace(/ia/g, "ĵa")
		.replace(/ie/g, "ĵě")
		.replace(/iu/g, "ĵôu̯")
		.replace(/ua/g, "wa")
		.replace(/uo/g, "wô")
		.replace(/ui/g, "wěi̯")
		.replace(/un/g, "wən")
		.replace(/üe/g, "ɥě")
		.replace(/ün/g, "yn")
		.replace(/io/g, "ĵɔ")
		.replace(/er/g, "aɚ̯")
		.replace(/e/g, "ɤ")
		.replace(/ü/g, "y")
		.replace(/ê/g, "ɛ")
		.replace(/o/g, "ɔ")
		.replace(/ě/g, "e")
		.replace(/ô/g, "o")

		.replace(/zh/g, "ʈʂ")
		.replace(/ch/g, "ʈʂʰ")
		.replace(/sh/g, "ʂ")
		.replace(/p/g, "pʰ")
		.replace(/b/g, "p")
		.replace(/t/g, "tʰ")
		.replace(/d/g, "t")
		.replace(/z/g, "ts")
		.replace(/c/g, "tsʰ")
		.replace(/r/g, "ʐ")
		.replace(/j/g, "tɕ")
		.replace(/q/g, "tɕʰ")
		.replace(/x/g, "ɕ")
		.replace(/k/g, "kʰ")
		.replace(/g/g, "k")
		.replace(/h/g, "x")
		.replace(/ĵ/g, "j")

		.replace(/'/g, "");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}