function cyrlat() {
	document.transcription.text1.value = document.transcription.text1.value
		.replace(/ă/g, "ӑ")
		.replace(/Ă/g, "Ӑ")
		.replace(/ĕ/g, "ӗ")
		.replace(/Ĕ/g, "Ӗ")
		.replace(/ç/g, "ҫ")
		.replace(/Ç/g, "Ҫ")
		.replace(/ÿ/g, "ӳ")
		.replace(/Ÿ/g, "Ӳ")
		.replace(/ў/g, "ӳ")
		.replace(/Ў/g, "Ӳ")
		.replace(/ү/g, "ӳ")
		.replace(/Ү/g, "Ӳ");

	document.transcription.text2.value = document.transcription.text1.value
		.replace(/ă/g, "ӑ")
		.replace(/Ă/g, "Ӑ")
		.replace(/ĕ/g, "ӗ")
		.replace(/Ĕ/g, "Ӗ")
		.replace(/ç/g, "ҫ")
		.replace(/Ç/g, "Ҫ")
		.replace(/ÿ/g, "ӳ")
		.replace(/Ÿ/g, "Ӳ")
		.replace(/ў/g, "ӳ")
		.replace(/Ў/g, "Ӳ")
		.replace(/ү/g, "ӳ")
		.replace(/Ү/g, "Ӳ")

		.replace(/а/g, "a")
		.replace(/ӑ/g, "ă")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/д/g, "d")
		.replace(/е/g, "e")
		.replace(/ё/g, "jo")
		.replace(/ӗ/g, "ĕ")
		.replace(/ж/g, "ž")
		.replace(/з/g, "z")
		.replace(/и/g, "i")
		.replace(/й/g, "j")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/о/g, "o")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/ҫ/g, "ś")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ӳ/g, "ü")
		.replace(/ф/g, "f")
		.replace(/х/g, "h")
		.replace(/ц/g, "ts")
		.replace(/ч/g, "č")
		.replace(/ш/g, "š")
		.replace(/щ/g, "šč")
		.replace(/ъ/g, "ʺ")
		.replace(/ы/g, "y")
		.replace(/ь/g, "ʹ")
		.replace(/э/g, "e")
		.replace(/ю/g, "ju")
		.replace(/я/g, "ja")

		.replace(/А/g, "A")
		.replace(/Ӑ/g, "Ă")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Д/g, "D")
		.replace(/Е/g, "E")
		.replace(/Ё/g, "Jo")
		.replace(/Ӗ/g, "Ĕ")
		.replace(/Ж/g, "Ž")
		.replace(/З/g, "Z")
		.replace(/И/g, "I")
		.replace(/Й/g, "J")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/О/g, "O")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Ҫ/g, "Ś")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ӳ/g, "Ü")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "H")
		.replace(/Ц/g, "Ts")
		.replace(/Ч/g, "Č")
		.replace(/Ш/g, "Š")
		.replace(/Щ/g, "Šč")
		.replace(/Ъ/g, "ʺ")
		.replace(/Ы/g, "Y")
		.replace(/Ь/g, "ʹ")
		.replace(/Э/g, "E")
		.replace(/Ю/g, "Ju")
		.replace(/Я/g, "Ja")
		.replace(/«/g, "\u201c")
		.replace(/»/g, "\u201d");
}

function latcyr() {}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}