function cyrlat() {
	document.transcription.text2.value = document.transcription.text1.value

		.replace(/(0|1|2|3|4|5|6|7|8|9)Х/g, "$1X")
		.replace(/(0|1|2|3|4|5|6|7|8|9)х/g, "$1x")
		.replace(/Х(0|1|2|3|4|5|6|7|8|9)/g, "X$1")
		.replace(/х(0|1|2|3|4|5|6|7|8|9)/g, "x$1")

		.replace(/(Д|Т|З|С|Л|Н|д|т|з|с|л|н)Е/g, "$1ЬЭ")
		.replace(/(Д|Т|З|С|Л|Н|д|т|з|с|л|н)е/g, "$1ьэ")
		.replace(/(Д|Т|З|С|Л|Н|д|т|з|с|л|н)Ё/g, "$1ЬО")
		.replace(/(Д|Т|З|С|Л|Н|д|т|з|с|л|н)ё/g, "$1ьо")
		.replace(/(Д|Т|З|С|Л|Н|д|т|з|с|л|н)И/g, "$1ЬӤ")
		.replace(/(Д|Т|З|С|Л|Н|д|т|з|с|л|н)и/g, "$1ьӥ")
		.replace(/(Д|Т|З|С|Л|Н|д|т|з|с|л|н)Ю/g, "$1ЬУ")
		.replace(/(Д|Т|З|С|Л|Н|д|т|з|с|л|н)ю/g, "$1ьу")
		.replace(/(Д|Т|З|С|Л|Н|д|т|з|с|л|н)Я/g, "$1ЬА")
		.replace(/(Д|Т|З|С|Л|Н|д|т|з|с|л|н)я/g, "$1ьа")

		.replace(/(Б|В|Г|Ж|Ӝ|Ӟ|К|М|П|Р|Ф|Х|Ц|Ч|Ӵ|Ш|Щ|б|в|г|ж|ӝ|ӟ|к|м|п|р|ф|х|ц|ч|ӵ|ш|щ)э/g, "$1ë")
		.replace(/(Б|В|Г|Ж|Ӝ|Ӟ|К|М|П|Р|Ф|Х|Ц|Ч|Ӵ|Ш|Щ|б|в|г|ж|ӝ|ӟ|к|м|п|р|ф|х|ц|ч|ӵ|ш|щ)Э/g, "$1Ë")
		.replace(/(Б|В|Г|Ж|Ӝ|Ӟ|К|М|П|Р|Ф|Х|Ц|Ч|Ӵ|Ш|Щ|б|в|г|ж|ӝ|ӟ|к|м|п|р|ф|х|ц|ч|ӵ|ш|щ)е/g, "$1э")
		.replace(/(Б|В|Г|Ж|Ӝ|Ӟ|К|М|П|Р|Ф|Х|Ц|Ч|Ӵ|Ш|Щ|б|в|г|ж|ӝ|ӟ|к|м|п|р|ф|х|ц|ч|ӵ|ш|щ)Е/g, "$1Э")

		.replace(/Е/g, "Йэ")
		.replace(/Ё/g, "Йо")
		.replace(/И/g, "Ӥ")
		.replace(/Ю/g, "Йу")
		.replace(/Я/g, "Йа")
		.replace(/е/g, "йэ")
		.replace(/ё/g, "йо")
		.replace(/и/g, "ӥ")
		.replace(/ю/g, "йу")
		.replace(/я/g, "йа")

		.replace(/ддь/g, "ďď")
		.replace(/тть/g, "ťť")
		.replace(/ззь/g, "źź")
		.replace(/ссь/g, "śś")
		.replace(/лль/g, "lly")
		.replace(/ннь/g, "ńń")
		.replace(/Ддь/g, "Ďď")
		.replace(/Тть/g, "Ťť")
		.replace(/Ззь/g, "Źź")
		.replace(/Ссь/g, "Śś")
		.replace(/Лль/g, "Lly")
		.replace(/Ннь/g, "Ńń")
		.replace(/ДД(Ь|ь)/g, "ĎĎ")
		.replace(/ТТ(Ь|ь)/g, "ŤŤ")
		.replace(/ЗЗ(Ь|ь)/g, "ŹŹ")
		.replace(/СС(Ь|ь)/g, "ŚŚ")
		.replace(/НН(Ь|ь)/g, "ŃŃ")
		.replace(/ЛЛЬ/g, "LLY")
		.replace(/ЛЛь/g, "LLy")

		.replace(/дь/g, "ď")
		.replace(/ть/g, "ť")
		.replace(/зь/g, "ź")
		.replace(/сь/g, "ś")
		.replace(/ль/g, "ly")
		.replace(/нь/g, "ń")
		.replace(/Д(Ь|ь)/g, "Ď")
		.replace(/Т(Ь|ь)/g, "Ť")
		.replace(/З(Ь|ь)/g, "Ź")
		.replace(/С(Ь|ь)/g, "Ś")
		.replace(/Л(Ь|ь)/g, "Ly")
		.replace(/Н(Ь|ь)/g, "Ń")

		.replace(/дъ/g, "д")
		.replace(/тъ/g, "т")
		.replace(/зъ/g, "з")
		.replace(/съ/g, "с")
		.replace(/лъ/g, "л")
		.replace(/нъ/g, "н")
		.replace(/Д(Ъ|ъ)/g, "Д")
		.replace(/Т(Ъ|ъ)/g, "Т")
		.replace(/З(Ъ|ъ)/g, "З")
		.replace(/С(Ъ|ъ)/g, "С")
		.replace(/Л(Ъ|ъ)/g, "Л")
		.replace(/Н(Ъ|ъ)/g, "Н")

		.replace(/ӞӞ/g, "DDŹ")
		.replace(/Ӟӟ/g, "Ddź")
		.replace(/ӟӟ/g, "ddź")

		.replace(/а/g, "a")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/д/g, "d")
		.replace(/ж/g, "ž")
		.replace(/ӝ/g, "j")
		.replace(/з/g, "z")
		.replace(/ӟ/g, "dź")
		.replace(/и/g, "i")
		.replace(/ӥ/g, "i")
		.replace(/й/g, "y")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/о/g, "o")
		.replace(/ӧ/g, "ö")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ф/g, "f")
		.replace(/х/g, "h")
		.replace(/ц/g, "c")
		.replace(/ч/g, "ć")
		.replace(/ӵ/g, "č")
		.replace(/ш/g, "š")
		.replace(/щ/g, "ś")
		.replace(/ъ/g, "ʼ")
		.replace(/ы/g, "ï")
		.replace(/ь/g, "y")
		.replace(/э/g, "e")

		.replace(/А/g, "A")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Д/g, "D")
		.replace(/Ж/g, "Ž")
		.replace(/Ӝ/g, "J")
		.replace(/З/g, "Z")
		.replace(/Ӟ/g, "Dź")
		.replace(/И/g, "I")
		.replace(/Ӥ/g, "I")
		.replace(/Й/g, "Y")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/О/g, "O")
		.replace(/Ӧ/g, "Ö")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "H")
		.replace(/Ц/g, "C")
		.replace(/Ч/g, "Ć")
		.replace(/Ӵ/g, "Č")
		.replace(/Ш/g, "Š")
		.replace(/Щ/g, "Ś")
		.replace(/Ъ/g, "ʼ")
		.replace(/Ы/g, "Ï")
		.replace(/Ь/g, "Y")
		.replace(/Э/g, "E")
		.replace(/«/g, "\u201c")
		.replace(/»/g, "\u201d");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}