function latcyr() {}

function cyrlat() {
	document.transcription.text2.value = document.transcription.text1.value
		.replace(/(Б|В|Г|Д|Ж|З|К|Л|М|Н|Ң|П|Р|С|Т|Ф|Х|Һ|Ц|Ч|Җ|Ш|Щ|б|в|г|д|ж|з|к|л|м|н|ң|п|р|с|т|ф|х|һ|ц|ч|җ|ш|щ)(Э|э)/g, "$1$2\u0300")
		.replace(/(Б|В|Г|Д|Ж|З|К|Л|М|Н|Ң|П|Р|С|Т|Ф|Х|Һ|Ц|Ч|Җ|Ш|Щ|б|в|г|д|ж|з|к|л|м|н|ң|п|р|с|т|ф|х|һ|ц|ч|җ|ш|щ)Е/g, "$1Э")
		.replace(/(Б|В|Г|Д|Ж|З|К|Л|М|Н|Ң|П|Р|С|Т|Ф|Х|Һ|Ц|Ч|Җ|Ш|Щ|б|в|г|д|ж|з|к|л|м|н|ң|п|р|с|т|ф|х|һ|ц|ч|җ|ш|щ)е/g, "$1э")
		.replace(/(Э|э)\u0300(Э|э)/g, "$1$2")

		.replace(/(\p{Uppercase})(\p{Uppercase}) Е/ug, "$1$2 ЙЭ")
		.replace(/Е (\p{Uppercase})(\p{Uppercase})/ug, "ЙЭ $1$2")
		.replace(/Е(\p{Uppercase})/ug, "ЙЭ$1")
		.replace(/(Е|е|Э|э)Е/g, "$1Э")
		.replace(/(Е|е|Э|э)е/g, "$1э")
		.replace(/Е/g, "Йэ")
		.replace(/е/g, "йэ")

		.replace(/Ё/g, "Йо")
		.replace(/Ю/g, "Йу")
		.replace(/Я/g, "Йа")
		.replace(/ё/g, "йо")
		.replace(/ю/g, "йу")
		.replace(/я/g, "йа")

		.replace(/(А|Ә|И|О|Ө|У|Ү|Э|а|ә|и|о|ө|у|ү|э)(И|и)/g, "$1\u02bc$2")
		.replace(/(И|и)(А|Ә|И|О|Ө|У|Ү|Э|а|ә|и|о|ө|у|ү|э)/g, "$1\u02bc$2")

		.replace(/(А|Ә|И|О|Ө|У|Ү|Ы|Э|а|ә|и|о|ө|у|ү|ы|э)й(А|Ә|И|О|Ө|У|Ү|Ы|Э|а|ә|и|о|ө|у|ү|ы|э)/g, "$1ӣ$2")
		.replace(/(А|Ә|И|О|Ө|У|Ү|Ы|Э|а|ә|и|о|ө|у|ү|ы|э)Й(А|Ә|И|О|Ө|У|Ү|Ы|Э|а|ә|и|о|ө|у|ү|ы|э)/g, "$1Ӣ$2")
		.replace(/(А|Ә|Б|В|Г|Д|Ж|З|И|Й|К|Л|М|Н|Ң|О|Ө|П|Р|С|Т|У|Ү|Ф|Х|Һ|Ц|Ч|Ш|Щ|Ъ|Ь|Э|а|ә|б|в|г|д|ж|җ|з|и|й|к|л|м|н|ң|о|ө|п|р|с|т|у|ү|ф|х|һ|ц|ч|ш|щ|ъ|ь|э)й/g, "$1и")
		.replace(/(А|Ә|Б|В|Г|Д|Ж|З|И|Й|К|Л|М|Н|Ң|О|Ө|П|Р|С|Т|У|Ү|Ф|Х|Һ|Ц|Ч|Ш|Щ|Ъ|Ь|Э|а|ә|б|в|г|д|ж|җ|з|и|й|к|л|м|н|ң|о|ө|п|р|с|т|у|ү|ф|х|һ|ц|ч|ш|щ|ъ|ь|э)Й/g, "$1И")
		.replace(/ӣ/g, "й")
		.replace(/Ӣ/g, "Й")

		.replace(/а/g, "a")
		.replace(/ә/g, "ä")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/д/g, "d")
		.replace(/ж/g, "ž")
		.replace(/җ/g, "j")
		.replace(/з/g, "z")
		.replace(/и/g, "i")
		.replace(/й/g, "y")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/ң/g, "ṅ")
		.replace(/о/g, "o")
		.replace(/ө/g, "ö")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ү/g, "ü")
		.replace(/ф/g, "f")
		.replace(/х/g, "ḥ")
		.replace(/һ/g, "h")
		.replace(/ц/g, "c")
		.replace(/ч/g, "č")
		.replace(/ш/g, "š")
		.replace(/щ/g, "ś")
		.replace(/ъ/g, "\u02bc")
		.replace(/ы/g, "ï")
		.replace(/ь/g, "ÿ")
		.replace(/э/g, "e")
		.replace(/А/g, "A")
		.replace(/Ә/g, "Ä")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Д/g, "D")
		.replace(/Ж/g, "Ž")
		.replace(/Җ/g, "J")
		.replace(/З/g, "Z")
		.replace(/И/g, "I")
		.replace(/Й/g, "Y")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/Ң/g, "Ṅ")
		.replace(/О/g, "O")
		.replace(/Ө/g, "Ö")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ү/g, "Ü")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "Ḥ")
		.replace(/Һ/g, "H")
		.replace(/Ц/g, "C")
		.replace(/Ч/g, "Č")
		.replace(/Ш/g, "Š")
		.replace(/Щ/g, "Ś")
		.replace(/Ъ/g, "\u02bc")
		.replace(/Ы/g, "Ï")
		.replace(/Ь/g, "Ÿ")
		.replace(/Э/g, "E");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}