
var translit;
var car;

function cyrlat () {
translit = document.transcription.text1.value;
translit = translit.replace(/бе/g, "бэ");
translit = translit.replace(/ве/g, "вэ");
translit = translit.replace(/ге/g, "гэ");
translit = translit.replace(/ғе/g, "ғэ");
translit = translit.replace(/де/g, "дэ");
translit = translit.replace(/же/g, "жэ");
translit = translit.replace(/зе/g, "зэ");
translit = translit.replace(/ке/g, "кэ");
translit = translit.replace(/қе/g, "қэ");
translit = translit.replace(/ле/g, "лэ");
translit = translit.replace(/ме/g, "мэ");
translit = translit.replace(/не/g, "нэ");
translit = translit.replace(/пе/g, "пэ");
translit = translit.replace(/ре/g, "рэ");
translit = translit.replace(/се/g, "сэ");
translit = translit.replace(/те/g, "тэ");
translit = translit.replace(/фе/g, "фэ");
translit = translit.replace(/хе/g, "хэ");
translit = translit.replace(/ҳе/g, "ҳэ");
translit = translit.replace(/це/g, "цэ");
translit = translit.replace(/че/g, "чэ");
translit = translit.replace(/ше/g, "шэ");
translit = translit.replace(/ще/g, "щэ");
translit = translit.replace(/ъе/g, "ъэ");

translit = translit.replace(/Бе/g, "Бэ");
translit = translit.replace(/Ве/g, "Вэ");
translit = translit.replace(/Ге/g, "Гэ");
translit = translit.replace(/Ғе/g, "Ғэ");
translit = translit.replace(/Де/g, "Дэ");
translit = translit.replace(/Же/g, "Жэ");
translit = translit.replace(/Зе/g, "Зэ");
translit = translit.replace(/Ке/g, "Кэ");
translit = translit.replace(/Қе/g, "Қэ");
translit = translit.replace(/Ле/g, "Лэ");
translit = translit.replace(/Ме/g, "Мэ");
translit = translit.replace(/Не/g, "Нэ");
translit = translit.replace(/Пе/g, "Пэ");
translit = translit.replace(/Ре/g, "Рэ");
translit = translit.replace(/Се/g, "Сэ");
translit = translit.replace(/Те/g, "Тэ");
translit = translit.replace(/Фе/g, "Фэ");
translit = translit.replace(/Хе/g, "Хэ");
translit = translit.replace(/Ҳе/g, "Ҳэ");
translit = translit.replace(/Це/g, "Цэ");
translit = translit.replace(/Че/g, "Чэ");
translit = translit.replace(/Ше/g, "Шэ");
translit = translit.replace(/Ще/g, "Щэ");
translit = translit.replace(/Ъе/g, "Ъэ");

translit = translit.replace(/БЕ/g, "БЭ");
translit = translit.replace(/ВЕ/g, "ВЭ");
translit = translit.replace(/ГЕ/g, "ГЭ");
translit = translit.replace(/ҒЕ/g, "ҒЭ");
translit = translit.replace(/ДЕ/g, "ДЭ");
translit = translit.replace(/ЖЕ/g, "ЖЭ");
translit = translit.replace(/ЗЕ/g, "ЗЭ");
translit = translit.replace(/КЕ/g, "КЭ");
translit = translit.replace(/ҚЕ/g, "ҚЭ");
translit = translit.replace(/ЛЕ/g, "ЛЭ");
translit = translit.replace(/МЕ/g, "МЭ");
translit = translit.replace(/НЕ/g, "НЭ");
translit = translit.replace(/ПЕ/g, "ПЭ");
translit = translit.replace(/РЕ/g, "РЭ");
translit = translit.replace(/СЕ/g, "СЭ");
translit = translit.replace(/ТЕ/g, "ТЭ");
translit = translit.replace(/ФЕ/g, "ФЭ");
translit = translit.replace(/ХЕ/g, "ХЭ");
translit = translit.replace(/ҲЕ/g, "ҲЭ");
translit = translit.replace(/ЦЕ/g, "ЦЭ");
translit = translit.replace(/ЧЕ/g, "ЧЭ");
translit = translit.replace(/ШЕ/g, "ШЭ");
translit = translit.replace(/ЩЕ/g, "ЩЭ");
translit = translit.replace(/ЪЕ/g, "ЪЭ");

translit = translit.replace(/бйе/g, "бйэ");
translit = translit.replace(/вйе/g, "вйэ");
translit = translit.replace(/гйе/g, "гйэ");
translit = translit.replace(/ғйе/g, "ғйэ");
translit = translit.replace(/дйе/g, "дйэ");
translit = translit.replace(/жйе/g, "жйэ");
translit = translit.replace(/зйе/g, "зйэ");
translit = translit.replace(/кйе/g, "кйэ");
translit = translit.replace(/қйе/g, "қйэ");
translit = translit.replace(/лйе/g, "лйэ");
translit = translit.replace(/мйе/g, "мйэ");
translit = translit.replace(/нйе/g, "нйэ");
translit = translit.replace(/пйе/g, "пйэ");
translit = translit.replace(/рйе/g, "рйэ");
translit = translit.replace(/сйе/g, "сйэ");
translit = translit.replace(/тйе/g, "тйэ");
translit = translit.replace(/фйе/g, "фйэ");
translit = translit.replace(/хйе/g, "хйэ");
translit = translit.replace(/ҳйе/g, "ҳйэ");
translit = translit.replace(/цйе/g, "цйэ");
translit = translit.replace(/чйе/g, "чйэ");
translit = translit.replace(/шйе/g, "шйэ");
translit = translit.replace(/щйе/g, "щйэ");
translit = translit.replace(/ъйе/g, "ъйэ");

translit = translit.replace(/Бйе/g, "Бйэ");
translit = translit.replace(/Вйе/g, "Вйэ");
translit = translit.replace(/Гйе/g, "Гйэ");
translit = translit.replace(/Ғйе/g, "Ғйэ");
translit = translit.replace(/Дйе/g, "Дйэ");
translit = translit.replace(/Жйе/g, "Жйэ");
translit = translit.replace(/Зйе/g, "Зйэ");
translit = translit.replace(/Кйе/g, "Кйэ");
translit = translit.replace(/Қйе/g, "Қйэ");
translit = translit.replace(/Лйе/g, "Лйэ");
translit = translit.replace(/Мйе/g, "Мйэ");
translit = translit.replace(/Нйе/g, "Нйэ");
translit = translit.replace(/Пйе/g, "Пйэ");
translit = translit.replace(/Рйе/g, "Рйэ");
translit = translit.replace(/Сйе/g, "Сйэ");
translit = translit.replace(/Тйе/g, "Тйэ");
translit = translit.replace(/Фйе/g, "Фйэ");
translit = translit.replace(/Хйе/g, "Хйэ");
translit = translit.replace(/Ҳйе/g, "Ҳйэ");
translit = translit.replace(/Цйе/g, "Цйэ");
translit = translit.replace(/Чйе/g, "Чйэ");
translit = translit.replace(/Шйе/g, "Шйэ");
translit = translit.replace(/Щйе/g, "Щйэ");
translit = translit.replace(/Ъйе/g, "Ъйэ");

translit = translit.replace(/БЙЕ/g, "БЙЭ");
translit = translit.replace(/ВЙЕ/g, "ВЙЭ");
translit = translit.replace(/ГЙЕ/g, "ГЙЭ");
translit = translit.replace(/ҒЙЕ/g, "ҒЙЭ");
translit = translit.replace(/ДЙЕ/g, "ДЙЭ");
translit = translit.replace(/ЖЙЕ/g, "ЖЙЭ");
translit = translit.replace(/ЗЙЕ/g, "ЗЙЭ");
translit = translit.replace(/КЙЕ/g, "КЙЭ");
translit = translit.replace(/ҚЙЕ/g, "ҚЙЭ");
translit = translit.replace(/ЛЙЕ/g, "ЛЙЭ");
translit = translit.replace(/МЙЕ/g, "МЙЭ");
translit = translit.replace(/НЙЕ/g, "НЙЭ");
translit = translit.replace(/ПЙЕ/g, "ПЙЭ");
translit = translit.replace(/РЙЕ/g, "РЙЭ");
translit = translit.replace(/СЙЕ/g, "СЙЭ");
translit = translit.replace(/ТЙЕ/g, "ТЙЭ");
translit = translit.replace(/ФЙЕ/g, "ФЙЭ");
translit = translit.replace(/ХЙЕ/g, "ХЙЭ");
translit = translit.replace(/ҲЙЕ/g, "ҲЙЭ");
translit = translit.replace(/ЦЙЕ/g, "ЦЙЭ");
translit = translit.replace(/ЧЙЕ/g, "ЧЙЭ");
translit = translit.replace(/ШЙЕ/g, "ШЙЭ");
translit = translit.replace(/ЩЙЕ/g, "ЩЙЭ");
translit = translit.replace(/ЪЙЕ/g, "ЪЙЭ");

translit = translit.replace(/сҳ/g, "s·h");
translit = translit.replace(/Сҳ/g, "S·h");
translit = translit.replace(/СҲ/g, "S·H");

translit = translit.replace(/гҳ/g, "g·h");
translit = translit.replace(/Гҳ/g, "G·h");
translit = translit.replace(/ГҲ/g, "G·H");

translit = translit.replace(/кҳ/g, "k·h");
translit = translit.replace(/Кҳ/g, "K·h");
translit = translit.replace(/КҲ/g, "K·H");

translit = translit.replace(/цҳ/g, "ts·h");
translit = translit.replace(/Цҳ/g, "Ts·h");
translit = translit.replace(/ЦҲ/g, "TS·H");

translit = translit.replace(/а/g, "a");
translit = translit.replace(/б/g, "b");
translit = translit.replace(/в/g, "w");
translit = translit.replace(/г/g, "g");
translit = translit.replace(/ғ/g, "gh");
translit = translit.replace(/д/g, "d");
translit = translit.replace(/е/g, "ye");
translit = translit.replace(/ё/g, "yo");
translit = translit.replace(/ж/g, "j");
translit = translit.replace(/з/g, "z");
translit = translit.replace(/и/g, "i");
translit = translit.replace(/й/g, "y");
translit = translit.replace(/к/g, "k");
translit = translit.replace(/қ/g, "q");
translit = translit.replace(/л/g, "l");
translit = translit.replace(/м/g, "m");
translit = translit.replace(/н/g, "n");
translit = translit.replace(/о/g, "o");
translit = translit.replace(/п/g, "p");
translit = translit.replace(/р/g, "r");
translit = translit.replace(/с/g, "s");
translit = translit.replace(/т/g, "t");
translit = translit.replace(/у/g, "u");
translit = translit.replace(/ў/g, "ŭ");
translit = translit.replace(/ф/g, "f");
translit = translit.replace(/х/g, "kh");
translit = translit.replace(/ҳ/g, "h");
translit = translit.replace(/ц/g, "ts");
translit = translit.replace(/ч/g, "ch");
translit = translit.replace(/ш/g, "sh");
translit = translit.replace(/щ/g, "shch");
translit = translit.replace(/ь/g, "ʼ");
translit = translit.replace(/ъ/g, "ʼ");
translit = translit.replace(/э/g, "e");
translit = translit.replace(/ю/g, "yu");
translit = translit.replace(/я/g, "ya");

translit = translit.replace(/А/g, "A");
translit = translit.replace(/Б/g, "B");
translit = translit.replace(/В/g, "W");
translit = translit.replace(/Г/g, "G");
translit = translit.replace(/Ғ/g, "Gh");
translit = translit.replace(/Д/g, "D");
translit = translit.replace(/Е/g, "Ye");
translit = translit.replace(/Ё/g, "Yo");
translit = translit.replace(/Ж/g, "J");
translit = translit.replace(/З/g, "Z");
translit = translit.replace(/И/g, "I");
translit = translit.replace(/Й/g, "Y");
translit = translit.replace(/К/g, "K");
translit = translit.replace(/Қ/g, "Q");
translit = translit.replace(/Л/g, "L");
translit = translit.replace(/М/g, "M");
translit = translit.replace(/Н/g, "N");
translit = translit.replace(/О/g, "O");
translit = translit.replace(/П/g, "P");
translit = translit.replace(/Р/g, "R");
translit = translit.replace(/С/g, "S");
translit = translit.replace(/Т/g, "T");
translit = translit.replace(/У/g, "U");
translit = translit.replace(/Ў/g, "Ŭ");
translit = translit.replace(/Ф/g, "F");
translit = translit.replace(/Х/g, "Kh");
translit = translit.replace(/Ҳ/g, "H");
translit = translit.replace(/Ц/g, "Ts");
translit = translit.replace(/Ч/g, "Ch");
translit = translit.replace(/Ш/g, "Sh");
translit = translit.replace(/Щ/g, "Shch");
translit = translit.replace(/Ь/g, "ʼ");
translit = translit.replace(/Ъ/g, "ʼ");
translit = translit.replace(/Э/g, "E");
translit = translit.replace(/Ю/g, "Yu");
translit = translit.replace(/Я/g, "Ya");
document.transcription.text2.value = translit;
}

function latcyr () {
}

function copy1()
{ textRange=document.transcription.text1.createTextRange();
textRange.execCommand("Copy");
textRange="";
}
function copy2()
{ textRange=document.transcription.text2.createTextRange();
textRange.execCommand("Copy");
textRange="";
}
