//  copyright lexilogos.com
var car;
function latcyr () {
}
function cyrlat () {
car = document.transcription.text1.value;
translit = document.transcription.text1.value;
  translit = translit.replace(/ғ/g, "ҕ");
  translit = translit.replace(/Ғ/g, "Ҕ");
  translit = translit.replace(/ҳ/g, "һ");
  translit = translit.replace(/Ҳ/g, "Һ");
  translit = translit.replace(/ң/g, "ҥ");
  translit = translit.replace(/Ң/g, "Ҥ");
  car = car.replace(/ғ/g, "ҕ");
  car = car.replace(/Ғ/g, "Ҕ");
  car = car.replace(/ҳ/g, "һ");
  car = car.replace(/Ҳ/g, "Һ");
  car = car.replace(/ң/g, "ҥ");
  car = car.replace(/Ң/g, "Ҥ");
  
  car = car.replace(/а/g, "a");
  car = car.replace(/б/g, "b");
  car = car.replace(/в/g, "w");
  car = car.replace(/г/g, "g");
  car = car.replace(/ҕ/g, "ǧ");
  car = car.replace(/д/g, "d");
  car = car.replace(/е/g, "ê");
  car = car.replace(/ж/g, "ž");
  car = car.replace(/з/g, "z");
  car = car.replace(/и/g, "i");
  car = car.replace(/й/g, "ý");
  car = car.replace(/к/g, "k");
  car = car.replace(/л/g, "l");
  car = car.replace(/м/g, "m");
  car = car.replace(/н/g, "n");
  car = car.replace(/ҥ/g, "ň");
  car = car.replace(/о/g, "o");
  car = car.replace(/ө/g, "ö");
  car = car.replace(/п/g, "p");
  car = car.replace(/р/g, "r");
  car = car.replace(/с/g, "s");
  car = car.replace(/һ/g, "h");
  car = car.replace(/т/g, "t");
  car = car.replace(/у/g, "u");
  car = car.replace(/ү/g, "ü");
  car = car.replace(/ф/g, "f");
  car = car.replace(/х/g, "q");
  car = car.replace(/ц/g, "ts");
  car = car.replace(/ч/g, "ç");
  car = car.replace(/ш/g, "ş");
  car = car.replace(/щ/g, "şş");
  car = car.replace(/ы/g, "y");
  car = car.replace(/э/g, "e");
  car = car.replace(/ъ/g, "ʼ");
  car = car.replace(/ь/g, "Ь");
  car = car.replace(/ё/g, "ýo");
  car = car.replace(/ю/g, "ýu");
  car = car.replace(/я/g, "ýa");
  car = car.replace(/А/g, "A");
  car = car.replace(/Б/g, "B");
  car = car.replace(/В/g, "W");
  car = car.replace(/Г/g, "G");
  car = car.replace(/Ҕ/g, "Ǧ");
  car = car.replace(/Д/g, "D");
  car = car.replace(/Е/g, "Ê");
  car = car.replace(/Ж/g, "Ž");
  car = car.replace(/З/g, "Z");
  car = car.replace(/И/g, "I");
  car = car.replace(/Й/g, "Ý");
  car = car.replace(/К/g, "K");
  car = car.replace(/Л/g, "L");
  car = car.replace(/М/g, "M");
  car = car.replace(/Н/g, "N");
  car = car.replace(/Ҥ/g, "Ň");
  car = car.replace(/О/g, "O");
  car = car.replace(/Ө/g, "Ö");
  car = car.replace(/П/g, "P");
  car = car.replace(/Р/g, "R");
  car = car.replace(/С/g, "S");
  car = car.replace(/Һ/g, "H");
  car = car.replace(/Т/g, "T");
  car = car.replace(/У/g, "U");
  car = car.replace(/Ү/g, "Ü");
  car = car.replace(/Ф/g, "F");
  car = car.replace(/Х/g, "Q");
  car = car.replace(/Ц/g, "Ts");
  car = car.replace(/Ч/g, "Ç");
  car = car.replace(/Ш/g, "Ş");
  car = car.replace(/Щ/g, "ŞŞ");
  car = car.replace(/Ы/g, "Y");
  car = car.replace(/Э/g, "E");
  car = car.replace(/Ъ/g, "ʼ");
  car = car.replace(/Ё/g, "Ýo");
  car = car.replace(/Ю/g, "Ýu");
  car = car.replace(/Я/g, "Ýa");
  car = car.replace(/dЬ/g, "j");
  car = car.replace(/DЬ/g, "J");
  car = car.replace(/nЬ/g, "ný");
  car = car.replace(/NЬ/g, "Ný");
  car = car.replace(/Ь/g, "");
  car = car.replace(/»/g, "\u201d");
  car = car.replace(/«/g, "\u201c");
document.transcription.text1.value=translit;
document.transcription.text2.value=car;
}
function copy1()
{ textRange=document.transcription.text1.createTextRange();   textRange.execCommand("Copy");   textRange="";
}
function copy2()
{ textRange=document.transcription.text2.createTextRange();   textRange.execCommand("Copy");   textRange="";
}