var car;
function cyrlat () {
car = document.transcription.text1.value;
car = car.replace(/Ե(Ւ|ւ)/g, "Վ");
car = car.replace(/եւ/g, "վ");
car = car.replace(/(Ք|Կ)ԵԱ/g, "$1Â");
car = car.replace(/(Ք|Կ|ք|կ)եա/g, "$1â");
car = car.replace(/(Ք|Կ)ԵՈՒ/g, "$1Û");
car = car.replace(/(Ք|Կ|ք|կ)եու/g, "$1û");
car = car.replace(/Ո(Ւ|ւ)/g, "U");
car = car.replace(/ու/g, "u");
car = car.replace(/Ի(Ւ|ւ)/g, "Ü");
car = car.replace(/իւ/g, "ü");
car = car.replace(/Է(Օ|օ)/g, "Ö");
car = car.replace(/էօ/g, "ö");
car = car.replace(/Ն(Կ|կ)/g, "N");
car = car.replace(/նկ/g, "n");

car = car.replace(/Ա/g, "A");
car = car.replace(/Բ/g, "Ḅ"); //b/
car = car.replace(/Գ/g, "K"); //g/
car = car.replace(/Դ/g, "Ḍ"); //d/
car = car.replace(/Ե/g, "Y");
car = car.replace(/Զ/g, "Z");
car = car.replace(/Է/g, "E");
car = car.replace(/Ը/g, "I");
car = car.replace(/Թ/g, "T"); //tʰ/
car = car.replace(/Ժ/g, "J");
car = car.replace(/Ի/g, "İ");
car = car.replace(/Լ/g, "L");
car = car.replace(/Խ/g, "H");
car = car.replace(/Ծ/g, "Dz"); //ts/
car = car.replace(/Կ/g, "G"); //k/
car = car.replace(/Հ/g, "H");
car = car.replace(/Ձ/g, "Ḍz"); //dz/
car = car.replace(/Ղ/g, "Ġ");
car = car.replace(/Ճ/g, "C"); //tʃ/
car = car.replace(/Մ/g, "M");
car = car.replace(/Յ/g, "Y");
car = car.replace(/Ն/g, "N");
car = car.replace(/Շ/g, "Ş");
car = car.replace(/Ո/g, "O");
car = car.replace(/Չ/g, "Ç"); //tʃʰ/
car = car.replace(/Պ/g, "B"); //p/
car = car.replace(/Ջ/g, "Ḍj"); //dʒ/
car = car.replace(/Ռ/g, "Ř");
car = car.replace(/Ս/g, "S");
car = car.replace(/Վ/g, "V");
car = car.replace(/Տ/g, "D"); //t/
car = car.replace(/Ր/g, "R");
car = car.replace(/Ց/g, "C"); //tsʰ/
car = car.replace(/Ւ/g, "W");
car = car.replace(/Փ/g, "P"); //pʰ/
car = car.replace(/Ք/g, "K"); //kʰ/
car = car.replace(/Օ/g, "O");
car = car.replace(/Ֆ/g, "F");
car = car.replace(/ա/g, "a");
car = car.replace(/բ/g, "ḅ"); //b/
car = car.replace(/գ/g, "k"); //g/
car = car.replace(/դ/g, "ḍ"); //d/
car = car.replace(/ե/g, "y");
car = car.replace(/զ/g, "z");
car = car.replace(/է/g, "e");
car = car.replace(/ը/g, "ı");
car = car.replace(/թ/g, "t"); //tʰ/
car = car.replace(/ժ/g, "j");
car = car.replace(/ի/g, "i");
car = car.replace(/լ/g, "l");
car = car.replace(/խ/g, "h");
car = car.replace(/ծ/g, "dz"); //ts/
car = car.replace(/կ/g, "g"); //k/
car = car.replace(/հ/g, "h");
car = car.replace(/ձ/g, "ḍz"); //dz/
car = car.replace(/ղ/g, "ġ");
car = car.replace(/ճ/g, "c"); //tʃ/
car = car.replace(/մ/g, "m");
car = car.replace(/յ/g, "y");
car = car.replace(/ն/g, "n");
car = car.replace(/շ/g, "ş");
car = car.replace(/ո/g, "o");
car = car.replace(/չ/g, "ç"); //tʃʰ/
car = car.replace(/պ/g, "b"); //p/
car = car.replace(/ջ/g, "ḍj"); //dʒ/
car = car.replace(/ռ/g, "ř");
car = car.replace(/ս/g, "s");
car = car.replace(/վ/g, "v");
car = car.replace(/տ/g, "d"); //t/
car = car.replace(/ր/g, "r");
car = car.replace(/ց/g, "c"); //tsʰ/
car = car.replace(/ւ/g, "w");
car = car.replace(/փ/g, "p"); //pʰ/
car = car.replace(/ք/g, "k"); //kʰ/
car = car.replace(/օ/g, "o");
car = car.replace(/ֆ/g, "f");

car = car.replace(/(A|I|O|U|E|İ|Ö|Ü)(G|Ġ)/g, "$1Ğ");
car = car.replace(/(A|I|O|U|E|İ|Ö|Ü|a|ı|o|u|e|i|ö|ü)(g|ġ)/g, "$1ğ");
car = car.replace(/Ġ/g, "G");
car = car.replace(/ġ/g, "g");

car = car.replace(/:/g, "։");
car = car.replace(/՝/g, ";");
car = car.replace(/`/g, ";");
car = car.replace(/․/g, ":");
car = car.replace(/։/g, ".");
car = car.replace(/՜/g, "");
car = car.replace(/՞/g, "");
car = car.replace(/֊/g, "-");
car = car.replace(/՚/g, "’");
car = car.replace(/՛/g, "");
document.transcription.text2.value=car;
}
function latcyr () {
car = document.transcription.text2.value;
car = car.replace(/(A|Â|E|I|İ|Î|O|Ö|U|Û|Ü)Y/g, "$1Ẏ");
car = car.replace(/(A|Â|E|I|İ|Î|O|Ö|U|Û|Ü|a|â|e|ı|i|î|o|ö|u|û|ü)y/g, "$1ẏ");
car = car.replace(/Ẏ(A|Â|E|I|İ|Î|O|Ö|U|Û|Ü|a|â|e|ı|i|î|o|ö|u|û|ü)/g, "Y$1");
car = car.replace(/ẏ(a|â|e|ı|i|î|o|ö|u|û|ü)/g, "y$1");

car = car.replace(/(A|I|O|U)G/g, "$1Ġ");
car = car.replace(/(A|I|O|U|a|ı|o|u)g/g, "$1ġ");
car = car.replace(/(A|I|O|U)K/g, "$1Ḳ");
car = car.replace(/(A|I|O|U|a|ı|o|u)k/g, "$1ḳ");
car = car.replace(/G(A|I|O|U|a|ı|o|u)/g, "Ġ$1");
car = car.replace(/g(a|ı|o|u)/g, "ġ$1");
car = car.replace(/K(A|I|O|U|a|ı|o|u)/g, "Ḳ$1");
car = car.replace(/k(a|ı|o|u)/g, "ḳ$1");
car = car.replace(/Ġ(Â|E|İ|Î|Ö|Û|Ü|â|e|i|î|ö|û|ü)/g, "G$1");
car = car.replace(/ġ(â|e|i|î|ö|û|ü)/g, "g$1");
car = car.replace(/Ḳ(Â|E|İ|Î|Ö|Û|Ü|â|e|i|î|ö|û|ü)/g, "K$1");
car = car.replace(/ḳ(â|e|i|î|ö|û|ü)/g, "k$1");

car = car.replace(/(A|I|O|U)Ğ/g, "$1Ġ");
car = car.replace(/(A|I|O|U|a|ı|o|u)ğ/g, "$1ġ");
car = car.replace(/(E|İ|Ö|Ü)Ğ/g, "$1G");
car = car.replace(/(E|İ|Ö|Ü|e|i|ö|ü)ğ/g, "$1g");

car = car.replace(/(K|G)Â/g, "$1YA");
car = car.replace(/(K|G|k|g)â/g, "$1ya");
car = car.replace(/(K|G)Û/g, "$1YU");
car = car.replace(/(K|G|k|g)û/g, "$1yu");

car = car.replace(/Â/g, "A");
car = car.replace(/â/g, "a");
car = car.replace(/Î/g, "İẎ");
car = car.replace(/î/g, "iẏ");

car = car.replace(/A/g, "Ա");
car = car.replace(/a/g, "ա");
car = car.replace(/B/g, "Պ");
car = car.replace(/b/g, "պ");  
car = car.replace(/C/g, "Ճ");
car = car.replace(/c/g, "ճ");
car = car.replace(/Ç/g, "Չ");
car = car.replace(/ç/g, "չ");  
car = car.replace(/D/g, "Տ");
car = car.replace(/d/g, "տ");
car = car.replace(/E/g, "Է");
car = car.replace(/e/g, "է");  
car = car.replace(/F/g, "Ֆ");
car = car.replace(/f/g, "ֆ");
car = car.replace(/G/g, "Կ");
car = car.replace(/g/g, "կ"); 
car = car.replace(/Ġ/g, "Ղ");
car = car.replace(/ġ/g, "ղ");
car = car.replace(/H/g, "Հ");
car = car.replace(/h/g, "հ");  
car = car.replace(/I/g, "Ը");
car = car.replace(/ı/g, "ը");
car = car.replace(/İ/g, "Ի");
car = car.replace(/i/g, "ի");   
car = car.replace(/J/g, "Ժ");
car = car.replace(/j/g, "ժ");
car = car.replace(/K/g, "Ք");
car = car.replace(/k/g, "ք");  
car = car.replace(/Ḳ/g, "Գ");
car = car.replace(/ḳ/g, "գ");  
car = car.replace(/L/g, "Լ");
car = car.replace(/l/g, "լ");
car = car.replace(/M/g, "Մ");
car = car.replace(/m/g, "մ");  
car = car.replace(/N/g, "Ն");
car = car.replace(/n/g, "ն"); 
car = car.replace(/Ñ/g, "ՆԿ");
car = car.replace(/ñ/g, "նկ");
car = car.replace(/O/g, "Օ");
car = car.replace(/o/g, "օ");  
car = car.replace(/Ö/g, "Էօ");
car = car.replace(/ö/g, "էօ");
car = car.replace(/P/g, "Փ");
car = car.replace(/p/g, "փ");
car = car.replace(/Q/g, "Գ");
car = car.replace(/q/g, "գ");
car = car.replace(/R/g, "Ր");
car = car.replace(/r/g, "ր");
car = car.replace(/S/g, "Ս");
car = car.replace(/s/g, "ս");  
car = car.replace(/Ş/g, "Շ");
car = car.replace(/ş/g, "շ");
car = car.replace(/T/g, "Թ");
car = car.replace(/t/g, "թ");
car = car.replace(/U/g, "Ու");
car = car.replace(/u/g, "ու");
car = car.replace(/Ü/g, "Իւ");
car = car.replace(/ü/g, "իւ");  
car = car.replace(/V/g, "Վ");
car = car.replace(/v/g, "վ");
car = car.replace(/W/g, "Վ");
car = car.replace(/w/g, "վ");
car = car.replace(/X/g, "Խ");
car = car.replace(/x/g, "խ");
car = car.replace(/Y/g, "Ե");
car = car.replace(/y/g, "ե");
car = car.replace(/Ẏ/g, "Յ");
car = car.replace(/ẏ/g, "յ");
car = car.replace(/Z/g, "Զ");
car = car.replace(/z/g, "զ"); 
document.transcription.text1.value=car;
}
function copy1()
{ textRange=document.transcription.text1.createTextRange();   textRange.execCommand("Copy");   textRange="";
}
function copy2()
{ textRange=document.transcription.text2.createTextRange();   textRange.execCommand("Copy");   textRange="";
}
