function leftright() {
	document.transcription.text2.value = document.transcription.text1.value
		.replace(/[ЬЪьъ]/g, "")

		.replace(/([СЦ])Ҳ/g, "$1\u0027Ҳ")
		.replace(/([СЦсц])ҳ/g, "$1\u0027ҳ")

		.replace(/(\p{Uppercase})(\p{Uppercase}) Я/ug, "$1$2 YA")
		.replace(/(\p{Uppercase})Я/ug, "$1YA")
		.replace(/Я (\p{Uppercase})(\p{Uppercase})/ug, "YA $1$2")
		.replace(/Я(\p{Uppercase})/ug, "YA$1")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ю/ug, "$1$2 YU")
		.replace(/(\p{Uppercase})Ю/ug, "$1YU")
		.replace(/Ю (\p{Uppercase})(\p{Uppercase})/ug, "YU $1$2")
		.replace(/Ю(\p{Uppercase})/ug, "YU$1")
		.replace(/(\p{Uppercase})(\p{Uppercase}) [ШЩ]/ug, "$1$2 SH")
		.replace(/(\p{Uppercase})[ШЩ]/ug, "$1SH")
		.replace(/[ШЩ] (\p{Uppercase})(\p{Uppercase})/ug, "SH $1$2")
		.replace(/[ШЩ](\p{Uppercase})/ug, "SH$1")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ч/ug, "$1$2 CH")
		.replace(/(\p{Uppercase})Ч/ug, "$1CH")
		.replace(/Ч (\p{Uppercase})(\p{Uppercase})/ug, "CH $1$2")
		.replace(/Ч(\p{Uppercase})/ug, "CH$1")

		.replace(/а/g, "a")
		.replace(/ә/g, "á")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/ғ/g, "ǵ")
		.replace(/д/g, "d")
		.replace(/[еэ]/g, "e")
		.replace(/ж/g, "j")
		.replace(/з/g, "z")
		.replace(/и/g, "i")
		.replace(/й/g, "y")
		.replace(/к/g, "k")
		.replace(/қ/g, "q")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/ң/g, "ń")
		.replace(/о/g, "o")
		.replace(/ө/g, "ó")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ў/g, "w")
		.replace(/ү/g, "ú")
		.replace(/ф/g, "f")
		.replace(/х/g, "x")
		.replace(/ҳ/g, "h")
		.replace(/ц/g, "c")
		.replace(/ч/g, "ch")
		.replace(/[шщ]/g, "sh")
		.replace(/ы/g, "ı")
		.replace(/ю/g, "yu")
		.replace(/я/g, "ya")
		.replace(/А/g, "A")
		.replace(/Ә/g, "Á")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Ғ/g, "Ǵ")
		.replace(/Д/g, "D")
		.replace(/[ЕЭ]/g, "E")
		.replace(/Ж/g, "J")
		.replace(/З/g, "Z")
		.replace(/И/g, "I")
		.replace(/Й/g, "Y")
		.replace(/К/g, "K")
		.replace(/Қ/g, "Q")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/Ң/g, "Ń")
		.replace(/О/g, "O")
		.replace(/Ө/g, "Ó")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ў/g, "W")
		.replace(/Ү/g, "Ú")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "X")
		.replace(/Ҳ/g, "H")
		.replace(/Ц/g, "C")
		.replace(/Ч/g, "Ch")
		.replace(/[ШЩ]/g, "Sh")
		.replace(/Ы/g, "Í")
		.replace(/Ю/g, "Yu")
		.replace(/Я/g, "Ya")
		.replace(/«/g, "\u201c")
		.replace(/»/g, "\u201d");
}

function leftbottom() {
	document.transcription.text3.value = document.transcription.text1.value
		.replace(/(Ь|Ъ|ь|ъ)(е|и|о)/g, "$1й$2")
		.replace(/(Ь|Ъ)(Е|И|О)/g, "$1Й$2")

		.replace(/а/g, "a")
		.replace(/ә/g, "ä")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/ғ/g, "ğ")
		.replace(/д/g, "d")
		.replace(/е/g, "e")
		.replace(/ё/g, "yo")
		.replace(/ж/g, "j")
		.replace(/з/g, "z")
		.replace(/и/g, "i")
		.replace(/й/g, "y")
		.replace(/к/g, "k")
		.replace(/қ/g, "q")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/ң/g, "ñ")
		.replace(/о/g, "o")
		.replace(/ө/g, "ö")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ү/g, "ü")
		.replace(/ў/g, "w")
		.replace(/ф/g, "f")
		.replace(/х/g, "x")
		.replace(/ҳ/g, "h")
		.replace(/ц/g, "c")
		.replace(/ч/g, "ç")
		.replace(/ш/g, "ş")
		.replace(/щ/g, "ş")
		.replace(/ъ/g, "")
		.replace(/ы/g, "ı")
		.replace(/ь/g, "")
		.replace(/э/g, "e")
		.replace(/ю/g, "yu")
		.replace(/я/g, "ya")
		.replace(/А/g, "A")
		.replace(/Ә/g, "Ä")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Ғ/g, "Ğ")
		.replace(/Д/g, "D")
		.replace(/Е/g, "E")
		.replace(/Ё/g, "Yo")
		.replace(/Ж/g, "J")
		.replace(/З/g, "Z")
		.replace(/И/g, "İ")
		.replace(/Й/g, "Y")
		.replace(/К/g, "K")
		.replace(/Қ/g, "Q")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/Ң/g, "Ñ")
		.replace(/О/g, "O")
		.replace(/Ө/g, "Ö")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ү/g, "Ü")
		.replace(/Ў/g, "W")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "X")
		.replace(/Ҳ/g, "H")
		.replace(/Ц/g, "C")
		.replace(/Ч/g, "Ç")
		.replace(/Ш/g, "Ş")
		.replace(/Щ/g, "Ş")
		.replace(/Ъ/g, "")
		.replace(/Ы/g, "I")
		.replace(/Ь/g, "")
		.replace(/Э/g, "E")
		.replace(/Ю/g, "Yu")
		.replace(/Я/g, "Ya")
		.replace(/«/g, "\u201c")
		.replace(/»/g, "\u201d");
}

function rightleft() {
	document.transcription.text2.value = document.transcription.text2.value.replace(/['ˈ’‘ʻʼ´`ʿʹˊ׳′ʽߵ՚ߴ᾿ՙ῾‛ʾ՛ˋ]/g, "\u0027")
		.normalize('NFD')
		.replace(/([AaGgIiNnOoUu])\u0027/g, "$1\u0301")
		.replace(/i\u0301/g, "ı")
		.replace(/İ/g, "I")
		.normalize('NFC');

	document.transcription.text1.value = document.transcription.text2.value
		.replace(/C[Hh]/g, "Ч")
		.replace(/S[Hh]/g, "Ш")
		.replace(/Y[Uu]/g, "Ю")
		.replace(/Y[Aa]/g, "Я")

		.replace(/([CS])[\u0027|\u2019|\u02bc]([Hh])/g, "$1$2")
		.replace(/([cs])[\u0027|\u2019|\u02bc]h/g, "$1h")

		.replace(/A/g, "А")
		.replace(/Á/g, "Ә")
		.replace(/B/g, "Б")
		.replace(/V/g, "В")
		.replace(/G/g, "Г")
		.replace(/Ǵ/g, "Ғ")
		.replace(/D/g, "Д")
		.replace(/E/g, "Е")
		.replace(/J/g, "Ж")
		.replace(/Z/g, "З")
		.replace(/I|İ/g, "И")
		.replace(/Y/g, "Й")
		.replace(/K/g, "К")
		.replace(/Q/g, "Қ")
		.replace(/L/g, "Л")
		.replace(/M/g, "М")
		.replace(/N/g, "Н")
		.replace(/Ń/g, "Ң")
		.replace(/O/g, "О")
		.replace(/Ó/g, "Ө")
		.replace(/P/g, "П")
		.replace(/R/g, "Р")
		.replace(/S/g, "С")
		.replace(/T/g, "Т")
		.replace(/U/g, "У")
		.replace(/U/g, "У")
		.replace(/Ú/g, "Ү")
		.replace(/F/g, "Ф")
		.replace(/X/g, "Х")
		.replace(/H/g, "Ҳ")
		.replace(/Í/g, "Ы")

		.replace(/ch/g, "ч")
		.replace(/sh/g, "ш")
		.replace(/yu/g, "ю")
		.replace(/ya/g, "я")
		.replace(/a/g, "а")
		.replace(/á/g, "ә")
		.replace(/b/g, "б")
		.replace(/v/g, "в")
		.replace(/g/g, "г")
		.replace(/ǵ/g, "ғ")
		.replace(/d/g, "д")
		.replace(/j/g, "ж")
		.replace(/z/g, "з")
		.replace(/i/g, "и")
		.replace(/y/g, "й")
		.replace(/k/g, "к")
		.replace(/q/g, "қ")
		.replace(/l/g, "л")
		.replace(/m/g, "м")
		.replace(/n/g, "н")
		.replace(/ń/g, "ң")
		.replace(/o/g, "о")
		.replace(/ó/g, "ө")
		.replace(/p/g, "п")
		.replace(/r/g, "р")
		.replace(/s/g, "с")
		.replace(/t/g, "т")
		.replace(/u/g, "у")
		.replace(/w/g, "ў")
		.replace(/ú/g, "ү")
		.replace(/f/g, "ф")
		.replace(/x/g, "х")
		.replace(/h/g, "ҳ")
		.replace(/c/g, "ц")
		.replace(/ı|í/g, "ы")
		.replace(/\u201c/g, "«")
		.replace(/\u201d/g, "»");
		leftbottom();
}

function rightleft {}

function rightbottom {}

function bottomleft {}

function bottomright {}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}
