function latcyr() {}

function cyrlat() {
	document.transcription.text1.value = document.transcription.text1.value
		.replace(/(?<=\p{Script=Cyrl})a/ug, "а")
		.replace(/a(?=\p{Script=Cyrl})/ug, "а")
		.replace(/(?<=\p{Script=Cyrl})e/ug, "е")
		.replace(/e(?=\p{Script=Cyrl})/ug, "е")
		.replace(/(?<=\p{Script=Cyrl})ë/ug, "ё")
		.replace(/ë(?=\p{Script=Cyrl})/ug, "ё")
		.replace(/(?<=\p{Script=Cyrl})o/ug, "о")
		.replace(/o(?=\p{Script=Cyrl})/ug, "о")
		.replace(/(?<=\p{Script=Cyrl})p/ug, "р")
		.replace(/p(?=\p{Script=Cyrl})/ug, "р")
		.replace(/(?<=\p{Script=Cyrl})c/ug, "с")
		.replace(/c(?=\p{Script=Cyrl})/ug, "с")
		.replace(/(?<=\p{Script=Cyrl})y/ug, "у")
		.replace(/y(?=\p{Script=Cyrl})/ug, "у")
		.replace(/(?<=\p{Script=Cyrl})x/ug, "х")
		.replace(/x(?=\p{Script=Cyrl})/ug, "х")
		
		.replace(/(?<=\p{Script=Cyrl})A/ug, "А")
		.replace(/A(?=\p{Script=Cyrl})/ug, "А")
		.replace(/(?<=\p{Script=Cyrl})B/ug, "В")
		.replace(/B(?=\p{Script=Cyrl})/ug, "В")
		.replace(/(?<=\p{Script=Cyrl})E/ug, "Е")
		.replace(/E(?=\p{Script=Cyrl})/ug, "Е")
		.replace(/(?<=\p{Script=Cyrl})Ë/ug, "Ё")
		.replace(/Ë(?=\p{Script=Cyrl})/ug, "Ё")
		.replace(/(?<=\p{Script=Cyrl})K/ug, "К")
		.replace(/K(?=\p{Script=Cyrl})/ug, "К")
		.replace(/(?<=\p{Script=Cyrl})M/ug, "М")
		.replace(/M(?=\p{Script=Cyrl})/ug, "М")
		.replace(/(?<=\p{Script=Cyrl})H/ug, "Н")
		.replace(/H(?=\p{Script=Cyrl})/ug, "Н")
		.replace(/(?<=\p{Script=Cyrl})O/ug, "О")
		.replace(/O(?=\p{Script=Cyrl})/ug, "О")
		.replace(/(?<=\p{Script=Cyrl})P/ug, "Р")
		.replace(/P(?=\p{Script=Cyrl})/ug, "Р")
		.replace(/(?<=\p{Script=Cyrl})C/ug, "С")
		.replace(/C(?=\p{Script=Cyrl})/ug, "С")
		.replace(/(?<=\p{Script=Cyrl})T/ug, "Т")
		.replace(/T(?=\p{Script=Cyrl})/ug, "Т")
		.replace(/(?<=\p{Script=Cyrl})X/ug, "Х")
		.replace(/X(?=\p{Script=Cyrl})/ug, "Х");
	
	document.transcription.text2.value = document.transcription.text1.value
		.replace(/(?<=\p{Lu}|\p{Lu}\p{Lu} )Я/ug, "ИА")
		.replace(/Я(?=\p{Lu}| \p{Lu}\p{Lu})/ug, "ИА")
		.replace(/Я/g, "Иа")
		.replace(/я/g, "иа")
		.replace(/(?<=\p{Lu}|\p{Lu}\p{Lu} )Ю/ug, "ИУ")
		.replace(/Ю(?=\p{Lu}| \p{Lu}\p{Lu})/ug, "ИУ")
		.replace(/Ю/g, "Иу")
		.replace(/ю/g, "иу")
		.replace(/(?<=\p{Lu}|\p{Lu}\p{Lu} )Ъ/ug, "ИЭ")
		.replace(/Ъ(?=\p{Lu}| \p{Lu}\p{Lu})/ug, "ИЭ")
		.replace(/Ъ/g, "Иэ")
		.replace(/ъ/g, "иэ")		
		.replace(/(?<=\p{Lu}|\p{Lu}\p{Lu} )Щ/ug, "ШЧ")
		.replace(/Щ(?=\p{Lu}| \p{Lu}\p{Lu})/ug, "ШЧ")
		.replace(/Щ/g, "Шч")
		.replace(/щ/g, "шч")
		.replace(/(?<=\p{Lu}|\p{Lu}\p{Lu} )Ц/ug, "ТС")
		.replace(/Ц(?=\p{Lu}| \p{Lu}\p{Lu})/ug, "ТС")
		.replace(/Ц/g, "Тс")
		.replace(/ц/g, "тс")
		.replace(/(?<=\p{Lu}|\p{Lu}\p{Lu} )Х/ug, "К\u0048")
		.replace(/Х(?=\p{Lu}| \p{Lu}\p{Lu})/ug, "К\u0048")
		.replace(/Х/g, "К\u0068")
		.replace(/х/g, "к\u0068")
		.replace(/(?<=\p{Lu}|\p{Lu}\p{Lu} )Ж/ug, "З\u0048")
		.replace(/Ж(?=\p{Lu}| \p{Lu}\p{Lu})/ug, "З\u0048")
		.replace(/Ж/g, "З\u0068")
		.replace(/ж/g, "з\u0068")
		.replace(/(?<=\p{Lu}|\p{Lu}\p{Lu} )Ш/ug, "С\u0048")
		.replace(/Ш(?=\p{Lu}| \p{Lu}\p{Lu})/ug, "С\u0048")
		.replace(/Ш/g, "С\u0068")
		.replace(/ш/g, "с\u0068")
		.replace(/(?<=\p{Lu}|\p{Lu}\p{Lu} )Ч/ug, "\u0043\u0048")
		.replace(/Ч(?=\p{Lu}| \p{Lu}\p{Lu})/ug, "\u0043\u0048")
		.replace(/Ч/g, "\u0043\u0068")
		.replace(/ч/g, "\u0063\u0068")

		.replace(/А/g, "A")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Д/g, "D")
		.replace(/[ЕЁ]/g, "E")
		.replace(/З/g, "Z")
		.replace(/[ИЙ]/g, "I")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/О/g, "O")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ф/g, "F")
		.replace(/Ы/g, "Y")
		.replace(/Ь/g, "")
		.replace(/Э/g, "E")
		.replace(/а/g, "a")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/д/g, "d")
		.replace(/[её]/g, "e")
		.replace(/з/g, "z")
		.replace(/[ий]/g, "i")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/о/g, "o")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ф/g, "f")
		.replace(/ы/g, "y")
		.replace(/ь/g, "")
		.replace(/э/g, "e")
		.normalize('NFC');
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}