//  copyright lexilogos.com
var car;
function cyrlat () {
car = document.transcription.text1.value;
  car = car.replace(/Ά/g, "А\u0301");
  car = car.replace(/ά/g, "а\u0301");
  car = car.replace(/Έ/g, "Е\u0301");
  car = car.replace(/έ/g, "е\u0301");
  car = car.replace(/Ή/g, "Ӣ\u0301");
  car = car.replace(/ή/g, "ӣ\u0301");
  car = car.replace(/Ί/g, "И\u0301");
  car = car.replace(/ί/g, "и\u0301");
  car = car.replace(/Ό/g, "О\u0301");
  car = car.replace(/ό/g, "о\u0301");
  car = car.replace(/Ύ/g, "У\u0301");
  car = car.replace(/ύ/g, "у\u0301"); 
  car = car.replace(/Ώ/g, "Ө\u0301");
  car = car.replace(/ώ/g, "ө\u0301");
  car = car.replace(/ΐ/g, "и\u0308\u0301");
  car = car.replace(/ΰ/g, "у\u0308\u0301"); 	
  car = car.replace(/Ϊ/g, "И\u0308");
  car = car.replace(/ϊ/g, "и\u0308");
  car = car.replace(/Ϋ/g, "У\u0308");
  car = car.replace(/ϋ/g, "у\u0308");
  car = car.replace(/Α/g, "А");
  car = car.replace(/α/g, "а");
  car = car.replace(/Β/g, "В");
  car = car.replace(/β/g, "в");
  car = car.replace(/ϐ/g, "в");
  car = car.replace(/Γ/g, "Г");
  car = car.replace(/γ/g, "г");
  car = car.replace(/Δ/g, "Д");
  car = car.replace(/δ/g, "д");
  car = car.replace(/Ε/g, "Е");
  car = car.replace(/ε/g, "е");
  car = car.replace(/ϵ/g, "е");
  car = car.replace(/Ζ/g, "З");
  car = car.replace(/ζ/g, "з");
  car = car.replace(/Η/g, "Ӣ");
  car = car.replace(/η/g, "ӣ");
  car = car.replace(/Θ/g, "Ҫ");
  car = car.replace(/θ/g, "ҫ");
  car = car.replace(/ϑ/g, "ҫ");
  car = car.replace(/Ι/g, "И");
  car = car.replace(/ι/g, "и");
  car = car.replace(/Κ/g, "К");
  car = car.replace(/κ/g, "к");
  car = car.replace(/ϰ/g, "к");
  car = car.replace(/Λ/g, "Л");
  car = car.replace(/λ/g, "л");
  car = car.replace(/Μ/g, "М");
  car = car.replace(/μ/g, "м");
  car = car.replace(/Ν/g, "Н");
  car = car.replace(/ν/g, "н");
  car = car.replace(/Ξ/g, "Қ");
  car = car.replace(/ξ/g, "қ");
  car = car.replace(/Ο/g, "О");
  car = car.replace(/ο/g, "о");
  car = car.replace(/Π/g, "Б");
  car = car.replace(/π/g, "б");
  car = car.replace(/Ρ/g, "Р");
  car = car.replace(/ρ/g, "р");
  car = car.replace(/ϱ/g, "р");
  car = car.replace(/Σ/g, "С");
  car = car.replace(/σ/g, "с");
  car = car.replace(/ς/g, "с");
  car = car.replace(/Τ/g, "Т");
  car = car.replace(/τ/g, "т");
  car = car.replace(/Υ/g, "У");
  car = car.replace(/υ/g, "у");
  car = car.replace(/Φ/g, "Ф");
  car = car.replace(/φ/g, "ф");
  car = car.replace(/Χ/g, "Х");
  car = car.replace(/χ/g, "х");
  car = car.replace(/Ψ/g, "П");
  car = car.replace(/ψ/g, "п");
  car = car.replace(/Ω/g, "Ө");
  car = car.replace(/ω/g, "ө");
document.transcription.text2.value=car;
}
function copy1()
{ textRange=document.transcription.text1.createTextRange();   textRange.execCommand("Copy");   textRange="";
}
function copy2()
{ textRange=document.transcription.text2.createTextRange();   textRange.execCommand("Copy");   textRange="";
}