function topleft() {
	document.transcription.text2.value = document.transcription.text1.value
		.replace(/(0|1|2|3|4|5|6|7|8|9)Х/g, "$1X")
		.replace(/(0|1|2|3|4|5|6|7|8|9)х/g, "$1x")
		.replace(/Х(0|1|2|3|4|5|6|7|8|9)/g, "X$1")
		.replace(/х(0|1|2|3|4|5|6|7|8|9)/g, "x$1")

		.replace(/Й(А|а)/g, "Й$1\u0300")
		.replace(/йа/g, "йа\u0300")
		.replace(/Й(Э|э)/g, "Й$1\u0300")
		.replace(/йэ/g, "йэ\u0300")
		.replace(/Й(У|у)/g, "Й$1\u0300")
		.replace(/йу/g, "йу\u0300")
		.replace(/Й(О|о)/g, "Й$1\u0300")
		.replace(/йо/g, "йо\u0300")

		.replace(/(Б|б|В|в|Г|г|Д|д|Ж|ж|З|з|Й|й|К|к|Л|л|М|м|Н|н|П|п|Р|р|С|с|Т|т|Ф|ф|Х|х|Ц|ц|Ч|ч|Ш|ш|Щ|щ)Ы/g, "$1Ɩ")
		.replace(/(Б|б|В|в|Г|г|Д|д|Ж|ж|З|з|Й|й|К|к|Л|л|М|м|Н|н|П|п|Р|р|С|с|Т|т|Ф|ф|Х|х|Ц|ц|Ч|ч|Ш|ш|Щ|щ)ы/g, "$1ɩ")
		.replace(/(Б|б|В|в|Г|г|Д|д|Ж|ж|З|з|Й|й|К|к|Л|л|М|м|Н|н|П|п|Р|р|С|с|Т|т|Ф|ф|Х|х|Ц|ц|Ч|ч|Ш|ш|Щ|щ)Ɩ(А|а|Б|б|В|в|Г|г|Д|д|Е|е|Ё|ё|Ж|ж|З|з|И|и|Й|й|К|к|Л|л|М|м|Н|н|О|о|П|п|Р|р|С|с|Т|т|У|у|Ф|ф|Х|х|Ц|ц|Ч|ч|Ш|ш|Щ|щ|Ъ|ъ|Ы|ы|Ь|ь|Э|э|Ю|ю|Я|я)/g, "$1Ы$2")
		.replace(/(Б|б|В|в|Г|г|Д|д|Ж|ж|З|з|Й|й|К|к|Л|л|М|м|Н|н|П|п|Р|р|С|с|Т|т|Ф|ф|Х|х|Ц|ц|Ч|ч|Ш|ш|Щ|щ)ɩ(А|а|Б|б|В|в|Г|г|Д|д|Е|е|Ё|ё|Ж|ж|З|з|И|и|Й|й|К|к|Л|л|М|м|Н|н|О|о|П|п|Р|р|С|с|Т|т|У|у|Ф|ф|Х|х|Ц|ц|Ч|ч|Ш|ш|Щ|щ|Ъ|ъ|Ы|ы|Ь|ь|Э|э|Ю|ю|Я|я)/g, "$1ы$2")
		.replace(/(А|а|Б|б|В|в|Г|г|Д|д|Е|е|Ё|ё|Ж|ж|З|з|И|и|Й|й|К|к|Л|л|М|м|Н|н|О|о|П|п|Р|р|С|с|Т|т|У|у|Ф|ф|Х|х|Ц|ц|Ч|ч|Ш|ш|Щ|щ|Ъ|ъ|Ы|ы|Ь|ь|Э|э|Ю|ю|Я|я)(Б|б|В|в|Г|г|Д|д|Ж|ж|З|з|Й|й|К|к|Л|л|М|м|Н|н|П|п|Р|р|С|с|Т|т|Ф|ф|Х|х|Ц|ц|Ч|ч|Ш|ш|Щ|щ)Ɩ/g, "$1$2Ы")
		.replace(/(А|а|Б|б|В|в|Г|г|Д|д|Е|е|Ё|ё|Ж|ж|З|з|И|и|Й|й|К|к|Л|л|М|м|Н|н|О|о|П|п|Р|р|С|с|Т|т|У|у|Ф|ф|Х|х|Ц|ц|Ч|ч|Ш|ш|Щ|щ|Ъ|ъ|Ы|ы|Ь|ь|Э|э|Ю|ю|Я|я)(Б|б|В|в|Г|г|Д|д|Ж|ж|З|з|Й|й|К|к|Л|л|М|м|Н|н|П|п|Р|р|С|с|Т|т|Ф|ф|Х|х|Ц|ц|Ч|ч|Ш|ш|Щ|щ)ɩ/g, "$1$2ы")

		.replace(/ɩ/g, "и")
		.replace(/Ɩ/g, "И")

		/*.replace(/Т(С|с)/g, "Т\u2019$1")
		.replace(/тс/g, "т\u2019с")*/

		.replace(/дж/g, "џ")
		.replace(/Д(Ж|ж)/g, "Џ")

		.replace(/(\p{Uppercase})(\p{Uppercase}) Я/ug, "$1$2 ЬА")
		.replace(/(\p{Uppercase})Я/ug, "$1ЬА")
		.replace(/Я (\p{Uppercase})(\p{Uppercase})/ug, "ЬА $1$2")
		.replace(/Я(\p{Uppercase})/ug, "ЬА$1")
		.replace(/Я/g, "Ьа")
		.replace(/я/g, "ьа")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Е/ug, "$1$2 ЬЭ")
		.replace(/(\p{Uppercase})Е/ug, "$1ЬЭ")
		.replace(/Е (\p{Uppercase})(\p{Uppercase})/ug, "ЬЭ $1$2")
		.replace(/Е(\p{Uppercase})/ug, "ЬЭ$1")
		.replace(/Е/g, "Ьэ")
		.replace(/е/g, "ьэ")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ё/ug, "$1$2 ЬО")
		.replace(/(\p{Uppercase})Ё/ug, "$1ЬО")
		.replace(/Ё (\p{Uppercase})(\p{Uppercase})/ug, "ЬО $1$2")
		.replace(/Ё(\p{Uppercase})/ug, "ЬО$1")
		.replace(/Ё/g, "Ьо")
		.replace(/ё/g, "ьо")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ю/ug, "$1$2 ЬУ")
		.replace(/(\p{Uppercase})Ю/ug, "$1ЬУ")
		.replace(/Ю (\p{Uppercase})(\p{Uppercase})/ug, "ЬУ $1$2")
		.replace(/Ю(\p{Uppercase})/ug, "ЬУ$1")
		.replace(/Ю/g, "Ьу")
		.replace(/ю/g, "ьу")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Щ/ug, "$1$2 ШХ")
		.replace(/(\p{Uppercase})Щ/ug, "$1ШХ")
		.replace(/Щ (\p{Uppercase})(\p{Uppercase})/ug, "ШХ $1$2")
		.replace(/Щ(\p{Uppercase})/ug, "ШХ$1")
		.replace(/Щ/g, "Шх")
		.replace(/щ/g, "шх")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ш/ug, "$1$2 СХ")
		.replace(/(\p{Uppercase})Ш/ug, "$1СХ")
		.replace(/Ш (\p{Uppercase})(\p{Uppercase})/ug, "СХ $1$2")
		.replace(/Ш(\p{Uppercase})/ug, "СХ$1")
		.replace(/Ш/g, "Сх")
		.replace(/ш/g, "сх")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ж/ug, "$1$2 ЗХ")
		.replace(/(\p{Uppercase})Ж/ug, "$1ЗХ")
		.replace(/Ж (\p{Uppercase})(\p{Uppercase})/ug, "ЗХ $1$2")
		.replace(/Ж(\p{Uppercase})/ug, "ЗХ$1")
		.replace(/Ж/g, "Зх")
		.replace(/ж/g, "зх")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ч/ug, "$1$2 \u0043Х")
		.replace(/(\p{Uppercase})Ч/ug, "$1\u0043Х")
		.replace(/Ч (\p{Uppercase})(\p{Uppercase})/ug, "\u0043Х $1$2")
		.replace(/Ч(\p{Uppercase})/ug, "\u0043Х$1")
		.replace(/Ч/g, "\u0043х")
		.replace(/ч/g, "\u0063х")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ц/ug, "$1$2 ТС")
		.replace(/(\p{Uppercase})Ц/ug, "$1ТС")
		.replace(/Ц (\p{Uppercase})(\p{Uppercase})/ug, "ТС $1$2")
		.replace(/Ц(\p{Uppercase})/ug, "ТС$1")
		.replace(/Ц/g, "Тс")
		.replace(/ц/g, "тс")

		.replace(/(Б|В|Г|Д|Џ|З|К|Л|М|Н|П|Р|С|Т|Ф|Х)Ь(А|И|Ы|О|У)/g, "$1И$2")
		.replace(/(Б|В|Г|Д|Џ|З|К|Л|М|Н|П|Р|С|Т|Ф|Х|б|в|г|д|џ|з|к|л|м|н|п|р|с|т|ф|х)ь(а|и|ы|о|у)/g, "$1и$2")
		.replace(/(Б|В|Г|Д|Џ|З|К|Л|М|Н|П|Р|С|Т|Ф|Х)ЬЭ/g, "$1Э")
		.replace(/(Б|В|Г|Д|Џ|З|К|Л|М|Н|П|Р|С|Т|Ф|Х|б|в|г|д|џ|з|к|л|м|н|п|р|с|т|ф|х)ьэ/g, "$1э")
		.replace(/Ь(А|Э|И|Ы|О|У|а|э|и|ы|о|у)/g, "Й$1")
		.replace(/ь(а|э|и|ы|о|у)/g, "й$1")
		.replace(/ЬЬ/g, "Й")
		.replace(/(Ь|ь)ь/g, "й")

		.replace(/а/g, "a")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/д/g, "d")
		.replace(/џ/g, "j")
		.replace(/з/g, "z")
		.replace(/и/g, "i")
		.replace(/й/g, "ẏ")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/о/g, "o")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ф/g, "f")
		.replace(/х/g, "h")
		.replace(/ы/g, "y")
		.replace(/э/g, "e")

		.replace(/А/g, "A")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Д/g, "D")
		.replace(/Џ/g, "J")
		.replace(/З/g, "Z")
		.replace(/И/g, "I")
		.replace(/Й/g, "Ẏ")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/О/g, "O")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "H")
		.replace(/Ы/g, "Y")
		.replace(/Э/g, "E")

		.replace(/(Ь|Ъ|ь|ъ)/g, "")

		.replace(/ẎY/g, "ẎI")
		.replace(/(Ẏ|ẏ)y/g, "$1i")
		.replace(/Y(Ẏ|ẏ)((?!A|E|I|O|U|Y|Ẏ))/g, "Y$2")
		.replace(/yẏ((?!a|e|i|o|u|y|ẏ))/g, "y$1")
		.replace(/YẎ(A|E|I|O|U|Y|Ẏ)/g, "IẎ$1")
		.replace(/Yẏ(a|e|i|o|u|y|ẏ)/g, "Iẏ$1")
		.replace(/yẏ(a|e|i|o|u|y|ẏ)/g, "iẏ$1")

		.replace(/(B|C|D|F|G|H|K|L|M|N|P|R|S|T|V|Z)ẎI/g, "$1I")
		.replace(/(B|C|D|F|G|H|K|L|M|N|P|R|S|T|V|Z|b|c|d|f|g|h|k|l|m|n|p|r|s|t|v|z)ẏi/g, "$1i")

		.replace(/(A|E|O|U|Y|Ẏ)Ẏ((?!A|E|I|O|U|Y|Ẏ))/g, "$1I$2")
		.replace(/(A|E|O|U|Y|Ẏ|a|e|o|u|y|ẏ)ẏ((?!a|e|i|o|u|y|ẏ))/g, "$1i$2")
		.replace(/IẎ((?!A|E|I|O|U|Y|Ẏ))/g, "I$1")
		.replace(/(I|i)ẏ((?!a|e|i|o|u|y|ẏ))/g, "$1$2")

		.replace(/Ẏ/g, "Y")
		.replace(/ẏ/g, "y")

		.replace(/«/g, "\u201e")
		.replace(/»/g, "\u201c")
		.normalize('NFC');
}

function topright() {
	document.transcription.text1.value = document.transcription.text1.value
		.replace(/<</g, "«")
		.replace(/>>/g, "»")
		.replace(/(\p{Script=Cyrl})A/ug, "$1А")
		.replace(/(\p{Script=Cyrl})C/ug, "$1С")
		.replace(/(\p{Script=Cyrl})E/ug, "$1Е")
		.replace(/(\p{Script=Cyrl})Ë/ug, "$1Ё")
		.replace(/(\p{Script=Cyrl})O/ug, "$1О")
		.replace(/(\p{Script=Cyrl})P/ug, "$1Р")
		.replace(/(\p{Script=Cyrl})X/ug, "$1Х")
		.replace(/(\p{Script=Cyrl})a/ug, "$1а")
		.replace(/(\p{Script=Cyrl})c/ug, "$1с")
		.replace(/(\p{Script=Cyrl})e/ug, "$1е")
		.replace(/(\p{Script=Cyrl})ë/ug, "$1ё")
		.replace(/(\p{Script=Cyrl})o/ug, "$1о")
		.replace(/(\p{Script=Cyrl})p/ug, "$1р")
		.replace(/(\p{Script=Cyrl})x/ug, "$1х")
		.replace(/A(\p{Script=Cyrl})/ug, "А$1")
		.replace(/C(\p{Script=Cyrl})/ug, "С$1")
		.replace(/E(\p{Script=Cyrl})/ug, "Е$1")
		.replace(/Ë(\p{Script=Cyrl})/ug, "Ё$1")
		.replace(/O(\p{Script=Cyrl})/ug, "О$1")
		.replace(/P(\p{Script=Cyrl})/ug, "Р$1")
		.replace(/X(\p{Script=Cyrl})/ug, "Х$1")
		.replace(/a(\p{Script=Cyrl})/ug, "а$1")
		.replace(/c(\p{Script=Cyrl})/ug, "с$1")
		.replace(/e(\p{Script=Cyrl})/ug, "е$1")
		.replace(/ë(\p{Script=Cyrl})/ug, "ё$1")
		.replace(/o(\p{Script=Cyrl})/ug, "о$1")
		.replace(/p(\p{Script=Cyrl})/ug, "р$1")
		.replace(/x(\p{Script=Cyrl})/ug, "х$1");

	document.transcription.text3.value = document.transcription.text1.value
		.replace(/([ЪЬ])([АОУ])/g, "$1\u2019$2")
		.replace(/([ЪЬъь])([аоу])/g, "$1\u2019$2")
		.replace(/ЪЕ/g, "ЙÉ")
		.replace(/([Ъъ])е/g, "йé")
		.replace(/([ЬЪ])Э/g, "$1\u2019Э")
		.replace(/([ЬЪьъ])э/g, "$1\u2019э")

		.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])Я/g, "$1Ä")
		.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])я/g, "$1ä")
		.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])Э/g, "$1É")
		.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])э/g, "$1é")
		.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])Е/g, "$1E")
		.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])е/g, "$1e")
		.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])Ё/g, "$1Ö")
		.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])ё/g, "$1ö")
		.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])Ю/g, "$1Ü")
		.replace(/([БВГДЖЗКЛМНПРСТФХЦЧШЩЬбвгджзклмнпрстфхцчшщь])ю/g, "$1ü")

		.replace(/(\p{Uppercase})Я/ug, "$1ЙА")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Я/ug, "$1$2 ЙА")
		.replace(/Я (\p{Uppercase})(\p{Uppercase})/ug, "ЙА $1$2")
		.replace(/Я(\p{Uppercase})/ug, "ЙА$1")
		.replace(/Я/g, "Йа")
		.replace(/я/g, "йа")
		.replace(/(\p{Uppercase})Е/ug, "$1ЙЭ")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Е/ug, "$1$2 ЙЭ")
		.replace(/Е (\p{Uppercase})(\p{Uppercase})/ug, "ЙЭ $1$2")
		.replace(/Е(\p{Uppercase})/ug, "ЙЭ$1")
		.replace(/Е/g, "Йэ")
		.replace(/е/g, "йэ")
		.replace(/(\p{Uppercase})Ё/ug, "$1ЙО")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ё/ug, "$1$2 ЙО")
		.replace(/Ё (\p{Uppercase})(\p{Uppercase})/ug, "ЙО $1$2")
		.replace(/Ё(\p{Uppercase})/ug, "ЙО$1")
		.replace(/Ё/g, "Йо")
		.replace(/ё/g, "йо")
		.replace(/(\p{Uppercase})Ю/ug, "$1ЙУ")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ю/ug, "$1$2 ЙУ")
		.replace(/Ю (\p{Uppercase})(\p{Uppercase})/ug, "ЙУ $1$2")
		.replace(/Ю(\p{Uppercase})/ug, "ЙУ$1")
		.replace(/Ю/g, "Йу")
		.replace(/ю/g, "йу")

		.replace(/а/g, "a")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/д/g, "d")
		.replace(/е/g, "je")
		.replace(/ж/g, "ž")
		.replace(/з/g, "z")
		.replace(/и/g, "i")
		.replace(/й/g, "j")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/о/g, "o")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ф/g, "f")
		.replace(/х/g, "h")
		.replace(/ц/g, "c")
		.replace(/ч/g, "č")
		.replace(/ш/g, "š")
		.replace(/щ/g, "ś")
		.replace(/ы/g, "y")
		.replace(/ь/g, "j")
		.replace(/ъ/g, "")
		.replace(/э/g, "e")
		.replace(/ю/g, "ju")
		.replace(/ё/g, "jo")
		.replace(/я/g, "ja")

		.replace(/А/g, "A")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Д/g, "D")
		.replace(/Е/g, "Je")
		.replace(/Ж/g, "Ž")
		.replace(/З/g, "Z")
		.replace(/И/g, "I")
		.replace(/Й/g, "J")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/О/g, "O")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "H")
		.replace(/Ц/g, "C")
		.replace(/Ч/g, "Č")
		.replace(/Ш/g, "Š")
		.replace(/Щ/g, "Ś")
		.replace(/Ы/g, "Y")
		.replace(/Ь/g, "J")
		.replace(/Ъ/g, "")
		.replace(/Э/g, "E")
		.replace(/Ю/g, "Ju")
		.replace(/Ё/g, "Jo")
		.replace(/Я/g, "Ja");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}

function copy3() {
	navigator.clipboard.writeText(document.transcription.text3.value);
}
