function latgeo() {
	document.transcription.text1.value = document.transcription.text2.value
		.replace(/(\u2018|\u2019|\u02bc)/g, "\u0027")
		.replace(/İ/g, "I")
		.replace(/ı/g, "i")
		.normalize('NFD')
		.replace(/(3|Ʒ)(\u002a|\u003e|\u005c)/g, "ʒ")
		.replace(/ʒ(\u002a|\u003e|\u005c)/g, "Ʒ")
		.replace(/(C\u0327|c\u0327|K|k|P|p|T|Z|z|Ʒ|ʒ)\u0027/g, "$1\u030c")
		.replace(/3\u0027/g, "ʒ\u030c")
		.replace(/(C\u0327|c\u0327|K|k|P|p|Z|z)\u0301/g, "$1\u030c")
		.replace(/t(\u0027|\u0306|\u030c)/g, "t\u200c\u030c")
		.replace(/(G|g|T)\u0306/g, "$1\u030c")
		.replace(/T(S|s)/g, "Ʒ")
		.replace(/ts/g, "ʒ")
		.replace(/D(Z|z)/g, "Z\u030c")
		.replace(/dz/g, "z\u030c")

		.replace(/Ӡ/g, "Ʒ")
		.replace(/ӡ/g, "ʒ")
		.replace(/З/g, "Ʒ")
		.replace(/з/g, "ʒ")
		.normalize('NFC')

		.replace(/P̌/g, "Ô")
		.replace(/Ǩ/g, "Ü")
		.replace(/Ç̌/g, "Ö")
		.replace(/Ť/g, "Û")
		.replace(/A/g, "\u2060")
		.replace(/Z/g, "A")
		.replace(/\u2060/g, "Z")
		.replace(/O/g, "\u2060")
		.replace(/P/g, "O")
		.replace(/\u2060/g, "P")
		.replace(/Ž/g, "Â")
		.replace(/Ǧ/g, "Ğ")
		.replace(/I/g, "İ")
		.replace(/T/g, "\u2060")
		.replace(/U/g, "T")
		.replace(/\u2060/g, "U")
		.replace(/Ʒ/g, "É")
		.replace(/Ǯ/g, "W")
		.replace(/p̌/g, "ô")
		.replace(/ǩ/g, "ü")
		.replace(/ç̌/g, "ö")
		.replace(/t‌̌/g, "û")
		.replace(/a/g, "\u2060")
		.replace(/z/g, "a")
		.replace(/\u2060/g, "z")
		.replace(/o/g, "\u2060")
		.replace(/p/g, "o")
		.replace(/\u2060/g, "p")
		.replace(/ž/g, "â")
		.replace(/ǧ/g, "ğ")
		.replace(/t/g, "\u2060")
		.replace(/u/g, "t")
		.replace(/\u2060/g, "u")
		.replace(/ʒ/g, "é")
		.replace(/ǯ/g, "w");
}

function geolat() {
	document.transcription.text2.value = document.transcription.text1.value
		.replace(/A/g, "\u2060")
		.replace(/Z/g, "A")
		.replace(/\u2060/g, "Z")
		.replace(/O/g, "\u2060")
		.replace(/P/g, "O")
		.replace(/\u2060/g, "P")
		.replace(/U/g, "\u2060")
		.replace(/T/g, "U")
		.replace(/\u2060/g, "T")
		.replace(/Â/g, "Ž")
		.replace(/Ğ/g, "Ǧ")
		.replace(/İ/g, "I")
		.replace(/Ô/g, "P̌")
		.replace(/Ö/g, "Ç̌")
		.replace(/Û/g, "Ť")
		.replace(/Ü/g, "Ǩ")
		.replace(/É/g, "Ʒ")
		.replace(/W/g, "Ǯ")
		.replace(/a/g, "\u2060")
		.replace(/z/g, "a")
		.replace(/\u2060/g, "z")
		.replace(/o/g, "\u2060")
		.replace(/p/g, "o")
		.replace(/\u2060/g, "p")
		.replace(/u/g, "\u2060")
		.replace(/t/g, "u")
		.replace(/\u2060/g, "t")
		.replace(/â/g, "ž")
		.replace(/ğ/g, "ǧ")
		.replace(/ı/g, "i")
		.replace(/ô/g, "p̌")
		.replace(/ö/g, "ç̌")
		.replace(/û/g, "t‌̌")
		.replace(/ü/g, "ǩ")
		.replace(/é/g, "ʒ")
		.replace(/w/g, "ǯ");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}