function cyrlat() {
	document.transcription.text1.value = document.transcription.text1.value
		.replace(/a/g, "а")
		.replace(/b/g, "б")
		.replace(/c/g, "ц")
		.replace(/ç/g, "ч")
		.replace(/d/g, "д")
		.replace(/e/g, "е")
		.replace(/ë/g, "э")
		.replace(/f/g, "ф")
		.replace(/g/g, "г")
		.replace(/h/g, "х")
		.replace(/i/g, "и")
		.replace(/j/g, "ј")
		.replace(/k/g, "к")
		.replace(/l/g, "љ")
		.replace(/m/g, "м")
		.replace(/n/g, "н")
		.replace(/o/g, "о")
		.replace(/p/g, "п")
		.replace(/q/g, "ћ")
		.replace(/r/g, "р")
		.replace(/s/g, "с")
		.replace(/t/g, "т")
		.replace(/u/g, "у")
		.replace(/v/g, "в")
		.replace(/x/g, "ѕ")
		.replace(/y/g, "ү")
		.replace(/z/g, "з")
		.replace(/A/g, "А")
		.replace(/B/g, "Б")
		.replace(/C/g, "Ц")
		.replace(/Ç/g, "Ч")
		.replace(/D/g, "Д")
		.replace(/E/g, "Е")
		.replace(/Ë/g, "Э")
		.replace(/F/g, "Ф")
		.replace(/G/g, "Г")
		.replace(/H/g, "Х")
		.replace(/I/g, "І")
		.replace(/J/g, "Ј")
		.replace(/K/g, "К")
		.replace(/L/g, "Љ")
		.replace(/M/g, "М")
		.replace(/N/g, "Н")
		.replace(/O/g, "О")
		.replace(/P/g, "П")
		.replace(/Q/g, "Ћ")
		.replace(/R/g, "Р")
		.replace(/S/g, "С")
		.replace(/T/g, "Т")
		.replace(/U/g, "У")
		.replace(/V/g, "В")
		.replace(/X/g, "Ѕ")
		.replace(/Y/g, "Ү")
		.replace(/Z/g, "З")
		.replace(/гј/g, "ђ")
		.replace(/Гј/g, "Ђ")
		.replace(/ГЈ/g, "Ђ")
		.replace(/ѕх/g, "џ")
		.replace(/Ѕх/g, "Џ")
		.replace(/ЅХ/g, "Џ")
		.replace(/тх/g, "ҫ")
		.replace(/Тх/g, "Ҫ")
		.replace(/ТХ/g, "Ҫ")
		.replace(/дх/g, "ҙ")
		.replace(/Дх/g, "Ҙ")
		.replace(/ДХ/g, "Ҙ")
		.replace(/сх/g, "ш")
		.replace(/Сх/g, "Ш")
		.replace(/СХ/g, "Ш")
		.replace(/нј/g, "њ")
		.replace(/Нј/g, "Њ")
		.replace(/Нј/g, "Њ")
		.replace(/љљ/g, "л")
		.replace(/Љљ/g, "Л")
		.replace(/ЉЉ/g, "Л")
		.replace(/зх/g, "ж")
		.replace(/Зх/g, "Ж")
		.replace(/ЗХ/g, "Ж");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}