var car;
function cyrlat () {
car = document.transcription.text1.value;
  car = car.replace(/a/g, "а");
  car = car.replace(/b/g, "б");
  car = car.replace(/c/g, "ц"); 
  car = car.replace(/ç/g, "ч");
  car = car.replace(/d/g, "д");
  car = car.replace(/e/g, "е");
  car = car.replace(/ë/g, "э");
  car = car.replace(/f/g, "ф");
  car = car.replace(/g/g, "г");
  car = car.replace(/h/g, "х");
  car = car.replace(/i/g, "и");
  car = car.replace(/j/g, "ј");
  car = car.replace(/k/g, "к");
  car = car.replace(/l/g, "љ");
  car = car.replace(/m/g, "м");
  car = car.replace(/n/g, "н");
  car = car.replace(/o/g, "о");
  car = car.replace(/p/g, "п");
  car = car.replace(/q/g, "ћ");
  car = car.replace(/r/g, "р");
  car = car.replace(/s/g, "с");
  car = car.replace(/t/g, "т");
  car = car.replace(/u/g, "у");
  car = car.replace(/v/g, "в");
  car = car.replace(/x/g, "ѕ");
  car = car.replace(/y/g, "ү");
  car = car.replace(/z/g, "з");
  car = car.replace(/A/g, "А");
  car = car.replace(/B/g, "Б");
  car = car.replace(/C/g, "Ц");
  car = car.replace(/Ç/g, "Ч");
  car = car.replace(/D/g, "Д");
  car = car.replace(/E/g, "Е");
  car = car.replace(/Ë/g, "Э");
  car = car.replace(/F/g, "Ф");
  car = car.replace(/G/g, "Г");
  car = car.replace(/H/g, "Х");
  car = car.replace(/I/g, "І");
  car = car.replace(/J/g, "Ј");
  car = car.replace(/K/g, "К");
  car = car.replace(/L/g, "Љ");
  car = car.replace(/M/g, "М");
  car = car.replace(/N/g, "Н");
  car = car.replace(/O/g, "О");
  car = car.replace(/P/g, "П");
  car = car.replace(/Q/g, "Ћ");
  car = car.replace(/R/g, "Р");
  car = car.replace(/S/g, "С");
  car = car.replace(/T/g, "Т");
  car = car.replace(/U/g, "У");
  car = car.replace(/V/g, "В");
  car = car.replace(/X/g, "Ѕ");
  car = car.replace(/Y/g, "Ү");
  car = car.replace(/Z/g, "З");
  car = car.replace(/гј/g, "ђ");
  car = car.replace(/Гј/g, "Ђ");
  car = car.replace(/ГЈ/g, "Ђ");
  car = car.replace(/ѕх/g, "џ");
  car = car.replace(/Ѕх/g, "Џ");
  car = car.replace(/ЅХ/g, "Џ");
  car = car.replace(/тх/g, "ҫ");
  car = car.replace(/Тх/g, "Ҫ");
  car = car.replace(/ТХ/g, "Ҫ");
  car = car.replace(/дх/g, "ҙ");
  car = car.replace(/Дх/g, "Ҙ");
  car = car.replace(/ДХ/g, "Ҙ");
  car = car.replace(/сх/g, "ш");
  car = car.replace(/Сх/g, "Ш");
  car = car.replace(/СХ/g, "Ш");
  car = car.replace(/нј/g, "њ");
  car = car.replace(/Нј/g, "Њ");
  car = car.replace(/Нј/g, "Њ");
  car = car.replace(/љљ/g, "л");
  car = car.replace(/Љљ/g, "Л");
  car = car.replace(/ЉЉ/g, "Л");
  car = car.replace(/зх/g, "ж");
  car = car.replace(/Зх/g, "Ж");
  car = car.replace(/ЗХ/g, "Ж");
document.transcription.text2.value=car;
}
function copy1()
{ navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2()
{ navigator.clipboard.writeText(document.transcription.text2.value);
}