function cyrlat() {
	document.transcription.text2.value = document.transcription.text1.value
		.normalize('NFD')
		.replace(/ᆪᄉ/g, 'ᆨᄊ')
		.replace(/ᆬᄌ/g, 'ᆫᄍ')
		.replace(/ᆰᄀ/g, 'ᆯᄁ')
		.replace(/ᆲᄇ/g, 'ᆯᄈ')
		.replace(/ᆹᄉ/g, 'ᆸᄊ')
		.replace(/ᆳᄉ/g, 'ᆯᄊ')

		.replace(/ᆪᄋ/g, 'ᆨᄉ')
		.replace(/ᆬᄋ/g, 'ᆫᄌ')
		.replace(/ᆭᄋ/g, 'ᆫᄒ')
		.replace(/ᆰᄋ/g, 'ᆯᄀ')
		.replace(/ᆲᄋ/g, 'ᆯᄇ')
		.replace(/ᆶᄋ/g, 'ᆯᄒ')
		.replace(/ᆱᄋ/g, 'ᆯᄆ')
		.replace(/ᆹᄋ/g, 'ᆸᄉ')
		.replace(/ㄿᄋ/g, 'ᆯᄑ')
		.replace(/ᆳᄋ/g, 'ᆯᄉ')
		.replace(/ㄾᄋ/g, 'ᆯᄐ')

		.replace(/ᆭᄀ/g, 'ᆫᄏ')
		.replace(/ᆭᄃ/g, 'ᆫᄐ')
		.replace(/ᆭᄇ/g, 'ᆫᄑ')
		.replace(/ᆭᄌ/g, 'ᆫᄎ')
		.replace(/ᆶᄀ/g, 'ᆯᄏ')
		.replace(/ᆶᄃ/g, 'ᆯᄐ')
		.replace(/ᆶᄇ/g, 'ᆯᄑ')
		.replace(/ᆶᄌ/g, 'ᆯᄎ')
		.replace(/ᆬᄒ/g, 'ᆫᄎ')
		.replace(/ᆰᄒ/g, 'ᆯᄏ')
		.replace(/ᆲᄒ/g, 'ᆯᄑ')

		.replace(/ᆪ/g, 'ᆨ')
		.replace(/ᆬ/g, 'ᆫ')
		.replace(/ᆭ/g, 'ᆫ')
		.replace(/ᆰ/g, 'ᆨ')
		.replace(/ᆲ/g, 'ᆯ')
		.replace(/ᆶ/g, 'ᆯ')
		.replace(/ᆱ/g, 'ᆷ')
		.replace(/ᆹ/g, 'ᆸ')
		.replace(/ㄿ/g, 'ᇁ')
		.replace(/ᆳ/g, 'ᆯ')
		.replace(/ㄾ/g, 'ᆯ')

		.replace(/ᆮ이/g, '지')
		.replace(/ᆮ히/g, '치')
		.replace(/ᇀ이/g, '치')

		.replace(/ᆨᄋ/g, 'ᄀ')
		.replace(/ᆩᄋ/g, 'ᄁ')
		.replace(/ᆫᄋ/g, 'ᄂ')
		.replace(/ᆮᄋ/g, 'ᄃ')
		.replace(/ᆯᄋ/g, 'ᄅ')
		.replace(/ᆷᄋ/g, 'ᄆ')
		.replace(/ᆸᄋ/g, 'ᄇ')
		.replace(/ᆺᄋ/g, 'ᄉ')
		.replace(/ᆻᄋ/g, 'ᄊ')
		.replace(/ᆽᄋ/g, 'ᄌ')
		.replace(/ᆾᄋ/g, 'ᄎ')
		.replace(/ᆿᄋ/g, 'ᄏ')
		.replace(/ᇀᄋ/g, 'ᄐ')
		.replace(/ᇁᄋ/g, 'ᄑ')
		.replace(/ᇂᄋ/g, 'ᄋ')

		.replace(/(ᆨ|ᆿ)ᄂ/g, 'ᆼᄂ')
		.replace(/(ᆸ|ᇁ)ᄂ/g, 'ᆷᄂ')
		.replace(/(ᆮ|ᆺ|ᆻ|ᆽ|ᆾ|ᇀ|ᇂ)ᄂ/g, 'ᆫᄂ')
		.replace(/(ᆨ|ᆿ)ᄅ/g, 'ᆼᄂ')
		.replace(/ᆫᄅ/g, 'ᆯᄅ')
		.replace(/(ᆷ|ᆸ)ᄅ/g, 'ᆷᄂ')
		.replace(/ᆼᄅ/g, 'ᆼᄂ')
		.replace(/(ᆮ|ᆺ|ᆻ|ᆽ|ᆾ|ᇀ|ᇂ)ᄅ/g, 'ᆫᄂ')
		.replace(/(ᆨ|ᆿ)ᄆ/g, 'ᆼᄆ')
		.replace(/(ᆸ|ᇁ)ᄆ/g, 'ᆷᄆ')
		.replace(/(ᆮ|ᆺ|ᆻ|ᆽ|ᆾ|ᇀ|ᇂ)ᄆ/g, 'ᆫᄆ')

		.replace(/ᇂᄀ/g, 'ᄏ')
		.replace(/ᇂᄃ/g, 'ᄐ')
		.replace(/ᇂᄇ/g, 'ᄑ')
		.replace(/ᇂᄌ/g, 'ᄎ')

		.replace(/ᇂᄂ/g, 'ᆫᄂ')
		.replace(/ᇂ(ᄅ|ᄆ|ᄉ|ᄎ|ᄏ|ᄐ|ᄑ|ᄒ|ᄁ|ᄄ|ᄈ|ᄊ|ᄍ)/g, '$1')

		.replace(/ᆫᄅ/g, 'ᆯᄅ')
		.replace(/ᆯᄂ/g, 'ᆯᄅ')

		.replace(/ᆫᄀ/g, 'ᆫ-ᄀ')
		.replace(/ᆼᄋ/g, 'ᆼ-ᄋ')


		.replace(/시/g, 'shi')
		.replace(/씨/g, 'ṡhi')
		.replace(/샤/g, 'shya')
		.replace(/쌰/g, 'ṡhya')
		.replace(/섀/g, 'shyè')
		.replace(/썌/g, 'ṡhyè')
		.replace(/셔/g, 'shyõ')
		.replace(/쎠/g, 'ṡhyõ')
		.replace(/셰/g, 'shye')
		.replace(/쎼/g, 'ṡhye')
		.replace(/쇼/g, 'shyo')
		.replace(/쑈/g, 'ṡhyo')
		.replace(/슈/g, 'shyu')
		.replace(/쓔/g, 'ṡhyu')
		.replace(/쉬/g, 'shwi')
		.replace(/쒸/g, 'ṡhwi')

		.replace(/ᆯᄅ/g, 'll')
		.replace(/ᄀ/g, 'g')
		.replace(/ᆨ/g, 'k')
		.replace(/ᄁ/g, 'ḳ')
		.replace(/ᆩ/g, 'k')
		.replace(/ᄂ/g, 'n')
		.replace(/ᆫ/g, 'n')
		.replace(/ᄃ/g, 'd')
		.replace(/ᆮ/g, 't')
		.replace(/ᄄ/g, 'ṭ')
		.replace(/ᄅ/g, 'r')
		.replace(/ᆯ/g, 'l')
		.replace(/ᄆ/g, 'm')
		.replace(/ᆷ/g, 'm')
		.replace(/ᄇ/g, 'b')
		.replace(/ᆸ/g, 'p')
		.replace(/ᄈ/g, 'ṗ')
		.replace(/ᄉ/g, 's')
		.replace(/ᆺ/g, 't')
		.replace(/ᄊ/g, 'ṡ')
		.replace(/ᆻ/g, 't')
		.replace(/ᄋ/g, '')
		.replace(/ᆼ/g, 'ng')
		.replace(/ᄌ/g, 'j')
		.replace(/ᆽ/g, 't')
		.replace(/ᄍ/g, 'ċh')
		.replace(/ᄎ/g, 'ch')
		.replace(/ᆾ/g, 't')
		.replace(/ᄏ/g, 'k')
		.replace(/ᆿ/g, 'k')
		.replace(/ᄐ/g, 't')
		.replace(/ᇀ/g, 't')
		.replace(/ᄑ/g, 'p')
		.replace(/ᇁ/g, 'p')
		.replace(/ᄒ/g, 'h')
		.replace(/ᇂ/g, 't')

		.replace(/ᅡ/g, 'a')
		.replace(/ᅢ/g, 'è')
		.replace(/ᅣ/g, 'ya')
		.replace(/ᅤ/g, 'yè')
		.replace(/ᅥ/g, 'õ')
		.replace(/ᅦ/g, 'e')
		.replace(/ᅧ/g, 'yõ')
		.replace(/ᅨ/g, 'ye')
		.replace(/ᅩ/g, 'o')
		.replace(/ᅪ/g, 'wa')
		.replace(/ᅫ/g, 'wè')
		.replace(/ᅬ/g, 'we')
		.replace(/ᅭ/g, 'yo')
		.replace(/ᅮ/g, 'u')
		.replace(/ᅯ/g, 'wõ')
		.replace(/ᅰ/g, 'we')
		.replace(/ᅱ/g, 'wi')
		.replace(/ᅲ/g, 'yu')
		.replace(/ᅳ/g, 'ũ')
		.replace(/ᅴ/g, 'ũi')
		.replace(/ᅵ/g, 'i');
		.normalize('NFC')
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}