function leftright() {
	document.transcription.text2.value = document.transcription.text1.value
		.replace(/Щ/g, "Ш")
		.replace(/щ/g, "ш")
		.replace(/Ц/g, "С")
		.replace(/ц/g, "с")

		.replace(/([БВГДЖҖЗКЛМНҢПРСТФХЦЧШЩ])Е/g, "$1Э")
		.replace(/([БВГДЖҖЗКЛМНҢПРСТФХЦЧШЩбвгджҗзклмнңпрстфхцчшщ])е/g, "$1э")
		.replace(/(\p{Uppercase})Я/ug, "$1ЙА")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Я/ug, "$1$2 ЙА")
		.replace(/Я (\p{Uppercase})(\p{Uppercase})/ug, "ЙА $1$2")
		.replace(/Я(\p{Uppercase})/ug, "ЙА$1")
		.replace(/Я/g, "Йа")
		.replace(/я/g, "йа")
		.replace(/(\p{Uppercase})Е/ug, "$1ЙЭ")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Е/ug, "$1$2 ЙЭ")
		.replace(/Е (\p{Uppercase})(\p{Uppercase})/ug, "ЙЭ $1$2")
		.replace(/Е(\p{Uppercase})/ug, "ЙЭ$1")
		.replace(/Е/g, "Йэ")
		.replace(/е/g, "йэ")
		.replace(/(\p{Uppercase})Ё/ug, "$1ЙО")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ё/ug, "$1$2 ЙО")
		.replace(/Ё (\p{Uppercase})(\p{Uppercase})/ug, "ЙО $1$2")
		.replace(/Ё(\p{Uppercase})/ug, "ЙО$1")
		.replace(/Ё/g, "Йо")
		.replace(/ё/g, "йо")
		.replace(/(\p{Uppercase})Ю/ug, "$1ЙУ")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ю/ug, "$1$2 ЙУ")
		.replace(/Ю (\p{Uppercase})(\p{Uppercase})/ug, "ЙУ $1$2")
		.replace(/Ю(\p{Uppercase})/ug, "ЙУ$1")
		.replace(/Ю/g, "Йу")
		.replace(/ю/g, "йу")

		.replace(/а/g, "a")
		.replace(/ә/g, "ä")
		.replace(/б/g, "b")
		.replace(/в/g, "w")
		.replace(/г/g, "g")
		.replace(/д/g, "d")
		.replace(/ж/g, "ž")
		.replace(/җ/g, "j")
		.replace(/з/g, "z")
		.replace(/и/g, "i")
		.replace(/й/g, "ý")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/ң/g, "ň")
		.replace(/о/g, "o")
		.replace(/ө/g, "ö")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ү/g, "ü")
		.replace(/ф/g, "f")
		.replace(/х/g, "h")
		.replace(/ч/g, "ç")
		.replace(/ш/g, "ş")
		.replace(/ъ/g, "")
		.replace(/ы/g, "y")
		.replace(/ь/g, "")
		.replace(/э/g, "e")
		.replace(/А/g, "A")
		.replace(/Ә/g, "Ä")
		.replace(/Б/g, "B")
		.replace(/В/g, "W")
		.replace(/Г/g, "G")
		.replace(/Д/g, "D")
		.replace(/Ж/g, "Ž")
		.replace(/Җ/g, "J")
		.replace(/З/g, "Z")
		.replace(/И/g, "I")
		.replace(/Й/g, "Ý")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/Ң/g, "Ň")
		.replace(/О/g, "O")
		.replace(/Ө/g, "Ö")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ү/g, "Ü")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "H")
		.replace(/Ч/g, "Ç")
		.replace(/Ш/g, "Ş")
		.replace(/Ъ/g, "")
		.replace(/Ы/g, "Y")
		.replace(/Ь/g, "")
		.replace(/Э/g, "E");
		leftbottom();
}

function rightleft() {
	document.transcription.text2.value = document.transcription.text2.value
		.replace(/C/g, "Ç")
		.replace(/c/g, "ç")
		.replace(/V/g, "W")
		.replace(/v/g, "w")
		.replace(/Ñ/g, "Ň")
		.replace(/ñ/g, "ň")
		.replace(/Ÿ/g, "Ý")
		.replace(/ÿ/g, "ý")
		.replace(/İ/g, "I")
		.replace(/(\p{Script=Latn})[¥Ұ]/ug, "$1Ý")
		.replace(/[¥Ұ](\p{Script=Latn})/ug, "Ý$1")
		.replace(/(\p{Script=Latn})\$/ug, "$1Ş")
		.replace(/\$(\p{Script=Latn})/ug, "Ş$1")
		.replace(/(\p{Script=Latn})¢/ug, "$1ş")
		.replace(/¢(\p{Script=Latn})/ug, "ş$1")
		.replace(/(\p{Script=Latn})£/ug, "$1Ž")
		.replace(/£(\p{Script=Latn})/ug, "Ž$1")
		.replace(/(\p{Script=Latn})ſ/ug, "$1ž")
		.replace(/ſ(\p{Script=Latn})/ug, "ž$1");

	document.transcription.text1.value = document.transcription.text2.value
		.replace(/a/g, "а")
		.replace(/b/g, "б")
		.replace(/ç/g, "ч")
		.replace(/d/g, "д")
		.replace(/e/g, "э")
		.replace(/ä/g, "ә")
		.replace(/f/g, "ф")
		.replace(/g/g, "г")
		.replace(/h/g, "х")
		.replace(/i/g, "и")
		.replace(/j/g, "җ")
		.replace(/ž/g, "ж")
		.replace(/k/g, "к")
		.replace(/l/g, "л")
		.replace(/m/g, "м")
		.replace(/n/g, "н")
		.replace(/ň/g, "ң")
		.replace(/o/g, "о")
		.replace(/ö/g, "ө")
		.replace(/p/g, "п")
		.replace(/r/g, "р")
		.replace(/s/g, "с")
		.replace(/ş/g, "ш")
		.replace(/t/g, "т")
		.replace(/u/g, "у")
		.replace(/ü/g, "ү")
		.replace(/w/g, "в")
		.replace(/y/g, "ы")
		.replace(/ý/g, "й")
		.replace(/z/g, "з")
		.replace(/A/g, "А")
		.replace(/B/g, "Б")
		.replace(/Ç/g, "Ч")
		.replace(/D/g, "Д")
		.replace(/E/g, "Э")
		.replace(/Ä/g, "Ә")
		.replace(/F/g, "Ф")
		.replace(/G/g, "Г")
		.replace(/H/g, "Х")
		.replace(/I/g, "И")
		.replace(/J/g, "Җ")
		.replace(/Ž/g, "Ж")
		.replace(/K/g, "К")
		.replace(/L/g, "Л")
		.replace(/M/g, "М")
		.replace(/N/g, "Н")
		.replace(/Ň/g, "Ң")
		.replace(/O/g, "О")
		.replace(/Ö/g, "Ө")
		.replace(/P/g, "П")
		.replace(/R/g, "Р")
		.replace(/S/g, "С")
		.replace(/Ş/g, "Ш")
		.replace(/T/g, "Т")
		.replace(/U/g, "У")
		.replace(/Ü/g, "Ү")
		.replace(/W/g, "В")
		.replace(/Y/g, "Ы")
		.replace(/Ý/g, "Й")
		.replace(/Z/g, "З")

		.replace(/йа/g, "я")
		.replace(/йо/g, "ё")
		.replace(/йу/g, "ю")
		.replace(/Й([Аа])/g, "Я")
		.replace(/Й([Оо])/g, "Ё")
		.replace(/Й([Уу])/g, "Ю")

		.replace(/ййэ/g, "ййе")
		.replace(/ЙЙЭ/g, "ЙЙЕ")

		.replace(/([БЦЧДФГҒХҲЖКҚЛМНПРСШТВЗбцчдфгғхҳжкқлмнпрсштвз])йэ/g, "$1ье")
		.replace(/([БЦЧДФГҒХҲЖКҚЛМНПРСШТВЗ])ЙЭ/g, "$1ЬЕ")
		.replace(/([БЦЧДФГҒХҲЖКҚЛМНПРСШТВЗбцчдфгғхҳжкқлмнпрсштвз])э/g, "$1е")
		.replace(/([БЦЧДФГҒХҲЖКҚЛМНПРСШТВЗ])Э/g, "$1Е")

		.replace(/йэ/g, "е")
		.replace(/Й(Э|э)/g, "Е")

		.replace(/\u201e/g, "\u00ab")
		.replace(/\u201c/g, "\u00bb");
}

function rightbottom() {
	document.transcription.text3.value = document.transcription.text2.value
		.replace(/J/g, "C")
		.replace(/Ž/g, "J")
		.replace(/Ň/g, "Ñ")
		.replace(/I/g, "İ")
		.replace(/Y/g, "I")
		.replace(/Ý/g, "Y")
		.replace(/W/g, "V")
		.replace(/j/g, "c")
		.replace(/ž/g, "j")
		.replace(/ň/g, "ñ")
		.replace(/y/g, "ı")
		.replace(/ý/g, "y")
		.replace(/w/g, "v")
		.replace(/([AÄBCÇDEFGHIİJLMNÑOÖPRSŞTUÜVYZ])G/g, "$1Ğ")
		.replace(/([AÄBCÇDEFGHIİJLMNÑOÖPRSŞTUÜVYZaäbcçdefghıijlmnñoöprsştuüvyz])g/g, "$1ğ");
}

function bottomright() {
	document.transcription.text2.value = document.transcription.text3.value
		.replace(/V/g, "W")
		.replace(/Y/g, "Ý")
		.replace(/I/g, "Y")
		.replace(/İ/g, "I")
		.replace(/Ñ/g, "Ň")
		.replace(/J/g, "Ž")
		.replace(/C/g, "J")
		.replace(/Ğ/g, "G")
		.replace(/v/g, "w")
		.replace(/y/g, "ý")
		.replace(/ı/g, "y")
		.replace(/ñ/g, "ň")
		.replace(/j/g, "ž")
		.replace(/c/g, "j")
		.replace(/ğ/g, "g");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}

function copy3() {
	navigator.clipboard.writeText(document.transcription.text3.value);
}
