//  copyright lexilogos.com
var car;
function latgeo () {
car = document.transcription.text2.value;
car = car.replace(/ʒ/g, "э");
car = car.replace(/ȝ/g, "э");
car = car.replace(/ǯ/g, "ў");
car = car.replace(/u/g, "т");
car = car.replace(/ť/g, "ю");
car = car.replace(/t̆/g, "ю");
car = car.replace(/t́/g, "ю");
car = car.replace(/t/g, "у");
car = car.replace(/p̌/g, "ё");
car = car.replace(/ṕ/g, "ё");
car = car.replace(/p/g, "о");
car = car.replace(/o/g, "п");
car = car.replace(/ǧ/g, "ғ");
car = car.replace(/ğ/g, "ғ");
car = car.replace(/ǩ/g, "ү");
car = car.replace(/ḱ/g, "ү");
car = car.replace(/z/g, "а");
car = car.replace(/ž/g, "я");
car = car.replace(/a/g, "з");
car = car.replace(/ç̌/g, "ө");
car = car.replace(/ḉ/g, "ө");
car = car.replace(/Ʒ/g, "Э");
car = car.replace(/Ȝ/g, "Э");
car = car.replace(/Ǯ/g, "Ў");
car = car.replace(/U/g, "Т");
car = car.replace(/T/g, "У");
car = car.replace(/Ť/g, "Ю");
car = car.replace(/T̆/g, "Ю");
car = car.replace(/T́/g, "Ю");
car = car.replace(/Ṕ/g, "Ё");
car = car.replace(/P̌/g, "Ё");
car = car.replace(/P/g, "О");
car = car.replace(/O/g, "П");
car = car.replace(/Ǧ/g, "Ғ");
car = car.replace(/Ğ/g, "Ғ");
car = car.replace(/Ǩ/g, "Ү");
car = car.replace(/Ḱ/g, "Ү");
car = car.replace(/Z/g, "А");
car = car.replace(/Ž/g, "Я");
car = car.replace(/A/g, "З");
car = car.replace(/Ç̌/g, "Ө");
car = car.replace(/Ḉ/g, "Ө");

car = car.replace(/ў/g, "w");
car = car.replace(/т/g, "t");
car = car.replace(/у/g, "u");
car = car.replace(/ю/g, "û");
car = car.replace(/э/g, "é");
car = car.replace(/о/g, "o");
car = car.replace(/ё/g, "ô");
car = car.replace(/п/g, "p");
car = car.replace(/ғ/g, "ğ");
car = car.replace(/ү/g, "ü");
car = car.replace(/а/g, "a");
car = car.replace(/я/g, "â");
car = car.replace(/з/g, "z");
car = car.replace(/ө/g, "ö");
car = car.replace(/Ў/g, "W");
car = car.replace(/Т/g, "T");
car = car.replace(/У/g, "U");
car = car.replace(/Ю/g, "Û");
car = car.replace(/Э/g, "É");
car = car.replace(/О/g, "O");
car = car.replace(/Ё/g, "Ô");
car = car.replace(/П/g, "P");
car = car.replace(/Ғ/g, "Ğ");
car = car.replace(/Ү/g, "Ü");
car = car.replace(/А/g, "A");
car = car.replace(/Я/g, "Â");
car = car.replace(/З/g, "Z");
car = car.replace(/Ө/g, "Ö");
document.transcription.text1.value=car;
}
function geolat () {
car = document.transcription.text1.value;
car = car.replace(/w/g, "ў");
car = car.replace(/t/g, "т");
car = car.replace(/u/g, "у");
car = car.replace(/û/g, "ю");
car = car.replace(/é/g, "э");
car = car.replace(/o/g, "о");
car = car.replace(/ô/g, "ё");
car = car.replace(/p/g, "п");
car = car.replace(/ğ/g, "ғ");
car = car.replace(/ü/g, "ү");
car = car.replace(/a/g, "а");
car = car.replace(/â/g, "я");
car = car.replace(/z/g, "з");
car = car.replace(/ö/g, "ө");
car = car.replace(/W/g, "Ў");
car = car.replace(/T/g, "Т");
car = car.replace(/U/g, "У");
car = car.replace(/Û/g, "Ю");
car = car.replace(/É/g, "Э");
car = car.replace(/O/g, "О");
car = car.replace(/Ô/g, "Ё");
car = car.replace(/P/g, "П");
car = car.replace(/Ğ/g, "Ғ");
car = car.replace(/Ü/g, "Ү");
car = car.replace(/A/g, "А");
car = car.replace(/Â/g, "Я");
car = car.replace(/Z/g, "З");
car = car.replace(/Ö/g, "Ө");

car = car.replace(/ў/g, "ǯ");
car = car.replace(/т/g, "u");
car = car.replace(/у/g, "t");
car = car.replace(/ю/g, "ť");
car = car.replace(/э/g, "ʒ");
car = car.replace(/о/g, "p");
car = car.replace(/ё/g, "p̌");
car = car.replace(/п/g, "o");
car = car.replace(/ғ/g, "ǧ");
car = car.replace(/ү/g, "ǩ");
car = car.replace(/а/g, "z");
car = car.replace(/я/g, "ž");
car = car.replace(/з/g, "a");
car = car.replace(/ө/g, "ç̌");
car = car.replace(/Ў/g, "Ǯ");
car = car.replace(/Т/g, "U");
car = car.replace(/У/g, "T");
car = car.replace(/Ю/g, "Ť");
car = car.replace(/Э/g, "Ʒ");
car = car.replace(/О/g, "P");
car = car.replace(/Ё/g, "P̌");
car = car.replace(/П/g, "O");
car = car.replace(/Ғ/g, "Ǧ");
car = car.replace(/Ү/g, "Ǩ");
car = car.replace(/А/g, "Z");
car = car.replace(/Я/g, "Ž");
car = car.replace(/З/g, "A");
car = car.replace(/Ө/g, "Ç̌");

document.transcription.text2.value=car;
}
function copy1()
{ textRange=document.transcription.text1.createTextRange();   textRange.execCommand("Copy");   textRange="";
}
function copy2()
{ textRange=document.transcription.text2.createTextRange();   textRange.execCommand("Copy");   textRange="";
}