function cyrlat() {
	document.transcription.text1.value = document.transcription.text1.value
		.replace(/Ы/g, "Ъ")
		.replace(/ы/g, "ъ");

	document.transcription.text2.value = document.transcription.text1.value
		.replace(/ъ̀/g, "ъ")
		.replace(/дж/g, "џ")
		.replace(/Дж/g, "Џ")
		.replace(/ДЖ/g, "Џ")
		.replace(/тс/g, "т-с")
		.replace(/Тс/g, "Т-с")
		.replace(/ТС/g, "Т-С")

		.replace(/кя/g, "кâ")
		.replace(/кю/g, "кû")
		.replace(/гя/g, "гâ")
		.replace(/гю/g, "гû")
		.replace(/ля/g, "лâ")
		.replace(/лю/g, "лû")
		.replace(/Кя/g, "Кâ")
		.replace(/Кю/g, "Кû")
		.replace(/Гя/g, "Гâ")
		.replace(/Гю/g, "Гû")
		.replace(/Ля/g, "Лâ")
		.replace(/Лю/g, "Лû")
		.replace(/КЯ/g, "КÂ")
		.replace(/КЮ/g, "КÛ")
		.replace(/ГЯ/g, "ГÂ")
		.replace(/ГЮ/g, "ГÛ")
		.replace(/ЛЯ/g, "ЛÂ")
		.replace(/ЛЮ/g, "ЛÛ")

		.replace(/а/g, "a")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/д/g, "d")
		.replace(/е/g, "e")
		.replace(/ж/g, "j")
		.replace(/з/g, "z")
		.replace(/и/g, "i")
		.replace(/ѝ/g, "ì")
		.replace(/й/g, "y")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/о/g, "o")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ф/g, "f")
		.replace(/х/g, "h")
		.replace(/ц/g, "ѕ")
		.replace(/џ/g, "c")
		.replace(/ч/g, "ç")
		.replace(/ш/g, "ş")
		.replace(/щ/g, "şt")
		.replace(/ъ/g, "ı")
		.replace(/ь/g, "y")
		.replace(/ю/g, "yu")
		.replace(/я/g, "ya")

		.replace(/А/g, "A")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Д/g, "D")
		.replace(/Е/g, "E")
		.replace(/Ж/g, "J")
		.replace(/З/g, "Z")
		.replace(/И/g, "İ")
		.replace(/Ѝ/g, "Ì")
		.replace(/Й/g, "Y")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/О/g, "O")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "H")
		.replace(/Ц/g, "Ѕ")
		.replace(/Ч/g, "Ç")
		.replace(/Џ/g, "C")
		.replace(/Ш/g, "Ş")
		.replace(/Щ/g, "Şt")
		.replace(/Ъ/g, "I")
		.replace(/Ь/g, "Y")
		.replace(/Ю/g, "Yu")
		.replace(/Я/g, "Ya")

		.replace(/aѕ/g, "ats")
		.replace(/eѕ/g, "ets")
		.replace(/ıѕ/g, "ıts")
		.replace(/iѕ/g, "its")
		.replace(/oѕ/g, "ots")
		.replace(/uѕ/g, "uts")
		.replace(/Aѕ/g, "Ats")
		.replace(/Eѕ/g, "Ets")
		.replace(/Iѕ/g, "Its")
		.replace(/İѕ/g, "İts")
		.replace(/Oѕ/g, "Ots")
		.replace(/Uѕ/g, "Uts")
		.replace(/AЅ/g, "ATS")
		.replace(/EЅ/g, "ETS")
		.replace(/IЅ/g, "ITS")
		.replace(/İЅ/g, "İTS")
		.replace(/OЅ/g, "OTS")
		.replace(/UЅ/g, "UTS");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}
