var car;
function cyrlat () {
car = document.transcription.text1.value;
  car = car.replace(/ е/g, " je");
  car = car.replace(/\nе/g, "\nje");
  car = car.replace(/\rе/g, "\rje");
  car = car.replace(/^е/g, "je");

  car = car.replace(/ае/g, "аje");
  car = car.replace(/әе/g, "әje");
  car = car.replace(/ие/g, "иje");
  car = car.replace(/ые/g, "ыje");
  car = car.replace(/ее/g, "еje");
  car = car.replace(/эе/g, "эje");
  car = car.replace(/уе/g, "уje");
  car = car.replace(/ое/g, "оje");
  car = car.replace(/өе/g, "өje");
  car = car.replace(/ёе/g, "ёje");
  car = car.replace(/үе/g, "үje");
  car = car.replace(/йе/g, "йje");
  car = car.replace(/юе/g, "юje");
  car = car.replace(/яе/g, "яje");

  car = car.replace(/ Е/g, " je");
  car = car.replace(/\nЕ/g, "\nje");
  car = car.replace(/\rЕ/g, "\rje");
  car = car.replace(/^Е/g, "je");

  car = car.replace(/Ае/g, "Аje");
  car = car.replace(/Әе/g, "Әje");
  car = car.replace(/Ие/g, "Иje");
  car = car.replace(/Ые/g, "Ыje");
  car = car.replace(/Ее/g, "Еje");
  car = car.replace(/Эе/g, "Эje");
  car = car.replace(/Уе/g, "Уje");
  car = car.replace(/Ое/g, "Оje");
  car = car.replace(/Өе/g, "Өje");
  car = car.replace(/Ёе/g, "Ёje");
  car = car.replace(/Үе/g, "Үje");
  car = car.replace(/Йе/g, "Йje");
  car = car.replace(/Юе/g, "Юje");
  car = car.replace(/Яе/g, "Яje");

  car = car.replace(/АЕ/g, "Аje");
  car = car.replace(/ӘЕ/g, "Әje");
  car = car.replace(/ИЕ/g, "Иje");
  car = car.replace(/ЫЕ/g, "Ыje");
  car = car.replace(/ЕЕ/g, "Еje");
  car = car.replace(/ЭЕ/g, "Эje");
  car = car.replace(/УЕ/g, "Уje");
  car = car.replace(/ОЕ/g, "Оje");
  car = car.replace(/ӨЕ/g, "Өje");
  car = car.replace(/ЁЕ/g, "Ёje");
  car = car.replace(/ҮЕ/g, "Үje");
  car = car.replace(/ЙЕ/g, "Йje");
  car = car.replace(/ЮЕ/g, "Юje");
  car = car.replace(/ЯЕ/g, "Яje");

  car = car.replace(/а/g, "a");
  car = car.replace(/ә/g, "ä");
  car = car.replace(/б/g, "b");
  car = car.replace(/в/g, "v");
  car = car.replace(/г/g, "g");
  car = car.replace(/һ/g, "h");
  car = car.replace(/д/g, "d");
  car = car.replace(/е/g, "e");
  car = car.replace(/ё/g, "jo");
  car = car.replace(/ж/g, "ž");
  car = car.replace(/җ/g, "dž");
  car = car.replace(/з/g, "z");
  car = car.replace(/к/g, "k");
  car = car.replace(/и/g, "i");
  car = car.replace(/й/g, "j");
  car = car.replace(/л/g, "l");
  car = car.replace(/м/g, "m");
  car = car.replace(/н/g, "n");
  car = car.replace(/ң/g, "ň");
  car = car.replace(/о/g, "o");
  car = car.replace(/ө/g, "ö");
  car = car.replace(/п/g, "p");
  car = car.replace(/р/g, "r");
  car = car.replace(/с/g, "s");
  car = car.replace(/т/g, "t");
  car = car.replace(/у/g, "u");
  car = car.replace(/ү/g, "ü");
  car = car.replace(/ф/g, "f");
  car = car.replace(/х/g, "q");
  car = car.replace(/ц/g, "c");
  car = car.replace(/ч/g, "č");
  car = car.replace(/ш/g, "š");
  car = car.replace(/щ/g, "ś");
  car = car.replace(/ъ/g, "ʼ");
  car = car.replace(/ы/g, "y");
  car = car.replace(/ь/g, "ĭ");
  car = car.replace(/э/g, "e");
  car = car.replace(/ю/g, "ju");
  car = car.replace(/я/g, "ja");
  car = car.replace(/А/g, "A");
  car = car.replace(/Ә/g, "Ä");
  car = car.replace(/Б/g, "B");
  car = car.replace(/В/g, "V");
  car = car.replace(/Г/g, "G");
  car = car.replace(/Һ/g, "H");
  car = car.replace(/Д/g, "D");
  car = car.replace(/Е/g, "Je");
  car = car.replace(/Ё/g, "Jo");
  car = car.replace(/Ж/g, "Ž");
  car = car.replace(/Җ/g, "Dž");
  car = car.replace(/З/g, "Z");
  car = car.replace(/К/g, "K");
  car = car.replace(/И/g, "I");
  car = car.replace(/Й/g, "J");
  car = car.replace(/Л/g, "L");
  car = car.replace(/М/g, "M");
  car = car.replace(/Н/g, "N");
  car = car.replace(/Ң/g, "Ň");
  car = car.replace(/О/g, "O");
  car = car.replace(/Ө/g, "Ö");
  car = car.replace(/П/g, "P");
  car = car.replace(/Р/g, "R");
  car = car.replace(/С/g, "S");
  car = car.replace(/Т/g, "T");
  car = car.replace(/У/g, "U");
  car = car.replace(/Ү/g, "Ü");
  car = car.replace(/Ф/g, "F");
  car = car.replace(/Х/g, "Q");
  car = car.replace(/Ц/g, "C");
  car = car.replace(/Ч/g, "Č");
  car = car.replace(/Ш/g, "Š");
  car = car.replace(/Щ/g, "Ś");
  car = car.replace(/Ъ/g, "ʼ");
  car = car.replace(/Ы/g, "Y");
  car = car.replace(/Ь/g, "Ĭ");
  car = car.replace(/Э/g, "E");
  car = car.replace(/Ю/g, "Ju");
  car = car.replace(/Я/g, "Ja");
document.transcription.text2.value=car;
}
function copy1()
{ textRange=document.transcription.text1.createTextRange();   textRange.execCommand("Copy");   textRange="";
}
function copy2()
{ textRange=document.transcription.text2.createTextRange();   textRange.execCommand("Copy");   textRange="";
}
