function cyrlat() {
document.transcription.text2.value = document.transcription.text1.value
	.replace(/<</g, "«")
		.replace(/>>/g, "»")
		.replace(/<</g, "«")
		.replace(/>>/g, "»")

		.replace(/(Ж|Ц|Ш)И/g, "$1Ы")
		.replace(/(Ж|Ц|Ш|ж|ц|ш)и/g, "$1ы")
		.replace(/(Й|Ч|Щ)Ы/g, "$1И")
		.replace(/(Й|Ч|Щ|й|ч|щ)ы/g, "$1и")

		.replace(/Ы(А|Б|В|Г|Д|Е|Ё|Ж|З|И|Й|К|Л|М|Н|О|П|Р|С|Т|У|Ф|Х|Ц|Ч|Ш|Щ|Ъ|Ы|Ь|Э|Ю|Я|а|б|в|г|д|е|ё|ж|з|и|й|к|л|м|н|о|п|р|с|т|у|ф|х|ц|ч|ш|щ|ъ|ы|ь|э|ю|я)/g, "Ӹ$1")
		.replace(/ы(а|б|в|г|д|е|ё|ж|з|и|й|к|л|м|н|о|п|р|с|т|у|ф|х|ц|ч|ш|щ|ъ|ы|ь|э|ю|я)/g, "ӹ$1")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ы/ug, "$1$2 ЫЙ")
		.replace(/(\p{Uppercase})Ы/ug, "$1ЫЙ")
		.replace(/Ы (\p{Uppercase})(\p{Uppercase})/ug, "ЫЙ $1$2")
		.replace(/Ы(\p{Uppercase})/ug, "ЫЙ$1")
		.replace(/Ы/g, "Ый")
		.replace(/ы/g, "ый")
		.replace(/Ӹ/g, "Ы")
		.replace(/ӹ/g, "ы")

		.replace(/Ъ/g, "ъ")
		.replace(/Ь/g, "ь")



		.replace(/(Б|В|Г|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)Е/g, "$1E")
		.replace(/(Б|В|Г|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)е/g, "$1e")
		.replace(/(Б|В|Г|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)Э/g, "$1ъE")
		.replace(/(Б|В|Г|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)э/g, "$1ъe")

		.replace(/(Б|В|Г|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)Я/g, "$1ьA")
		.replace(/(Б|В|Г|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)я/g, "$1ьa")
		.replace(/(Б|В|Г|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)Ё/g, "$1ьO")
		.replace(/(Б|В|Г|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)ё/g, "$1ьo")
		.replace(/(Б|В|Г|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)Ю/g, "$1ьU")
		.replace(/(Б|В|Г|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Т|Ф|Х|Ц|Ч|Ш|Щ|б|в|г|д|ж|з|й|к|л|м|н|п|р|с|т|ф|х|ц|ч|ш|щ)ю/g, "$1ьu")

		.replace(/ьA(Бь|Вь|Гь|Дь|Зь|Й|Кь|Ль|Мь|Нь|Пь|Рь|Сь|Ть|Фь|Хь|Ч|Щ|бь|вь|гь|дь|зь|й|кь|ль|мь|нь|пь|рь|сь|ть|фь|хь|ч|щ)/g, "ьE$1")
		.replace(/ьa(бь|вь|гь|дь|зь|й|кь|ль|мь|нь|пь|рь|сь|ть|фь|хь|ч|щ)/g, "ьe$1")
		.replace(/ьO(Бь|Вь|Гь|Дь|Зь|Й|Кь|Ль|Мь|Нь|Пь|Рь|Сь|Ть|Фь|Хь|Ч|Щ|бь|вь|гь|дь|зь|й|кь|ль|мь|нь|пь|рь|сь|ть|фь|хь|ч|щ)/g, "ьÖ$1")
		.replace(/ьo(бь|вь|гь|дь|зь|й|кь|ль|мь|нь|пь|рь|сь|ть|фь|хь|ч|щ)/g, "ьö$1")
		.replace(/ьU(Бь|Вь|Гь|Дь|Зь|Й|Кь|Ль|Мь|Нь|Пь|Рь|Сь|Ть|Фь|Хь|Ч|Щ|бь|вь|гь|дь|зь|й|кь|ль|мь|нь|пь|рь|сь|ть|фь|хь|ч|щ)/g, "ьÜ$1")
		.replace(/ьu(бь|вь|гь|дь|зь|й|кь|ль|мь|нь|пь|рь|сь|ть|фь|хь|ч|щ)/g, "ьü$1")

		.replace(/ьa/g, "à")
		.replace(/ьA/g, "À")
		.replace(/ьu/g, "ù")
		.replace(/ьU/g, "Ù")

		.replace(/Д(Ж|ж)/g, "C")
		.replace(/дж/g, "c")

		.replace(/а/g, "a")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/д/g, "d")
		.replace(/е/g, "ye")
		.replace(/ж/g, "j")
		.replace(/з/g, "z")
		.replace(/и/g, "i")
		.replace(/й/g, "y")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/о/g, "o")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ф/g, "f")
		.replace(/х/g, "h")
		.replace(/ч/g, "ç")
		.replace(/ш/g, "ş")
		.replace(/ъ/g, "")
		.replace(/ы/g, "ı")
		.replace(/ь/g, "")
		.replace(/э/g, "e")
		.replace(/ю/g, "yu")
		.replace(/ё/g, "yo")
		.replace(/я/g, "ya")

		.replace(/А/g, "A")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Д/g, "D")
		.replace(/Е/g, "Ye")
		.replace(/Ж/g, "J")
		.replace(/З/g, "Z")
		.replace(/И/g, "İ")
		.replace(/Й/g, "Y")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/О/g, "O")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "H")
		.replace(/Ч/g, "Ç")
		.replace(/Ш/g, "Ş")
		.replace(/Ы/g, "I")
		.replace(/Ь/g, "")
		.replace(/Э/g, "E")
		.replace(/Ю/g, "Yu")
		.replace(/Ё/g, "Yo")
		.replace(/Я/g, "Ya")

		.replace(/(A|À|E|I|İ|O|Ö|U|Ù|Ü|a|à|e|ı|i|o|ö|u|ù|ü)щ(A|À|E|I|İ|O|Ö|U|Ù|Ü|a|à|e|ı|i|o|ö|u|ù|ü)/g, "$1şş$2")
		.replace(/(A|À|E|I|İ|O|Ö|U|Ù|Ü)Щ(A|À|E|I|İ|O|Ö|U|Ù|Ü)/g, "$1ŞŞ$2")
		.replace(/(A|À|E|I|İ|O|Ö|U|Ù|Ü)Щ(a|à|e|ı|i|o|ö|u|ù|ü)/g, "$1Şş$2")
		.replace(/(a|à|e|ı|i|o|ö|u|ù|ü)Щ(A|À|E|I|İ|O|Ö|U|Ù|Ü)/g, "$1ŞŞ$2")
		.replace(/щ/g, "ş")
		.replace(/Щ/g, "Ş")

		.replace(/(A|À|E|I|İ|O|Ö|U|Ù|Ü|a|à|e|ı|i|o|ö|u|ù|ü)ц/g, "$1ts")
		.replace(/(A|À|E|I|İ|O|Ö|U|Ù|Ü)Ц/g, "$1TS")
		.replace(/ц/g, "s")
		.replace(/Ц/g, "S")

		.replace(/(G|g|K|k|L|l)à/g, "$1â")
		.replace(/(G|g|K|k|L|l)À/g, "$1Â")
		.replace(/(G|g|K|k|L|l)ù/g, "$1û")
		.replace(/(G|g|K|k|L|l)ù/g, "$1Û")
		.replace(/à/g, "a")
		.replace(/À/g, "A")
		.replace(/ù/g, "u")
		.replace(/Ù/g, "U");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}
