var car;

function cyrlat () {
car = document.transcription.text1.value;
car = car.normalize('NFD');
car = car.replace(/(ं|ँ)(क|ख|ग|घ|ह)/g, "\u0303ṅ$2");
car = car.replace(/(ं|ँ)(त|थ|द|ध|ल|स)/g, "\u0303n$2");
car = car.replace(/(ं|ँ)(प|फ|ब|भ|व)/g, "\u0303m$2");
car = car.replace(/(ं|ँ)/g, "\u0303");
car = car.replace(/क़/g, "q\u200c");
car = car.replace(/ख़/g, "x\u200c");
car = car.replace(/ग़/g, "ġ\u200c");
car = car.replace(/ज़/g, "z\u200c");
car = car.replace(/झ़/g, "ź\u200c");
car = car.replace(/फ़/g, "f\u200c");
car = car.replace(/ड़/g, "ṛ\u200c");
car = car.replace(/ढ़/g, "ṛh\u200c");
car = car.replace(/क/g, "k\u200c");
car = car.replace(/ख/g, "kh\u200c");
car = car.replace(/ग/g, "g\u200c");
car = car.replace(/घ/g, "gh\u200c");
car = car.replace(/ङ/g, "ṅ\u200c");
car = car.replace(/ह/g, "h\u200c");
car = car.replace(/च/g, "c\u200c");
car = car.replace(/छ/g, "ch\u200c");
car = car.replace(/ज/g, "j\u200c");
car = car.replace(/झ/g, "jh\u200c");
car = car.replace(/ञ/g, "ñ\u200c");
car = car.replace(/य/g, "y\u200c");
car = car.replace(/श/g, "ś\u200c");
car = car.replace(/ट/g, "ṭ\u200c");
car = car.replace(/ठ/g, "ṭh\u200c");
car = car.replace(/ड/g, "ḍ\u200c");
car = car.replace(/ढ/g, "ḍh\u200c");
car = car.replace(/ण/g, "ṇ\u200c");
car = car.replace(/र/g, "r\u200c");
car = car.replace(/ष/g, "ṣ\u200c");
car = car.replace(/त/g, "t\u200c");
car = car.replace(/थ/g, "th\u200c");
car = car.replace(/द/g, "d\u200c");
car = car.replace(/ध/g, "dh\u200c");
car = car.replace(/न/g, "n\u200c");
car = car.replace(/ल/g, "l\u200c");
car = car.replace(/स/g, "s\u200c");
car = car.replace(/प/g, "p\u200c");
car = car.replace(/फ/g, "ph\u200c");
car = car.replace(/ब/g, "b\u200c");
car = car.replace(/भ/g, "bh\u200c");
car = car.replace(/म/g, "m\u200c");
car = car.replace(/व/g, "v\u200c");
car = car.replace(/ळ/g, "ḷ\u200c");
car = car.replace(/व़/g, "w\u200c");
car = car.replace(/\u200c(ि|ु|ृ|े|ो|ा|ी|ू|ै|ौ)/g, "$1");
car = car.replace(/\u200c्/g, "");
car = car.replace(/\u200c(क़|ख़|ग़|ज़|झ़|फ़|ड़|ढ़|क|ख|ग|घ|ङ|ह|च|छ|ज|झ|ञ|य|श|ट|ठ|ड|ढ|ण|र|ष|त|थ|द|ध|न|ल|स|प|फ|ब|भ|म|व|ळ|व़|इ|उ|ऋ|ए|ओ|आ|ई|ऊ|ऐ|औ|ः)/g, "a$1");
car = car.replace(/\u200c/g, "");
car = car.replace(/अ/g, "a");
car = car.replace(/इ/g, "i");
car = car.replace(/ि/g, "i");
car = car.replace(/उ/g, "u");
car = car.replace(/ु/g, "u");
car = car.replace(/ऋ/g, "ŕ");
car = car.replace(/ृ/g, "ŕ");
car = car.replace(/ए/g, "e");
car = car.replace(/े/g, "e");
car = car.replace(/ओ/g, "o");
car = car.replace(/ो/g, "o");
car = car.replace(/आ/g, "ā");
car = car.replace(/ा/g, "ā");
car = car.replace(/ई/g, "ī");
car = car.replace(/ी/g, "ī");
car = car.replace(/ऊ/g, "ū");
car = car.replace(/ू/g, "ū");
car = car.replace(/ऐ/g, "ai");
car = car.replace(/ै/g, "ai");
car = car.replace(/औ/g, "au");
car = car.replace(/ौ/g, "au");
car = car.replace(/ः/g, "ḥ");
car = car.replace(/\u0964/g, "\u002e");
car = car.replace(/\u0965/g, "");  
car = car.normalize('NFC');
document.transcription.text2.value = car;
}
function copy1()
{ textRange=document.transcription.text1.createTextRange();
textRange.execCommand("Copy");
textRange="";
}
function copy2()
{ textRange=document.transcription.text2.createTextRange();
textRange.execCommand("Copy");
textRange="";
}
