function cyrlat() {
	document.transcription.text2.value = document.transcription.text1.value
		.replace(/\u0301/g, "")

		.replace(/Ÿ/g, "Ӳ")
		.replace(/ÿ/g, "ӳ")
		.replace(/Ĕ/g, "Ӗ")
		.replace(/ĕ/g, "ӗ")

		.replace(/(\p{Script=Cyrl})Ç/ug, "$1Ҫ")
		.replace(/Ç(\p{Script=Cyrl})/ug, "Ҫ$1")
		.replace(/(\p{Script=Cyrl})ç/ug, "$1ҫ")
		.replace(/ç(\p{Script=Cyrl})/ug, "ҫ$1")

		.replace(/(\p{Script=Cyrl})Ă/ug, "$1Ӑ")
		.replace(/Ă(\p{Script=Cyrl})/ug, "Ӑ$1")
		.replace(/(\p{Script=Cyrl})ă/ug, "$1ӑ")
		.replace(/ă(\p{Script=Cyrl})/ug, "ӑ$1")

		.replace(/(\p{Script=Cyrl})Ç/ug, "$1Ҫ")
		.replace(/Ç(\p{Script=Cyrl})/ug, "Ҫ$1")
		.replace(/(\p{Script=Cyrl})ç/ug, "$1ҫ")
		.replace(/ç(\p{Script=Cyrl})/ug, "ҫ$1")

        .replace(/([АӐЕЁӖИОУӲЫЭЮЯ])Щ([АӐЕЁӖИОУӲЫЭЮЯ])/g, "$1ҪҪ$2")
		.replace(/([АӐЕЁӖИОУӲЫЭЮЯаӑеёӗиоуӳыэюя])щ([аӑеёӗиоуӳыэюя])/g, "$1ҫҫ$2")
		.replace(/щ/g, "ҫ")
		.replace(/Щ/g, "Ҫ")

		.replace(/(Б|В|Г|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Ҫ|Т|Ф|Х|Ц|Ч|Ш)Я/g, "$1ЬА")
		.replace(/(б|в|г|д|ж|з|й|к|л|м|н|п|р|с|ҫ|т|ф|х|ц|ч|ш)Я/g, "$1ьА")
		.replace(/(Б|В|Г|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Ҫ|Т|Ф|Х|Ц|Ч|Ш|б|в|г|д|ж|з|й|к|л|м|н|п|р|с|ҫ|т|ф|х|ц|ч|ш)я/g, "$1ьа")
		.replace(/(Б|В|Г|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Ҫ|Т|Ф|Х|Ц|Ч|Ш)Ю/g, "$1ЬУ")
		.replace(/(б|в|г|д|ж|з|й|к|л|м|н|п|р|с|ҫ|т|ф|х|ц|ч|ш)Ю/g, "$1ьУ")
		.replace(/(Б|В|Г|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Ҫ|Т|Ф|Х|Ц|Ч|Ш|б|в|г|д|ж|з|й|к|л|м|н|п|р|с|ҫ|т|ф|х|ц|ч|ш)ю/g, "$1ьу")
		.replace(/(Б|В|Г|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Ҫ|Т|Ф|Х|Ц|Ч|Ш|б|в|г|д|ж|з|й|к|л|м|н|п|р|с|ҫ|т|ф|х|ц|ч|ш)Е/g, "$1Э")
		.replace(/(Б|В|Г|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Ҫ|Т|Ф|Х|Ц|Ч|Ш|б|в|г|д|ж|з|й|к|л|м|н|п|р|с|ҫ|т|ф|х|ц|ч|ш)е/g, "$1э")
		.replace(/(Б|В|Г|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Ҫ|Т|Ф|Х|Ц|Ч|Ш)Ё/g, "$1ЬО")
		.replace(/(б|в|г|д|ж|з|й|к|л|м|н|п|р|с|ҫ|т|ф|х|ц|ч|ш)Ё/g, "$1ьО")
		.replace(/(Б|В|Г|Д|Ж|З|Й|К|Л|М|Н|П|Р|С|Ҫ|Т|Ф|Х|Ц|Ч|Ш|б|в|г|д|ж|з|й|к|л|м|н|п|р|с|ҫ|т|ф|х|ц|ч|ш)ё/g, "$1ьо")

		.replace(/Ь(И|и)/g, "Й$1")
		.replace(/ьи/g, "йи")
		.replace(/Ь(О|о)/g, "Й$1")
		.replace(/ьо/g, "йо")

		.replace(/(\p{Lu})(\p{Lu}) Я/ug, "$1$2 ЙА")
		.replace(/(\p{Lu})Я/ug, "$1ЙА")
		.replace(/Я (\p{Lu})(\p{Lu})/ug, "ЙА $1$2")
		.replace(/Я(\p{Lu})/ug, "ЙА$1")
		.replace(/Я/g, "Йа")
		.replace(/я/g, "йа")
		.replace(/(\p{Lu})(\p{Lu}) Е/ug, "$1$2 ЙЭ")
		.replace(/(\p{Lu})Е/ug, "$1ЙЭ")
		.replace(/Е (\p{Lu})(\p{Lu})/ug, "ЙЭ $1$2")
		.replace(/Е(\p{Lu})/ug, "ЙЭ$1")
		.replace(/Е/g, "Йэ")
		.replace(/е/g, "йэ")
		.replace(/(\p{Lu})(\p{Lu}) Ё/ug, "$1$2 ЙО")
		.replace(/(\p{Lu})Ё/ug, "$1ЙО")
		.replace(/Ё (\p{Lu})(\p{Lu})/ug, "ЙО $1$2")
		.replace(/Ё(\p{Lu})/ug, "ЙО$1")
		.replace(/Ё/g, "Йо")
		.replace(/ё/g, "йо")
		.replace(/(\p{Lu})(\p{Lu}) Ю/ug, "$1$2 ЙУ")
		.replace(/(\p{Lu})Ю/ug, "$1ЙУ")
		.replace(/Ю (\p{Lu})(\p{Lu})/ug, "ЙУ $1$2")
		.replace(/Ю(\p{Lu})/ug, "ЙУ$1")
		.replace(/Ю/g, "Йу")
		.replace(/ю/g, "йу")
		.replace(/(\p{Lu})(\p{Lu}) Ц/ug, "$1$2 ТС")
		.replace(/(\p{Lu})Ц/ug, "$1ТС")
		.replace(/Ц (\p{Lu})(\p{Lu})/ug, "ТС $1$2")
		.replace(/Ц(\p{Lu})/ug, "ТС$1")
		.replace(/Ц/g, "Тс")
		.replace(/ц/g, "тс")

		.replace(/(Ъ|ъ)/g, "")

		.replace(/Р(Ь|ь)/g, "Ŗ")
		.replace(/рь/g, "ŗ")
		.replace(/Л(Ь|ь)/g, "Ļ")
		.replace(/ль/g, "ļ")
		.replace(/Н(Ь|ь)/g, "Ņ")
		.replace(/нь/g, "ņ")
		.replace(/Т(Ь|ь)/g, "Ț")
		.replace(/ть/g, "ț")

		.replace(/а/g, "a")
		.replace(/ӑ/g, "o")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/д/g, "d")
		.replace(/е/g, "e")
		.replace(/ӗ/g, "ö")
		.replace(/ж/g, "ž")
		.replace(/з/g, "z")
		.replace(/и/g, "i")
		.replace(/й/g, "j")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/о/g, "ó")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/ҫ/g, "ș")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ӳ/g, "y")
		.replace(/ф/g, "f")
		.replace(/х/g, "h")
		.replace(/ч/g, "c")
		.replace(/ш/g, "š")
		.replace(/ь/g, "")
		.replace(/ы/g, "ë")
		.replace(/э/g, "e")

		.replace(/А/g, "A")
		.replace(/Ӑ/g, "O")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Д/g, "D")
		.replace(/Е/g, "E")
		.replace(/Ӗ/g, "Ö")
		.replace(/Ж/g, "Ž")
		.replace(/З/g, "Z")
		.replace(/И/g, "I")
		.replace(/Й/g, "J")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/О/g, "Ó")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Ҫ/g, "Ș")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ӳ/g, "Y")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "H")
		.replace(/Ч/g, "C")
		.replace(/Ш/g, "Š")
		.replace(/Ь/g, "")
		.replace(/Ы/g, "Ë")
		.replace(/Э/g, "E")

		.replace(/\u2039/g, "\u2018")
		.replace(/\u203a/g, "\u2019")
		.replace(/\u00ab/g, "\u201c")
		.replace(/\u00bb/g, "\u201d");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}