function cyrlat() {
	document.transcription.text2.value = document.transcription.text1.value

		.replace(/(А|Е|Ё|И|О|Ө|У|Ү|Ы|Ю|Я)Ц/g, "$1ТС")
		.replace(/(а|е|ё|и|о|ө|у|ү|ы|ю|я)Ц/g, "$1Тс")
		.replace(/(а|е|ё|и|о|ө|у|ү|ы|ю|я)ц/g, "$1тс")
		.replace(/Ц/g, "С")
		.replace(/ц/g, "с")

		.replace(/(А|Е|Ё|И|О|Ө|У|Ү|Ы|Ю|Я)Щ(А|Е|Ё|И|О|Ө|У|Ү|Ы|Ю|Я)/g, "$1ШШ$2")
		.replace(/(А|Е|Ё|И|О|Ө|У|Ү|Ы|Ю|Я)щ(а|е|ё|и|о|ө|у|ү|ы|ю|я)/g, "$1Шш$2")
		.replace(/(а|е|ё|и|о|ө|у|ү|ы|ю|я)щ(а|е|ё|и|о|ө|у|ү|ы|ю|я)/g, "$1шш$2")
		.replace(/щ/g, "ш")
		.replace(/Щ/g, "Ш")

		.replace(/(Б|В|Г|Д|Ж|З|К|Л|М|Н|Ң|П|Р|С|Т|Ф|Х|Ч|Ш)Я/g, "$1ЬА")
		.replace(/(б|в|г|д|ж|з|к|л|м|н|ң|п|р|с|т|ф|х|ч|ш)Я/g, "$1ьА")
		.replace(/(Б|В|Г|Д|Ж|З|К|Л|М|Н|Ң|П|Р|С|Т|Ф|Х|Ч|Ш|Щ|б|в|г|д|ж|з|к|л|м|н|ң|п|р|с|т|ф|х|ч|ш)я/g, "$1ьа")
		.replace(/(Б|В|Г|Д|Ж|З|К|Л|М|Н|Ң|П|Р|С|Т|Ф|Х|Ч|Ш|Щ|б|в|г|д|ж|з|к|л|м|н|ң|п|р|с|т|ф|х|ч|ш)Ю/g, "$1Ү")
		.replace(/(Б|В|Г|Д|Ж|З|К|Л|М|Н|Ң|П|Р|С|Т|Ф|Х|Ч|Ш|Щ|б|в|г|д|ж|з|к|л|м|н|ң|п|р|с|т|ф|х|ч|ш)ю/g, "$1ү")
		.replace(/(Б|В|Г|Д|Ж|З|Й|К|Л|М|Н|Ң|П|Р|С|Т|Ф|Х|Ч|Ш|Щ|б|в|г|д|ж|з|й|к|л|м|н|ң|п|р|с|т|ф|х|ч|ш)Е/g, "$1Э")
		.replace(/(Б|В|Г|Д|Ж|З|Й|К|Л|М|Н|Ң|П|Р|С|Т|Ф|Х|Ч|Ш|Щ|б|в|г|д|ж|з|й|к|л|м|н|ң|п|р|с|т|ф|х|ч|ш)е/g, "$1э")
		.replace(/(Б|В|Г|Д|Ж|З|К|Л|М|Н|Ң|П|Р|С|Т|Ф|Х|Ч|Ш|Щ|б|в|г|д|ж|з|к|л|м|н|ң|п|р|с|т|ф|х|ч|ш)Ё/g, "$1Ө")
		.replace(/(Б|В|Г|Д|Ж|З|К|Л|М|Н|Ң|П|Р|С|Т|Ф|Х|Ч|Ш|Щ|б|в|г|д|ж|з|к|л|м|н|ң|п|р|с|т|ф|х|ч|ш)ё/g, "$1ө")

		.replace(/Ь(И|и)/g, "Й$1")
		.replace(/ьи/g, "йи")

		.replace(/(\p{Uppercase})(\p{Uppercase}) Я/ug, "$1$2 ЙА")
		.replace(/(\p{Uppercase})Я/ug, "$1ЙА")
		.replace(/Я (\p{Uppercase})(\p{Uppercase})/ug, "ЙА $1$2")
		.replace(/Я(\p{Uppercase})/ug, "ЙА$1")
		.replace(/Я/g, "Йа")
		.replace(/я/g, "йа")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Е/ug, "$1$2 ЙЭ")
		.replace(/(\p{Uppercase})Е/ug, "$1ЙЭ")
		.replace(/Е (\p{Uppercase})(\p{Uppercase})/ug, "ЙЭ $1$2")
		.replace(/Е(\p{Uppercase})/ug, "ЙЭ$1")
		.replace(/Е/g, "Йэ")
		.replace(/е/g, "йэ")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ё/ug, "$1$2 ЙО")
		.replace(/(\p{Uppercase})Ё/ug, "$1ЙО")
		.replace(/Ё (\p{Uppercase})(\p{Uppercase})/ug, "ЙО $1$2")
		.replace(/Ё(\p{Uppercase})/ug, "ЙО$1")
		.replace(/Ё/g, "Йо")
		.replace(/ё/g, "йо")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ю/ug, "$1$2 ЙУ")
		.replace(/(\p{Uppercase})Ю/ug, "$1ЙУ")
		.replace(/Ю (\p{Uppercase})(\p{Uppercase})/ug, "ЙУ $1$2")
		.replace(/Ю(\p{Uppercase})/ug, "ЙУ$1")
		.replace(/Ю/g, "Йу")
		.replace(/ю/g, "йу")

		.replace(/ааъ/g, "āā")
		.replace(/аъ/g, "ā")
		.replace(/а/g, "a")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/д/g, "d")
		.replace(/ж/g, "j")
		.replace(/з/g, "z")
		.replace(/ииъ/g, "ĩĩ")
		.replace(/иъ/g, "ĩ")
		.replace(/и/g, "i")
		.replace(/й/g, "y")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/ң/g, "ñ")
		.replace(/ооъ/g, "ōō")
		.replace(/оъ/g, "ō")
		.replace(/о/g, "o")
		.replace(/өөъ/g, "õõ")
		.replace(/өъ/g, "õ")
		.replace(/ө/g, "ö")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/ууъ/g, "ūū")
		.replace(/уъ/g, "ū")
		.replace(/у/g, "u")
		.replace(/үүъ/g, "ũũ")
		.replace(/үъ/g, "ũ")
		.replace(/ү/g, "ü")
		.replace(/ф/g, "f")
		.replace(/х/g, "h")
		.replace(/ч/g, "ç")
		.replace(/ш/g, "ş")
		.replace(/ь/g, "")
		.replace(/ыыъ/g, "īī")
		.replace(/ыъ/g, "ī")
		.replace(/ы/g, "ı")
		.replace(/ээъ/g, "ēē")
		.replace(/эъ/g, "ē")
		.replace(/э/g, "e")

		.replace(/ААЪ/g, "ĀĀ")
		.replace(/А(Ъ|ъ)/g, "Ā")
		.replace(/А/g, "A")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Д/g, "D")
		.replace(/Ж/g, "J")
		.replace(/З/g, "Z")
		.replace(/ИИЪ/g, "ĨĨ")
		.replace(/И(Ъ|ъ)/g, "Ĩ")
		.replace(/И/g, "İ")
		.replace(/Й/g, "Y")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/Ң/g, "Ñ")
		.replace(/ООЪ/g, "ŌŌ")
		.replace(/О(Ъ|ъ)/g, "Ō")
		.replace(/О/g, "O")
		.replace(/ӨӨЪ/g, "ÕÕ")
		.replace(/Ө(Ъ|ъ)/g, "Õ")
		.replace(/Ө/g, "Ö")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/УУЪ/g, "ŪŪ")
		.replace(/У(Ъ|ъ)/g, "Ū")
		.replace(/У/g, "U")
		.replace(/ҮҮЪ/g, "ŨŨ")
		.replace(/Ү(Ъ|ъ)/g, "Ũ")
		.replace(/Ү/g, "Ü")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "H")
		.replace(/Ч/g, "Ç")
		.replace(/Ш/g, "Ş")
		.replace(/Ь/g, "")
		.replace(/ЫЫЪ/g, "ĪĪ")
		.replace(/Ы(Ъ|ъ)/g, "Ī")
		.replace(/Ы/g, "I")
		.replace(/ЭЭЪ/g, "ĒĒ")
		.replace(/Э(Ъ|ъ)/g, "Ē")
		.replace(/Э/g, "E")

		.replace(/\u2039/g, "\u2018")
		.replace(/\u203a/g, "\u2019")
		.replace(/\u00ab/g, "\u201c")
		.replace(/\u00bb/g, "\u201d")

		.replace(/(Ъ|ъ)/g, "")

		.normalize('NFC');
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}