function newLineUppercase($0, $1) {
	return '\n' + $1.toUpperCase();
};

function latgeo() {
	document.transcription.text1.value = document.transcription.text2.value

		//1. convert all BIG letters into small
		.replace(/A/g, "a")
		.replace(/B/g, "b")
		.replace(/G/g, "g")
		.replace(/D/g, "d")
		.replace(/E/g, "e")
		.replace(/V/g, "v")
		.replace(/Z/g, "z")
		.replace(/T/g, "t")
		.replace(/I/g, "i")
		.replace(/K'/g, "k'")
		.replace(/L/g, "l")
		.replace(/M/g, "m")
		.replace(/N/g, "n")
		.replace(/O/g, "o")
		.replace(/P'/g, "p'")
		.replace(/J/g, "j")
		.replace(/R/g, "r")
		.replace(/S/g, "s")
		.replace(/Ť/g, "t'")
		.replace(/T'/g, "t'")
		.replace(/U/g, "u")
		.replace(/P/g, "p")
		.replace(/K/g, "k")
		.replace(/Ǧ/g, "ǧ")
		.replace(/Ğ/g, "ǧ")
		.replace(/Q/g, "q")
		.replace(/Ş/g, "ş")
		.replace(/Ç/g, "ç")
		.replace(/Z'/g, "z'")
		.replace(/Ç/g, "ç'")
		.replace(/X/g, "x")
		.replace(/C/g, "c")
		.replace(/Č/g, "č")
		.replace(/H/g, "h")
		.replace(/F/g, "f")
		.replace(/Y/g, "y")
		.replace(/Ǯ/g, "ǯ")


		//2. convert all special characters 
		//3. convert old version of alphabet into version used in this converter
		.replace(/ʼ/g, "’")
		.replace(/’/g, "’")
		.replace(/'/g, "’")
		.replace(/ğ/g, "ǧ")
		.replace(/ɣ/g, "ǧ")
		.replace(/ts/g, "3")
		.replace(/З/g, "3")
		.replace(/з/g, "3")
		.replace(/ʒ/g, "3")
		.replace(/Ʒ/g, "3")
		.replace(/ǯ/g, "3'")
		.replace(/ť/g, "t'")
		.replace(/t̆/g, "t'")
		.replace(/t\u200c\u030c/g, "t'")
		.replace(/ǩ/g, "k'")
		.replace(/Ǩ/g, "k'")
		.replace(/ḱ/g, "k'")
		.replace(/Ḱ/g, "k'")
		.replace(/p̌/g, "p'")
		.replace(/ṕ/g, "p'")
		.replace(/Ṕ/g, "p'")
		.replace(/ç̌/g, "ç'")
		.replace(/ç̌/g, "ç'")
		.replace(/ḉ/g, "ç'")
		.replace(/Ḉ/g, "ç'")
		.replace(/ž/g, "z'")
		.replace(/Ž/g, "z'")

		//4. again apostrof just for each case: š, č plus apostrof
		.replace(/ʼ/g, "'")
		.replace(/’/g, "'")
		.replace(/’/g, "'")

		//5. dotted and dotless I in Turkish, just to avoid spelling mistake
		.replace(/İ/g, "i")
		.replace(/i/g, "i")
		.replace(/I/g, "i")
		.replace(/ı/g, "i")


		//6. standard convertion LAT-GEO
		.replace(/a/g, "ა")
		.replace(/b/g, "ბ")
		.replace(/g/g, "გ")
		.replace(/d/g, "დ")
		.replace(/e/g, "ე")
		.replace(/v/g, "ვ")
		.replace(/t'/g, "ტ")
		.replace(/t/g, "თ")
		.replace(/i/g, "ი")
		.replace(/k'/g, "კ")
		.replace(/l/g, "ლ")
		.replace(/m/g, "მ")
		.replace(/n/g, "ნ")
		.replace(/o/g, "ო")
		.replace(/p'/g, "პ")
		.replace(/j/g, "ჟ")
		.replace(/r/g, "რ")
		.replace(/s/g, "ს")
		.replace(/u/g, "უ")
		.replace(/p/g, "ფ")
		.replace(/k/g, "ქ")
		.replace(/ǧ/g, "ღ")
		.replace(/q/g, "ყ")
		.replace(/ş/g, "შ")
		.replace(/ç'/g, "ჭ")
		.replace(/ç/g, "ჩ")
		.replace(/z'/g, "ძ")
		.replace(/z/g, "ზ")
		.replace(/3'/g, "წ")
		.replace(/3/g, "ც")
		.replace(/x/g, "ხ")
		.replace(/c/g, "ჯ")
		.replace(/h/g, "ჰ")
		.replace(/f/g, "ჶ")
		.replace(/y/g, "ჲ");
}

function geolat() {
	document.transcription.text2.value = document.transcription.text1.value
		.replace(/ა/g, "a")
		.replace(/ბ/g, "b")
		.replace(/გ/g, "g")
		.replace(/დ/g, "d")
		.replace(/ე/g, "e")
		.replace(/ვ/g, "v")
		.replace(/ზ/g, "z")
		.replace(/თ/g, "t")
		.replace(/ი/g, "i")
		.replace(/კ/g, "k'")
		.replace(/ლ/g, "l")
		.replace(/მ/g, "m")
		.replace(/ნ/g, "n")
		.replace(/ო/g, "o")
		.replace(/პ/g, "p'")
		.replace(/ჟ/g, "j")
		.replace(/რ/g, "r")
		.replace(/ს/g, "s")
		.replace(/ტ/g, "t'")
		.replace(/უ/g, "u")
		.replace(/ფ/g, "p")
		.replace(/ქ/g, "k")
		.replace(/ღ/g, "ǧ")
		.replace(/ყ/g, "q")
		.replace(/შ/g, "ş")
		.replace(/ჩ/g, "ç")
		.replace(/ც/g, "з")
		.replace(/ძ/g, "z'")
		.replace(/წ/g, "з'")
		.replace(/ჭ/g, "ç'")
		.replace(/ხ/g, "x")
		.replace(/ჯ/g, "c")
		.replace(/ჰ/g, "h")
		.replace(/ჶ/g, "f")
		.replace(/ჲ/g, "y")

		.replace(/\u2018/g, "\u0027")
		.replace(/\u2019/g, "\u0027")
		.replace(/T'/g, "Ť")
		.replace(/T\u0306/g, "Ť")
		.replace(/K'/g, "Ǩ")
		.replace(/K\u0306/g, "Ǩ")
		.replace(/Ḱ/g, "Ǩ")
		.replace(/P'/g, "P̌")
		.replace(/P\u0306/g, "P̌")
		.replace(/Ṕ/g, "P̌")
		.replace(/Ç'/g, "Ç̌")
		.replace(/Ç\u030c/g, "Ç̌")
		.replace(/Ḉ/g, "Ç̌")
		.replace(/Z'/g, "Ž")
		.replace(/Z\u0306/g, "Ž")
		.replace(/З'/g, "Ǯ")
		.replace(/З/g, "Ʒ")
		.replace(/Ʒ\u0306/g, "Ǯ")
		.replace(/İ/g, "I")

		.replace(/t'/g, "t‌̌")
		.replace(/ť/g, "t‌̌")
		.replace(/t\u030c/g, "t‌̌")
		.replace(/t\u0306/g, "t‌̌")
		.replace(/k'/g, "ǩ")
		.replace(/k\u0306/g, "ǩ")
		.replace(/ḱ/g, "ǩ")
		.replace(/p'/g, "p̌")
		.replace(/p\u0306/g, "p̌")
		.replace(/ṕ/g, "p̌")
		.replace(/ç'/g, "ç̌")
		.replace(/ç\u030c/g, "ç̌")
		.replace(/ḉ/g, "ç̌")
		.replace(/z'/g, "ž")
		.replace(/z\u0306/g, "ž")
		.replace(/з'/g, "ǯ")
		.replace(/3'/g, "ǯ")
		.replace(/з/g, "ʒ")
		.replace(/ʒ\u0306/g, "ǯ")
		.replace(/ı/g, "i")
		.normalize('NFD')
		.replace(/\n(\p{Ll})/ug, newLineUppercase)
		.replace(/T‌̌/g, "Ť")
		.normalize('NFC');
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}