function latcyr() {
	document.transcription.text2.value = document.transcription.text2.value
		.replace(/ä/g, "ə")
		.replace(/Ä/g, "Ə")
		.replace(/(\p{Script=Latn})ә/ug, "$1ə")
		.replace(/ә(\p{Script=Latn})/ug, "ə$1")
		.replace(/(\p{Script=Latn})Ә/ug, "$1Ə")
		.replace(/Ә(\p{Script=Latn})/ug, "Ə$1");

	document.transcription.text1.value = document.transcription.text2.value
		.replace(/a/g, "а")
		.replace(/b/g, "б")
		.replace(/c/g, "ҹ")
		.replace(/ç/g, "ч")
		.replace(/d/g, "д")
		.replace(/e/g, "е")
		.replace(/ə/g, "ә")
		.replace(/f/g, "ф")
		.replace(/g/g, "ҝ")
		.replace(/q/g, "г")
		.replace(/ğ/g, "ғ")
		.replace(/h/g, "һ")
		.replace(/x/g, "х")
		.replace(/ı/g, "ы")
		.replace(/i/g, "и")
		.replace(/j/g, "ж")
		.replace(/k/g, "к")
		.replace(/l/g, "л")
		.replace(/m/g, "м")
		.replace(/n/g, "н")
		.replace(/o/g, "о")
		.replace(/ö/g, "ө")
		.replace(/p/g, "п")
		.replace(/r/g, "р")
		.replace(/s/g, "с")
		.replace(/ş/g, "ш")
		.replace(/t/g, "т")
		.replace(/u/g, "у")
		.replace(/ü/g, "ү")
		.replace(/v/g, "в")
		.replace(/y/g, "ј")
		.replace(/z/g, "з")
		.replace(/A/g, "А")
		.replace(/B/g, "Б")
		.replace(/C/g, "Ҹ")
		.replace(/Ç/g, "Ч")
		.replace(/D/g, "Д")
		.replace(/E/g, "Е")
		.replace(/Ə/g, "Ә")
		.replace(/F/g, "Ф")
		.replace(/G/g, "Ҝ")
		.replace(/Q/g, "Г")
		.replace(/Ğ/g, "Ғ")
		.replace(/H/g, "Һ")
		.replace(/X/g, "Х")
		.replace(/I/g, "Ы")
		.replace(/İ/g, "И")
		.replace(/J/g, "Ж")
		.replace(/K/g, "К")
		.replace(/L/g, "Л")
		.replace(/M/g, "М")
		.replace(/N/g, "Н")
		.replace(/O/g, "О")
		.replace(/Ö/g, "Ө")
		.replace(/P/g, "П")
		.replace(/R/g, "Р")
		.replace(/S/g, "С")
		.replace(/Ş/g, "Ш")
		.replace(/T/g, "Т")
		.replace(/U/g, "У")
		.replace(/Ü/g, "Ү")
		.replace(/V/g, "В")
		.replace(/Y/g, "Ј")
		.replace(/Z/g, "З");
}

function cyrlat() {
	document.transcription.text1.value = document.transcription.text1.value
		.replace(/я/g, "ә")
		.replace(/ъ/g, "ҹ")
		.replace(/й/g, "ј")
		.replace(/ц/g, "ү")
		.replace(/щ/g, "h")
		.replace(/ь/g, "ғ")
		.replace(/э/g, "ҝ")
		.replace(/Я/g, "Ә")
		.replace(/Ъ/g, "Ҹ")
		.replace(/Й/g, "Ј")
		.replace(/Ц/g, "Ү")
		.replace(/Щ/g, "H")
		.replace(/Ь/g, "Ғ")
		.replace(/Э/g, "Ҝ");

	document.transcription.text2.value = document.transcription.text1.value
		.replace(/а/g, "a")
		.replace(/б/g, "b")
		.replace(/ҹ/g, "c")
		.replace(/ч/g, "ç")
		.replace(/д/g, "d")
		.replace(/е/g, "e")
		.replace(/ә/g, "ə")
		.replace(/ф/g, "f")
		.replace(/ҝ/g, "g")
		.replace(/г/g, "q")
		.replace(/ғ/g, "ğ")
		.replace(/һ/g, "h")
		.replace(/х/g, "x")
		.replace(/ы/g, "ı")
		.replace(/и/g, "i")
		.replace(/ж/g, "j")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/о/g, "o")
		.replace(/ө/g, "ö")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/ш/g, "ş")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ү/g, "ü")
		.replace(/в/g, "v")
		.replace(/ј/g, "y")
		.replace(/з/g, "z")
		.replace(/А/g, "A")
		.replace(/Б/g, "B")
		.replace(/Ҹ/g, "C")
		.replace(/Ч/g, "Ç")
		.replace(/Д/g, "D")
		.replace(/Е/g, "E")
		.replace(/Ә/g, "Ə")
		.replace(/Ф/g, "F")
		.replace(/Ҝ/g, "G")
		.replace(/Г/g, "Q")
		.replace(/Ғ/g, "Ğ")
		.replace(/Һ/g, "H")
		.replace(/Х/g, "X")
		.replace(/Ы/g, "I")
		.replace(/И/g, "İ")
		.replace(/Ж/g, "J")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/О/g, "O")
		.replace(/Ө/g, "Ö")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Ш/g, "Ş")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ү/g, "Ü")
		.replace(/В/g, "V")
		.replace(/Ј/g, "Y")
		.replace(/З/g, "Z")
		.replace(/ʼ/g, "");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}
