function latcyr() {
	document.transcription.text1.value = document.transcription.text2.value
		.replace(/Α/g, "A")
		.replace(/α/g, "a")
		.replace(/Β/g, "B")
		.replace(/β/g, "b")
		.replace(/Χ/g, "C")
		.replace(/χ/g, "c")
		.replace(/Δ/g, "D")
		.replace(/δ/g, "d")
		.replace(/Ε/g, "E")
		.replace(/ε/g, "e")
		.replace(/Φ/g, "F")
		.replace(/ϕ/g, "f")
		.replace(/Γ/g, "G")
		.replace(/γ/g, "g")
		.replace(/Η/g, "H")
		.replace(/η/g, "h")
		.replace(/Ι/g, "I")
		.replace(/ι/g, "i")
		.replace(/ϑ/g, "J")
		.replace(/φ/g, "j")
		.replace(/Κ/g, "K")
		.replace(/κ/g, "k")
		.replace(/Λ/g, "L")
		.replace(/λ/g, "l")
		.replace(/Μ/g, "M")
		.replace(/μ/g, "m")
		.replace(/Ν/g, "N")
		.replace(/ν/g, "n")
		.replace(/Ο/g, "O")
		.replace(/ο/g, "o")
		.replace(/Π/g, "P")
		.replace(/π/g, "p")
		.replace(/Θ/g, "Q")
		.replace(/θ/g, "q")
		.replace(/Ρ/g, "R")
		.replace(/ρ/g, "r")
		.replace(/Σ/g, "S")
		.replace(/σ/g, "s")
		.replace(/Τ/g, "T")
		.replace(/τ/g, "t")
		.replace(/Υ/g, "U")
		.replace(/υ/g, "u")
		.replace(/ς/g, "V")
		.replace(/ϖ/g, "v")
		.replace(/Ω/g, "W")
		.replace(/ω/g, "w")
		.replace(/Ξ/g, "X")
		.replace(/ξ/g, "x")
		.replace(/Ψ/g, "Y")
		.replace(/ψ/g, "y")
		.replace(/Ζ/g, "Z")
		.replace(/ζ/g, "z");
}

function cyrlat() {
	document.transcription.text2.value = document.transcription.text1.value
		.replace(/A/g, "Α")
		.replace(/a/g, "α")
		.replace(/B/g, "Β")
		.replace(/b/g, "β")
		.replace(/C/g, "Χ")
		.replace(/c/g, "χ")
		.replace(/D/g, "Δ")
		.replace(/d/g, "δ")
		.replace(/E/g, "Ε")
		.replace(/e/g, "ε")
		.replace(/F/g, "Φ")
		.replace(/f/g, "ϕ")
		.replace(/G/g, "Γ")
		.replace(/g/g, "γ")
		.replace(/H/g, "Η")
		.replace(/h/g, "η")
		.replace(/I/g, "Ι")
		.replace(/i/g, "ι")
		.replace(/J/g, "ϑ")
		.replace(/j/g, "φ")
		.replace(/K/g, "Κ")
		.replace(/k/g, "κ")
		.replace(/L/g, "Λ")
		.replace(/l/g, "λ")
		.replace(/M/g, "Μ")
		.replace(/m/g, "μ")
		.replace(/N/g, "Ν")
		.replace(/n/g, "ν")
		.replace(/O/g, "Ο")
		.replace(/o/g, "ο")
		.replace(/P/g, "Π")
		.replace(/p/g, "π")
		.replace(/Q/g, "Θ")
		.replace(/q/g, "θ")
		.replace(/R/g, "Ρ")
		.replace(/r/g, "ρ")
		.replace(/S/g, "Σ")
		.replace(/s/g, "σ")
		.replace(/T/g, "Τ")
		.replace(/t/g, "τ")
		.replace(/U/g, "Υ")
		.replace(/u/g, "υ")
		.replace(/V/g, "ς")
		.replace(/v/g, "ϖ")
		.replace(/W/g, "Ω")
		.replace(/w/g, "ω")
		.replace(/X/g, "Ξ")
		.replace(/x/g, "ξ")
		.replace(/Y/g, "Ψ")
		.replace(/y/g, "ψ")
		.replace(/Z/g, "Ζ")
		.replace(/z/g, "ζ");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}