function latcyr() {

	document.transcription.text2.value = document.transcription.text2.value
		.replace(/â/g, "å")
		.replace(/Â/g, "Å")
		.replace(/á/g, "ă")
		.replace(/Á/g, "Ă")
		.replace(/é/g, "ĕ")
		.replace(/É/g, "Ĕ")
		.replace(/ú/g, "ŭ")
		.replace(/Ú/g, "Ŭ")
		.replace(/ŏ/g, "å")
		.replace(/Ŏ/g, "Å")
		.replace(/ô/g, "å")
		.replace(/Ô/g, "Å");

	document.transcription.text1.value = document.transcription.text2.value
		.replace(/’/g, "'")
		.replace(/'/g, "-")
		.replace(/dzh/g, "ч")
		.replace(/Dzh/g, "Ч")
		.replace(/DZH/g, "Ч")
		.replace(/d-z-h/g, "дзхь")
		.replace(/D-z-h/g, "Дзхь")
		.replace(/D-Z-H/g, "ДЗХЬ")
		.replace(/dz-h/g, "ѕхь")
		.replace(/Dz-h/g, "Ѕхь")
		.replace(/DZ-H/g, "ЅХЬ")
		.replace(/d-zh/g, "дж")
		.replace(/D-zh/g, "Дж")
		.replace(/D-ZH/g, "ДЖ")
		.replace(/d-z/g, "дз")
		.replace(/D-z/g, "Дз")
		.replace(/D-Z/g, "ДЗ")
		.replace(/z-h/g, "зхь")
		.replace(/Z-h/g, "Зхь")
		.replace(/Z-H/g, "ЗХЬ")
		.replace(/t-x/g, "тш")
		.replace(/T-x/g, "Тш")
		.replace(/T-X/g, "ТШ")
		.replace(/k-h/g, "кьхь")
		.replace(/K-h/g, "КЬхь")
		.replace(/K-H/g, "КЬХЬ")
		.replace(/tx/g, "щ")
		.replace(/Tx/g, "Щ")
		.replace(/TX/g, "Щ")
		.replace(/zh/g, "ж")
		.replace(/Zh/g, "Ж")
		.replace(/ZH/g, "Ж")
		.replace(/dz/g, "ѕ")
		.replace(/Dz/g, "Ѕ")
		.replace(/DZ/g, "Ѕ")
		.replace(/kh/g, "х")
		.replace(/Kh/g, "Х")
		.replace(/KH/g, "Х")

		.replace(/u/g, "у")
		.replace(/j/g, "ј")
		.replace(/m/g, "м")
		.replace(/i/g, "и")
		.replace(/å/g, "о")
		.replace(/o/g, "ё")
		.replace(/g/g, "г")
		.replace(/n/g, "н")
		.replace(/s/g, "с")
		.replace(/y/g, "і")
		.replace(/b/g, "б")
		.replace(/f/g, "ф")
		.replace(/v/g, "в")
		.replace(/w/g, "ў")
		.replace(/q/g, "к")
		.replace(/t/g, "т")
		.replace(/l/g, "л")
		.replace(/e/g, "э")
		.replace(/ĕ/g, "є")
		.replace(/ŭ/g, "ю")
		.replace(/c/g, "ц")
		.replace(/z/g, "з")
		.replace(/a/g, "а")
		.replace(/k/g, "кь")
		.replace(/ă/g, "я")
		.replace(/p/g, "п")
		.replace(/d/g, "д")
		.replace(/r/g, "р")
		.replace(/U/g, "У")
		.replace(/J/g, "Ј")
		.replace(/M/g, "М")
		.replace(/I/g, "И")
		.replace(/Å/g, "О")
		.replace(/O/g, "Ё")
		.replace(/G/g, "Г")
		.replace(/N/g, "Н")
		.replace(/x/g, "ш")
		.replace(/X/g, "Ш")
		.replace(/S/g, "С")
		.replace(/Y/g, "І")
		.replace(/B/g, "Б")
		.replace(/F/g, "Ф")
		.replace(/V/g, "В")
		.replace(/W/g, "Ў")
		.replace(/Q/g, "К")
		.replace(/T/g, "Т")
		.replace(/L/g, "Л")
		.replace(/E/g, "Э")
		.replace(/Ĕ/g, "Є")
		.replace(/Ŭ/g, "Ю")
		.replace(/C/g, "Ц")
		.replace(/Z/g, "З")
		.replace(/A/g, "А")
		.replace(/K/g, "КЬ")
		.replace(/Ă/g, "Я")
		.replace(/P/g, "П")
		.replace(/D/g, "Д")
		.replace(/R/g, "Р")
		.replace(/h/g, "хь")
		.replace(/H/g, "ХЬ");
}

function cyrlat() {

	document.transcription.text1.value = document.transcription.text1.value

		.replace(/е/g, "ё")
		.replace(/Е/g, "Ё")
		.replace(/ы/g, "і")
		.replace(/Ы/g, "І")
		.replace(/й/g, "ј")
		.replace(/Й/g, "Ј")
		.replace(/ҳ/g, "хь")
		.replace(/Ҳ/g, "ХЬ")
		.replace(/қ/g, "кь")
		.replace(/Қ/g, "КЬ")
		.replace(/ҹ/g, "щ")
		.replace(/Ҹ/g, "Щ");

	document.transcription.text2.value = document.transcription.text1.value

		.replace(/дзхь/g, "d-z-h")
		.replace(/Дзхь/g, "D-z-h")
		.replace(/ДЗХЬ/g, "D-Z-H")
		.replace(/ѕхь/g, "dz-h")
		.replace(/Ѕхь/g, "Dz-h")
		.replace(/ЅХЬ/g, "DZ-H")
		.replace(/дж/g, "d-zh")
		.replace(/Дж/g, "D-zh")
		.replace(/ДЖ/g, "D-ZH")
		.replace(/кьхь/g, "k-h")
		.replace(/КЬхь/g, "K-h")
		.replace(/КЬХЬ/g, "K-H")
		.replace(/тш/g, "t-x")
		.replace(/Тш/g, "T-x")
		.replace(/ТШ/g, "T-X")
		.replace(/зхь/g, "z-h")
		.replace(/Зхь/g, "Z-h")
		.replace(/ЗХЬ/g, "Z-H")
		.replace(/дз/g, "d-z")
		.replace(/Дз/g, "D-z")
		.replace(/ДЗ/g, "D-Z")

		.replace(/є/g, "ĕ")
		.replace(/ў/g, "w")
		.replace(/кь/g, "k")
		.replace(/у/g, "u")
		.replace(/ј/g, "j")
		.replace(/м/g, "m")
		.replace(/и/g, "i")
		.replace(/о/g, "å")
		.replace(/ё/g, "o")
		.replace(/г/g, "g")
		.replace(/н/g, "n")
		.replace(/ш/g, "x")
		.replace(/с/g, "s")
		.replace(/і/g, "y")
		.replace(/б/g, "b")
		.replace(/ф/g, "f")
		.replace(/в/g, "v")
		.replace(/т/g, "t")
		.replace(/л/g, "l")
		.replace(/э/g, "e")
		.replace(/ю/g, "ŭ")
		.replace(/ц/g, "c")
		.replace(/хь/g, "h")
		.replace(/з/g, "z")
		.replace(/а/g, "a")
		.replace(/к/g, "q")
		.replace(/я/g, "ă")
		.replace(/п/g, "p")
		.replace(/д/g, "d")
		.replace(/р/g, "r")
		.replace(/Є/g, "Ĕ")
		.replace(/Ў/g, "W")
		.replace(/КЬ/g, "K")
		.replace(/У/g, "U")
		.replace(/Ј/g, "J")
		.replace(/М/g, "M")
		.replace(/И/g, "I")
		.replace(/О/g, "Å")
		.replace(/Ё/g, "O")
		.replace(/Г/g, "G")
		.replace(/Н/g, "N")
		.replace(/Ш/g, "X")
		.replace(/С/g, "S")
		.replace(/І/g, "Y")
		.replace(/Б/g, "B")
		.replace(/Ф/g, "F")
		.replace(/В/g, "V")
		.replace(/Т/g, "T")
		.replace(/Л/g, "L")
		.replace(/Э/g, "E")
		.replace(/Ю/g, "Ŭ")
		.replace(/Ц/g, "C")
		.replace(/ХЬ/g, "H")
		.replace(/З/g, "Z")
		.replace(/А/g, "A")
		.replace(/К/g, "Q")
		.replace(/Я/g, "Ă")
		.replace(/П/g, "P")
		.replace(/Д/g, "D")
		.replace(/Р/g, "R")
		.replace(/«/g, "“")
		.replace(/»/g, "”")
		.replace(/ - /g, " – ")
		.replace(/х/g, "kh")
		.replace(/Х/g, "Kh")
		.replace(/щ/g, "tx")
		.replace(/Щ/g, "Tx")
		.replace(/ж/g, "zh")
		.replace(/Ж/g, "Zh")
		.replace(/ѕ/g, "dz")
		.replace(/Ѕ/g, "Dz")
		.replace(/ч/g, "dzh")
		.replace(/Ч/g, "Dzh")
		.replace(/-/g, "'");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}