function latcyr() {}

function cyrlat() {
	document.transcription.text2.value = document.transcription.text1.value
		.replace(/ е/g, " ye")
		.replace(/\nе/g, "\nye")
		.replace(/\rе/g, "\rye")
		.replace(/^е/g, "ye")

		.replace(/ае/g, "аye")
		.replace(/ие/g, "иye")
		.replace(/ые/g, "ыye")
		.replace(/ее/g, "еye")
		.replace(/эе/g, "эye")
		.replace(/уе/g, "уye")
		.replace(/ое/g, "оye")
		.replace(/өе/g, "өye")
		.replace(/ёе/g, "ёye")
		.replace(/үе/g, "үye")
		.replace(/йе/g, "йye")
		.replace(/юе/g, "юye")
		.replace(/яе/g, "яye")
		.replace(/ье/g, "ye")
		.replace(/ъе/g, "ye")

		.replace(/ Е/g, " Ye")
		.replace(/\nЕ/g, "\nYe")
		.replace(/\rЕ/g, "\rYe")
		.replace(/^Е/g, "Ye")

		.replace(/Ае/g, "Аye")
		.replace(/Ие/g, "Иye")
		.replace(/Ые/g, "Ыye")
		.replace(/Ее/g, "Еye")
		.replace(/Эе/g, "Эye")
		.replace(/Уе/g, "Уye")
		.replace(/Ое/g, "Оye")
		.replace(/Өе/g, "Өye")
		.replace(/Ёе/g, "Ёye")
		.replace(/Үе/g, "Үye")
		.replace(/Йе/g, "Йye")
		.replace(/Юе/g, "Юye")
		.replace(/Яе/g, "Яye")

		.replace(/АЕ/g, "АYE")
		.replace(/ИЕ/g, "ИYE")
		.replace(/ЫЕ/g, "ЫYE")
		.replace(/ЕЕ/g, "ЕYE")
		.replace(/ЭЕ/g, "ЭYE")
		.replace(/УЕ/g, "УYE")
		.replace(/ОЕ/g, "ОYE")
		.replace(/ӨЕ/g, "ӨYE")
		.replace(/ЁЕ/g, "ЁYE")
		.replace(/ҮЕ/g, "ҮYE")
		.replace(/ЙЕ/g, "ЙYE")
		.replace(/ЮЕ/g, "ЮYE")
		.replace(/ЯЕ/g, "ЯYE")
		.replace(/ЬЕ/g, "YE")
		.replace(/ЪЕ/g, "YE")

		.replace(/а/g, "a")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/д/g, "d")
		.replace(/е/g, "e")
		.replace(/ё/g, "yo")
		.replace(/ж/g, "j")
		.replace(/з/g, "z")
		.replace(/и/g, "i")
		.replace(/й/g, "y")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/ң/g, "ň")
		.replace(/о/g, "o")
		.replace(/ө/g, "ö")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ү/g, "ü")
		.replace(/ф/g, "f")
		.replace(/х/g, "h")
		.replace(/ц/g, "c")
		.replace(/ч/g, "č")
		.replace(/ш/g, "š")
		.replace(/щ/g, "ś")
		.replace(/ъ/g, "")
		.replace(/ы/g, "ï")
		.replace(/ь/g, "")
		.replace(/э/g, "e")
		.replace(/ю/g, "yu")
		.replace(/я/g, "ya")
		.replace(/А/g, "A")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Д/g, "D")
		.replace(/Е/g, "E")
		.replace(/Ё/g, "Yo")
		.replace(/Ж/g, "J")
		.replace(/З/g, "Z")
		.replace(/И/g, "I")
		.replace(/Й/g, "Y")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/Ң/g, "Ň")
		.replace(/О/g, "O")
		.replace(/Ө/g, "Ö")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ү/g, "Ü")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "H")
		.replace(/Ц/g, "C")
		.replace(/Ч/g, "Č")
		.replace(/Ш/g, "Š")
		.replace(/Щ/g, "Ś")
		.replace(/Ъ/g, "")
		.replace(/Ы/g, "Ï")
		.replace(/Ь/g, "")
		.replace(/Э/g, "E")
		.replace(/Ю/g, "Yu")
		.replace(/Я/g, "Ya");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}