function cyrlat() {
	document.transcription.text1.value = document.transcription.text1.value
		.replace(/´¨(ı|i)/g, "ΐ")
		.replace(/´¨(u|y)/g, "ΰ")
		.replace(/¨´(ı|i)/g, "ΐ")
		.replace(/¨´(u|y)/g, "ΰ")
		.replace(/(´ü|ű)/g, "ΰ")

		.replace(/q/g, "ψ")
		.replace(/w/g, "ω")
		.replace(/e/g, "ε")
		.replace(/r/g, "ρ")
		.replace(/t/g, "τ")
		.replace(/y/g, "υ")
		.replace(/u/g, "υ")
		.replace(/ı/g, "ι")
		.replace(/o/g, "ο")
		.replace(/p/g, "π")
		.replace(/ğ/g, "γ")
		.replace(/ü/g, "ϋ")
		.replace(/a/g, "α")
		.replace(/s/g, "σ")
		.replace(/d/g, "δ")
		.replace(/f/g, "φ")
		.replace(/g/g, "γ")
		.replace(/h/g, "χ")
		.replace(/j/g, "θ")
		.replace(/k/g, "κ")
		.replace(/l/g, "λ")
		.replace(/ş/g, "σ")
		.replace(/i/g, "η")
		.replace(/z/g, "ζ")
		.replace(/x/g, "ξ")
		.replace(/c/g, "ς")
		.replace(/v/g, "β")
		.replace(/b/g, "β")
		.replace(/n/g, "ν")
		.replace(/m/g, "μ")
		.replace(/ö/g, "ο")
		.replace(/ç/g, "ς")
		.replace(/Q/g, "Ψ")
		.replace(/W/g, "Ω")
		.replace(/E/g, "Ε")
		.replace(/R/g, "Ρ")
		.replace(/T/g, "Τ")
		.replace(/Y/g, "Υ")
		.replace(/U/g, "Υ")
		.replace(/I/g, "Ι")
		.replace(/O/g, "Ο")
		.replace(/P/g, "Π")
		.replace(/Ğ/g, "Γ")
		.replace(/Ü/g, "Ϋ")
		.replace(/A/g, "Α")
		.replace(/S/g, "Σ")
		.replace(/D/g, "Δ")
		.replace(/F/g, "Φ")
		.replace(/G/g, "Γ")
		.replace(/H/g, "Χ")
		.replace(/J/g, "Θ")
		.replace(/K/g, "Κ")
		.replace(/L/g, "Λ")
		.replace(/Ş/g, "Σ")
		.replace(/İ/g, "Η")
		.replace(/Z/g, "Ζ")
		.replace(/X/g, "Ξ")
		.replace(/C/g, "Σ")
		.replace(/V/g, "Β")
		.replace(/B/g, "Β")
		.replace(/N/g, "Ν")
		.replace(/M/g, "Μ")
		.replace(/Ö/g, "Ο")
		.replace(/Ç/g, "Σ")

		.replace(/(á|α´)/g, "ά")
		.replace(/(é|ε´)/g, "έ")
		.replace(/(í|ι´)/g, "ί")
		.replace(/η´/g, "ή")
		.replace(/(ó|ο´)/g, "ό")
		.replace(/(ú|ý|υ´)/g, "ύ")
		.replace(/(ẃ|ω´)/g, "ώ")
		.replace(/(Á|Α´)/g, "Ά")
		.replace(/(É|Ε´)/g, "Έ")
		.replace(/(Í|Ι´)/g, "Ί")
		.replace(/Η´/g, "Ή")
		.replace(/(Ó|Ο´)/g, "Ό")
		.replace(/(Ú|Ý|Υ´)/g, "Ύ")
		.replace(/(Ẃ|Ω´)/g, "Ώ")

		.replace(/(ï|ι¨)/g, "ϊ")
		.replace(/(Ï|Ι¨)/g, "Ϊ")
		.replace(/(ÿ|υ¨)/g, "ϋ")
		.replace(/(Ÿ|Υ¨)/g, "Ϋ")

		.replace(/ϊ´/g, "ΐ")
		.replace(/ϋ´/g, "ΰ")

		.replace(/ί(\u002a|\u005c)/g, "ή")
		.replace(/Ί(\u002a|\u005c)/g, "Ή")
		.replace(/ή(\u002a|\u005c)/g, "ί")
		.replace(/Ή(\u002a|\u005c)/g, "Ί")

		.replace(/τ(\u002a|\u005c)/g, "θ")
		.replace(/Τ(\u002a|\u005c)/g, "Θ")
		.replace(/θ(\u002a|\u005c)/g, "τ")
		.replace(/Θ(\u002a|\u005c)/g, "Τ")

		.replace(/σ(\u002a|\u005c)/g, "ς")
		.replace(/ς(\u002a|\u005c)/g, "σ")

		.replace(/π(\u002a|\u005c)/g, "ψ")
		.replace(/Π(\u002a|\u005c)/g, "Ψ")
		.replace(/ψ(\u002a|\u005c)/g, "π")
		.replace(/Ψ(\u002a|\u005c)/g, "Π");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}