function cyrlat() {
	document.transcription.text2.value = document.transcription.text1.value
		.replace(/([АЕЁИОӨУҮЫЮЯЭӘ])Ц/g, "$1ТС")
		.replace(/([аеёиоөуүыюяэә])Ц/g, "$1Тс")
		.replace(/([аеёиоөуүыюяэә])ц/g, "$1тс")
		.replace(/Ц/g, "С")
		.replace(/ц/g, "с")

		.replace(/([АЕЁИОӨУҮЫЮЯЭӘ])Щ([АЕЁИОӨУҮЫЮЯЭӘ])/g, "$1ШШ$2")
		.replace(/([АЕЁИОӨУҮЫЮЯЭӘ])щ([аеёиоөуүыюяэә])/g, "$1Шш$2")
		.replace(/([аеёиоөуүыюяэә])щ([аеёиоөуүыюяэә])/g, "$1шш$2")
		.replace(/щ/g, "ш")
		.replace(/Щ/g, "Ш")

		.replace(/([БВГҒДЖЗҘКҠЛМНҢПРСҪТФХҺЧШ])Я/g, "$1ЬА")
		.replace(/([бвгғджзҙкҡлмнңпрсҫтфхһчш])Я/g, "$1ьА")
		.replace(/([БВГҒДЖЗҘКҠЛМНҢПРСҪТФХҺЧШбвгғджзҙкҡлмнңпрсҫтфхһчш])я/g, "$1ьа")
		.replace(/([БВГҒДЖЗҘКҠЛМНҢПРСҪТФХҺЧШбвгғджзҙкҡлмнңпрсҫтфхһчш])Ю/g, "$1Ү")
		.replace(/([БВГҒДЖЗҘКҠЛМНҢПРСҪТФХҺЧШбвгғджзҙкҡлмнңпрсҫтфхһчш])ю/g, "$1ү")
		.replace(/([БВГҒДЖЗҘЙКҠЛМНҢПРСҪТФХҺЧШбвгғджзҙйкҡлмнңпрсҫтфхһчш])Е/g, "$1Э")
		.replace(/([БВГҒДЖЗҘЙКҠЛМНҢПРСҪТФХҺЧШбвгғджзҙйкҡлмнңпрсҫтфхһчш])е/g, "$1э")
		.replace(/([БВГҒДЖЗҘКҠЛМНҢПРСҪТФХҺЧШбвгғджзҙкҡлмнңпрсҫтфхһчш])Ё/g, "$1Ө")
		.replace(/([БВГҒДЖЗҘКҠЛМНҢПРСҪТФХҺЧШбвгғджзҙкҡлмнңпрсҫтфхһчш])ё/g, "$1ө")

		.replace(/Ь([Ии])/g, "Й$1")
		.replace(/ьи/g, "йи")

		.replace(/(\p{Uppercase})(\p{Uppercase}) Я/ug, "$1$2 ЙА")
		.replace(/(\p{Uppercase})Я/ug, "$1ЙА")
		.replace(/Я (\p{Uppercase})(\p{Uppercase})/ug, "ЙА $1$2")
		.replace(/Я(\p{Uppercase})/ug, "ЙА$1")
		.replace(/Я/g, "Йа")
		.replace(/я/g, "йа")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Е/ug, "$1$2 ЙЭ")
		.replace(/(\p{Uppercase})Е/ug, "$1ЙЭ")
		.replace(/Е (\p{Uppercase})(\p{Uppercase})/ug, "ЙЭ $1$2")
		.replace(/Е(\p{Uppercase})/ug, "ЙЭ$1")
		.replace(/Е/g, "Йэ")
		.replace(/е/g, "йэ")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ё/ug, "$1$2 ЙО")
		.replace(/(\p{Uppercase})Ё/ug, "$1ЙО")
		.replace(/Ё (\p{Uppercase})(\p{Uppercase})/ug, "ЙО $1$2")
		.replace(/Ё(\p{Uppercase})/ug, "ЙО$1")
		.replace(/Ё/g, "Йо")
		.replace(/ё/g, "йо")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ю/ug, "$1$2 ЙУ")
		.replace(/(\p{Uppercase})Ю/ug, "$1ЙУ")
		.replace(/Ю (\p{Uppercase})(\p{Uppercase})/ug, "ЙУ $1$2")
		.replace(/Ю(\p{Uppercase})/ug, "ЙУ$1")
		.replace(/Ю/g, "Йу")
		.replace(/ю/g, "йу")

		.replace(/(Ъ|ъ)/g, "")

		.replace(/([АЫОУ])У/g, "$1В")
		.replace(/([АЫОУаыоу])у/g, "$1в")
		.replace(/([ИЭӘӨҮ])Ү/g, "$1В")
		.replace(/([ИЭӘӨҮиэәөү])ү/g, "$1в")

		.replace(/а/g, "a")
		.replace(/б/g, "b")
		.replace(/в/g, "w")
		.replace(/г/g, "g")
		.replace(/ғ/g, "ğ")
		.replace(/д/g, "d")
		.replace(/ҙ/g, "ź")
		.replace(/е/g, "e")
		.replace(/ж/g, "j")
		.replace(/з/g, "z")
		.replace(/и/g, "i")
		.replace(/й/g, "y")
		.replace(/к/g, "k")
		.replace(/ҡ/g, "q")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/ң/g, "ñ")
		.replace(/о/g, "o")
		.replace(/ө/g, "ö")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/ҫ/g, "ś")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ү/g, "ü")
		.replace(/ф/g, "f")
		.replace(/х/g, "x")
		.replace(/һ/g, "h")
		.replace(/ч/g, "ç")
		.replace(/ш/g, "ş")
		.replace(/ь/g, "")
		.replace(/ы/g, "ı")
		.replace(/э/g, "e")
		.replace(/ә/g, "ä")

		.replace(/А/g, "A")
		.replace(/Б/g, "B")
		.replace(/В/g, "W")
		.replace(/Г/g, "G")
		.replace(/Ғ/g, "Ğ")
		.replace(/Д/g, "D")
		.replace(/Ҙ/g, "Ź")
		.replace(/Е/g, "E")
		.replace(/Ж/g, "J")
		.replace(/З/g, "Z")
		.replace(/И/g, "İ")
		.replace(/Й/g, "Y")
		.replace(/К/g, "K")
		.replace(/Ҡ/g, "Q")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/Ң/g, "Ñ")
		.replace(/О/g, "O")
		.replace(/Ө/g, "Ö")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Ҫ/g, "Ś")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ү/g, "Ü")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "X")
		.replace(/Һ/g, "H")
		.replace(/Ч/g, "Ç")
		.replace(/Ш/g, "Ş")
		.replace(/Ь/g, "")
		.replace(/Ы/g, "I")
		.replace(/Э/g, "E")
		.replace(/Ә/g, "Ä")

		.replace(/\u2039/g, "\u2018")
		.replace(/\u203a/g, "\u2019")
		.replace(/\u00ab/g, "\u201c")
		.replace(/\u00bb/g, "\u201d")

		.normalize('NFC');
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}
