function cyrlat() {
	document.transcription.text1.value = document.transcription.text1.value
		.replace(/ă/g, "ӑ")
		.replace(/Ă/g, "Ӑ")
		.replace(/ĕ/g, "ӗ")
		.replace(/Ĕ/g, "Ӗ")
		.replace(/ǎ/g, "ӑ")
		.replace(/Ǎ/g, "Ӑ")
		.replace(/ě/g, "ӗ")
		.replace(/Ě/g, "Ӗ")
		.replace(/ç/g, "ҫ")
		.replace(/Ç/g, "Ҫ")
		.replace(/ÿ/g, "ӳ")
		.replace(/Ÿ/g, "Ӳ")
		.replace(/ў/g, "ӳ")
		.replace(/Ў/g, "Ӳ")
		.replace(/ү/g, "ӳ")
		.replace(/Ү/g, "Ӳ");

	document.transcription.text2.value = document.transcription.text1.value
		.replace(/\u0301/g, "\u0323")

		.replace(/ е/g, " yе")
		.replace(/\nе/g, "\nyе")
		.replace(/\rе/g, "\ryе")
		.replace(/^е/g, "yе")
		.replace(/\u003eе/g, "\u003eyе")

		.replace(/ Е/g, " Yе")
		.replace(/\nЕ/g, "\nYе")
		.replace(/\rЕ/g, "\rYе")
		.replace(/^Е/g, "Yе")
		.replace(/\u003eЕ/g, "\u003eYе")

		.replace(/ае/g, "аyе")
		.replace(/ӑе/g, "ӑyе")
		.replace(/ее/g, "еyе")
		.replace(/ёе/g, "ёyе")
		.replace(/ӗе/g, "ӗyе")
		.replace(/ие/g, "иyе")
		.replace(/ое/g, "оyе")
		.replace(/уе/g, "уyе")
		.replace(/ӳе/g, "ӳyе")
		.replace(/ъе/g, "ъyе")
		.replace(/ые/g, "ыyе")
		.replace(/ье/g, "ьyе")
		.replace(/эе/g, "эyе")
		.replace(/юе/g, "юyе")
		.replace(/яе/g, "яyе")

		.replace(/Ае/g, "Аyе")
		.replace(/Ӑе/g, "Ӑyе")
		.replace(/Ее/g, "Еyе")
		.replace(/Ёе/g, "Ёyе")
		.replace(/Ӗе/g, "Ӗyе")
		.replace(/Ие/g, "Иyе")
		.replace(/Ое/g, "Оyе")
		.replace(/Уе/g, "Уyе")
		.replace(/Ӳе/g, "Ӳyе")
		.replace(/Ъе/g, "Ъyе")
		.replace(/Ые/g, "Ыyе")
		.replace(/Ье/g, "Ьyе")
		.replace(/Эе/g, "Эyе")
		.replace(/Юе/g, "Юyе")
		.replace(/Яе/g, "Яyе")

		.replace(/АЕ/g, "АYЕ")
		.replace(/ӐЕ/g, "ӐYЕ")
		.replace(/ЕЕ/g, "ЕYЕ")
		.replace(/ЁЕ/g, "ЁYЕ")
		.replace(/ӖЕ/g, "ӖYЕ")
		.replace(/ИЕ/g, "ИYЕ")
		.replace(/ОЕ/g, "ОYЕ")
		.replace(/УЕ/g, "УYЕ")
		.replace(/ӲЕ/g, "ӲYЕ")
		.replace(/ЪЕ/g, "ЪYЕ")
		.replace(/ЫЕ/g, "ЫYЕ")
		.replace(/ЬЕ/g, "ЬYЕ")
		.replace(/ЭЕ/g, "ЭYЕ")
		.replace(/ЮЕ/g, "ЮYЕ")
		.replace(/ЯЕ/g, "ЯYЕ")

		.replace(/айе/g, "аyyе")
		.replace(/ӑйе/g, "ӑyyе")
		.replace(/ейе/g, "еyyе")
		.replace(/ёйе/g, "ёyyе")
		.replace(/ӗйе/g, "ӗyyе")
		.replace(/ийе/g, "иyyе")
		.replace(/ойе/g, "оyyе")
		.replace(/уйе/g, "уyyе")
		.replace(/ӳйе/g, "ӳyyе")
		.replace(/ыйе/g, "ыyyе")
		.replace(/эйе/g, "эyyе")
		.replace(/юйе/g, "юyyе")
		.replace(/яйе/g, "яyyе")

		.replace(/Айе/g, "Аyyе")
		.replace(/Ӑйе/g, "Ӑyyе")
		.replace(/Ейе/g, "Еyyе")
		.replace(/Ёйе/g, "Ёyyе")
		.replace(/Ӗйе/g, "Ӗyyе")
		.replace(/Ийе/g, "Иyyе")
		.replace(/Ойе/g, "Оyyе")
		.replace(/Уйе/g, "Уyyе")
		.replace(/Ӳйе/g, "Ӳyyе")
		.replace(/Ыйе/g, "Ыyyе")
		.replace(/Эйе/g, "Эyyе")
		.replace(/Юйе/g, "Юyyе")
		.replace(/Яйе/g, "Яyyе")

		.replace(/АЙЕ/g, "АYYЕ")
		.replace(/ӐЙЕ/g, "ӐYYЕ")
		.replace(/ЕЙЕ/g, "ЕYYЕ")
		.replace(/ЁЙЕ/g, "ЁYYЕ")
		.replace(/ӖЙЕ/g, "ӖYYЕ")
		.replace(/ИЙЕ/g, "ИYYЕ")
		.replace(/ОЙЕ/g, "ОYYЕ")
		.replace(/УЙЕ/g, "УYYЕ")
		.replace(/ӲЙЕ/g, "ӲYYЕ")
		.replace(/ЫЙЕ/g, "ЫYYЕ")
		.replace(/ЭЙЕ/g, "ЭYYЕ")
		.replace(/ЮЙЕ/g, "ЮYYЕ")
		.replace(/ЯЙЕ/g, "ЯYYЕ")

		.replace(/ ё/g, " yё")
		.replace(/\nё/g, "\nyё")
		.replace(/\rё/g, "\ryё")
		.replace(/^ё/g, "yё")
		.replace(/\u003eё/g, "\u003eyё")

		.replace(/ Ё/g, " Yё")
		.replace(/\nЁ/g, "\nYё")
		.replace(/\rЁ/g, "\rYё")
		.replace(/^Ё/g, "Yё")
		.replace(/\u003eЁ/g, "\u003eYё")

		.replace(/аё/g, "аyё")
		.replace(/ӑё/g, "ӑyё")
		.replace(/её/g, "еyё")
		.replace(/ёё/g, "ёyё")
		.replace(/ӗё/g, "ӗyё")
		.replace(/иё/g, "иyё")
		.replace(/оё/g, "оyё")
		.replace(/уё/g, "уyё")
		.replace(/ӳё/g, "ӳyё")
		.replace(/ъё/g, "ъyё")
		.replace(/ыё/g, "ыyё")
		.replace(/ьё/g, "ьyё")
		.replace(/эё/g, "эyё")
		.replace(/юё/g, "юyё")
		.replace(/яё/g, "яyё")

		.replace(/Аё/g, "Аyё")
		.replace(/Ӑё/g, "Ӑyё")
		.replace(/Её/g, "Еyё")
		.replace(/Ёё/g, "Ёyё")
		.replace(/Ӗё/g, "Ӗyё")
		.replace(/Иё/g, "Иyё")
		.replace(/Оё/g, "Оyё")
		.replace(/Уё/g, "Уyё")
		.replace(/Ӳё/g, "Ӳyё")
		.replace(/Ъё/g, "Ъyё")
		.replace(/Ыё/g, "Ыyё")
		.replace(/Ьё/g, "Ьyё")
		.replace(/Эё/g, "Эyё")
		.replace(/Юё/g, "Юyё")
		.replace(/Яё/g, "Яyё")

		.replace(/АЁ/g, "АYЁ")
		.replace(/ӐЁ/g, "ӐYЁ")
		.replace(/ЕЁ/g, "ЕYЁ")
		.replace(/ЁЁ/g, "ЁYЁ")
		.replace(/ӖЁ/g, "ӖYЁ")
		.replace(/ИЁ/g, "ИYЁ")
		.replace(/ОЁ/g, "ОYЁ")
		.replace(/УЁ/g, "УYЁ")
		.replace(/ӲЁ/g, "ӲYЁ")
		.replace(/ЪЁ/g, "ЪYЁ")
		.replace(/ЫЁ/g, "ЫYЁ")
		.replace(/ЬЁ/g, "ЬYЁ")
		.replace(/ЭЁ/g, "ЭYЁ")
		.replace(/ЮЁ/g, "ЮYЁ")
		.replace(/ЯЁ/g, "ЯYЁ")

		.replace(/айё/g, "аyyё")
		.replace(/ӑйё/g, "ӑyyё")
		.replace(/ейё/g, "еyyё")
		.replace(/ёйё/g, "ёyyё")
		.replace(/ӗйё/g, "ӗyyё")
		.replace(/ийё/g, "иyyё")
		.replace(/ойё/g, "оyyё")
		.replace(/уйё/g, "уyyё")
		.replace(/ӳйё/g, "ӳyyё")
		.replace(/ыйё/g, "ыyyё")
		.replace(/эйё/g, "эyyё")
		.replace(/юйё/g, "юyyё")
		.replace(/яйё/g, "яyyё")

		.replace(/Айё/g, "Аyyё")
		.replace(/Ӑйё/g, "Ӑyyё")
		.replace(/Ейё/g, "Еyyё")
		.replace(/Ёйё/g, "Ёyyё")
		.replace(/Ӗйё/g, "Ӗyyё")
		.replace(/Ийё/g, "Иyyё")
		.replace(/Ойё/g, "Оyyё")
		.replace(/Уйё/g, "Уyyё")
		.replace(/Ӳйё/g, "Ӳyyё")
		.replace(/Ыйё/g, "Ыyyё")
		.replace(/Эйё/g, "Эyyё")
		.replace(/Юйё/g, "Юyyё")
		.replace(/Яйё/g, "Яyyё")

		.replace(/АЙЁ/g, "АYYЁ")
		.replace(/ӐЙЁ/g, "ӐYYЁ")
		.replace(/ЕЙЁ/g, "ЕYYЁ")
		.replace(/ЁЙЁ/g, "ЁYYЁ")
		.replace(/ӖЙЁ/g, "ӖYYЁ")
		.replace(/ИЙЁ/g, "ИYYЁ")
		.replace(/ОЙЁ/g, "ОYYЁ")
		.replace(/УЙЁ/g, "УYYЁ")
		.replace(/ӲЙЁ/g, "ӲYYЁ")
		.replace(/ЫЙЁ/g, "ЫYYЁ")
		.replace(/ЭЙЁ/g, "ЭYYЁ")
		.replace(/ЮЙЁ/g, "ЮYYЁ")
		.replace(/ЯЙЁ/g, "ЯYYЁ")

		.replace(/ э/g, " е")
		.replace(/\nэ/g, "\nе")
		.replace(/\rэ/g, "\rе")
		.replace(/^э/g, "е")
		.replace(/\u003eэ/g, "\u003eе")

		.replace(/ Э/g, " Е")
		.replace(/\nЭ/g, "\nЕ")
		.replace(/\rЭ/g, "\rЕ")
		.replace(/^Э/g, "Е")
		.replace(/\u003eЭ/g, "\u003eЕ")

		.replace(/аэ/g, "ае")
		.replace(/ӑэ/g, "ӑе")
		.replace(/еэ/g, "ее")
		.replace(/ёэ/g, "ёе")
		.replace(/ӗэ/g, "ӗе")
		.replace(/иэ/g, "ие")
		.replace(/йэ/g, "йе")
		.replace(/оэ/g, "ое")
		.replace(/уэ/g, "уе")
		.replace(/ӳэ/g, "ӳе")
		.replace(/ъэ/g, "ъе")
		.replace(/ыэ/g, "ые")
		.replace(/ьэ/g, "ье")
		.replace(/ээ/g, "эе")
		.replace(/юэ/g, "юе")
		.replace(/яэ/g, "яе")

		.replace(/Аэ/g, "Ае")
		.replace(/Ӑэ/g, "Ӑе")
		.replace(/Еэ/g, "Ее")
		.replace(/Ёэ/g, "Ёе")
		.replace(/Ӗэ/g, "Ӗе")
		.replace(/Иэ/g, "Ие")
		.replace(/Йэ/g, "Йе")
		.replace(/Оэ/g, "Ое")
		.replace(/Уэ/g, "Уе")
		.replace(/Ӳэ/g, "Ӳе")
		.replace(/Ъэ/g, "Ъе")
		.replace(/Ыэ/g, "Ые")
		.replace(/Ьэ/g, "Ье")
		.replace(/Ээ/g, "Эе")
		.replace(/Юэ/g, "Юе")
		.replace(/Яэ/g, "Яе")

		.replace(/АЭ/g, "АЕ")
		.replace(/ӐЭ/g, "ӐЕ")
		.replace(/ЕЭ/g, "ЕЕ")
		.replace(/ЁЭ/g, "ЁЕ")
		.replace(/ӖЭ/g, "ӖЕ")
		.replace(/ИЭ/g, "ИЕ")
		.replace(/ЙЭ/g, "ЙЕ")
		.replace(/ОЭ/g, "ОЕ")
		.replace(/УЭ/g, "УЕ")
		.replace(/ӲЭ/g, "ӲЕ")
		.replace(/ЪЭ/g, "ЪЕ")
		.replace(/ЫЭ/g, "ЫЕ")
		.replace(/ЬЭ/g, "ЬЕ")
		.replace(/ЭЭ/g, "ЭЕ")
		.replace(/ЮЭ/g, "ЮЕ")
		.replace(/ЯЭ/g, "ЯЕ")

		.replace(/ль/g, "ļ")
		.replace(/нь/g, "ņ")
		.replace(/рь/g, "ŗ")
		.replace(/ть/g, "ț")
		.replace(/Ль/g, "Ļ")
		.replace(/Нь/g, "Ņ")
		.replace(/Рь/g, "Ŗ")
		.replace(/Ть/g, "Ț")
		.replace(/ЛЬ/g, "Ļ")
		.replace(/НЬ/g, "Ņ")
		.replace(/РЬ/g, "Ŗ")
		.replace(/ТЬ/g, "Ț")

		.replace(/дж/g, "џ")
		.replace(/Дж/g, "Џ")
		.replace(/ДЖ/g, "Џ")

		.replace(/а/g, "a")
		.replace(/ӑ/g, "o")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/д/g, "d")
		.replace(/е/g, "e")
		.replace(/ё/g, "ë")
		.replace(/ӗ/g, "ö")
		.replace(/ж/g, "ž")
		.replace(/з/g, "z")
		.replace(/и/g, "i")
		.replace(/й/g, "y")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/о/g, "ò")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/ҫ/g, "ś")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ӳ/g, "ü")
		.replace(/ф/g, "f")
		.replace(/х/g, "h")
		.replace(/ц/g, "c")
		.replace(/ч/g, "č")
		.replace(/џ/g, "j")
		.replace(/ш/g, "š")
		.replace(/щ/g, "ŝ")
		.replace(/ъ/g, "ʼ")
		.replace(/ы/g, "ï")
		.replace(/ь/g, "")
		.replace(/э/g, "è")
		.replace(/ю/g, "yu")
		.replace(/я/g, "ya")

		.replace(/А/g, "A")
		.replace(/Ӑ/g, "O")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Д/g, "D")
		.replace(/Е/g, "E")
		.replace(/Ё/g, "Ë")
		.replace(/Ӗ/g, "Ö")
		.replace(/Ж/g, "Ž")
		.replace(/З/g, "Z")
		.replace(/И/g, "I")
		.replace(/Й/g, "Y")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/О/g, "Ò")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Ҫ/g, "Ś")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ӳ/g, "Ü")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "H")
		.replace(/Ц/g, "C")
		.replace(/Ч/g, "Č")
		.replace(/Џ/g, "J")
		.replace(/Ш/g, "Š")
		.replace(/Щ/g, "Ŝ")
		.replace(/Ъ/g, "ʼ")
		.replace(/Ы/g, "Ï")
		.replace(/Ь/g, "")
		.replace(/Э/g, "È")
		.replace(/Ю/g, "Yu")
		.replace(/Я/g, "Ya")
		.replace(/«/g, "\u201c")
		.replace(/»/g, "\u201d");
}

function latcyr() {
	document.transcription.text2.value = document.transcription.text2.value
		.replace(/w/g, "v")
		.replace(/W/g, "V");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}