function leftright() {
	document.transcription.text1.value = document.transcription.text1.value
		.replace(/(\p{Script=Cyrl})(I|1)/ug, "$1Ӏ")
		.replace(/(I|1)(\p{Script=Cyrl})/ug, "Ӏ$2")
		.replace(/(\p{Script=Cyrl})l/ug, "$1ӏ")
		.replace(/l(\p{Script=Cyrl})/ug, "ӏ$1")

		.replace(/(\p{Lowercase})( )?Ӏ/ug, "$1$2ӏ")
		.replace(/(\p{Uppercase})( )?Ӏ( )?(\p{Lowercase})/ug, "$1$2ӏ$3$4");
	
	document.transcription.text2.value = document.transcription.text1.value
		.replace(/(\p{Uppercase})(\p{Uppercase}) Я/ug, "$1$2 ЙА")
		.replace(/(\p{Uppercase})Я/ug, "$1ЙА")
		.replace(/Я (\p{Uppercase})(\p{Uppercase})/ug, "ЙА $1$2")
		.replace(/Я(\p{Uppercase})/ug, "ЙА$1")
		.replace(/Я/g, "Йа")
		.replace(/я/g, "йа")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ё/ug, "$1$2 ЙО")
		.replace(/(\p{Uppercase})Ё/ug, "$1ЙО")
		.replace(/Ё (\p{Uppercase})(\p{Uppercase})/ug, "ЙО $1$2")
		.replace(/Ё(\p{Uppercase})/ug, "ЙО$1")
		.replace(/Ё/g, "Йо")
		.replace(/ё/g, "йо")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ю/ug, "$1$2 ЙУ")
		.replace(/(\p{Uppercase})Ю/ug, "$1ЙУ")
		.replace(/Ю (\p{Uppercase})(\p{Uppercase})/ug, "ЙУ $1$2")
		.replace(/Ю(\p{Uppercase})/ug, "ЙУ$1")
		.replace(/Ю/g, "Йу")
		.replace(/ю/g, "йу")

		.replace(/у(а|е|и|о|у|ы|э)/g, "ў$1")
		.replace(/У(А|Е|И|О|У|Ы|Э|а|е|и|о|у|ы|э)/g, "Ў$1")
		.replace(/(А|Е|И|О|У|Ы|Э|а|е|и|о|у|ы|э)у/g, "$1ў")
		.replace(/(А|Е|И|О|У|Ы|Э)У/g, "$1Ў")

		.replace(/кхъ/g, "къхъ")
		.replace(/Кхъ/g, "Къхъ")
		.replace(/КХЪ/g, "КЪХЪ")
		.replace(/жь/g, "j")
		.replace(/Ж(Ь|ь)/g, "J")
		.replace(/хь/g, "ħ")
		.replace(/Х(Ь|ь)/g, "Ħ")
		.replace(/гъ/g, "ġ")
		.replace(/Г(Ъ|ъ)/g, "Ġ")
		.replace(/къ/g, "q")
		.replace(/К(Ъ|ъ)/g, "Q")
		.replace(/лъ/g, "ł")
		.replace(/Л(Ъ|ъ)/g, "Ł")
		.replace(/хъ/g, "ḥ")
		.replace(/Х(Ъ|ъ)/g, "Ḥ")
		.replace(/жъ/g, "ż")
		.replace(/Ж(Ъ|ъ)/g, "Ż")
		.replace(/чъ/g, "ċ")
		.replace(/Ч(Ъ|ъ)/g, "Ċ")
		.replace(/шъ/g, "ṣ")
		.replace(/Ш(Ъ|ъ)/g, "Ṣ")
		.replace(/чӏ/g, "ċӏ")
		.replace(/Ч(Ӏ|ӏ)/g, "Ċ$1")
		.replace(/кӏ/g, "čӏ")
		.replace(/Ч(Ӏ|ӏ)/g, "Č$1")

		.replace(/а/g, "a")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/д/g, "d")
		.replace(/е/g, "é")
		.replace(/ж/g, "ž")
		.replace(/з/g, "z")
		.replace(/и/g, "í")
		.replace(/й/g, "y")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/о/g, "o")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ў/g, "w")
		.replace(/ф/g, "f")
		.replace(/х/g, "x")
		.replace(/ц/g, "c")
		.replace(/ч/g, "č")
		.replace(/ш/g, "š")
		.replace(/щ/g, "ṡ")
		.replace(/ъ/g, "")
		.replace(/ы/g, "i")
		.replace(/ь/g, "")
		.replace(/э/g, "e")
		.replace(/ӏ/g, "h")
		.replace(/А/g, "A")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Д/g, "D")
		.replace(/Е/g, "É")
		.replace(/Ж/g, "Ž")
		.replace(/З/g, "Z")
		.replace(/И/g, "Í")
		.replace(/Й/g, "Y")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/О/g, "O")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ў/g, "W")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "X")
		.replace(/Ц/g, "C")
		.replace(/Ч/g, "Č")
		.replace(/Ш/g, "Š")
		.replace(/Щ/g, "Ṡ")
		.replace(/Ъ/g, "")
		.replace(/Ы/g, "I")
		.replace(/Ь/g, "")
		.replace(/Э/g, "E")
		.replace(/Ӏ/g, "H")

		.replace(/\u2039/g, "\u2018")
		.replace(/\u203a/g, "\u2019")
		.replace(/\u00ab/g, "\u201c")
		.replace(/\u00bb/g, "\u201d");
}

function rightleft() {}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value)
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value)
}
