
var car;
var translit;
function cyrlat () {
car = document.transcription.text1.value;
translit = document.transcription.text1.value;
  translit = translit.replace(/ҳ/g, "һ");
  car = car.replace(/ҳ/g, "һ");
  translit = translit.replace(/Ҳ/g, "Һ");
  car = car.replace(/Ҳ/g, "Һ");
  translit = translit.replace(/й/g, "ј");
  car = car.replace(/й/g, "ј");
  translit = translit.replace(/Й/g, "Ј");
  car = car.replace(/Й/g, "Ј");
  translit = translit.replace(/җ/g, "ҹ");
  car = car.replace(/җ/g, "ҹ");
  translit = translit.replace(/Җ/g, "Ҹ");
  car = car.replace(/Җ/g, "Ҹ");
  translit = translit.replace(/э/g, "е");
  car = car.replace(/э/g, "е");
  translit = translit.replace(/Э/g, "Е");
  car = car.replace(/Э/g, "Е");
  translit = translit.replace(/я/g, "ја");
  car = car.replace(/я/g, "ја");
  translit = translit.replace(/Я/g, "Ја");
  car = car.replace(/Я/g, "Ја");
  translit = translit.replace(/ю/g, "ју");
  car = car.replace(/ю/g, "ју");
  translit = translit.replace(/Ю/g, "Ју");
  car = car.replace(/Ю/g, "Ју");
  translit = translit.replace(/ц/g, "с");
  car = car.replace(/ц/g, "с");
  translit = translit.replace(/Ц/g, "С");
  car = car.replace(/Ц/g, "С");
  
  car = car.replace(/а/g, "a");
  car = car.replace(/б/g, "b");
  car = car.replace(/ҹ/g, "c");
  car = car.replace(/ч/g, "ç");
  car = car.replace(/д/g, "d");
  car = car.replace(/е/g, "e");
  car = car.replace(/ә/g, "ə");
  car = car.replace(/ф/g, "f");
  car = car.replace(/ҝ/g, "g");
  car = car.replace(/г/g, "q");
  car = car.replace(/ғ/g, "ğ");
  car = car.replace(/һ/g, "h");
  car = car.replace(/х/g, "x");
  car = car.replace(/ы/g, "ı");
  car = car.replace(/и/g, "i");
  car = car.replace(/ж/g, "j");
  car = car.replace(/к/g, "k");
  car = car.replace(/л/g, "l");
  car = car.replace(/м/g, "m");
  car = car.replace(/н/g, "n");
  car = car.replace(/о/g, "o");
  car = car.replace(/ө/g, "ö");
  car = car.replace(/п/g, "p");
  car = car.replace(/р/g, "r");
  car = car.replace(/с/g, "s");
  car = car.replace(/ш/g, "ş");
  car = car.replace(/т/g, "t");
  car = car.replace(/у/g, "u");
  car = car.replace(/ү/g, "ü");
  car = car.replace(/в/g, "v");
  car = car.replace(/ј/g, "y");
  car = car.replace(/з/g, "z");
  car = car.replace(/ь/g, "");
  car = car.replace(/ъ/g, "");
  car = car.replace(/А/g, "A");
  car = car.replace(/Б/g, "B");
  car = car.replace(/Ҹ/g, "C");
  car = car.replace(/Ч/g, "Ç");
  car = car.replace(/Д/g, "D");
  car = car.replace(/Е/g, "E");
  car = car.replace(/Ә/g, "Ə");
  car = car.replace(/Ф/g, "F");
  car = car.replace(/Ҝ/g, "G");
  car = car.replace(/Г/g, "Q");
  car = car.replace(/Ғ/g, "Ğ");
  car = car.replace(/Һ/g, "H");
  car = car.replace(/Х/g, "X");
  car = car.replace(/Ы/g, "I");
  car = car.replace(/И/g, "İ");
  car = car.replace(/Ж/g, "J");
  car = car.replace(/К/g, "K");
  car = car.replace(/Л/g, "L");
  car = car.replace(/М/g, "M");
  car = car.replace(/Н/g, "N");
  car = car.replace(/О/g, "O");
  car = car.replace(/Ө/g, "Ö");
  car = car.replace(/П/g, "P");
  car = car.replace(/Р/g, "R");
  car = car.replace(/С/g, "S");
  car = car.replace(/Ш/g, "Ş");
  car = car.replace(/Т/g, "T");
  car = car.replace(/У/g, "U");
  car = car.replace(/Ү/g, "Ü");
  car = car.replace(/В/g, "V");
  car = car.replace(/Ј/g, "Y");
  car = car.replace(/З/g, "Z");
  car = car.replace(/Ь/g, "");
  car = car.replace(/Ъ/g, "");
  car = car.replace(/ʼ/g, "");
  car = car.replace(/ə/g, "ä");
  car = car.replace(/Ə/g, "Ä");
   document.transcription.text1.value=translit;
   document.transcription.text2.value=car;
}
function latcyr () {
car = document.transcription.text2.value;
  car = car.replace(/ä/g, "ə");
  car = car.replace(/Ä/g, "Ə");
document.transcription.text1.value=car;
}
function copy1()
{ navigator.clipboard.writeText(document.transcription.text1.value);
}
function copy2()
{ navigator.clipboard.writeText(document.transcription.text2.value);
}
