function cyrlat() {
	document.transcription.text1.value = document.transcription.text1.value
		.replace(/ҳ/g, "һ")
		.replace(/Ҳ/g, "Һ")
		.replace(/й/g, "ј")
		.replace(/Й/g, "Ј")
		.replace(/җ/g, "ҹ")
		.replace(/Җ/g, "Ҹ")
		.replace(/э/g, "е")
		.replace(/Э/g, "Е")
		.replace(/я/g, "ја")
		.replace(/Я/g, "Ја")
		.replace(/ю/g, "ју")
		.replace(/Ю/g, "Ју")
		.replace(/ц/g, "с")
		.replace(/Ц/g, "С");
	document.transcription.text2.value = document.transcription.text1.value
		.replace(/ҳ/g, "һ")
		.replace(/Ҳ/g, "Һ")
		.replace(/й/g, "ј")
		.replace(/Й/g, "Ј")
		.replace(/җ/g, "ҹ")
		.replace(/Җ/g, "Ҹ")
		.replace(/э/g, "е")
		.replace(/Э/g, "Е")
		.replace(/я/g, "ја")
		.replace(/Я/g, "Ја")
		.replace(/ю/g, "ју")
		.replace(/Ю/g, "Ју")
		.replace(/ц/g, "с")
		.replace(/Ц/g, "С")

		.replace(/а/g, "a")
		.replace(/б/g, "b")
		.replace(/ҹ/g, "c")
		.replace(/ч/g, "ç")
		.replace(/д/g, "d")
		.replace(/е/g, "e")
		.replace(/ә/g, "ə")
		.replace(/ф/g, "f")
		.replace(/ҝ/g, "g")
		.replace(/г/g, "q")
		.replace(/ғ/g, "ğ")
		.replace(/һ/g, "h")
		.replace(/х/g, "x")
		.replace(/ы/g, "ı")
		.replace(/и/g, "i")
		.replace(/ж/g, "j")
		.replace(/к/g, "k")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/о/g, "o")
		.replace(/ө/g, "ö")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/ш/g, "ş")
		.replace(/т/g, "t")
		.replace(/у/g, "u")
		.replace(/ү/g, "ü")
		.replace(/в/g, "v")
		.replace(/ј/g, "y")
		.replace(/з/g, "z")
		.replace(/ь/g, "")
		.replace(/ъ/g, "")
		.replace(/А/g, "A")
		.replace(/Б/g, "B")
		.replace(/Ҹ/g, "C")
		.replace(/Ч/g, "Ç")
		.replace(/Д/g, "D")
		.replace(/Е/g, "E")
		.replace(/Ә/g, "Ə")
		.replace(/Ф/g, "F")
		.replace(/Ҝ/g, "G")
		.replace(/Г/g, "Q")
		.replace(/Ғ/g, "Ğ")
		.replace(/Һ/g, "H")
		.replace(/Х/g, "X")
		.replace(/Ы/g, "I")
		.replace(/И/g, "İ")
		.replace(/Ж/g, "J")
		.replace(/К/g, "K")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/О/g, "O")
		.replace(/Ө/g, "Ö")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Ш/g, "Ş")
		.replace(/Т/g, "T")
		.replace(/У/g, "U")
		.replace(/Ү/g, "Ü")
		.replace(/В/g, "V")
		.replace(/Ј/g, "Y")
		.replace(/З/g, "Z")
		.replace(/Ь/g, "")
		.replace(/Ъ/g, "")
		.replace(/ʼ/g, "")
		.replace(/ə/g, "ä")
		.replace(/Ə/g, "Ä");
}

function latcyr() {
	document.transcription.text1.value = document.transcription.text2.value
		.replace(/ä/g, "ə")
		.replace(/Ä/g, "Ə");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}
