var car;
function cyrlat () {
car = document.transcription.text1.value;
  car = car.replace(/Â/g, "A")
           .replace(/â/g, "a")
           .replace(/Î/g, "İ")
           .replace(/î/g, "i")
           .replace(/Û/g, "U")
           .replace(/û/g, "u") 
           .replace(/(C|c)h/g, "$1-h")
           .replace(/(Ğ|ğ)h/g, "$1-h")
           .replace(/(E|e)u/g, "$1-u")
           .replace(/(O|o)e/g, "$1-e")
           .replace(/(S|s)h/g, "$1-h")
           .replace(/(U|u)e/g, "$1-e")
           .replace(/(I|ı)e/g, "$1-e")
           .replace(/(Ö|ö)u/g, "$1-u")
           .replace(/(Ü|ü)u/g, "$1-u")
           .replace(/CH/g, "C-H")
           .replace(/ĞH/g, "Ğ-H")
           .replace(/EU/g, "E-U")
           .replace(/OE/g, "O-E")
           .replace(/SH/g, "S-H")
           .replace(/UE/g, "U-E")
           .replace(/IE/g, "I-E")
           .replace(/ÖU/g, "Ö-U")
           .replace(/ÜU/g, "Ü-U")
           .replace(/j/g, "jh")
           .replace(/c/g, "j")
           .replace(/ç/g, "ch")
           .replace(/k/g, "c")
           .replace(/ğ/g, "qh")
           .replace(/ı/g, "eu")
           .replace(/ö/g, "oe")
           .replace(/ş/g, "sh")
           .replace(/ü/g, "ue")
           .replace(/J/g, "Jh")
           .replace(/C/g, "J")
           .replace(/Ç/g, "Ch")
           .replace(/K/g, "C")
           .replace(/Ğ/g, "QH")
           .replace(/I/g, "Eu")
           .replace(/İ/g, "I")
           .replace(/Ö/g, "Oe")
           .replace(/Ş/g, "Sh")
           .replace(/Ü/g, "Ue")
           .replace(/i([aeiou])/g, "i-$1")
           .replace(/I([AEIOUaeiou])/g, "I-$1")           
           .replace(/y/g, "i\u200c")
           .replace(/Y/g, "I\u200c")
           .replace(/i\u200c([aeiou])/g, "y$1")
           .replace(/I\u200c([AEIOUaeiou])/g, "Y$1")
           .replace(/([Ii])i\u200c/g, "$1y")
           .replace(/II\u200c/g, "IY")
           .replace(/\u200c/g, "")
  
           .replace(/C([EIei])/g, "K$1")
           .replace(/c([ei])/g, "k$1")
           .replace(/C([Uu])/g, "Q$1")
           .replace(/cu/g, "qu") 
           .replace(/CCH([EI])/g, "QC$1")
           .replace(/Cch([ei])/g, "Qc$1")
           .replace(/cch([ei])/g, "qc$1")
           .replace(/CH([EI])/g, "C$1")
           .replace(/Ch([ei])/g, "C$1")
           .replace(/ch([ei])/g, "c$1")

           .replace(/GH([EI])/g, "G-H$1")
           .replace(/Gh([ei])/g, "G-h$1")
           .replace(/gh([ei])/g, "g-h$1")
           .replace(/G([EI])/g, "GH$1")
           .replace(/G([ei])/g, "Gh$1")
           .replace(/g([ei])/g, "gh$1")
           .replace(/J([EIei])/g, "G$1")
           .replace(/j([ei])/g, "g$1")
           .replace(/GJ([EI])/g, "QC$1")
           .replace(/Cch([ei])/g, "Qc$1")
           .replace(/cch([ei])/g, "qc$1")
           .replace(/CH([EI])/g, "C$1")
           .replace(/Ch([ei])/g, "C$1")
           .replace(/ch([ei])/g, "c$1");
   document.transcription.text2.value=car;
}
function latcyr () {/*
car = document.transcription.text2.value;
  car = car.replace(/C([EI])/g, "CH$1")
           .replace(/C([ei])/g, "Ch$1")
           .replace(/c([ei])/g, "ch$1")
           .replace(/Q([Uu])/g, "C$1")
           .replace(/qu/g, "cu")
           .replace(/S[Hh]/g, "Ş")
           .replace(/sh/g, "ş")
           .replace(/C[Hh]/g, "Ç")
           .replace(/ch/g, "ç")
           .replace(/J/g, "C")
           .replace(/j/g, "c")
           .replace(/C[Hh]/g, "J")
           .replace(/ch/g, "j")
           .replace(/S[Hh]/g, "Ş")
           .replace(/sh/g, "ş")
           .replace(/I/g, "İ")
           .replace(/E[Uu]/g, "I")
           .replace(/eu/g, "ı")
           .replace(/O[Ee]/g, "Ö")
           .replace(/oe/g, "ö")
           .replace(/U[Ee]/g, "Ü")
           .replace(/ue/g, "ü")
           .replace(/KA/g, "KÂ")
           .replace(/KU/g, "KÛ")
           .replace(/([Kk])a/g, "$1â")
           .replace(/([Kk])u/g, "$1û")
           .replace(/Q/g, "K")
           .replace(/q/g, "k")
           .replace(/W/g, "Ğ")
           .replace(/w/g, "ğ")
           .replace(/Ü-U/g, "ÜU")
           .replace(/Ö-U/g, "ÖU")
           .replace(/I-E/g, "IE")
           .replace(/U-E/g, "UE")
           .replace(/S-H/g, "SH")
           .replace(/O-E/g, "OE")
           .replace(/E-U/g, "EU")
           .replace(/C-H/g, "CH")
           .replace(/(Ü|ü)-u/g, "$1u")
           .replace(/(Ö|ö)-u/g, "$1u")
           .replace(/(I|ı)-e/g, "$1e")
           .replace(/(U|u)-e/g, "$1e")
           .replace(/(S|s)-h/g, "$1h")
           .replace(/(O|o)-e/g, "$1e")
           .replace(/(E|e)-u/g, "$1u")
           .replace(/(C|c)-h/g, "$1h");
   document.transcription.text1.value=car;
*/}
function copy1()
{ textRange=document.transcription.text1.createTextRange();   textRange.execCommand("Copy");   textRange="";
}
function copy2()
{ textRange=document.transcription.text2.createTextRange();   textRange.execCommand("Copy");   textRange="";
}
