function cyrlat() {
	document.transcription.text1.value = document.transcription.text1.value
		.replace(/ə/g, "ә")
		.replace(/Ə/g, "Ә");

	document.transcription.text2.value = document.transcription.text1.value
		//Я, Ё, Ю 
		.replace(/(\p{Uppercase})(\p{Uppercase}) Я/ug, "$1$2 ЬА")
		.replace(/(\p{Uppercase})Я/ug, "$1ЬА")
		.replace(/Я (\p{Uppercase})(\p{Uppercase})/ug, "ЬА $1$2")
		.replace(/Я(\p{Uppercase})/ug, "ЬА$1")
		.replace(/Я/g, "Ьа")
		.replace(/я/g, "ьа")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ё/ug, "$1$2 ЬО")
		.replace(/(\p{Uppercase})Ё/ug, "$1ЬО")
		.replace(/Ё (\p{Uppercase})(\p{Uppercase})/ug, "ЬО $1$2")
		.replace(/Ё(\p{Uppercase})/ug, "ЬО$1")
		.replace(/Ё/g, "Ьо")
		.replace(/ё/g, "ьо")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ю/ug, "$1$2 ЬУ")
		.replace(/(\p{Uppercase})Ю/ug, "$1ЬУ")
		.replace(/Ю (\p{Uppercase})(\p{Uppercase})/ug, "ЬУ $1$2")
		.replace(/Ю(\p{Uppercase})/ug, "ЬУ$1")
		.replace(/Ю/g, "Ьу")
		.replace(/ю/g, "ьу")

		//Щ
		.replace(/([АӘЕИОӨУҰҮЫІЭаәеиоөуұүыіэ])щ([аәеиоөуұүыіэ])/g, "$1шш$2")
		.replace(/([АӘЕИОӨУҰҮЫІЭаәеиоөуұүыіэ])Щ([АӘЕИОӨУҰҮЫІЭ])/g, "$1ШШ$2")
		.replace(/щ/g, "ш")
		.replace(/Щ/g, "Ш")

		.replace(/Э/g, "Е")
		.replace(/э/g, "е")

		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХҺЦЧШ])ЬА/g, "$1Ә")
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХҺЦЧШ])([Ьь])а/g, "$1ә")
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХҺЦЧШбвгғджзйкқлмнңпрстфхһцчш])ьа/g, "$1ә")
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХҺЦЧШ])ЬЫ/g, "$1І")
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХҺЦЧШ])([Ьь])ы/g, "$1і")
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХҺЦЧШбвгғджзйкқлмнңпрстфхһцчш])ьы/g, "$1і")
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХҺЦЧШ])ЬО/g, "$1Ө")
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХҺЦЧШ])([Ьь])о/g, "$1ө")
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХҺЦЧШбвгғджзйкқлмнңпрстфхһцчш])ьо/g, "$1ө")
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХҺЦЧШ])ЬУ/g, "$1Ү")
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХҺЦЧШ])([Ьь])у/g, "$1ү")
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХҺЦЧШбвгғджзйкқлмнңпрстфхһцчш])ьу/g, "$1ү")

		//У
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХҺЦЧШЬЪ])У([АОҰЫӘЕӨҮІ])/g, "$1Ӯ$2")
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХҺЦЧШЬЪ])УУ/g, "$1ӮУ")
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХҺЦЧШЬЪ])УИ/g, "$1ӮИ")
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХҺЦЧШЬЪбвгғджзйкқлмнңпрстфхһцчшьъ])у([аоұыәеөүі])/g, "$1ӯ$2")
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХҺЦЧШЬЪбвгғджзйкқлмнңпрстфхһцчшьъ])уу/g, "$1ӯў")
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХҺЦЧШЬЪбвгғджзйкқлмнңпрстфхһцчшьъ])уи/g, "$1ӯи")
		.replace(/([АОУҰЫӘЕИӨУҮІ])У/g, "$1Ў")
		.replace(/([АОУҰЫӘЕИӨУҮІаоуұыәеиөуүі])у/g, "$1ў")
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХҺЦЧШЬЪ])У/g, "$1Ӯ")
		.replace(/([БВГҒДЖЗЙКҚЛМНҢПРСТФХҺЦЧШЬЪбвгғджзйкқлмнңпрстфхһцчшьъ])у/g, "$1ӯ")
		.replace(/У([БВГҒДЖЗЙКҚЛМНҢПРСТФХҺЦЧШбвгғджзйкқлмнңпрстфхһцчш])/g, "Ӯ$1")
		.replace(/у([бвгғджзйкқлмнңпрстфхһцчш])/g, "ӯ$1")
		.replace(/У/g, "Ў")
		.replace(/у/g, "ў")
		.replace(/Ӯ/g, "У")
		.replace(/ӯ/g, "у")

		.replace(/Ь([АӘЕИОӨУҰҮЫІЭаәеиоөуұүыіэ])/g, "Й$1")
		.replace(/ь([аәеиоөуұүыіэ])/g, "й$1")
		.replace(/([Ьь])/g, "")

		.replace(/(\p{Uppercase})(\p{Uppercase}) Ш/ug, "$1$2 SH")
		.replace(/(\p{Uppercase})Ш/ug, "$1SH")
		.replace(/Ш (\p{Uppercase})(\p{Uppercase})/ug, "SH $1$2")
		.replace(/Ш(\p{Uppercase})/ug, "SH$1")
		.replace(/(\p{Uppercase})(\p{Uppercase}) Ч/ug, "$1$2 CH")
		.replace(/(\p{Uppercase})Ч/ug, "$1CH")
		.replace(/Ч (\p{Uppercase})(\p{Uppercase})/ug, "CH $1$2")
		.replace(/Ч(\p{Uppercase})/ug, "CH$1")
	
		.replace(/а/g, "a")
		.replace(/ә/g, "á")
		.replace(/б/g, "b")
		.replace(/в/g, "v")
		.replace(/г/g, "g")
		.replace(/ғ/g, "ǵ")
		.replace(/д/g, "d")
		.replace(/е/g, "e")
		.replace(/ё/g, "yo")
		.replace(/ж/g, "j")
		.replace(/з/g, "z")
		.replace(/и/g, "ý")
		.replace(/й/g, "y")
		.replace(/к/g, "k")
		.replace(/қ/g, "q")
		.replace(/л/g, "l")
		.replace(/м/g, "m")
		.replace(/н/g, "n")
		.replace(/ң/g, "ń")
		.replace(/о/g, "o")
		.replace(/ө/g, "ó")
		.replace(/п/g, "p")
		.replace(/р/g, "r")
		.replace(/с/g, "s")
		.replace(/т/g, "t")
		.replace(/ў/g, "w")
		.replace(/у/g, "ẃ")
		.replace(/ұ/g, "u")
		.replace(/ү/g, "ú")
		.replace(/ф/g, "f")
		.replace(/х/g, "x")
		.replace(/һ/g, "h")
		.replace(/ц/g, "c")
		.replace(/ч/g, "ch")
		.replace(/ш/g, "sh")
		.replace(/ъ/g, "")
		.replace(/ы/g, "ı")
		.replace(/і/g, "i")
		.replace(/ь/g, "")
		.replace(/э/g, "e")
		.replace(/ю/g, "yu")
		.replace(/я/g, "ya")
		.replace(/А/g, "A")
		.replace(/Ә/g, "Á")
		.replace(/Б/g, "B")
		.replace(/В/g, "V")
		.replace(/Г/g, "G")
		.replace(/Ғ/g, "Ǵ")
		.replace(/Д/g, "D")
		.replace(/Е/g, "E")
		.replace(/Ж/g, "J")
		.replace(/З/g, "Z")
		.replace(/И/g, "Ý")
		.replace(/Й/g, "Y")
		.replace(/К/g, "K")
		.replace(/Қ/g, "Q")
		.replace(/Л/g, "L")
		.replace(/М/g, "M")
		.replace(/Н/g, "N")
		.replace(/Ң/g, "Ń")
		.replace(/О/g, "O")
		.replace(/Ө/g, "Ó")
		.replace(/П/g, "P")
		.replace(/Р/g, "R")
		.replace(/С/g, "S")
		.replace(/Т/g, "T")
		.replace(/Ў/g, "W")
		.replace(/У/g, "Ẃ")
		.replace(/Ұ/g, "U")
		.replace(/Ү/g, "Ú")
		.replace(/Ф/g, "F")
		.replace(/Х/g, "X")
		.replace(/Һ/g, "H")
		.replace(/Ц/g, "C")
		.replace(/Ч/g, "Ch")
		.replace(/Ш/g, "Sh")
		.replace(/Ъ/g, "")
		.replace(/Ы/g, "Í")
		.replace(/І/g, "I")
		.replace(/Ь/g, "")
		.replace(/Э/g, "E")
		.replace(/Ю/g, "Yu")
		.replace(/Я/g, "Ya")
		.replace(/«/g, "\u201c")
		.replace(/»/g, "\u201d");
}

function copy1() {
	navigator.clipboard.writeText(document.transcription.text1.value);
}

function copy2() {
	navigator.clipboard.writeText(document.transcription.text2.value);
}
