//  copyright lexilogos.com
var car;
function cyrlat () {
car = document.transcription.text1.value;
car = car.replace(/Ā/g, "A");
car = car.replace(/Á/g, "A");
car = car.replace(/Ǎ/g, "A");
car = car.replace(/Ă/g, "A");
car = car.replace(/À/g, "A");
car = car.replace(/Ē/g, "E");
car = car.replace(/É/g, "E");
car = car.replace(/Ě/g, "E");
car = car.replace(/Ĕ/g, "E");
car = car.replace(/È/g, "E");
car = car.replace(/Ê̄/g, "Ê");
car = car.replace(/Ế/g, "Ê");
car = car.replace(/Ê̌/g, "Ê");
car = car.replace(/Ê̆/g, "Ê");
car = car.replace(/Ề/g, "Ê");
car = car.replace(/Ī/g, "I");
car = car.replace(/Í/g, "I");
car = car.replace(/Ǐ/g, "I");
car = car.replace(/Ĭ/g, "I");
car = car.replace(/Ì/g, "I");
car = car.replace(/Ō/g, "O");
car = car.replace(/Ó/g, "O");
car = car.replace(/Ǒ/g, "O");
car = car.replace(/Ŏ/g, "O");
car = car.replace(/Ò/g, "O");
car = car.replace(/Ū/g, "U");
car = car.replace(/Ú/g, "U");
car = car.replace(/Ǔ/g, "U");
car = car.replace(/Ŭ/g, "U");
car = car.replace(/Ù/g, "U");
car = car.replace(/Ǖ/g, "Ü");
car = car.replace(/Ǘ/g, "Ü");
car = car.replace(/Ǚ/g, "Ü");
car = car.replace(/Ǜ/g, "Ü");
car = car.replace(/Ĉ/g, "Ch");
car = car.replace(/Ŋ/g, "Ng");
car = car.replace(/Ŝ/g, "Sh");
car = car.replace(/Ẑ/g, "Zh");
car = car.replace(/ā/g, "a");
car = car.replace(/ɑ̄/g, "a");
car = car.replace(/á/g, "a");
car = car.replace(/ɑ́/g, "a");
car = car.replace(/ǎ/g, "a");
car = car.replace(/ă/g, "a");
car = car.replace(/ɑ̌/g, "a");
car = car.replace(/à/g, "a");
car = car.replace(/ē/g, "e");
car = car.replace(/é/g, "e");
car = car.replace(/ě/g, "e");
car = car.replace(/ĕ/g, "e");
car = car.replace(/è/g, "e");
car = car.replace(/ê̄/g, "ê");
car = car.replace(/ế/g, "ê");
car = car.replace(/ê̌/g, "ê");
car = car.replace(/ê̆/g, "ê");
car = car.replace(/ề/g, "ê");
car = car.replace(/ī/g, "i");
car = car.replace(/í/g, "i");
car = car.replace(/ǐ/g, "i");
car = car.replace(/ĭ/g, "i");
car = car.replace(/ì/g, "i");
car = car.replace(/ō/g, "o");
car = car.replace(/ó/g, "o");
car = car.replace(/ǒ/g, "o");
car = car.replace(/ŏ/g, "o");
car = car.replace(/ò/g, "o");
car = car.replace(/ū/g, "u");
car = car.replace(/ú/g, "u");
car = car.replace(/ǔ/g, "u");
car = car.replace(/ŭ/g, "u");
car = car.replace(/ù/g, "u");
car = car.replace(/ǖ/g, "ü");
car = car.replace(/ǘ/g, "ü");
car = car.replace(/ǚ/g, "ü");
car = car.replace(/ǜ/g, "ü");
car = car.replace(/ĉ/g, "ch");
car = car.replace(/ŋ/g, "ng");
car = car.replace(/ŝ/g, "sh");
car = car.replace(/ẑ/g, "zh");
document.transcription.text1.value=car;
}
function copy1()
{ textRange=document.transcription.text1.createTextRange();   textRange.execCommand("Copy");   textRange="";
}
function copy2()
{ textRange=document.transcription.text2.createTextRange();   textRange.execCommand("Copy");   textRange="";
}